### ISSUE TITLE
Fix grammar

### ISSUE THREAD

**Issue by ghost** [ImagicalMine/ImagicalMine#1]

**Comment by MiroTheSuperDev** [comment]
please give a link to this description

**Comment by ghost** [comment]
"We're...back! Welcome to the new repository of the ImagicalMne project. https://imagicalmine.net" that description

**Comment by ghost** [comment]
Can you see the problem?
"ImagicalMine" Not "ImagicalMne"

**Comment by k3ithos** [comment]
Oops, I rush-typed it XD
