### ISSUE TITLE
invitation request

### ISSUE THREAD

**Issue by MiroTheSuperDev** [ImagicalMine/ImagicalMine#11]
i was a team member but i couldnt work or commit on any of the teams i joined except (mcrafterss)

because of schools and i got removed by daltosatic 

note : i can spell his name correct nvm

may i get invited again and thx

**Comment by MiroTheSuperDev** [comment]
@Taki21 and @TheDragonRing can prove that i have good manners

**Comment by dterweij** [comment]
You can contribute with pull requests right. I think that is the only right thing to do for developers. Then any code can be reviewed before merged.

**Comment by MiroTheSuperDev** [comment]
i would like to join because i was going to create a new respiratory that have something special for imagicalmine that we forgot to do before

**Comment by mhambre** [comment]
I believe Keith is only inviting a few people so what @DALTONTASTIC did won't happen again.

**Comment by k3ithos** [comment]
https://github.com/ImagicalCorp/Legal
15+ and only if you agree to that.
You can also simply just make a pull request. @AmiroEmad, I'm not inviting you because all you do is chat about Genisys.
