### ISSUE TITLE
Developer Requests

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#111251]
Hello,
This is a list of the developers that we would wish to have help on the ImagicalMine project. You can accept the invitation at https://github.com/ImagicalMine. We'd love you to help out on this supportive project! If you don't wish to help out, simply ignore the invitation for a week and we'll cancel it.
We're asking for you to fix bugs, implement helpful features that have been requested here and on the [forums](http://forums.imagicalmine.me) and just be a regular contributor the project! Thank you if you accept the invitation and do help us out!
- [x] @ChalkPE
- [x] @matcracker 
- [x] @DALTONTASTIC
- [x] @BlackShadow1
- [x] @tomoMinecrafter
- [x] @wsj7178
- [x] @AndreTheGamer
- [ ] @DeBe0
- [x] @AmiroEmad
- [x] @MCUnderground
- [x] @Taki21
- [x] @onebone
- [x] @kvetinac97
- [x] @0-Eclipse-0
- [ ] @ZINGDING
- [x] @DelxHQ
- [ ] @fycarman
- [x] @HotFireyDeath

@ImagicalMine/developers NOTICES:
- @EPICMC, a Minecraft server needs plugin developers to help out. Anybody interested? Contact @DALTONTASTIC at daltontastic@gmail.com or DM him via Twitter.
- Please urgently work on less lag and more bug fixes - aim to make this your best project yet! Thanks.

**Comment by flaxues** [comment]
I'm sorry but I can't develop I barely know PHP and 70% of the pocketmine/Imagicalmine api

**Comment by Taki21** [comment]
:+1:

**Comment by MCUnderground** [comment]
:0

**Comment by KillerXtream** [comment]
okay :)

**Comment by AmiroEmad** [comment]
hello i didnt get staff tag on the forums my name is Amir Emad

**Comment by Taki21** [comment]
lol its for github

**Comment by MCUnderground** [comment]
Why do you even worry about tag on forums? Be happy you are an developer

**Comment by Taki21** [comment]
@MCUnderground  i think @AmiroEmad  was just confused where invitation was...

**Comment by Taki21** [comment]
Oops...closed by acciedent

**Comment by AmiroEmad** [comment]
lol this happens alot

**Comment by ZINGDING** [comment]
:)

**Comment by keithkfng** [comment]
I feel like closing this project... We have nothing special than Genisys and ClearSky. All we have is a compiled file of lagging software with so many bugs you can't count on your fingers.

**Comment by flaxues** [comment]
@keithkfng 
If you really want to, just do it! maybe ClearSky becomes more active!

**Comment by Taki21** [comment]
Here something they dont have:
MOB AI and MOB MOVEMENT
An im planning something on it...

**Comment by PocketKiller** [comment]
I am working on fishing hooks.

**Comment by flaxues** [comment]
@Taki21 Genisys has a mob ai

**Comment by BlackShadow1** [comment]
Wait, you've deleted the project? @keithkfng?

**Comment by BlackShadow1** [comment]
Don't close the project and don't be sad @keithkfng .

**Comment by DelxHQ** [comment]
Damn.

**Comment by Taki21** [comment]
@flaxues  wow really! : (

**Comment by BlackShadow1** [comment]
A Mob AI that is very laggy. My server overload with Genisys and one skeleton in old php 5 version.

**Comment by keithkfng** [comment]
@flaxues shut up, will you?

**Comment by 0-Eclipse-0** [comment]
How exactly were we chosen? Just out of curiosity.

**Comment by 0-Eclipse-0** [comment]
We have more stars than Genisys and ClearSky.

**Comment by AmiroEmad** [comment]
because genisys and clearsky started after imagicalmine but the old history that i cant forget is the iron shovel lol

**Comment by Taki21** [comment]
@keithkfng I WANNA MAKE A LAG_FREE MOB AI! : D

**Comment by keithkfng** [comment]
Yes, ImagicalMine started before Genisys went open-source and before ClearSky. But we need to make it lag-free. That's my main goal to drag users back.

**Comment by 0-Eclipse-0** [comment]
So that is why you are requesting us as developers?

**Comment by keithkfng** [comment]
Yes, and to make this software the best it can be.

**Comment by keithkfng** [comment]
And code cleanup.

**Comment by 0-Eclipse-0** [comment]
Also I created a forum account.

**Comment by 0-Eclipse-0** [comment]
Can you create a team chat on Gitter for easier contact?

**Comment by AndreTheGamer** [comment]
@0-Eclipse-0 It's already has been created... Check the readme.md and you"ll see a button on which you can click and join.

**Comment by 0-Eclipse-0** [comment]
I mean an organisation chat.

**Comment by keithkfng** [comment]
There is a staff social chat on the forums - go to the forums tab and select staff social chat at the bottom.

**Comment by applqpak** [comment]
@keithkfng don't close a project in which you're come so far in.

And, @MCUnderground, no offence but you being just keep bragging about being in this GitHub org when you don't even really commit to anything..

**Comment by applqpak** [comment]
Also @Taki21, I don't know where else to say this... But, please do not take credit for developing an iOS App for 'GrimCraft' when I developed everything. BTW, you need to get your own UUID, and fix other multiple problems.

**Comment by 0-Eclipse-0** [comment]
@applqpak I agree with you about the project. It shouldn't be closed. @keithkfng I personally don't think the bugs are that bad and the servers arent that slow. We can fix those problems.

**Comment by keithkfng** [comment]
I NEED SOMEBODY TO FIX THE SPEED AND LAG PLEASE 😫

**Comment by AndreTheGamer** [comment]
@keithkfng Alright, will be working on it.  :+1:

**Comment by keithkfng** [comment]
@AndreTheGamer Awesome, thanks.

**Comment by Taki21** [comment]
@applqpak Whosaid i took credit? i just helped ._. plz move this converstaion somewhere else...

**Comment by applqpak** [comment]
@Taki21 where else? And if you don't believe me. Look at your repos.

**Comment by ZINGDING** [comment]
@keithkfng  Can I join here?
My skill is very low!  :(___

**Comment by keithkfng** [comment]
@ZINGDING of course you can! Even though your skill is low, you can still make this software better.
@applqpak I need you to stop arguing, going of off-topic and start committing XD

**Comment by applqpak** [comment]
@keithkfng lol

**Comment by MCUnderground** [comment]
I might be leaving, i dont have time and i dont find what to add/fix..

**Comment by keithkfng** [comment]
I think the main thing that I find spectacular about ImagicalMine is how many stars it accumulates per day and the number of forks it has(well, that being said, it was really from the mass pull request spamming XD)

**Comment by Pub4Game** [comment]
:)

**Comment by Pub4Game** [comment]
You add me to the team?

**Comment by 0-Eclipse-0** [comment]
Apparently yes

**Comment by 0-Eclipse-0** [comment]
@keithkfng We accumulated 4 stars in 2 hours yesterday.

**Comment by 0-Eclipse-0** [comment]
Im going to start working on the lag tomorrow. Goodnight guys.

**Comment by keithkfng** [comment]
@0-Eclipse-0 I keep track on github.com/trending XD

**Comment by PocketKiller** [comment]
oh that's why we get stars then.

**Comment by 0-Eclipse-0** [comment]
Lol and good morning.

**Comment by applqpak** [comment]
Lol

**Comment by 0-Eclipse-0** [comment]
I saw you followed me @applqpak

**Comment by Taki21** [comment]
we can also add unique features ! like pressing stairs to sit on...why make it a plugin when u can make a unique piece of imagicalmine?! : D

**Comment by keithkfng** [comment]
I need somebody to work on lag urgently... Thanks

**Comment by 0-Eclipse-0** [comment]
I'm currently working on fixing the dropper.

**Comment by 0-Eclipse-0** [comment]
@BlackShadow1 When you copy something (in this case the dispenser) and use it as something else (the dropper) please remember to rename the class.

**Comment by applqpak** [comment]
Is it ok to invite @ZINGDING?

**Comment by 0-Eclipse-0** [comment]
He already has an invitation. Tell him to go to the team page (github.com/imagicalmine) and it should show up.

**Comment by DALTONTASTIC** [comment]
I like that idea. Add code so that people can press twice on a stair to sit on it.

**Comment by applqpak** [comment]
@DALTONTASTIC yeah.

**Comment by applqpak** [comment]
Ah ok Eclipse.

**Comment by 0-Eclipse-0** [comment]
LexoDexo's Plugin List:

RandomFood v4.2, HelpModifer v1.4 Beta, DevBAN v1, NoExplode v1, LevelChat v0.0.1, SimpleHub v1, antiGrief v1, VIPSlots v0.0.4, Skywars v2.1, iProtector v3.1a, CustomAlerts v1.6, xyz v1.0.1, SimpleAuth v1.7.1, GrabBag v2.2.7, PurePerms v1.2.2, PvPWorlds v1, ClearLagg v1.1.0, BanItem v2.1, 1vs1 v0.0.5, LimitHeight v1.1, RestartMe v1.2.0, TouchHome v2, ChatCensor v1.4, EconomyAPI v2.0.9, EconomySell v2.0.7, EconomyShop v2.0.7, EBorder v1.0.0, SignWarp v1.5.1, PureChat v1.3.3

This Plugins are my own:
-SimpleHub
-antiGrief

And these plugins I have modified:
-RandomFood
-Skywars
-SimpleAuth
-GrabBag
-1vs1
-EBorder

**Comment by 0-Eclipse-0** [comment]
Gotta go to hockey.

**Comment by applqpak** [comment]
Ok. And have fun!

**Comment by DALTONTASTIC** [comment]
My server EPICMC is re-launching soon. Experienced plugin developers please contact me via email daltontastic@gmail.com or DM me on Twitter @DALTONTASTIC

**Comment by Taki21** [comment]
Ill be adding sitting on stais code MAYBE and code cleanup which should help decrease some lag @keithkfng

**Comment by PocketKiller** [comment]
@Taki21 make sure to make a disable option.

**Comment by Taki21** [comment]
@PocketKiller  
darn. forgot dat....more work xD

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
PLEASE USE THE GITTER CHAT AND STOP CHATTING LIKE ****!
@DALTONASTIC Adverts...

**Comment by PocketKiller** [comment]
OMG MY NETWORK...

**Comment by 0-Eclipse-0** [comment]
Who can guess what my next plugin will be?

**Comment by BlackShadow1** [comment]
@0-Eclipse-0 i had forgot, because yesterday i've tested alot.. Sorry

**Comment by 0-Eclipse-0** [comment]
Its ok, it just took me a while to find out the problem.

**Comment by BlackShadow1** [comment]
I think this can be closed.
