### ISSUE TITLE
RequestChunkRadiusPacket bug - not found

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#116258]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------<br>
There seems to be an issue with a file not finding the RequestChunkRadiusPacket in the right place - it's looking in src/pocketmine/network rather than src/pocketmine/network/protocol. There's also a screenshot attached for your needs.

![e5d31d6b-f3f9-4797-8dba-4aaea41e4401](https://cloud.githubusercontent.com/assets/13236085/13317516/9b059458-dc09-11e5-92a9-43a839ea8764.PNG) @

**Comment by PocketKiller** [comment]
Will do it.

**Comment by keithkfng** [comment]
@PocketKiller thanks.

**Comment by PocketKiller** [comment]
can I have the Backtrace?

**Comment by keithkfng** [comment]
![bef6295e-98f3-4cf4-a44b-ae389199e005](https://cloud.githubusercontent.com/assets/13236085/13317726/add8e1a6-dc0a-11e5-9599-221e7fec8c74.PNG)

**Comment by keithkfng** [comment]
Coming from Network.php, Server.php or PocketMine.php? Can't read LOL

**Comment by PocketKiller** [comment]
Network.
