### ISSUE TITLE
Messages not viewable on screen

### ISSUE THREAD

**Issue by dterweij** [ImagicalMine/ImagicalMine#12]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

![screenshot_3](https://cloud.githubusercontent.com/assets/1059028/15270897/3d63a49c-1a30-11e6-99e0-4f2891214695.png)

No text,.

## Reproducing the issue

just send something from for example the console.
Any broadcast message is not shown.

## Client information

0.14.2

**Comment by MarcoDiGio** [comment]
Last version doesn't work?

**Comment by robske110** [comment]
This is related to a very dumb copy of one single commit of the CS team.
I'm not angry that you copied. I'm fine with that.
But please, copy the right way

**Comment by MarcoDiGio** [comment]
@robske_110 https://github.com/ImagicalCorp/ImagicalMine/commit/a6221d8c25c20cee87717726df4fa20d882cfb57 this is the second commit. Has you can see, in your commit there are only 2 changes, Player.php and TextPacket.php. https://github.com/ClearSkyTeam/ClearSky/commit/4bba525cf78cad4c5fb5f1aea25697f14c6bb357

**Comment by dterweij** [comment]
Seems fine again. Text is shown again.
