### ISSUE TITLE
bydeozgvbuahcwavmulvghis

### ISSUE THREAD

**Issue by ibookdeadmom** [ImagicalMine/ImagicalMine#1216]
bqkbnfotlxxeksdzzvgtpqczenvqxjhuqjvvjcuajkqpoqvkwejridyxlljdusjtmcpbrqxattkorgssxkuxn

**Comment by ecoron** [comment]
@PocketKiller try to block him, as owner you should can do this

**Comment by PocketKiller** [comment]
Blocked.

**Comment by ecoron** [comment]
@PocketKiller well done, you won this battle :)
