### ISSUE TITLE
99% of players can NOT join.

### ISSUE THREAD

**Issue by FienixEC** [ImagicalMine/ImagicalMine#136025]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------
Anyone else dealing with the issue of players not being able to see the server online? since the PHP7 update with latest builds, I can see my server online and join, but 99% of my players cannot, they have tried reinstalling MCPE, deleting and re adding the server, nothing seems to work. Any input will be greatly appreciated. Thanks

**Comment by dterweij** [comment]
What is the message you see in console and what does the client see as message?

**Comment by FienixEC** [comment]
It just shows the server offline for everyone, "Cant Connect To World", and I see nothing in console. But I'm able to see it online and join, just no one else can...

**Comment by Taki21** [comment]
Me too...I am able to join on my regular ip (not local) but no one else can

**Comment by CyberPowerCrazii** [comment]
It might be a problem of your firewall. Check on your connection if your connected on private or public. Usually on public connections, firewall blocks apps from outside connections. As of windows 10, windows can detect your connection as public. So be sure to check.

**Comment by CyberPowerCrazii** [comment]
If your the owner and it cant connect your own device such as your phone or MCWE10. Check your antivirus if you have in your phone. For MCWE10, make sure MCWE10 is allowed to send connection in your firewall.

**Comment by CyberPowerCrazii** [comment]
Also, Check your antivirus on your computer. It might block your connection.

**Comment by AmiroEmad** [comment]
easy answer you didnt port forward your server + your local ip is not stable

**Comment by CyberPowerCrazii** [comment]
@AmiroEmad look at this message
**"Me too...I am able to join on my regular ip (not local) but no one else can"**
It means even an Imagical Member Can't connect

**Comment by Creeperface01** [comment]
If chunk radius is > 10, devices with 512 RAM can not join.

**Comment by Creeperface01** [comment]
And about IP it works fine for me :)
(anni1.minetox.cz)

**Comment by CyberPowerCrazii** [comment]
Yep. Old device won't join some servers.

**Comment by CyberPowerCrazii** [comment]
Also the console should tell you if players are trying to connect. IF it shows players tries to connect but it can't. The problem is your firewall or antivirus.

**Comment by FienixEC** [comment]
I use a 3rd party host. but yea, right now im using a "loaner server" and
it seems to be okay. but anyone with a device less then 720 mgbs of ram
cant join

**Comment by CyberPowerCrazii** [comment]
looks like this is not problem of pocketmine. Check their antivirus on their phones.

**Comment by Creeperface01** [comment]
or in your router

**Comment by CyberPowerCrazii** [comment]
yep

**Comment by PocketKiller** [comment]
Firewall.

**Comment by Taki21** [comment]
thx @CyberPowerCrazii : Helped alot! : D

**Comment by Taki21** [comment]
I have a NEW problem: Now **I** Cannot Join meaning 100% of the players **CANT** Join:
- I have port fowarded
- I have like 4 GB of Ram on My device (the one that runs the server)
- I have turned off the FireWall
My server has worked before but after update (0.14.0) the server stopp working and nobody cant connect

**Comment by CyberPowerCrazii** [comment]
Does console display that players trying to connect? Try using your public
ip address by searching "ip" in google. If you are using MCWE to connect,
it wont because it uses the same port to connect to xbox servers. Try
changing port in server's properties and port foward again.

**Comment by Taki21** [comment]
Lol Nvm srry... it works xD
