### ISSUE TITLE
Jenkins Slow down

### ISSUE THREAD

**Issue by sixteeN11** [ImagicalMine/ImagicalMine#138678]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

Hi,

i download the newest build with 9.58KB/s.
What is wrong?

**Comment by MasterWolf** [comment]
your connection speed... i just tested - 1267KB/s

**Comment by AmiroEmad** [comment]
if you want to test your download speed go to http://www.speedtest.net/

**Comment by keithkfng** [comment]
The Jenkins server is also being moved to the forums server, which will be hosted in London. It'll be heaps faster than our current one I hope.

**Comment by MasterWolf** [comment]
My download speed is 5.46 MB/s

**Comment by MasterWolf** [comment]
@keithkfng can you plz help me? Im making my new plugin on github. i created readme.md, plugin.yml but i dont know how to create folder on github! How to create it?!

**Comment by AmiroEmad** [comment]
@MasterWolf please dont post comments not related to imagicalmine issue tracker

**Comment by MasterWolf** [comment]
@AmiroEmad ok sorry i just need help...

**Comment by sixteeN11** [comment]
i came from germany, and the server has a gigabit uplink…

**Comment by dterweij** [comment]
@sixteeN11 Thats correct. Jenkins location is bad for a lot europe users. It is reported many times that makes this issue a duplicate. Read the closed issues aswell before make a new one.

Sollution: None
Possible sollution: Move Jenkins to a better location within europe with good speeds for all people or make a mirror in europe

You have to live with it (Thats why I make the phar myself, pull the code from github and make the phar local on your computer :) )

I suggest to close this issue as dupe.

**Comment by keithkfng** [comment]
Well currently the plan is to move the Jenkins server to the same server as the forums server. And it's hosted in London, not China, so it'll be faster as well :)
