### ISSUE TITLE
Forums are temporarily down

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#140603]
Forums are down for now because we are moving them to another server! It will be a single VPS dedicated to hosting the forums and possibly the Jenkins server. Please bear with us as we move them. There won't be anymore errors by the way(well, hopefully) XD

**Comment by keithkfng** [comment]
Forums available at forums.imagicalmine.net

**Comment by CyberPowerCrazii** [comment]
Tested. Working

**Comment by MCUnderground** [comment]
I will have a look

**Comment by AmiroEmad** [comment]
attachment system is ruined
