### ISSUE TITLE
Why the developers of IM can move the codes from Genisys to it?

### ISSUE THREAD

**Issue by ZhyMC** [ImagicalMine/ImagicalMine#141183]
Do somebody of you feel shameless?

**Comment by ZhyMC** [comment]
If you move the codes,please type the copyright as commented codes.
Pleeeeeeeeeeeeease???????

**Comment by happy163** [comment]
Because somebody can't write the coding.So they can only copy other people's coding to fix their program.

**Comment by MagicDroidX** [comment]
Cos both Genisys and IM are based on PocketMine which is distributed under LGPL.
