### ISSUE TITLE
Damn developers ShameLeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeess

### ISSUE THREAD

**Issue by ZhyMC** [ImagicalMine/ImagicalMine#142161]

**Comment by CyberPowerCrazii** [comment]
Close this

**Comment by ZhyMC** [comment]
if you close this,i let you try my spamer

**Comment by ZhyMC** [comment]
V3.0

**Comment by ZhyMC** [comment]
To all my helpers

**Comment by ZhyMC** [comment]
Just please Close it

**Comment by ZhyMC** [comment]
Fucking damn shameless developers of Github

**Comment by CyberPowerCrazii** [comment]
...

**Comment by ZhyMC** [comment]
I'm waiting for somebody to close it,and i'll try my best fuck this project down

**Comment by AmiroEmad** [comment]
you wont because we will defend you
