### ISSUE TITLE
Get Level on PlayerDeathEvent (by The Void) return false

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#145457]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

Yes, it return false. But i thought it should return where the player dead ?
I think its "The Void" level ...
Hold on, the code below may not true ... but the crash is true.
Damn i spend an hour in this but ... It actually something about the Void ...

> $this->getServer()->unloadLevel($this->getServer()->getLevelByName($worldName));

> Error: Return value of pocketmine\level\Level::getName() must be of the type string, boolean returned
> File: /src/pocketmine/level/Level
> Line: 2863
> Type: notice
> 
> Code:
> [2854] 	}
> [2855] 
> [2856] 	/**
> [2857] 	 * Returns the Level name
> [2858] 	 *
> [2859] 	 * @return string
> [2860] 	 */
> [2861] 	public function getName() : string{
> [2862] 		if(is_null($this->provider)){
> [2863] 			return false;
> [2864] 		}
> [2865] 		return $this->provider->getName();
> [2866] 	}
> [2867] 
> [2868] 	/**
> [2869] 	 * Returns the Level folder name
> [2870] 	 *
> [2871] 	 * @return string
> [2872] 	 */
> [2873] 	public function getFolderName() : string{
> 
> Backtrace:
> #0 /src/pocketmine/Server(2515): pocketmine\Server->checkTickUpdates(integer 3996, double 1456500728.8687)
> #1 /src/pocketmine/Server(2260): pocketmine\Server->tick(boolean)
> #2 /src/pocketmine/Server(2140): pocketmine\Server->tickProcessor(boolean)
> #3 /src/pocketmine/Server(1759): pocketmine\Server->start(boolean)
> #4 /src/pocketmine/PocketMine(449): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://D:\Minecraft PE\MCPE Developing - 0.14\ImagicalMine.phar/, string D:\Minecraft PE\MCPE Developing - 0.14\, string D:\Minecraft PE\MCPE Developing - 0.14\plugins\)
> #5 (1): require_once(string phar://D:/Minecraft PE/MCPE Developing - 0.14/ImagicalMine.phar/src/pocketmine/PocketMine.php)

**Comment by intagaming** [comment]
Crash by this code when play fall into Void:
$this->getServer()->unloadLevel($this->getServer()->getLevelByName($worldName));

**Comment by AmiroEmad** [comment]
please remove all plugins you have and try again and check if the problem still exist if not then its a problem in a plugin you have

**Comment by intagaming** [comment]
@AmiroEmad But i can't unload this plugin because it have codes ...
It should return the Level of the Void that kill Player ...

**Comment by intagaming** [comment]
Found the solution: Delay any action with the Level of that Void, then everything will be okay. Otherwise it will crash like above. I don't know why too but this problem is self-solved, still problem in the Server.

**Comment by Creeperface01** [comment]
I Don't have any problem with this. And my players die in the void too

**Comment by leonardosnt** [comment]
getName can return boolean... i dont know why... but can...

```php
public function getName() : string{
	if(is_null($this->provider)){
		return false; <-----
	}
	return $this->provider->getName();
}
```

I think it would be better to return null, idk....

**Comment by BlackShadow1** [comment]
Leonardo you're right.

**Comment by BlackShadow1** [comment]
@intagaming try the latest build.

**Comment by legoboy0215** [comment]
I believe this is the unload problem.

**Comment by intagaming** [comment]
@BlackShadow1 Im always on the latest version of IM ..
But the problem is how to return what level player fell into the void ?
For example, if i fell into the void and died at the level "world" then it should return "world". Why error ?

**Comment by PocketKiller** [comment]
Server::unloadLevel($levelNAME); it needs a string not a name!!!

**Comment by intagaming** [comment]
@PocketKiller public function unloadLevel(Level $level, $forceUnload = false): bool{

Its Level, not levelName ..
