### ISSUE TITLE
ImagicalMine Installation syntax error near unexpected token

### ISSUE THREAD

**Issue by PhilipphatePHP7** [ImagicalMine/ImagicalMine#1492]
How can I Choose the PHP binary ?

http://prntscr.com/a5q941

bash: line 34: syntax error near unexpected token `)'
bash: line 34: `        1 ) z="PHP_7.0.2_x86_Linux.tar.gz";;'

**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

**Comment by PocketKiller** [comment]
which one did you choose?

**Comment by PhilipphatePHP7** [comment]
How can I Choose anything if the screen shows this http://prntscr.com/a5q941
?

**Comment by PocketKiller** [comment]
please report this to ImagicalMine/php-build-scripts.
