### ISSUE TITLE
PHP7 Issue Plugins - Information

### ISSUE THREAD

**Issue by HostingItAll** [ImagicalMine/ImagicalMine#1497]
Removed Header as this post is for "Information" - These are no fault of ImagicalMine, but the plugins themselves.

Plugins with issues on PHP7:

MCG76_WorldEdit v0.5.2
EssentialsPE - Fixable with code changes - See https://github.com/ImagicalMine/ImagicalMine/issues/957
WorldEditArt v1.0.0_beta_dev_#048
SignShop v1.1.3 - Fixable with https://github.com/PocketMine-PHP7/ - Check for API
ManyWorlds v2.0.3 - Fixable with https://github.com/PocketMine-PHP7/ManyWorlds-PHP7 - Check for API
LuckyBlock v2.0.0
TouchIt_v2.phar
LiveSigns v1.2.1
Slapper v1.2.9.2 - Fixable with https://github.com/PMPlugins/Slapper/tree/php7
SkyBlockPE
Boat_v1.0
ItemCasePE - Fixable with https://github.com/PocketMine-PHP7/ItemCasePE-PHP7

**Comment by HostingItAll** [comment]
Added several more, feel free to contribute tested bad items.

**Comment by remotevase** [comment]
Thank you very, very much for writing this post. Can we add more plugins that do not work?

**Comment by HostingItAll** [comment]
Please do.

**Comment by kiyoshi-kurosaki** [comment]
@HostingItAll @remotevase @keithkfng So for this 

EssentialsPE - Just replace the values (src/EssentialsPE/Loader.php)

use pocketmine\nbt\tag\Byte;
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\tag\Double;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\Float;

to

use pocketmine\nbt\tag\ByteTag;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\DoubleTag;
use pocketmine\nbt\tag\EnumTag;
use pocketmine\nbt\tag\FloatTag;

**Comment by flaxues** [comment]
www.github.com/pocketmine-php7 has some compatible plugins with php7!!

**Comment by flaxues** [comment]
Worldeditart needs weak ref!

**Comment by flaxues** [comment]
Livesign is having errors with async

**Comment by da123rrell** [comment]
SkyBlock by @ImagicalCorporation 
EasyMessages by @gamecrafter
PocketTelegram by @ChalkPE

**Comment by remotevase** [comment]
Entity Manager
ExternalIPChecker
SpawningPool

**Comment by remotevase** [comment]
@HostingItAll--> Off topic: Do you give your customers imagicalmine or pocketmine? Your tab title says pocketmine, yet I'm pretty sure you use ImagicalMine. If you use ImagicalMine, please update the tab title.

**Comment by PocketKiller** [comment]
@remotevase @HostingItAll supports PM and IM

**Comment by flaxues** [comment]
can someone fix livesign?

**Comment by PainTR** [comment]
Someone have LiveSigns PHP7 version?

I'm getting this error:
[21:29:01] critical> RuntimeException: "pthreads detected an attempt to connect to an object which has already been destroyed" (EXCEPTION) in "/src/pocketmine/scheduler/AsyncTask" at line 73
[21:29:01] emergency> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[21:29:01] emergency> Please upload the "C:\Users\TRK\Desktop\ImagicalMine\CrashDump_Sun_Feb_21-19.29.01-GMT_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by HostingItAll** [comment]
@remotevase We support just about every software that runs MCPE, we will update our site to included Imagicalmine.

**Comment by XShockinFireX** [comment]
Slapper can also be fixed with this: https://github.com/PMPlugins/Slapper/tree/php7

**Comment by FuxonPlayz** [comment]
look at async error bellow in livesigns sorry for my bad english
Error: "Call to undefined method aliuly\livesigns\FetchTask::isFinished()" (EXCEPTION) in "/LiveSigns-PHP7.phar/src/aliuly/livesigns/Main" at line 34

**Comment by flaxues** [comment]
https://github.com/PocketMine-PHP7/ItemCasePE-PHP7

I fixed ItemCasePE

I don't know if it's the right way!

**Comment by da123rrell** [comment]
Caster by @MCUnderground

**Comment by FuxonPlayz** [comment]
Caster is working

**Comment by MCUnderground** [comment]
Caster should work

**Comment by MrsompopYT** [comment]
Live Sign PHP7 I am You Give me Link plase

**Comment by Ad5001** [comment]
@MrsompopYT There are plugins that do the same as LiveSigns in IM forums, just go check them out!

**Comment by remotevase** [comment]
This is actually an awesome thread, and I feel that we should keep it open until** all** plugins are updated

**Comment by TheDragonRing** [comment]
Thing is though @remotevase some never will be, but new plugins with same functionality will be made, I wouldn't count on WorldEditArt to ever be updated but new plugins with same functionality are being made! :P

**Comment by Ad5001** [comment]
@TheDragonRing there is world edit on IM forums

**Comment by TheDragonRing** [comment]
Yeah I'm that's why I said new ones being made @Ad5001 because its probably still being updated at least LOL
