### ISSUE TITLE
Not an issue ,but an advice for chinese

### ISSUE THREAD

**Issue by zzm317** [ImagicalMine/ImagicalMine#15124]
中国人请注意你的素质
丢人别往国外丢
有什么问题请你私下解决
我不认为你会和这个项目有什么仇
你想黑这个项目，有本事就写个更加好的项目
请文明竞争！

**Comment by ZhyMC** [comment]
谁告诉你advice可数了?
表里一套背后一套恶心不?

**Comment by zzm317** [comment]
@ZhyMC 随你怎么说
我不会去怀疑我的情报网

**Comment by zzm317** [comment]
@ZhyMC 连小号都不需要我也可以获取很多我不在的群的信息~

**Comment by zzm317** [comment]
@ZhyMC 顺便一提，你不要自己来对号入座啊，我这条issue可没at人~

**Comment by ZhyMC** [comment]
所以将来报道上出现了偏差,等于你们媒体也要负责吧?

**Comment by zzm317** [comment]
@ZhyMC 我并没有at任何人~
不要自己对号入座啊
顺便一提我又不是媒体
你们啊一颗赛艇

**Comment by ZhyMC** [comment]
还有我说语法问题,还有你在邮件和声音里态度的两面予以置评.
大神想秀些什么厉害的东西吗?情报网666

**Comment by MagicDroidX** [comment]
他好像也没对号入座哦
你们媒体不要 听得风便得雨
说现在有什么仇了
把指点你语法错误的人批判一番
你们啊
拿衣服
我是angry了
今天便得罪你们了吧

**Comment by zzm317** [comment]
@magicdroidx 说起来我这钓鱼贴居然真钓上来鱼了23333

**Comment by zzm317** [comment]
@ZhyMC 邮件？我并没有回过什么邮件啊

**Comment by MagicDroidX** [comment]
膜蛤无罪，钓鱼亲妈暴毙

**Comment by ZhyMC** [comment]
我喜欢在Issue号有15124的上面谈论一下人生经验

**Comment by zzm317** [comment]
@MagicDroidX 你倒是不要咬钩啊

**Comment by zzm317** [comment]
@MagicDroidX 咬钩是我的锅了喽

**Comment by zzm317** [comment]
@MagicDroidX 我辣么难得钓一次鱼。。。
你倒是给我留点乐子啊

**Comment by zzm317** [comment]
@MagicDroidX 真是的。。。兴趣都被你破坏了=-=

**Comment by MagicDroidX** [comment]
@pocketkiller Yet another chat room.

**Comment by zzm317** [comment]
@MagicDroidX 说起来nbs文件的处理相关可以qq私聊和我讲下么
我打算更新ZMusicBox让他支持nbs的

**Comment by ZhyMC** [comment]
很早就写好nbs文件解析了,然后用发包播放.
需要的话我给你ZhyNoteBlock源码一份

**Comment by keithkfng** [comment]
Someone summarise this and translate it please LOL
