### ISSUE TITLE
I have a bug, pleade solve it!

### ISSUE THREAD

**Issue by DCodeG** [ImagicalMine/ImagicalMine#17]
Hi! I have a bug that's its make me crazy, when i wslk, run on my server the console put me back on 3 blocks and alert this:
[17:01:10] warning> UbblyMaster moved wrongly!

**Comment by jarne** [comment]
That's no bug, your computer / the server is overloaded.

**Comment by dries-c** [comment]
its not if i have 20 tps its laggy!
