### ISSUE TITLE
HUGE lag spikes on join

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ImagicalMine/ImagicalMine#177857]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

When players join (even if no one else is online) there are huge lag spikes. TPS from 20 down to as low as 0.5 and cpu load from 10-20% to 100% every time.
This issue has been around since the beginning of I.M i believe (MCPE Windows 10)

**Comment by MCUnderground** [comment]
This might be beacuee of "php", and low ram. I can look around code

**Comment by XxDXM-hippiexX** [comment]
bc of php? you mean php7? it did it before i.m was php7..Not to try to compare..but clearsky dont have this issue.

**Comment by XxDXM-hippiexX** [comment]
I tried using php bianrys from clearsky and offical PM also raklib and spl..non worked. Maybe protocol issue?

**Comment by intagaming** [comment]
Maybe you have some infinite loop somewhere in your code ?

**Comment by XxDXM-hippiexX** [comment]
Its not a plugin issue..if thats what you mean. Im guessing level.php or network. I have tried other spl and raklib also tried diffrent php bianrys.

**Comment by XxDXM-hippiexX** [comment]
Im also getting reports that some players cant join at all..client side crash. Protocol issue?

**Comment by keithkfng** [comment]
Any errors?

**Comment by CyberPowerCrazii** [comment]
Can you send some information about your computer. Despite of running a server, it must be running on powerful computer, if your using laptop, laptops are not considered to run such as this server. Also check for any programs that uses your computer like torrents, streaming, or downloads.

**Comment by XxDXM-hippiexX** [comment]
No errors, its getting late here..tomorrow ill turn debug on and see what happens when one of the players who cant join trys to login and im running on windows 10 4 gigs ram 3.19 GHz duel core cpu. Except for the lag spikes it holds at 20 tps with 20-25 pple.

**Comment by XxDXM-hippiexX** [comment]
No errors in debug mode either, player says he can join from his iphone but not his ipad on any name/account

**Comment by XxDXM-hippiexX** [comment]
I tried warping him from the console thinking maybe a corrupted chuck or something but that didn't help. Theres one more person who cant join due to client side crash im waiting to see if hes on ipad also...not sure if that will even help tho lol

**Comment by PocketKiller** [comment]
iOS iPads running MCPE Have problems connecting to servers that are not local, says online but cannot join.

**Comment by XxDXM-hippiexX** [comment]
Ok so the cant join is a client side issue? but update on the lag thing..20 tps with 30% load at 28 people until someone joins then it jumps to like froze XD i really hope someone can find the issue here..cuz this php7 stuff is fast af

**Comment by PocketKiller** [comment]
can you reproduce this on a test (no plugins empty flat world) server?

**Comment by Creeperface01** [comment]
I'm using latest version With 70 players online and server runs at 20 TPS

**Comment by XxDXM-hippiexX** [comment]
what os you on? no lag spikes on join? ive had this problem since the beginning of imagicalMine and yes it still does it even with no plugins and 1 world loaded.

**Comment by XxDXM-hippiexX** [comment]
I have used other mcpe server software and dont run into the lag spike bug or client side crashes on join..

**Comment by XxDXM-hippiexX** [comment]
And when i say lag spike i mean tps drops then instantly back to 20 tps..

**Comment by deotern** [comment]
Confirmed, UDP Flood Attack
#231397 #231364
