### ISSUE TITLE
NEW Jenkins server!

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#184946]
Hi all,
I'm here to announce that a new Jenkins server has been released! You can access it @ [jenkins.imagicalmine.net](http://jenkins.imagicalmine.net), and the ":8080" part isn't required anymore! Because it's hosted on a new VPS, it'll mean you'll have faster download speeds than the old one. If, for any reason at all, you can't download files from the new server, don't worry! Our old server has been transferred to [mirror.imagicalmine.net:8080](http://mirror.imagicalmine.net:8080), and you can download phars from there. Happy downloading, and thanks for using IM!

**Comment by dterweij** [comment]
Thank you. The speed is awesome! This helps a lot people.

**Comment by ardaozkal** [comment]
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Out of bandwidth?

**Comment by keithkfng** [comment]
Sometimes the memory usage goes up and then it crashes Jenkins -_-

**Comment by ardaozkal** [comment]
I had same thing happen with mysql @ my webserver. I recommend setting up a cronjob to restart that/the server.

**Comment by PocketKiller** [comment]
enough
