### ISSUE TITLE
Fix Chunk Sending

### ISSUE THREAD

**Issue by CyberPowerCrazii** [ImagicalMine/ImagicalMine#185356]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------
Pocketmine team seems able to fix the chunk sending bug in mcpe client. Take a look on this commit of Intyre. https://github.com/PocketMine/PocketMine-MP/commit/e11b76318ce25560a17b33681a6d90d33f2c4c81

**Comment by keithkfng** [comment]
We fixed it a few days ago, make sure you're using the latest build.

**Comment by CyberPowerCrazii** [comment]
ok.

**Comment by CyberPowerCrazii** [comment]
build 58?

**Comment by keithkfng** [comment]
Check out our new Jenkins server.

**Comment by CyberPowerCrazii** [comment]
not working with build 58

**Comment by keithkfng** [comment]
Why are you using the ImagicalMine-PHP7-0.14 builds? I don't see a problem with just ImagicalMine. Plus, you're using the mirror server. It works perfectly fine for me. Chunks load well, just like they did before.

**Comment by CyberPowerCrazii** [comment]
wait let me see

**Comment by CyberPowerCrazii** [comment]
still not working. using build 729.
