### ISSUE TITLE
Infinite rain and thunder weather

### ISSUE THREAD

**Issue by CyberPowerCrazii** [ImagicalMine/ImagicalMine#186538]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

So I got up a server hosting with server.pro that offers imagicalmine. When I installed my world, everything was fine until rain and thunder came. It was infinite, when we type /weather clear, it becomes clear and later, rain and thunder came again. We tried /weather clear 999 but still no use. Players says "It is the first most powerful storm that stays forever in minecraft".

**Comment by keithkfng** [comment]
Edit your settings in server.properties and pocketmine.yml. But as far as I'm concerned, you can't edit those files if you're with a hosting provider that has a control panel with restrictions.

**Comment by CyberPowerCrazii** [comment]
I got access, What should I edit in pocketmine.yml?

**Comment by keithkfng** [comment]
The enable-weather switch.

**Comment by MCUnderground** [comment]
Feedback?

**Comment by dterweij** [comment]
It is a known issue reported before. Read the closed issues aswell before make a new one.
Sollution: Turn wheater off if it bugs you.
The parameter seconds is not working to the command.
Use plugin TimeCommander and do a clear command each 2 or 3 minutes so you it rains for max 2 or 3 minutes.

Case closed :)
