### ISSUE TITLE
iX你咋不上天呢?eT

### ISSUE THREAD

**Issue by uhjkbg80367** [ImagicalMine/ImagicalMine#18857]
@ibookcc @keithkfng @aodzip @MCPEPIG @ZombiePower @matcracker @PocketKiller @DRedDogPE @zzm317 Fuck IBookfMtTaCpEzSlYcFqUbHvKwNeDqUnAnR

**Comment by Creeperface01** [comment]
what is it?

**Comment by keithkfng** [comment]
It's a robot that's designed to spam the project, of course. It's an inappropriate (threat) directed to one person. Just as much time as it takes you to launch the robot, it takes the same time for me to launch a script to close it all, idiot behind the spamming.
