### ISSUE TITLE
Moved Wrongly issue!

### ISSUE THREAD

**Issue by ChavoJoker** [ImagicalMine/ImagicalMine#19]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

I always get the "(player) moved wrongly!" when a player walks on slabs, stairs, and also sprints in game. Players that join my server always complain that they're glitching/lagging because of it. I also tested my server with Ge****\* and I don't have that issue anymore. I really like using IM but everytime more than one player complains it starts to bother me. I have had this problem for a while now. Also I am using netherbox.com to host my server.

## Client information

14.1, 14.2, 14.3

**Comment by DCodeG** [comment]
I have the same

**Comment by ChavoJoker** [comment]
I thought this issue was fixed but I was wrong

**Comment by DCodeG** [comment]
Yeah :/ it a lot of hated this bug, because the players think that it's a lag

**Comment by ChavoJoker** [comment]
yeah they do think that! Then they somehow get kicked and they say they "lagged out"

**Comment by remotevase** [comment]
Not an issue

**Comment by ChavoJoker** [comment]
So what could be wrong then? I did run Genisys for a few hours and I didn't have "(player) moved wrongly!" anymore. Same specs and plugins as well

**Comment by remotevase** [comment]
Genysis has removed that message. We leave it because some servers use that message to van jackets who move wrongly.

**Comment by k3ithos** [comment]
@remotevase get your spelling right. I'm sick of it. It's Genisys, not Genysis.

**Comment by remotevase** [comment]
XP lol, then I gotta change dozens of messages all over the place. Of I go!
