### ISSUE TITLE
Crashing at "Building Terrain" when connecting with iPod using new ImagicalMine.phar.

### ISSUE THREAD

**Issue by bellevillerc** [ImagicalMine/ImagicalMine#196456]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

I grabbed the latest ImagicalMine.phar and noticed that I could log into the server using an iPhone 5 or my iPad, but noticed it would not work using two different iPod's for some reason.  It would just crash at the "Building Terrain" part when trying to connect on the iPods.  The iOS' are up to date and we are using the latest version of Minecraft PE.  The iOS devices have iOS ver 9.2.1.

I put the old ImagicalMine.phar file I had and tried again, and it works fine.  I did a ver command on the working version and got the following, if that helps. 

"This server is running ImagicalMine 1.0dev [ELITE] implementing API version 1.14.0 for Minecraft: PE v0.14.x alpha (protocol version 45)"

This is running on Windows 10 Pro 64Bit.

Thanks,

**Comment by AmiroEmad** [comment]
crash dump please

**Comment by bellevillerc** [comment]
Sorry, not sure how to get one of those.  It's the Minecraft app on the iPods that crashes/just closes when trying to connect.  But it's only the iPods that do this.  The iphones and ipad connect fine, and it's only when I use the updated (build #15) of the ImagicalMine.phar from the Jenkins server.

As for the console, it shows the person/device joined the game, then shows logged out due to timeout, as it crashes on the iPod.  Its also a clean fresh install that I am using.  I used the method 2 to install.  This is running on Windows 10 64Bit.



Method 2 Used.

Download Visual Studio C++ Redistributable for Visual Studio 2015.

Download the ZIP file from the ImagicalMine repository on GitHub. Unzip the archive and copy the files to where you want to install ImagicalMine.

Then...

Download the latest phar from here and place it with the unarchived files.

Run start.cmd, (as Admin)

**Comment by AmiroEmad** [comment]
thats because on ipose and android there is old php

**Comment by AmiroEmad** [comment]
https://codeload.github.com/ImagicalMine/ImagicalMine-Windows/zip/master

**Comment by AmiroEmad** [comment]
download this zip extract it on your pc and add the phar file your done

**Comment by AmiroEmad** [comment]
thx for contacting imagicalmine team need any further help ask on the forums or if there was an error you can use issue tracker

**Comment by PocketKiller** [comment]
Amir, do you know what you're saying?

**Comment by bellevillerc** [comment]
That is the Windows Master file I downloaded and used today when experiencing this issue.  But as I mentioned before, it's only an issue when trying to use the latest build (15) of ImagicalMine.phar.  Weird how it is only affects the iPods and not the phones or tablet.  OS' are all up to date and all have the same version of Minecraft on them.

**Comment by Creeperface01** [comment]
It can be caused by bad world

**Comment by bellevillerc** [comment]
The worlds are fresh, I tested with fresh installs trying to figure out what may be causing it.  Removed plugins and tested till I found it was something to do with the ImagicalMine.phar file.  even re-downloaded the newest and tried again, but still had issues.  Put the previous working ImagicalMine.phar file back and was fine.  Unfortunately it's used mainly on the iPods and that's the only ones having issues.  Works fine on the iphones andiPad I have.

**Comment by AmiroEmad** [comment]
it is vpn guard

**Comment by bellevillerc** [comment]
vpn guard?

**Comment by remotevase** [comment]
I have this same issue on LG Tribute using latest Android OS

**Comment by bellevillerc** [comment]
As a note, all the iOS devices have iOS ver 9.2.1

**Comment by CyberPowerCrazii** [comment]
Do you use android? Android devices work well for me. I use latest version of phar right now. I did not tested apple devices. Try using other android device. If it works, the problem is your apple device. Apple is closed source so maybe it stores temporary files that needed by minecraft. Try connecting to other servers that run on imagicalmine.

**Comment by keithkfng** [comment]
Well, I connected to the test server and it worked fine for my iPad. Not sure about iPhone's and iPod's, because I never bothered getting them out to charge :P

**Comment by CyberPowerCrazii** [comment]
hmm... we reproduced the apple devices... Maybe try checking its firewall. Sometimes, firewall is not your friend.

**Comment by XxDXM-hippiexX** [comment]
It is the chunk radius packet...almost 100% sure

**Comment by bellevillerc** [comment]
chunk radius packet????  Is that a setting or something I can change?

**Comment by CyberPowerCrazii** [comment]
chunk radius packet had nothing to do with devices that trying to connect. Before saying that, reproduce the issue on android devices...

**Comment by Black-Hat777** [comment]
We're finding the same issue with older iPads... notably iPad 2. 

Building terrain, app crashes and then can't join.

Have found that new update works on newer iPad models but the old ones such as the iPad 2 cannot join.

I have a feeling this has something to do with the chunk radius packet as above...? Issue hit around the same time it was added in last week.

**Comment by GlitchPlayer** [comment]
@keithkfng pushed an update about chunk radius update. check it out on jenkins.

**Comment by bellevillerc** [comment]
Jenkins not working, can't get onto it...  well keep trying though.

http://jenkins.imagicalmine.net/job/ImagicalMine

gives this...

**Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.10 (Ubuntu) Server at jenkins.imagicalmine.net Port 80**

**Comment by Black-Hat777** [comment]
Still not working even on latest build on iPad 2.

**Comment by Black-Hat777** [comment]
Could this have something to do with the older iOS (iPad 2, iPod Touch) devices having 32 bit ARM processors?

Newer 64 bit iOS devices such as the iPad Mini 2 / iPad Air are able to join straight away.

**Comment by 0-Eclipse-0** [comment]
I have the same problem with 4s. Usually works the 2nd time I try.

**Comment by Black-Hat777** [comment]
Hmm... the 4S is basically the same as an iPad 2 specs wise. Same A5 (32bit chip).

I still haven't even got the iPad 2 past the "Building Terrain" screen

**Comment by 0-Eclipse-0** [comment]
Here what's the IP. I want to see if I can join. So far for me it's been a 50:50 join to crash ratio with the servers I've tested.

**Comment by bellevillerc** [comment]
so how/where do I change this setting to 10?

Thanks
