### ISSUE TITLE
I have a bug, pleade solve it!

### ISSUE THREAD

**Issue by DCodeG** [ImagicalMine/ImagicalMine#20]
I have a bug, when i walk in my server the console send me:
UbblyMaster moved wrongly, its a bug, because, i create my server again to verify, and the bug continue, please, fix it!

**Comment by Michael-Tanjuakio** [comment]
Its called lag if you running on a home router or something, everything lags even for my server.

**Comment by remotevase** [comment]
lag, also not a bug

**Comment by DCodeG** [comment]
I run the (CENSORED) server with Genisys, and the error dont show..

**Comment by remotevase** [comment]
Because Genysis removed that error message, ImagicalMine did not.
