### ISSUE TITLE
Client crashes when opening keyboard

### ISSUE THREAD

**Issue by remotevase** [ImagicalMine/ImagicalMine#201813]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
----------------------------- <br>
Well, here I am again with another issue. This does not crash the server, but only the client. <br><br>
No, this is not a client related error, and I know that for 3 reasons: <br>
1) This is not an issue on MCPE issue tracker  <br>
2) It gives me the message "remote_vase moved wrongly" every time I try to log in <br> <br>
I also know that this is not a plugin error because: <br>
1) The issue persists when I remove all plugins <br> <br>
This is using all builds #3-15 from jenkins.imagicalmine.net. I have to go to mirror.imagicalmine.net:8080 and download build #715 in order for chat to work. On the mirror server, builds #717-732 do not work. <br> <br>
This is a major issue, as none of my server's players can log in (and of course, I will not remove my login plugin- it's a public server!)

**Comment by flaxues** [comment]
As far as I know is opening the chat just client side... Do you use any symbols in the chat people say that you will crash with symbols...

**Comment by remotevase** [comment]
no, no symbols other than "/"

**Comment by flaxues** [comment]
I mean in the chat..

**Comment by PocketKiller** [comment]
Not realted to the server, the client itself opens the keyboard. psh.

**Comment by remotevase** [comment]
No, this is not a client related error, and I know that for 2 reasons: 
1) This is not an issue on MCPE issue tracker 
2) It gives me the message "remote_vase moved wrongly" every time I try to open chat

**Comment by flaxues** [comment]
Did you tryed a clean install?
