### ISSUE TITLE
Chat Input Bug

### ISSUE THREAD

**Issue by Michael-Tanjuakio** [ImagicalMine/ImagicalMine#21]
- [ YES] This issue isn't related to any plugins or plugin related crashes.
- [ YES] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ YES] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ YES] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ YES] This issue matches the contributing guidelines - the link is just above the title field.

## Optional information

So the latest phar is now compatible with 14.3(need pistons already) and for some reason I can't do chat I think it has something to do with this warning

Warning: unpack(): Type n: not enough input, need 2, have 0 in phar://C:/Users/alex/Documents/PocketMine-MP/Pocketmine-MP.phar/src/pocketmine/utils/Binary.php on line 310

I tested this in a single player world and it works so this should be a ImagicalMine problem or a plugin problem 
https://forums.imagicalmine.net/threads/chat-input-bug.1277/#post-12702

I think its not the plugins but to be sure because this has never happened before :/

**Comment by andris155** [comment]
my server. :/
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/15453509/c8c43c5c-2018-11e6-846f-6d5d6f70ee09.PNG)

**Comment by Pandaken** [comment]
same issue. continuous server crashes and restarts.

**Comment by Ad5001** [comment]
I don't have this error... do you use the lastest phar? If true, how many RAM did you allow to the server?

**Comment by Michael-Tanjuakio** [comment]
That bug message is fixed,  when I left click I can not chat is MCPE 0.14.3 fault. >:(  (On Minecraft Windows 10 Edition)
