### ISSUE TITLE
0.14.3 Release/Download?

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#22]
Hello. I was wondering where the download for the 0.14.3 update of Imagicalmine mine was? I can't seem to find it in the releases, or the Imagicalmine forum. There was no notice about it either. However, some servers already have the 0.14.3 update. So where, or may someone comment the download here? Thank you!

**Comment by Ad5001** [comment]
There is the 0.14.3 phar : 
http://imagicalcorp.github.io/ImagicalMine/service-download/ImagicalMine.phar
