### ISSUE TITLE
Time to time server crashes, Console spam error?

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#23]
This has been spamming my console recently. Any solutions? Also, is this one of the reasons my server is, from time to time, crashing and then restarting?
21.05 10:23:31 [Server] INFO Warning: unpack(): Type v: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 353
21.05 10:23:31 [Server] INFO Warning: unpack(): Type n: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 296
21.05 10:23:31 [Server] INFO Warning: unpack(): Type v: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 353
21.05 10:23:31 [Server] INFO Warning: unpack(): Type n: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 296
21.05 10:23:30 [Server] INFO Warning: unpack(): Type v: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 353
21.05 10:23:30 [Server] INFO Warning: unpack(): Type n: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 296
21.05 10:23:30 [Server] INFO Warning: unpack(): Type v: not enough input, need 2, have 0 in phar:///imagicalmine.phar/src/pocketmine/utils/Binary.php on line 353

**Comment by Michael-Tanjuakio** [comment]
same its about chat

NOTICE the Type v: not enough input

**Comment by Ad5001** [comment]
Don't have this error... How much ram did you allow for your server?

**Comment by Michael-Tanjuakio** [comment]
I think he has a old phar

**Comment by k3ithos** [comment]
Maybe keep the template there when you submit an issue.
