### ISSUE TITLE
Hunger Ban

### ISSUE THREAD

**Issue by YaBoiLewis** [ImagicalMine/ImagicalMine#231398]
- [✅ ] This issue isn't related to any plugins or plugin related crashes.
- [ ✅] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [✅ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [✅ ] This issue matches the contributing guidelines - the link is just above the title field.

When you run out of Hunger, you die and get banned.

**Comment by applqpak** [comment]
Thanks for the report.

**Comment by applqpak** [comment]
Crash Dump, please?

**Comment by YaBoiLewis** [comment]
Hi,

No crash dump; you just get banned.

**Comment by DelxHQ** [comment]
Turn off hardcore then there you go :) Hope this helps.

**Comment by YaBoiLewis** [comment]
Didn't work. It's on peaceful but still occurs

**Comment by DelxHQ** [comment]
Please may I see your server configuration?

**Comment by YaBoiLewis** [comment]
#Properties Config file
#Fri Mar 25 08:50:13 EDT 2016
server-ip=188.165.79.8
server-port=25565
max-players=12
level-name=Spawn
motd=Minecraft: PE Server
white-list=off
announce-player-achievements=on
spawn-protection=16
redstone-calculation=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=(password)
auto-save=on
disable-logfile=off

**Comment by YaBoiLewis** [comment]
Any responses? @applqpak

**Comment by keithkfng** [comment]
Still an issue? Closed for now, reopen if needed.
