### ISSUE TITLE
Game mode change for cake23 failed!

### ISSUE THREAD

**Issue by PhilipphatesPHP7** [ImagicalMine/ImagicalMine#231344]
Hey! If I want to change my gamemode with /gamemode 0 or setGamemode(0) to Survival, I get this error:

05.03 07:42:45 [Server] INFO [14:42:45] system> Game mode change for cake23 failed!

- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

**Comment by BlackShadow1** [comment]
Debug?

**Comment by BlackShadow1** [comment]
Looked the code and tested - it appears only when you do /gamemode and your actual gamemode.

**Comment by PhilipphatesPHP7** [comment]
Thanks
