### ISSUE TITLE
Blackscreen / Keyboard Bug

### ISSUE THREAD

**Issue by JackboyPlay** [ImagicalMine/ImagicalMine#231346]
Hello, a FEW of my players have the bug with an black Keyboard /Blackscreen if they join cyn you fix it?

**Comment by remotevase** [comment]
Yes- I had this same problem--> restart the device. Then, when you join, open chat, open the keyboard (and if black keyboard, then) hit the back button, then reopen the keyboard

**Comment by dterweij** [comment]
Not a server issue.

**Comment by BlackShadow1** [comment]
Maybe MCPE issue?

**Comment by 0-Eclipse-0** [comment]
It's an issue with the screen sizes.

**Comment by PocketKiller** [comment]
It's MCPE not us!!!
can be radius LOL

**Comment by BlackShadow1** [comment]
I hate chunkradiusoacket.
