### ISSUE TITLE
Receiving supports

### ISSUE THREAD

**Issue by Francolpm** [ImagicalMine/ImagicalMine#231328]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

Hi there!

I know that ImagicalMine is based on Hydreon Corporation's Katana, but this is a great work! Congrats.
Sorry about the question here, I don't trying to spam you, but are you accepting donations or supports?
Because I want to give some of money to ImagicalMine, but there is no donate button o something like that.
Please, let me invite you to beerpay.io, a simple platform to monetize open source projects, like ImagicalMine.

Thanks for this work!

**Comment by 0-Eclipse-0** [comment]
Use https://gitter.im/ImagicalMine/ImagicalMine to ask questions like this.

**Comment by 0-Eclipse-0** [comment]
Closing for false issue

**Comment by keithkfng** [comment]
I'll register on beerpay.io soon, look out!

**Comment by Francolpm** [comment]
@0-Eclipse-0 sorry about this "false issue". I just didn't know where to ask, now I know. Thanks for the link!
@keithkfng you should try! 

Thanks for reply!

Cheers!

**Comment by 0-Eclipse-0** [comment]
Its all good.
