### ISSUE TITLE
Not reading server.properties file

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#231363]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
<Br>
<Br>
Whenever I edit the server.properties file and restart the server, it just resets all the options<Br>
<Br>
I don't know LOL<br>
<br>
Ubuntu 15.04 x64<br>
PHP version 7<br>
Latest build of ImagicalMine via GitHub<br>
<br>

**Comment by GlitchPlayer** [comment]
Maybe the file is a read only? Or make sure have admin previleges. I dont know ubuntu os but this might help

**Comment by deotern** [comment]
Are you using any hosting company?
If yes, the hosting company may limited the privilege to edit the properties file :) So thats why it reset everytime when you restart your server.

If no, check properly if the properties file is saved or not... Maybe theres a bug when you saving the files.. (For me, Im experiencing saving PHP files in Windows 10)

**Comment by keithkfng** [comment]
Permissions at 777, and no, I don't use a hosting company. Weird issue...

**Comment by keithkfng** [comment]
Found out what I left the server on when I saved it, and then it reset everything again LOL

**Comment by deotern** [comment]
Keith, is there anyway to contact you? Via email? or Twitter? Kik?

**Comment by keithkfng** [comment]
Email keithkfng@imagicalmine.me, @keithkfng on Twitter or on IM Forums. PM Forums is definitely not reliable.
