### ISSUE TITLE
Some players kicked randomly timeout error

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231387]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14061259/03955a56-f37c-11e5-8ac4-f1139720ea8a.PNG)

**Comment by BlackShadow1** [comment]
Try to reduce chunk-radius on pocketmine.yml file.

**Comment by andris155** [comment]
Current:  chunk-radius: 5

**Comment by BlackShadow1** [comment]
Mh.. So chunk-radius doesn't cause login timeout? This issue can be critical..

**Comment by 0-Eclipse-0** [comment]
Could be a plugin gone wrong?

**Comment by andris155** [comment]
27.03 19:59:42 [Server] INFO Plugins (21): SimpleGamemode v1.0, BanItem v2.2, PocketGuard v2.1.1, EssentialsPE v1.1.3, DevBAN v1, AlwaysSpawn v2.2.2, EconomyJob v2.0.4, ServerAuth v2.13, NoAdvertisingPE v1.0.1, EconomyAPI v2.0.9, LimitedCreative v1.0.0, MCG76_WorldEdit v0.5.2, SimpleMessages v1.2, PurePerms v1.3.5, ClearLagg v1.1.0, iProtector v3.1b, EconomyShop v2.0.7, MagicTelePortal v1.3.2, EconomySell v2.0.7, EconomyLand v2.0.9, PureChat v1.4.0

**Comment by BlackShadow1** [comment]
Any of these plugin use PlayerPreLoginEvent?

**Comment by Guillaume351** [comment]
Same issue, with only one plugin made by me. Even if I disable it, the bug stays

**Comment by remotevase** [comment]
Try removing auth plugins, and see if that helps

**Comment by Ragnok123** [comment]
From what version they are connecting and version of your imagicalmine?

**Comment by Guillaume351** [comment]
Already tried. I don't know their version, for me it's 0.14.1

**Comment by remotevase** [comment]
How is your Wi-Fi strength? Go to https://speed test.net to find out

**Comment by Guillaume351** [comment]
For me : 

> Hosted by FreeMobile (Paris) [1.59 km]: 1.677 ms
Testing download speed........................................
Download: 516.82 Mbit/s
Testing upload speed..................................................
Upload: 40.39 Mbit/s

**Comment by remotevase** [comment]
oh... that is unfortunate... As @deotern said, many people are getting this issue. I suspect that @andris155 this is happening because of a DDoS attack

**Comment by deotern** [comment]
@remotevase I said the Binary pack() error is caused by DDos ATTACK ONLY, I'm not sure if this error is an DDOS Attack....

**Comment by Ragnok123** [comment]
@deotern Servers are usually off if is DDoS attack

**Comment by remotevase** [comment]
Well, if my conclusion is correct, ImagicalNet is being ddos. I was able to join,

**Comment by keithkfng** [comment]
Reopen if needed.
