### ISSUE TITLE
TrappedChest

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalMine/ImagicalMine#231362]
We can't open TrappedChest, and some people and I need it, can you do something?

**Comment by hoyinm14mc** [comment]
I think the trapped chest inventory UI hasn't been implemented.

**Comment by hoyinm14mc** [comment]
This feature seems to be implemented and I could open trapped chests. Are you sure that you are using the latest ImagicalMine build?

**Comment by keithkfng** [comment]
Issue closed for now, reopen if needed.
