### ISSUE TITLE
new error php7 debian 

### ISSUE THREAD

**Issue by robozeri** [ImagicalMine/ImagicalMine#231343]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/imphp7/bin/php7/bin/../lib/libz.so.1)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/imphp7/bin/php7/bin/../lib/libyaml-0.so.2)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/imphp7/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/imphp7/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /root/imphp7/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /root/imphp7/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /root/imphp7/bin/php7/bin/../lib/libcurl.so.4

**Comment by 0-Eclipse-0** [comment]
Please don't create duplicated issues.
