### ISSUE TITLE
Linux Installer error

### ISSUE THREAD

**Issue by AndreyNazarchuk** [ImagicalMine/ImagicalMine#231372]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

Linux installer causes the server to crash repeatedly.

go to the web install link for linux and install Imagicalmine, then try to start it.

Ubuntu 15.x, php7, web installer

**Comment by tnpxxsheepdog** [comment]
@AndreyNazarchuk What is the feedback on console? Please paste it so I can take a look at it.

**Comment by AndreyNazarchuk** [comment]
Can't get it anymore because the Jenkins server is down again...

**Comment by tnpxxsheepdog** [comment]
@AndreyNazarchuk Here, you can use the one I run on my server, it is a few versions back but nothing major https://www.dropbox.com/s/e8ujpt38w2i4lsd/ImagicalMine.phar?dl=0

**Comment by AndreyNazarchuk** [comment]
Thanks

**Comment by tnpxxsheepdog** [comment]
@AndreyNazarchuk No problem, just paste anything that you think will help and I'll get you up and running soon!

**Comment by AndreyNazarchuk** [comment]
Heres the error.
`./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: Cannot open shared object file: no such file or directory.`

**Comment by tnpxxsheepdog** [comment]
Ok so go to the main folder of your server. Type `apt-get update`

Then install ALL of these by doing `apt-get install <name>`

perl gcc g++ make automake libtool autoconf m4

Example: `apt-get install libtool `

Do that for all of those and then REINSTALL IM by using the install command that you previously used.

**Comment by AndreyNazarchuk** [comment]
Yes it worked!!!
Thank you!!!
