### ISSUE TITLE
Torch error and crashs

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#231378]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

I received this error several times a day.
2016-03-21 [08:36:33] critical> Error: "Call to a member function isSolid() on integer" (EXCEPTION) in "/src/pocketmine/block/Torch" at line 64

And another problem I have found is the high incidence of crashes , but I am not good looking at the crashdump and I would love the ajuad you.
[crashdump.zip](https://github.com/ImagicalMine/ImagicalMine/files/185822/crashdump.zip)

**Comment by Pub4Game** [comment]
https://github.com/ImagicalMine/ImagicalMine/commit/dff3fe9af376a9f5b1176d54cbb9244af5351218
