### ISSUE TITLE
Player slots

### ISSUE THREAD

**Issue by kabluinc** [ImagicalMine/ImagicalMine#231357]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

If u have 100 slots for your server but only have 3 -4 active players, would this make any difference to the lag if it was 20 slots and 3-4 active players on it?

**Comment by PocketKiller** [comment]
?
