### ISSUE TITLE
Wiki (install instructions) need to be updated 

### ISSUE THREAD

**Issue by tnpxxsheepdog** [ImagicalMine/ImagicalMine#231373]
Ok first off I understand this is not the proper place to report this, however I tried to fork the project and edit the wiki and I don;t think it's possible. I have also contacted an admin to help with this but I am sure they are busy and forgot..

Ok for the linux part of the instructions for installing IM, this needs to be added:

Before installing IM, do the following

`apt-get update`

Then install ALL of these by doing `apt-get install <name>`

`perl gcc g++ make automake libtool autoconf m4`

Example: `apt-get install libtool`

This also needs to be added to the IM website where you select "Get IM" and it has the instructions. This is crucial as if libtool and other dependencies aren't installed, it will not work properly.

Again I understand this is not the proper place to report but the squeaky wheel gets the grease, This needs to be addressed and it is a simple fixed and I tried myself. So if you would like to get on me for posting this here, you're simply hurting the ability for people that are new to linux and lib to get IM.

Thanks 
TNPXXSHEEPDOG

**Comment by dterweij** [comment]
It realy depends on the use of OS. Ubuntu (build on Debian) uses apt and CentOS (build on Redhat) uses yum. SuSE uses YAST for example, slackware uses another tool to install something etc etc.
So Linux is the wrong word to use. Linux OS Distribution is the term to use and the WIKI should mention at least Debian and RedHat Distributions (apt and yum as these are the most used).
Besides that, the installation differs a lot between Ubuntu and CentOS. Complete different. The installation script provided is useless for CentOS. ImagicalMine devs should make at least two scripts. install-ubuntu.sh and install-centos.sh :)

**Comment by tnpxxsheepdog** [comment]
Agreed @dterweij No matter what there needs to be documentation added for at least a few distros, it is literally easy and will take 5 seconds to add (I tried but I'm not a github guru.) I just want as many people as possible to have access to this software!

**Comment by tnpxxsheepdog** [comment]
Added to the website and install docs. Closed 3182016
