### ISSUE TITLE
error php7

### ISSUE THREAD

**Issue by robozeri** [ImagicalMine/ImagicalMine#231332]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

**START ISSUE DETAILS BELOW**<br>
--------------------------------------
Hello I wanted to know how come running start.sh from this issue 
root@vps250454:~/sg# ./st*
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.15' not fo                                                                                                                                                             und (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not fo                                                                                                                                                             und (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libz.so.1)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libyaml-0.so.2)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.15' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libcurl.so.4)
root@vps250454:~/sg# /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not fo                                                                                                                                                             und (required by /root/sg/bin/php7/bin/../lib/libcurl.so.4)

**Comment by 0-Eclipse-0** [comment]
Install REMI repository, Install PHP 7 + weakref and pthreads extentions. ImagicalMine works fine with it.
Start ImagicalMine with the zts-php binary. Not php itself. Because zts-php is using pthreads and php not.
 
Link:
http://rpms.famillecollet.com/

**Comment by 0-Eclipse-0** [comment]
Hope that helps.

**Comment by robozeri** [comment]
I have a debian

2016-03-03 14:59 GMT+01:00 Eclipse <notifications@github.com>:

**Comment by keithkfng** [comment]
Maybe do "apt-get install libtool-bin" or "yum install libtool-bin" should work

**Comment by 0-Eclipse-0** [comment]
"sudo apt-get install libtool-bin" works on backtrack @keithkfng

**Comment by 0-Eclipse-0** [comment]
Try doing that @robozeri. If it works on Kali Linux then it should work on regular Debian.

**Comment by robozeri** [comment]
root@vps250454:~# apt-get install libtool-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libtool-bin

**Comment by robozeri** [comment]
this is my souce list 
deb http://ftp.debian.org/debian/ wheezy main
deb http://security.debian.org/ wheezy/updates main
deb http://http.us.debian.org/debian stable main contrib non-free
deb http://non-us.debian.org/debian-non-US stable/non-US main contrib non-free
deb http://security.debian.org stable/updates main contrib non-free
deb http://httpredir.debian.org/debian jessie main
deb-src http://httpredir.debian.org/debian jessie main
deb http://httpredir.debian.org/debian jessie-updates main
deb-src http://httpredir.debian.org/debian jessie-updates main
deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

**Comment by 0-Eclipse-0** [comment]
Strange.

**Comment by 0-Eclipse-0** [comment]
Try sudo apt-get

**Comment by 0-Eclipse-0** [comment]
It worked with both for me.

**Comment by BlackShadow1** [comment]
It's related to your lib, please, install them here https://github.com/ImagicalMine/IM-PHP-Binaries
