### ISSUE TITLE
I cannot enter Jenkins to download .phar file

### ISSUE THREAD

**Issue by silence8620** [ImagicalMine/ImagicalMine#231379]
I cannot enter Jenkins to download .phar file
now , Jenkins only  "EnderPE".

**Comment by silence8620** [comment]
A few days ago, it shows "the service is not available"

**Comment by dterweij** [comment]
Try my private build server for the time being. I opened it up for public for now.
Be aware that I turn off public access anytime.

http://jenkins.terweij.nl/job/PocketMine-Server-IM/
