### ISSUE TITLE
FPS lagg too many particile on block break.

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231377]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

https://github.com/ImagicalMine/ImagicalMine/commit/6d2896d693309fdbca101b2c11bc288fe54aca6e

**Comment by tnpxxsheepdog** [comment]
I can confirm this. 75% of the time when you break a block it freezes your game for 3-5 seconds. It's not on every block break but generally when you spawn into a new area and it's rendering, this happens. Same goes for placing a block!
