### ISSUE TITLE
Item pickup on windows 10 0.14.0 client not working correctly

### ISSUE THREAD

**Issue by TomBongers** [ImagicalMine/ImagicalMine#231352]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

When i login to a server running imagicalmine from my windows 10 MC 0.14.0 version the item pickup does not seem te be working correctly.

When i braek a dirt block for example it is shown as dropped on the ground. I move to pick it up but it doesn't appear in the bar at the bottom of the screen. 

If i open my inventory it does show up there. When i close the inventory again a duplicate plops out as if thrown.

When i try to place the blocks it won't work. If i pickup the thrown items after placing the blocks they do work but when i open and close my inventory they are ghost blocks again.

this does not happen on the iPhone pocket version of the game. everything seems to be OK there.

I hope this is a bit comprehensible. I made a youtube video of it in the hopes it is clearer.
https://youtu.be/Yly895ZnBKw

Clean imagical mine zip with the clean ImagicalMine.phar loggin in with Windows 10 MCE 0.14.0

**Comment by rWardy** [comment]
I can confirm this happens.  Not yet investigated it, but makes playing on Windows 10 impossible.

**Comment by intagaming** [comment]
I confirm these too. Minecraft Windows 10.

**Comment by GlitchPlayer** [comment]
I'm using windows 10 and I confirm this bug bit its not annoying anymore on latest build, latest build seems to fine to me. But the delay on picking block is longer. Like if you walk into it, it will pick up in 3-5 seconds.

**Comment by GlitchPlayer** [comment]
Try using latest build

**Comment by TomBongers** [comment]
I tried http://jenkins.imagicalmine.net/job/ImagicalMine/80/ but no real succes. Any other builds i should try?

**Comment by hoyinm14mc** [comment]
@TomBongers http://jenkins.imagicalmine.net/job/ImagicalMine/83/

**Comment by intagaming** [comment]
@hoyinm14mc @GlitchPlayer No. Still buggy.
This doesn't happen on the 0.13.x . Maybe there's some network/packet problem ?

**Comment by GlitchPlayer** [comment]
Yup. Delay on picking up items. I found this too on xbox clients. One day,
i played with my friend through MCWE and then we found out on picking items
delaying on its time. Might be problem of client.

**Comment by GlitchPlayer** [comment]
Could be bug on client

**Comment by leonardosnt** [comment]
@GlitchPlayer Nop , it just happens with pocketmine/imagicalmine

**Comment by GlitchPlayer** [comment]
No, I mean also on xbox servers. Me and my friend played on xbox server (if
you tried to play in xbox servers.) We found out that items are delaying to
pick up. Even chat. So we tried on another server we connected. Still the
same.

**Comment by rWardy** [comment]
It's not a delay @GlitchPlayer, it is a bug in some way. Items are thrown when the inventory closes, the hotbar re-organises etc.

**Comment by Skull3x** [comment]
It happens on Genisys too if you disable Limited Creative

**Comment by TomBongers** [comment]
Just tried http://jenkins.imagicalmine.net/job/ImagicalMine/92/ but still the same problem.

Hotbar not updated on item pickup (only after opening inventory)
Closing inventory results in drop of items in selected hotbar position andghost items remain

**Comment by intagaming** [comment]
This should be a little easier if there's something that can debug the network packet or droping events so that we can see what make the items drop when close the inventory ?

**Comment by Skull3x** [comment]
Basically it happens on every server that allows items to be dropped

**Comment by leonardosnt** [comment]
@Skull3x it happens on all that is based on pocketmine...

**Comment by Skull3x** [comment]
That really what I just said

**Comment by Skull3x** [comment]
Almost everything is based on pocketmine but edited versions of it exist

**Comment by TomBongers** [comment]
I tried https://github.com/Nukkit/Nukkit

The pickup and placement aspect of the game seems ok but when i start crafting there shit hits the fan ;)

Maybe there is some code useful for this problem there?

**Comment by GlitchPlayer** [comment]
Well, nukkit is written well in java and mcwe is written in c++ which somehow related to each other. Therefore, imagicalmine is written in php. Maybe there's a mess in some codes.

**Comment by c-hri-s** [comment]
It's got worse. With the latest W10 client you can't even select any blocks.

I've uploaded a video to demonstrate the problem:
http://webmshare.com/6BbOG (running PM, but same happens with IM)

I tried using a plugin which bypasses the drop, but it doesn't solve this - then you just can't select anything.

Playing with the W10 client on an iPad or W10 server works perfectly. Not sure what's different there, but I'd hope someone could perhaps debug what that's doing and replicate to fix the issue?

**Comment by dterweij** [comment]
I think it is solved with 0.14.1 client and some commits.
Can be closed i think.

**Comment by c-hri-s** [comment]
Yes. Fixed now
