### ISSUE TITLE
Latest dev build Torch console error

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231370]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

`15.03 12:40:31 [Server] CRITICAL Error: "Call to a member function isSolid() on integer" (EXCEPTION) in "/src/pocketmine/block/Torch" at line 64`

**Comment by BlackShadow1** [comment]
My fault, getId return int not bool..
