### ISSUE TITLE
Related to PHP7

### ISSUE THREAD

**Issue by AndreTheGamer** [ImagicalMine/ImagicalMine#231329]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

Anybody know how to install PHP7 on a dedicated server? 
It's running CentOS. I've tried multiple ways but keep getting
`` /home/test/bin/php7/bin/php: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
``

Any idea??

**Comment by keithkfng** [comment]
Use "curl -sL http://get.imagicalmine.net | bash"
Choose Linux and your bit system, then after the installation delete everything except for the bin folder.

**Comment by AndreTheGamer** [comment]
@keithkfng  Not it gives this error
`` ./bin/php7/bin/php: /lib/libm.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php) ``

-_-

**Comment by keithkfng** [comment]
Need to install libtool?

**Comment by AndreTheGamer** [comment]
@keithkfng  Yea, i think. Do you know how?

**Comment by keithkfng** [comment]
"yum install libtool" I think

**Comment by AndreTheGamer** [comment]
@keithkfng Nope, i've tried it but no luck getting it to install. Somehow it returns with a path of the libstools repo being changed. I don't really know. Any other ways? 

Error:
`` Cannot retrieve repository metadata (repomd.xml) for repository: testing-devtools-6. Please verify its path and try again
``

**Comment by keithkfng** [comment]
Yeah no... I'm not an expert with CentOS, I'm only used to Ubuntu.

**Comment by AndreTheGamer** [comment]
@keithkfng um.. alright

**Comment by ZINGDING** [comment]
@AndreTheGamer  Would you do "yum install libtool-bin"?

**Comment by dterweij** [comment]
@AndreTheGamer Install REMI repository, Install PHP 7 + weakref and pthreads extentions, ImagicalMine works fine with it.
One note: Start ImagicalMine with teh zts-php binary. Not php itself. Because zts-php is using pthreads and php not.

http://rpms.famillecollet.com/

```
[root@server03 ~]# php -v
PHP 7.0.4RC1 (cli) (built: Feb 18 2016 08:20:19) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

[root@server03 ~]# zts-php -v
PHP 7.0.4RC1 (cli) (built: Feb 18 2016 08:23:35) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

[root@server03 ~]# rpm -qa | grep weakref
php-pecl-weakref-0.3.2-1.el6.remi.7.0.x86_64

[root@server03 ~]# rpm -qa | grep pthreads
php-pecl-pthreads-3.1.6-1.el6.remi.7.0.x86_64


```

Start Imagicalmine with: # zts-php ./ImagicalMine.phar
Or create a own start.sh with the proper path to zts-php


The pre-compiled binaries from ImagicalMine are not working at CentOS.

**Comment by dterweij** [comment]
p.s. @keithkfng can you add this to the wiki ? System requirements?

**Comment by PocketKiller** [comment]
Report this on the IM-Libraries repo.

**Comment by AndreTheGamer** [comment]
@dterweij Can you give me a example of start.sh  with the proper path to zts-php?? Cause while running it using just the phar i was limited from looping the server if it crashed. And if i was using the start.sh i could of config it to loop.

**Comment by PocketKiller** [comment]
you use PHP-Genisys psh...

**Comment by keithkfng** [comment]
@dterweij will do
