### ISSUE TITLE
I need help with this crash

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#231353]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

[CrashDump_Mon_Mar_7-12.00.17-AST_2016.zip](https://github.com/ImagicalMine/ImagicalMine/files/161703/CrashDump_Mon_Mar_7-12.00.17-AST_2016.zip)

I need some help.

**Comment by BlackShadow1** [comment]
Plugin Issue,
