### ISSUE TITLE
Syntax error when using the get.imagicalmine.net script

### ISSUE THREAD

**Issue by Striker209** [ImagicalMine/ImagicalMine#231359]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

I can't install IM on Linux as there is a missing quote in the installer script

Go on imagicalmine.net
Copy the command line for the Linux installer
Run it in a shell
Boom you get a syntax error !

Linux (Ubuntu 14.04 LTS)

echo "system>   8) Czech"
echo "system>   9) Vietnamnese
echo "system>   10) Exit ImagicalMine installation"

**Comment by rWardy** [comment]
Should be sorted now.  Please retest

**Comment by AndreyNazarchuk** [comment]
If I type curl -sL http://get.imagicalmine.net | bash into my ubuntu command line, it installs fine but gives this error when trying to start ImagicalMine: 

./start.sh: line 54: ./bin/php7/bin/php: no such file or directory

This happens no matter which Linux installer I use.
Please fix!

**Comment by DelxHQ** [comment]
Try installing a new bin folder.

**Comment by AndreyNazarchuk** [comment]
I don't know how, I delete it before evey install.

**Comment by AndreyNazarchuk** [comment]
It's not fixed, try it yourself. You can't use the online installer on
Linux.

**Comment by Striker209** [comment]
What is issue you have ?

**Comment by MCUnderground** [comment]
Install php7?
