### ISSUE TITLE
Jenkins are down.

### ISSUE THREAD

**Issue by CyberPowerCrazii** [ImagicalMine/ImagicalMine#231322]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------
Jenkins is down, even mirror server.
![image](https://cloud.githubusercontent.com/assets/16515013/13423694/601d1498-dfd7-11e5-93b0-e083f6c88000.png)
![image](https://cloud.githubusercontent.com/assets/16515013/13423700/703f1bc8-dfd7-11e5-9bbc-ea33f4311ac2.png)

**Comment by keithkfng** [comment]
1. I've rebooted the Jenkins server and its online now! Thanks for submitting this and telling us about this issue.
2. I recommend you upgrade from Windows XP :P

**Comment by CyberPowerCrazii** [comment]
lol thanks XD
