### ISSUE TITLE
Latest dev build timeout error same players. (old build works perfectly)

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231371]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

1. join server.
2. wait building terrain
3. Timeout error in console, and player not login server.

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13793543/a6af25c4-eaf7-11e5-82a4-ceba30c1bf46.PNG)

**Comment by intagaming** [comment]
We have once. Some Nokia Lumia users can't connect into the IM servers and they will automatically be closed the game..

**Comment by remotevase** [comment]
Just a problem with pocketmine.yml
On like 107, change the number from 30 down to 5 and then it will work

**Comment by andris155** [comment]
Thanks. Fixed.
