### ISSUE TITLE
MultiCraft server start error.

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231321]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

```
01.03 09:17:35 [Multicraft] Loaded config for "Other: ImagicalMine"
01.03 09:17:35 [Multicraft] Server executable "/bin/php7/bin/php" not found, server startup might fail!
01.03 09:17:35 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
```

**Comment by CyberPowerCrazii** [comment]
corrupted php bin files.

**Comment by keithkfng** [comment]
No, it was a problem with compiling the bin files because there must have been an error... Anyway tell Intyre

**Comment by CyberPowerCrazii** [comment]
yeh...

**Comment by PocketKiller** [comment]
get Visual Studio.

**Comment by andris155** [comment]
Ubuntu server

**Comment by CyberPowerCrazii** [comment]
you might downloaded a wrong php files... make sure you are downloading latest php files for ubuntu

**Comment by andris155** [comment]
Used Linux 64 bit 7.0.3 php files.
