### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by PEMapModder** [ImagicalMine/ImagicalMine#231389]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
  - [x] duplicated: no
  - [x] related to plugins: no
  - [x] support request: no
  - [x] generic title: if this issue is tackled properly, this should be the only issue with this titl; it's already specific that it cannot be any more specific
  - [x] information in body: yes
  - [x] generic bug: no
    - [x] trackable: this issue is obviously trackable, unless you reset your own Git tree
    - [x] debuggable: I'm debugging it in this issue
    - [x] reproducible: it **is** happening
    - [x] reported professionally: I hope so
    - [x] is an actual bug: yes. Violating license of parent software is a critical issue.

## Issue description
This software is derived work from PocketMine-MP, which is licensed under the GNU Lesser General Public License Version 3 (LGPL-v3). Therefore, it must conform with the original license too.

Violations:
- [ ] It is difficult/impossible to find out what changes from PocketMine-MP have been made. The license requires derived work to explain significant changes made to the original software.
- [ ] It makes improper acknowledgement. For example, [this file](https://github.com/ImagicalMine/ImagicalMine/blob/master/src/pocketmine/player/PlayerListEntry.php) was originally written by me in my PocketMine-MP fork and has not been merged into PocketMine-MP, but no acknowledgement about it is present.

## Reproducing the issue
View the repository from https://GitHub.com/ImagicalMine/ImagicalMine

## Client information
* Linux, Android, Google Chrome.
* LG G3
* PHP not installed
* ImagicalMine commit: 0b208ae

### Appendix
Reader-friendly unofficial LGPL-v3 summary: https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)

**Comment by dterweij** [comment]
Tsss... Please put your time in solving bugs.
But if that commit is yours at PocketMine-MP repository, then yes, a credit has to be mentioned.

Please give a link that it is your work.

You could also make a pull request to solve it anyway.

**Comment by dterweij** [comment]
Besides, it is allowed to copy code from any fork. Official PocketMine-MP has it rights. We all have to follow the official PocketMine-MP rights. And those are pretty fine to do whatever all forks wants to do as longs as the code is public.
if you do not want that anyone use your code, then you have to make it closed source (zend coded for example) with agreement of original PocketMine-MP author.

Remember, it is OpenSource.

**Comment by BlackShadow1** [comment]
I'm online just now, I have a very slow connection for now, so I can't read the license. If I have to give you credits I'm going to give you the credits, sorry, but I really don't have memory that I can't take code from official repo..

**Comment by PEMapModder** [comment]
@dterweij I didn't say that I don't want anyone to use my code. But as a fork of PocketMine-MP, code that has never been merged into the PocketMine-MP repo, I still hold the right as author to the code I wrote on a repo licensed under LGPL v3, and acknowledgement needs to be given.

I found that I deleted the original branch, but proof that it once existed can still be found in PocketMine/PocketMine-MP#3729. Although it is a pull request, it was not merged into PocketMine-MP.

Also, LGPL v3 requires you to explain significant changes of derived work from the original repo, which I cannot find its existence at all.

**Comment by BlackShadow1** [comment]
https://github.com/ImagicalMine/ImagicalMine/commit/ab6889b76a80d04ac8340e248e8a6363b74129f1
I think it can be closed.

**Comment by PEMapModder** [comment]
You still have not resolved the issue about the first point I mentioned.

Also, I was actually talking about a file that appears to be completely unused in your repository, that is PlayerListEntry.php. But thanks for reminding me ;)

**Comment by BlackShadow1** [comment]
You're welcome. The first point.. I really don't know :/.. PlayerListEntry.php must be used when a player joins the game for load the skin i think.. I'll check.

**Comment by BlackShadow1** [comment]
Seems to be unused from all the class, thanks so much! Maybe someone writed it on a PR long time ago for the compatibility with Slapper.

**Comment by PEMapModder** [comment]
@BlackShadow1 It seems that @legoboy0215 copied it in 4a26394d05b62582a39251261ed1c8adead7f495. Due to the extreme chaos in early commits, it is almost impossible to track when this file was actually copied. But it seems that you can delete this unnecessary file now.

**Comment by BlackShadow1** [comment]
Yes, thanks a lot :) :+1:

**Comment by dterweij** [comment]
You can track each change back to zero. If I show the history of a file then i see when, what and who did do something to that file (using PHPStorm) but i bet some bare git commands in CLI can do it aswell  :)

I said a few time that all developers should use a proper Commit title and description. That makes it easier for makeing/showing a changelog. Whereby title or descriptions always reference a issue number when the commit is for an issue number. Use Fix or Solved in title with issuenumber to close the issue automaticly (if i am correct it is dong that and can be configured by other keywords by the project owner)
Also it disturbs me that most of the commits are not tested by developers at all (syntax checks, if the server starts at all etc etc).
Also, every developer should commit their changes in a batch. Not a commit each file.
Also, every developer should make a Pull request of their commits. Another developer should review the PR and accept or not (with a reason why), Never do a direct commit to the master or accept your own PR.
Each pull request should be in a form of label (like Patch-redstonerepeater  or Feature-hopper or Bugfix-issuenumber )

I see more PocketMine-MP clones doing it very very wrong.... learn how to use git(hub) :)

**Comment by legoboy0215** [comment]
Yes, I did do that. I merged it into ImagicalMine. Sorry @PEMapModder, I did not know that you wrote it, since I got the file from the phar @SavionLegendZzz had on his Twitter.

Again, I am sorry :(

**Comment by PEMapModder** [comment]
Well, that's how the ImagicalMine project started, that's why it was almost impossible to compare it with the PocketMine project from the very beginning.

**Comment by applqpak** [comment]
I think this needs to be opened?

**Comment by applqpak** [comment]
And thanks @PEMapModder for bringing up this topic.

**Comment by BlackShadow1** [comment]
This can close this issues? https://github.com/ImagicalMine/ImagicalMine/commit/823099750df0cd3c6ef63fc03a925dbbf518e81c
