### ISSUE TITLE
Crash when "Building Terrain" 

### ISSUE THREAD

**Issue by MineBuilderFR** [ImagicalMine/ImagicalMine#231336]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

**START ISSUE DETAILS BELOW**<br>
--------------------------------------
When I join server , M'y MCPE crash , i have test with other server using ImagicalMine and It crash (With old version I can join) :/

**Comment by 0-Eclipse-0** [comment]
What is your device RAM?

**Comment by remotevase** [comment]
Eclipse not problem with device. We fixed this issue in the latest phar file (about 10 hours ago)
