### ISSUE TITLE
Cactus grows way to high

### ISSUE THREAD

**Issue by dterweij** [ImagicalMine/ImagicalMine#231374]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

Cactus grows too high.

Let cactus grow, I dont know yet about how long it takes to grow that high.

CentOS 6.7
PHP 7.0.4
Current build.
Windows 10 / Android

![schermafdruk 2016-03-17 16 08 16](https://cloud.githubusercontent.com/assets/1059028/13850521/949b7dba-ec5a-11e5-9505-a72a4e9dcf34.png)

**Comment by MasterWolf** [comment]
WTF?!

**Comment by rWardy** [comment]
I can't see any code that would allow this.  I've fixed an issue where a cactus would grow 2 blocks at once, but it is limited to 3 high.  Only way this could happen is if somebody has manually put blocks n place, or via a plugin

**Comment by dterweij** [comment]
Seems okay now. Issue closed.
