### ISSUE TITLE
Out of memory (allocated 1526726656) (tried to allocate 1085440 bytes)

### ISSUE THREAD

**Issue by tnpxxsheepdog** [ImagicalMine/ImagicalMine#231381]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

Server has a memory leak I believe, I have never had problems with running out of memory and the VPS I use can for sure handle big processes. 

Random occurrence 

Debian PHP 7

ImagicalMine Crash Dump Thu Mar 24 13:12:51 CET 2016

Error: Out of memory (allocated 1526726656) (tried to allocate 1085440 bytes)
File: /src/pocketmine/Server
Line: 1900
Type: E_ERROR

Code:
[1891]     public function batchPackets(array $players, array $packets, $forceSync = false){
[1892]         Timings::$playerNetworkTimer->startTiming();
[1893]         $str = "";
[1894] 
[1895]         foreach($packets as $p){
[1896]             if($p instanceof DataPacket){
[1897]                 if(!$p->isEncoded){
[1898]                     $p->encode();
[1899]                 }
[1900]                 $str .= Binary::writeInt(strlen($p->buffer)) . $p->buffer;
[1901]             }else{
[1902]                 $str .= Binary::writeInt(strlen($p)) . $p;
[1903]             }
[1904]         }
[1905] 
[1906]         $targets = [];
[1907]         foreach($players as $p){
[1908]             if($p->isConnected()){
[1909]                 $targets[] = $this->identifiers[spl_object_hash($p)];
[1910]             }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.4 #0 [Protocol 45; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux brocraft 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.3.6 by 64FF00 for API(s) 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SpawnPoint 1.0.0 by HotshotHD for API(s) 1.13.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNO/tz2zaa/wpWzkztW1ES9bSVcW+9trPNbdLoYmezc1HGA5GghJokWAK0rGbyv9/3fQApSHZa
X+ofztNWJB7f+wmwX1pGZqI1DYej4+N+OJqE7ZYoS1W2pl9aZlPAVOvy5vL9+3fvW+1WJrTmSxx7
VxmmEpaJTJUbdsjTVEXciJiFo/540h+PR+MjdmhKCUNGsXqehb3j0XDYY4uNEfoIQCYyRXhdXUbd
QkW3wmQyF90rUd6JEuZTeAPyTnq9r+1WkVZLmbemCU+1aLciFQukMzw+CQEGg7+iWqQyYkmVR0aq
nC24iVYzjnD1IS9LvmEvipRvRKnbrH630232IlFlJK42ecROGeE4+gIkAPi+A49/1xIoXOrp1AH6
WZi1Km9hWJTBj9rw0tglh0cv7e6Bt/uFNiVAn7fmLTc7hFn7NPLWASmCR6vDmjrGNVBa0zP2VuKf
TGAhkzlgzyMBirnghlu26y2TvS1u219eFMGPUl/mKMy4Xnz8yGKiHhYLWtowd/LI0q84BSp7ZIr4
75yyv8ucl5vpdF1KI17n5hDGU5EfIoZFlSSiPDpiHbZ9fWlhhnswvwpQ0xc71/8ufA6Pgz/Yh2+H
h96wGxo5vZ30fG28AP0vUV+n7NNnB3PyqF6tFfp6PekdP6ZX1M+5ynMRgYMdHtVrHxN8jf3TZ8D/
wqykhs2xyI1MJCD7pIv0Ri1+AUg3K66RiiNHZNh7wDg4nCl5BC72qXXQY4dHU7b10PncumjwY1QC
pIsqKw4XSqWC50etz+3WUuSi5Cm6J6zS4IsAP+wMAdmikmncmvbAn0tlVKRg1XDUbvFC0ppw2OnB
sqU08Np74h9sKPltKhe4p3NMEKqcY2xrvZF5dc8WpQJSE8MGnXDc6QXDgGfxeMgOQnb1dsYuxELy
3E5OgujW9HtB+NdYLI6rATvs98Jx0AuDcHLE7o/HN2NkpFgVAH3S6XX68PabyIGr1gBee3byRuka
OwzQS0ovTSjTKJ9ZVYqZKDN6cSRvx9o78ht0xjDCK7NSpUbFjIevXgH3n534PqH8BkRAnwiBCZHz
RSqANlNWEDVjUQCluBnmtErMhT+QcQywrRsLdz5vCPEeMSwrjszO3l1df3z3/s0FDK3FQoNvwejK
mEJPu13Q4KpadCKVdWmvZbm7hQNyCO906PFNrz7LwENntMOyz6oVNbD8/Zy+lTk4x71U87nKxZ1W
aNvvcvEvDf/5A07zKk2Bh38pI96LNS9jjxNv0Odn4KzFU+Gbi3/v6q//5/UHMOfzLQnz+Vscf4Le
QG13sK2kbZ0sKkQH2AEmr2RWpOIMyPaY9AZ37XTSCXeZnFHkAGELdi14BpN6pZYrGRUPef9OnrfE
QHDyCXNMX12fvb/+MPtDU20o7XpQQAL/pWR+rrKME+JGBjvDu1IYPpCCvBfpP6rNZNTaN+PvZHoL
cT73KXmSxp39vuJULOlZqTy+/NH9ILRnwdfCrMBk4ptn06WHfD53L09nyOrtra1W9QN7bSY8tsJO
f4eli8qo2+dS0i7a2jo9Mp7A02WkcpVtzmavPX68QV9FGDpOdlUEYW0B/7a+FT3xt9/8hvQ7cO8D
9z5072jW3ykJR8Z8LizlQMt8vsPFE0QxgwpKJFV6VfB17ifNnXFPIP3O6Hcjbu+ZAu4OAU+PuXsB
CEAFb89nl91dfrY2cCXS9KER0Oi+FUz+2Ar+0E19K/s/qFYDPY1uHXFPUC72Uee80FUqPB790d1g
FO7H2Fc8fTbH9dDO57s0PIEVCdHLQK1tu2nHiTe4WxeEi98vC06eyUi3BPx5C/WYAX7P4jtsP+N/
SuMH3Z1hn2eIJ/vKS6uI948LYZ4tk/jYv5vhhqzuDjPIc7rmG70fifzRXZfs7+fO2UqmsmBX8APN
wfLZ+C4IrnZg53NOJGkbmd4A//Z45ZulkbPh/5GFrdvdli2P+zP7bjnY5ZOnsko3u+z9CVPew76v
2SfWejwVv0C1VCogzjt+Clx31jWlEN2MayiIu/v8YiKCTuZ8xc1e40ZD+5Vg7/n6Nq87fCChvbLt
3+JOqkrPLoN6vPWNJg+J3j49Q4tHYLAYQ5ObQWnqi8kb3BVUb19QPykDnYL56eKhrL7TdMgHCsT9
9CIZO3ZeAu1gCTV4Ov/oFKUqRGkk1pmtg1nzxs5VnsglwwPOeTnPDz6KmL3lJesPWC+cDvvTUcjO
L68ZHi3ggkyZ+HRe9Xp8En20v0LY3zi1v+PI/obK/i4y+zt06wbM/rrliVG7A9HfS3WOZyCIz9If
FKo0p+FJOOjj4HoFPAep1OZUJQmO8DxXFUS8wB5YBTxaSXEnMpEbXa8hiQaFzQWgydPwOMRxaAm0
gZogiHgaVSmnOZUTt/zeQdSn/QEhSlO1DpJULldmFzDPZcbTPWyZWjQjS44H0bE47eEbneIGzZhb
s4J+NlJl817cFY6UWCaJBPLM5pSotkdXkNMCLYzBs95THE6B6zRA+z1dqzKNt2NaiNhbgsfmpxeX
r84+vLnGUWujwa+VKDcOpRsqI5SHpQefOwXXGoDHp/9BfyAUaEMCze9EQ6umnalaomG5UTxuaoJX
Z5OlaIoMbZtFZIVVSbInY8QjSPY640sJWsE2F2yTXa+EFqzml/FSMGjpGOhOwwM3LEI7MGwhmMyj
tIrBmAH6Ax9AWFcqE3g5YB7C1DwRbaawW9QIki1KwW/ZRlWlg8VkwkBteF6JGEBjJdhUukHAP4t1
A64bi4SDzjRbq/wHw3hRCHAulFcGvAJr6QbIZ3gGatler0TOqmJZ8hgAdOY5uoAFNp3n7OB6BcE+
SGEIqEh5vqygOWN41k0Sc+6iJbzjZUYqfyOZ4tbzlYgcF7sbgYA6Uoq8s5a3shCx5B1VLrv41n0D
nnajkpvXV+9uxoOToH+D+0CMDaApm0OUW85biOjjijptvFLRENfwXoVpU5J8TclzndIlDE2TNIlS
oAOehCGVxpARIsFWkPZSUnIGgK3LbFHS5QeM61VlYoXeZntVJMae+7IoVVrEHbAcnhPvJCV0aaCG
1YGmw6xs/lYPzC5JK2tJYsYtqjIor1JgJNJ/sYyeYTBgGIcQmkvH7E5y9t/oRrCE3KlO1FOG8R83
Xq1gH0ez1wr4c3Rb5XMHiFUazBpyBZgWyQs6G1gJKSdGyW8nAmB0AWxuwV+S49ZwQIYMYwoDBwAb
Q1IXG+YsE5Y7N29mt4I9+Ah1GUgCjJTHMTCvrS0jmWC9t0AO15BEMcwysOCFQHmAtMSvFU9RwUt5
B2vveFoJduhQQi45AuAWH4QXEmkA9rFcinIKs4j55ypbgOjBQc/0Jo+uub5leIEFLtnB+Q+gVqdL
yySuWpXQxlVgZLBatxkFQOYCJThBG8SQgdQ05nESC6RPHMuqHHwRlxDsKzJC4AfctVT3ENaNABEA
O+Q8eUMaStWS8zpBn6dLRPDtNpPmB5CcKWlXLDDjkF3v7WWHwAHomfVRIsRD4LgEQaDz27tLcv1/
pGoBUsWCob7STGUmDYa4TCw53VZ22JWlo0eYbSC2gQMYWkuiiiTNMJFZOLXwNQklkWArEPUgTeQE
KoGQU2O0ugdOKrLYpQImFHoaCgzwLInIgAibst6cIg/FeAORi8f/z8nH4ut3iMf0/KeIh0KjIPwu
8jX0OGiagT9hfhVxTQ3i3CMJqmqpKLWhF2rEFlEAq2+6a08LAQ8EmRiti1YE4AkQKEIHCKo/CF3g
myA0jAvfkqmVJZRdKWUL9HK7bE65G2GA32192AYixPAOg4es7+A7Dxcjz64+BvkVIsKkqkkmSKsV
sN3bMABiFIXesjnoOT710aMEOa4HluslLxeg/CBSaWorQXSvR6VKtoSkuD3M7QGvzXheUfr2qYDK
psJPBtp1NNizBGcKNqImSR0Vsq2Jddg7mzvpDcxhpao0bgiREDvWOduSjkbLCqIcGBz3epZHdvCK
3OBBVCRbsbsbppJSZXVwxb1uPvDjkadTYMKpbt8UHrEfbx8W09Gqym+1lfcbMnkMhTSIlGGHg9ww
W3S3yTdLKGa0XRRgPYF10RYWgqrV7LzkZOzovFB22776MPxjfrfbfAgWi1v2DDxTCoLGAmzXcl2X
xg4RTjR5+3dBzfPcfsLRlIFgGqnNgfT9CJUg9UciYE8uJJED2iK3/kiDItFCNNmQYs2BH7vqGXT8
cmMQdpsFoWfMmPUIbWBqUiBjjcY2qmyzLDUbmOJiG+ucAu1eGHQ0ddhP0FEJ/Ogkw1LlfPahDXuB
ggXEn7WMzcqGbPLvBnxA4Kds6EqCbbGgSTDe0g47i8GfVjxNutAw2PolFmBnDhGgtPanct8hm7zs
wfIqrXv0Pax/eNq2fo14P8ocClLgCqxGkGVjkv8wy2d1ibAt/7H6wU10A4q1f14E7tUvxqCrEotq
abWvXMhkmClKsmdxL6LKVjkYe/Cev9PMajQIKl6KVdGRuUQyQle4/MhCLFhcgsLKlDDVVSntxSjl
qtW5U+rUArC1pmZdbbipwPS6y8gqiW74PPrrNnSnmxF1IYoiAKHYPo6WOkNFyZHpRKAOQ7bqtgR2
y5RlMLV0XQ4wRKcsSC4YL5g7hTe+Ax9iMPaJxkMPAjEPqSFvJyM4+Pnd9eWUUfyGf6IKWr4cWj4C
RDdlaAVEnsPckNeU02c7io+gJ4GY5Hgle6TkBpSg/Rm0wX7PJSMMijbHoUFiv43jLrE5a9wdrqOh
raev0PGRwQXXwkN2GILLPYKlzfowET42IUzUOSL318KngszhGiFjw1d/OYTfEVl8WERYTVJrve25
MaRQJ4VFGAYWewpsYTs4nhQxUNmwjk1ypZuWjj6XqxXINeV7lzfsSiuMeb4GQ1qJcs8W1XJJzZGG
tg9pbpwMwLuox9zOuubHhnIt9crqLKcezq5Ay/EPDDCqtakh+BtYQFRi2Ct/0E37Ytgjh5Xbld2P
FuxbQlJuuzaHzhPPT5ideL6pixFLJM+d6aMN1DTGFVZ9/8lmFcir6U1KaJ+hS49VNm/ZKApNHjQe
Dh5mNSc/NzJlbjmIdidNk1zPMlXlfp7Xri6vLQRtC1WNPSEAxccpG317Ky9hNLaGZWHsFhcsPOk/
upv4z4U9elgIC20h8GM3Rsd1qH2UTwPVHuJ5Gc4muCt+B6EXVSvxhEVgf11s3GmSs82mbiURJnQ6
X2c/l62SKqVlSkMcCTB+yshWDNRjl3iEA14LYGtR/aKsrVAHwTN05IxSItYRDf9NxLXKQIHWynjL
7xnflws0uRGVAVtn3dHFkCLIe+ts221OD9xRRxHUbnVBwbrcABMGHpcGVRFzMpfaVqNUcIuEDnO3
xY4lfNu517R3HhLvktOaSzqE+bUSlXD6dfspJtN4oEFZU3b8XdAKVVSpg+aesQLZAzzPKWAGID0k
2h4KB2RHGiWJoswgkRoMP240dLEbT1CxS6FFTqX4qWJVAGhb2FuDpMhu60kHy4U25hBq2+IxYAQR
bQdpSbaQYPn05s5u7RnM1EZXPC7CryXrwy4bX62NWON1/VqTeNCsAzwS3B1pwuvOKFQgMk/U1gpW
ClVPKDveATGUu0RfrvJNhs0cOYgG8eqGUOxO3TTbThPBYGqc8eUSKgN3+NMcq2GYxm9Gbx/nxtKD
4PRj9KQS8p4l4fKeY+K3L1g5ge24a6Ipcw80BYrFzn/KPuFjANmuTUcBn1EfutwZLwVWHHZmiTPC
LMHTcC3UUMr6MfPPWDEaNSepS4bSxcIDq0JbsN+yQ1e8dWDBUadh2osVYP9La7MH7Emp0G54FFbd
5CxSEF8Tf9inERSak5PPhOPcHfljcScBB61t+l2qzmAfJVrmYiXwo7FMsLzak4ltR8LwwDgTqaFm
hRrmRVVSTMfDYUZdjKbqhWoAirN1FepfAVDVWTeetvuv71qotH7sRoFooSJGU8GIWDMoQySYh6vw
PIMhrESAlTdezWBwoDZmi23KXr05u572X07ao5P7sD24H7T7L8OXMRRiNi4e4tVvhDHs9LjHluBC
2r4NR0d04SLdDcr2ysX9Xwni3ohc01Xr9EvrHFKg95EwhmnvtYh2ZvWvqTRiQJ+9ToJY3OFnxfab
5nrJIgL7W3kDeL6fx7z0h9z/uNG8V2XqvSYyNcJfnxj/O+Zl7L9k/hR+M25vaeHlF71zt50t7EWE
txyah01hvIGr2Zsd5qHK97k3HBnx0RdKy3v/3R3e2A9m6MPg9yJxBw8+qFWmfMI1BRvt07YBYdMH
2+6JjfBrlD5KnQV4KTvqDXsTeHzxGixoIib95GR80luEw5NjHi6AigkfDybRYMCPB2HUi/vJeDRi
LwD2bEXq6DtURt2KHLKYL3IoOm9LkZCm7ed1G07XdnT7//4cv/L+TRb2Uwr7XQDRKRsYX7/+L6eB
UCY=
===END CRASH DUMP===

**Comment by dterweij** [comment]
It does have this issue for a long long time. Thats why I use loop=yes and use TimeCommander plugin to issue a stop every 8 hours.

**Comment by tnpxxsheepdog** [comment]
Yes I will need to do this then, thanks for the idea!

**Comment by dterweij** [comment]
Issue can be closed
