### ISSUE TITLE
Mac install link problem!

### ISSUE THREAD

**Issue by mariobrostech** [ImagicalMine/ImagicalMine#231380]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

When I try to install ImagicalMine on my iMac, the installer fails to download. I've realized that the links for the ImagicalMine installer are different for Linux and Mac, even though they should be under the same installer. Apparently the Mac download link is inactive.

When you copy and paste the install code from imagicalmine.net into a terminal window, the script fails to run.

ImagicalMine, PHP 7, iMac x64

I thought that this can be fixed by simply using the linux install codes in the terminal window instead. This worked, however, when I try to choose my language it said that it couldn't find the file specified, and the installer crashed. Please help!

**Comment by 0-Eclipse-0** [comment]
What language did you choose?

**Comment by 0-Eclipse-0** [comment]
Check our language selection and see if yours in there.

**Comment by mariobrostech** [comment]
I am using english (us)

**Comment by mariobrostech** [comment]
It says press 1 for english (us)

**Comment by mariobrostech** [comment]
and thats what i did

**Comment by keithkfng** [comment]
Try again, it should work now.

**Comment by mariobrostech** [comment]
ok. Thanks!
