### ISSUE TITLE
Stupid anticheat

### ISSUE THREAD

**Issue by Dergercol** [ImagicalMine/ImagicalMine#231409]
<h4>Bad. Very bad anticheat!</h4>
<pre>When i walk on the grass, stairs,semiblocks ,ect...
PlayerMoveEvent will be set Cancelled... It is bad!
I cant disable anticheat because players can fly.
Please fix anticheat. This anticheat was on the pocketmine 1.3</pre>

<b><big>What i offer: </big></b>
<ul><li>Look at the Genisys code</li>
<li>Look at the Clearsky code</li>
<li>Fix it!!! This is impeding</li>

<small>Sorry for my english.... I.M. the best branch of PocketMine.
But this error is impending!</small>

![screenshot_2016-04-09-18-22-04](https://cloud.githubusercontent.com/assets/17719426/14403936/4462ac7a-fe83-11e5-8c60-b65331cfdc18.png)

**Comment by Ad5001** [comment]
Just disable the anticheat and use Darku's oe (on IM forums)

**Comment by jjplaying** [comment]
How / where can you disable the anti cheat?

**Comment by Ad5001** [comment]
In the pocktmine.yml :)

**Comment by jjplaying** [comment]
Yeah, I searched there first, but I can't find it (https://github.com/ImagicalMine/ImagicalMine/blob/master/src/pocketmine/resources/pocketmine.yml)

**Comment by Ad5001** [comment]
So maybe in the server.propreties (I'm sure at 100% that there is a function for that but thought it was in the plugin.yml maybe a staff would know this better than me)

**Comment by jjplaying** [comment]
No, I've also looked in server.properties. Maybe a developer knows where it is.

**Comment by remotevase** [comment]
I don't know of there is an option...
