### ISSUE TITLE
downgrade to 14.1

### ISSUE THREAD

**Issue by imjayl** [ImagicalMine/ImagicalMine#231468]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [√ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
Message on some plugins doesnt appear in mcpe 14.2

## Reproducing the issue
Downgrade to 14.1

## Client information
I used windows. Php7.. 14.2 phar version

**Comment by keithkfng** [comment]
This isn't an issue. The text issue is duplicated. Stop duplicating issues, else you'll be banned.
