### ISSUE TITLE
Mob AI isn't implemented yet send all online server players

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231410]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Reproducing the issue
Use mobspawn egg, and spawn mob

## Client information
latest dev

## Optional information
![12931221_782196505250005_34321240107518224_n](https://cloud.githubusercontent.com/assets/8324198/14406500/886fc724-fea9-11e5-8215-2d59b4c625ac.jpg)

**Comment by keithkfng** [comment]
Yeah, it isn't implemented yet. So wait.

**Comment by leonardosnt** [comment]
@keithkfng "... send all online server players"

**Comment by keithkfng** [comment]
???
