### ISSUE TITLE
$recipe?????

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#231450]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Optional information

Notice: Undefined variable: recipe in phar://D:/MINECRAFT/ImagicalMine/ImagicalMine-Windows-master/ImagicalMine.phar/src/pocketmine/Player.php on line 3030

Notice: Undefined variable: recipe in phar://D:/MINECRAFT/ImagicalMine/ImagicalMine-Windows-master/ImagicalMine.phar/src/pocketmine/Player.php on line 3039

**Comment by remotevase** [comment]
This is strange. Why?
Lines 3030 and 3039 have nothing to do with recipes!

**Comment by laurobeleche** [comment]
![3030](https://cloud.githubusercontent.com/assets/14208219/14866569/b689b648-0c9a-11e6-804a-1e78841fb004.png)

**Comment by remotevase** [comment]
Well, line 3038 defines it...I dont understand why this is happening!

**Comment by laurobeleche** [comment]
The line 3038 is setting $recipe , however, the line 3038 is in an open if the line 3030 which already contains a condition using the $recipe.
The variable must be declared before use, basic concept. what line 3038 is trying to do is reset the variable.

**Comment by keithkfng** [comment]
@laurobeleche try fixing it with a PR.

**Comment by andris155** [comment]
latest imagicalmine error:
```

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3032

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3041

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3032

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3041

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3032

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3041

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3032

Notice: Undefined variable: recipe in D:\Minecraft Szerverek\ImagicalMine\src\pocketmine\Player.php on line 3041
```

**Comment by matcracker** [comment]
Fixed.
