### ISSUE TITLE
please add experience level sound

### ISSUE THREAD

**Issue by SuperAdam47** [ImagicalMine/ImagicalMine#231420]
please add experience level sound!!!

**Comment by remotevase** [comment]
what do you mean

**Comment by Mike4l6** [comment]
when you get a experience point it will make the sound ding ling ling or something like that

**Comment by Creeperface01** [comment]
No sound sounds like dingilingilingylink

**Comment by remotevase** [comment]
lol. That's kind of a challenge, but I'll work on it. Give me some time, though. I still gotta figure out which folder it goes in.

**Comment by SuperAdam47** [comment]
okay hurry up! :D

**Comment by remotevase** [comment]
Well, I'll go as fast as I can, but we are more focused on bugs that crash the server, or don't let players join

**Comment by ImagicalGamer** [comment]
@remotevae dingilingilingylink

**Comment by remotevase** [comment]
XD who said 12 hours?

**Comment by Dev-Kevo** [comment]
lol
