### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by TheKnightGamer** [ImagicalMine/ImagicalMine#231452]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Optional information

@NiclasOlofsson here were you can help me with the maps implantation.

**Comment by NiclasOlofsson** [comment]
No thank you.

**Comment by TheKnightGamer** [comment]
That a shame well just got to work on this myself.

**Comment by TheKnightGamer** [comment]
You know why did I even try

**Comment by remotevase** [comment]
Implantation XD
You mean implementation right?

**Comment by TheKnightGamer** [comment]
Oh I wrote that stinking autocorrect

**Comment by remotevase** [comment]
Lol

**Comment by keithkfng** [comment]
What's the problem with maps? IM generated this beautiful world for me!
![image](https://cloud.githubusercontent.com/assets/13236085/14879131/c090160c-0d6a-11e6-9309-1da2379f3b56.png)

**Comment by NiclasOlofsson** [comment]
Well, Mojang added this really cool feature som years back .. http://minecraft.gamepedia.com/Map

**Comment by keithkfng** [comment]
Oh I get it... Oops. The item.

**Comment by TheKnightGamer** [comment]
OK I will check the website out.
