### ISSUE TITLE
Whats the 0.15 protocol?

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231442]

**Comment by remotevase** [comment]
We know this already. I need someone to find out the current protocol for us, as I dont understand how. I will make this into a chat for "what's the 0.15 protocol" @keithkfng I know you did this before, so I need your help now plz, thanks

**Comment by keithkfng** [comment]
I believe it's 60.

**Comment by remotevase** [comment]
Okay, I'll commit it soon

**Comment by remotevase** [comment]
It's actually 63, maybe 64?

**Comment by keithkfng** [comment]
Maybe. But remember I said that the 0.15 update process is going to take longer than usual? I'm pretty much dependent on Intyre pushing version updates to PM because I can't decompile MCPE. Move this conversation to forums, don't use the issue tracker as a messaging service or chat room.
