### ISSUE TITLE
Keyboard error.

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#231401]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Optional information
keyboard takes or does not carry the smartphone LG L40 . only in my SERVER .

**Comment by hoyinm14mc** [comment]
I think the keyboard issue is nothing to deal with the server software..

**Comment by laurobeleche** [comment]
but in Genesis operates normally

**Comment by remotevase** [comment]
Keyboard issue: I had this same issue. Get the latest build and you'll be fine
