### ISSUE TITLE
ImagicalMine Forum?

### ISSUE THREAD

**Issue by deotern** [ImagicalMine/ImagicalMine#231427]
When I go to ImagicalMine Forum, I saw there's no "Sign Up" or "Register" button...
May I know how can i register an account for ImagicalMine forum?
@keithkfng

**Comment by remotevase** [comment]
registration was closed due to high traffic of genysis users on ImagicalMine forums

**Comment by keithkfng** [comment]
Oops, I'll let you register @deotern

**Comment by deotern** [comment]
@keithkfng 
Done, I registered, but.... I go to my email, junk and inbox, I see no email is received from ImagicalMine... :(

**Comment by keithkfng** [comment]
@deotern I have confirmed your account manually. Just upload a profile pic and start posting :)
