### ISSUE TITLE
Error flood console

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231446]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Client information
latest dev. im, php 7.0.1, multicraft 2.0.1

## Optional information
```
27.04 14:54:47 [Server] INFO Notice: Undefined variable: recipe in phar:///ImagicalMine_1.4.phar/src/pocketmine/Player.php on line 3030
27.04 14:54:47 [Server] INFO Notice: Undefined variable: recipe in phar:///ImagicalMine_1.4.phar/src/pocketmine/Player.php on line 3039
```

**Comment by remotevase** [comment]
Latest build?

**Comment by andris155** [comment]
Yes

**Comment by remotevase** [comment]
Refer to #231450 for more info

**Comment by keithkfng** [comment]
@andris155 /\/\/\
