### ISSUE TITLE
Questions with ImagicalMine revenue and spends

### ISSUE THREAD

**Issue by deotern** [ImagicalMine/ImagicalMine#231423]
As I know, ImagicalMine do accept donation from others...
Idk if this is true, but I THINK ImagicalMine do accept benefits from hosting company that have listed in README.md

Alright, if my statement is true, then what is the money flow?
Don't tell me all money is spent for website hosting etc xD There's no such prefect ratio of revenue and spends.. Either there's money left or it's not enough of money...

If there're earnings, then how does @keithkfng use it? Putting these to his own pocket? xD 

P/S: I'm just standing in the middle of this issue, purely wanted to know more about the money flow of ImagicalMine

**Comment by remotevase** [comment]
Good question...  I dont think we get much revenue per month, maybe something like $15 US, and that is almost all for .net hosting...

**Comment by keithkfng** [comment]
I have to spend about $15 on the domain name and $5 for hosting the website and forums.

**Comment by remotevase** [comment]
YAY I was spot on with the $15!!!!!!!!!!!!

**Comment by dterweij** [comment]
No money left for the jenkins build VPS i guess thats why it redirects it to the phar creator page?
Altho i opened my personal jenkins build system for the public, it is used a lot... Would be nice to invest in a build vps id there s money for it. Else just use mine for the time being (url jekins.terweij.nl)

**Comment by keithkfng** [comment]
No, that VPS was free, but because it kept crashing we decided not to use it. I couldn't be bothered to setup another Jenkins server.
