### ISSUE TITLE
Server can not identify recent Imagicalmine phar upload?

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#231453]
## Issue description

Hello. I have recently uploaded the most recent update for Imagical Mine (.phar) but my server console is giving me an error and the server won't come online. Is there a way to resolve this issue? Thanks in advance. Here is what it says in the console:

27.04 19:43:25 [Multicraft] Server stopped
27.04 19:43:25 [Multicraft] Looks like a crash, check the server console. Return value: 255
27.04 19:43:25 [Multicraft] Restarting crashed server in 15 seconds
27.04 19:43:25 [Multicraft] Server shut down (starting)
27.04 19:43:25 [Server] INFO Failed to run command '/pocketmine/bin/php7/bin/php': No such file or directory
27.04 19:43:25 [Multicraft] Server executable "/pocketmine/bin/php7/bin/php" not found, server startup might fail!
27.04 19:43:25 [Multicraft] Loaded config for "MinecraftPE:ImagicalMine"
27.04 19:43:25 [Multicraft] Starting server!
27.04 19:43:25 [Multicraft] Loading server properties
27.04 19:43:10 [Multicraft] Server stopped
27.04 19:43:10 [Multicraft] Looks like a crash, check the server console. Return value: 255
27.04 19:43:10 [Multicraft] Restarting crashed server in 15 seconds
27.04 19:43:10 [Multicraft] Server shut down (starting)
27.04 19:43:10 [Server] INFO Failed to run command '/pocketmine/bin/php7/bin/php': No such file or directory
27.04 19:43:10 [Multicraft] Server executable "/pocketmine/bin/php7/bin/php" not found, server startup might fail!
27.04 19:43:10 [Multicraft] Loaded config for "MinecraftPE:ImagicalMine"
27.04 19:43:10 [Multicraft] Starting server!
27.04 19:43:10 [Multicraft] Loading server properties
27.04 19:42:55 [Multicraft] Server stopped
27.04 19:42:55 [Multicraft] Looks like a crash, check the server console. Return value: 255
27.04 19:42:55 [Multicraft] Restarting crashed server in 15 seconds
27.04 19:42:55 [Multicraft] Server shut down (starting)
27.04 19:42:55 [Server] INFO Failed to run command '/pocketmine/bin/php7/bin/php': No such file or directory
27.04 19:42:55 [Multicraft] Server executable "/pocketmine/bin/php7/bin/php" not found, server startup might fail!
27.04 19:42:55 [Multicraft] Loaded config for "MinecraftPE:ImagicalMine"
27.04 19:42:55 [Multicraft] Starting server!

**Comment by remotevase** [comment]
Try to not use Multicraft and see if that fixes it. Also try a fresh install, then copy the plugins and settings

**Comment by GlitchPlayer** [comment]
Please read first. There's no valid PHP 7 files in your server.
