### ISSUE TITLE
Updating for 14.2 compatibility

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#231444]
How do you update for the latest version of ImagicalMine? I have tried all the tutorials I've seen and none of them seem to work for me. Where exactly do you find the "server file" or is it just FTP Client in general (with all those other files). I recently uploaded the recent 14.2 compatibility file and it is in my server files, and yes, the server is working but I still can't seem to join with version 14.2? Any solutions? Thanks in advance.

**Comment by DALTONTASTIC** [comment]
Somebody add 0.14.2 protocol to https://github.com/ImagicalMine/ImagicalMine/blob/66e5e29f1cd453b8659b8260f0af45af6af2b1a2/src/pocketmine/network/protocol/Info.php I can't edit that branch!

**Comment by Riegert** [comment]
It updated a while ago, these reason may be why you can't join:

- You did not download the latest phar at the website.
- You did not delete the previous ImagicalMine.phar and replaced it.
- You uploaded it in the wrong directory.

It worked for me.

**Comment by DALTONTASTIC** [comment]
I'm reading that you can't break or place and there's tons of bugs?

**Comment by Pandaken** [comment]
Riegert, which directory do you upload the phar to? And where do you find the previous ImagicalMine.phar, because I can't seem to find it. Im using MultiCraft, if that helps.

**Comment by Pandaken** [comment]
In other words, may I have a step-by-step process because all those tutorials I have seen aren't helping me much ._.
