### ISSUE TITLE
Still Having issue with Imagical Mine Update (Using server host)

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#231458]
Hello. I have been continuously having the same problem and tried different methods but is not resolving.  I am using a Multicraft to run Imagical Mine on, and I understand that you have to replace the old phar. with the new phar. However, the new phar in console it says: "This server is running ImagicalMine 1.4 [ELITE] implementing API version 2.0.0 for Minecraft: PE v0.14.x alpha (protocol version 45)". I re-dowwloaded the latest phar. from the releases and it doesn't seem to work. Also, I believe start.sh is for people who run ImagicalMine themselves, but I use a server host. May I ask for a solution, and just in case it doesn't work, may I have a direct download for the latest Imagicalmine phar. just in case I'm downloading the wrong thing?

**Comment by drgimatt** [comment]
Why are you trying to replace the imagicalmine.phar in the first place? Are you updating your server to support new versions?

**Comment by Pandaken** [comment]
Yes the most recent one that came out to support 0.14.2

**Comment by drgimatt** [comment]
Here's the link for the latest version of the imagicalmine.phar: imagicalmine.github.io/ImagicalMine/list.txt

**Comment by drgimatt** [comment]
Once you update the server it will still display: "This server is running ImagicalMine 1.4 [ELITE] implementing API version 2.0.0 for Minecraft: PE v0.14.x alpha (protocol version 45)". That is normal, just make sure that you indeed updated it correctly.

**Comment by Riegert** [comment]
That's weird, I replaced my .phar and it worked flawlessly.

**Comment by Pandaken** [comment]
Oh! After playing around a bit, somehow it worked. I think its because I used some tutorial that kept telling me to change the name to pocket mine .phar. Thanks anyways for trying to help.
