### ISSUE TITLE
Long list of 0.14.2 bugs

### ISSUE THREAD

**Issue by jjplaying** [ImagicalMine/ImagicalMine#231447]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

Bugs in 0.14.2:
- You can't place blocks in survival or creative, there's a red message: "You can't place blocks here". Even if you have nothing in the hand and tap a sign for example, there's the message. PlayerInteractEvent seems to be cancelled too, because you can't use signs.
- You can't break blocks, it happens absolutely nothing (no break effect), like adventure gamemode on PC
- When you leave, there's a black screen for a short time (1-2 seconds), but the GUI like heart bar and chat is still there.
- When you write a colored message in the chat which has more than one line, the color gets removed in the other lines.

A bug which is not in ImagicalMine (I think):
- The chat is too high so there's the heart bar and hunger bar in front of the first line of a chat message.

## Client information

Mac OS X 10.11.4, Latest ImagicalMine, PHP 7, Client on iPad Mini Minecraft PE 0.14.2 and iPhone 6 Minecraft PE 0.14.2

**Comment by HimbeersaftLP** [comment]
I have the same problems on Windows Phone and on iOS (iPhone 5c). And there's one more issue, but I think it's MCPE, the popups are to high over the inventory bar, so a scoreboard e.g. will cover nearly the whole screen, that even irrtating on my 5 inch phone

**Comment by HimbeersaftLP** [comment]
That are all big problems, but I don't think they are IM's fault...

**Comment by jjplaying** [comment]
Sure, it's not IM's fault, but IM is the only one who can solve them

**Comment by jjplaying** [comment]
So the chat bug and status bar bug hasn't todo anything with IM, but the rest can only be solved by IM

**Comment by XxPeaceHellxX** [comment]
does not place the blocks?
In version 0.14.2

**Comment by blui22** [comment]
Look at this and you might be able to fix it. https://github.com/Nukkit/Nukkit/commit/8f18813820c241190f3ba18d54dc1119cb89303d

**Comment by blui22** [comment]
You might be able to fix it with this, PHP version, https://github.com/PocketMine/PocketMine-MP/commit/ac482621a108bfde0919e58d5aced382a760e719

The comment above this one is written in jar.

**Comment by keithkfng** [comment]
@blui22 this is actually fixed now :)

**Comment by remotevase** [comment]
@keithkfng @blui22 although, that IS what we ended up doing

**Comment by remotevase** [comment]
Oops lol
