### ISSUE TITLE
Phtreads 3.0.7

### ISSUE THREAD

**Issue by Dergercol** [ImagicalMine/ImagicalMine#231404]
<h1>Pocketmine with pthreads</h1>
<pre>Can i get any im or pm or genisys with pthreads 3.0.7?</pre>
<pre>I wanna get any link</pre>

<h6> Thanks...</h6>

**Comment by dterweij** [comment]
3.0.7 is old. Current is 3.1.6. Compile PHP yourself with 3.0.7, but it could fail PHP and/or starting IM.
Just use the latest PHP packages provided by IM. DIY link: https://pecl.php.net/package/pthreads :)
