### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#231466]
There were a couple of things I spotted on my console that I haven't seen before. Just wondering if anyone had any solutions or explanations for these:

29.04 16:55:46 [Server] INFO Notice: Undefined variable: recipe in phar:///imagicalmine.phar/src/pocketmine/Player.php on line 3041

29.04 16:55:46 [Server] INFO [16:55:46] warning> Can't keep up! Is the server overloaded?

29.04 17:05:47 [Server] INFO Warning: Illegal offset type in unset in phar:///plugins/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask.php on line 46

And just wondering how to reduce timeouts? Thanks in advance.

**Comment by Pandaken** [comment]
Also, I tried minimizing the amount of plugins with lots of data and server dump files, but it doesn't seem to be helping.

**Comment by keithkfng** [comment]
Try submitting it with the correct information. It clearly says not to delete the template and you just went ahead and did it.

**Comment by remotevase** [comment]
@keithkfng this person has never ever submitted an issue correctly, and I've read dozens of his issues. Usually, he posts the issues IN THE WRONG REPO!
