### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by iMOEchan** [ImagicalMine/ImagicalMine#231461]
When i type ./start.sh it said : Segmentation Fault

IMAGE : http://i.hizliresim.com/v5qBQD.png

**Comment by remotevase** [comment]
Try to remove all plugins, and do not remove the PR guidelines. Issue closed until more details are provided

**Comment by iMOEchan** [comment]
what is that ? “PR guidelines”

**Comment by iMOEchan** [comment]
what is that ? “PR guidelines”

**Comment by keithkfng** [comment]
Typo. It's issue guidelines. PR guidelines are pull request guidelines.

**Comment by iMOEchan** [comment]
SOLVED WorldEditArt and ItemCasePE caused the problem

**Comment by iMOEchan** [comment]
OOT - Can you accept my registration on forum ? my username is MOE thanks!

**Comment by remotevase** [comment]
@keithkfng lol oops
@iMOEchan wow, I wonder why that happened...
