### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DarkWav** [ImagicalMine/ImagicalMine#231431]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Reproducing the issue

 PHP 7.0.5@ImagicalMine1.4dev@Intel (R) Core i7 4790K @4.40Ghz
## Optional information

Bug Report: 

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwtv28aW/itTuUDlhSRLsmXHKtxdX8fpDW4e3tjdLBAFxogcSVNTJMsZWlaL/Pf9zpkhOZST
xmjvbrGLbRpUnJlz5rxfZH/rWL1Wneno6Hh0NMSfw14nkcZeFkVWdKa/dew2x3YnzayOVKfXWStj
5JKWzDa18kEoOtkTZaoechVZFYvvImnUd6J7c3txfn25D6BFmSQvdEJQF9PZ7OVaLnUkk9c6VbOZ
KaLZLM+iO2XXvHCVyK0qBvkqJ1AHdoBTB82hA3cG+wmeOtPD4dGzXscWEjROP3T2hmIX4FoV96ro
Tk6G+1Nh8uRWljZLMhnfgpCka2yh06V4TAaRvzf6Errx4fEE+EIwtzOdLpX9Ua7VOovVNSPv6tSq
pSrEkHGOv4RzdHp0+lmc/R+MlYXtzrMsUTJlLIePsFzxTxJtdzIafwHR7W2UpeC5jGw33L/I1rm0
ep6oC1iBeQX5gOBs/jM022thKq1OzGz2Wur0VbZcBqe8KB8r+o9t5Um51Cmu2u98/NTrqH+uYT7Z
unC1o6QzXcjEqF4ngmaJkMPh4SlwzGz15xMAATIMFhUg9KL7baEinSsBfqxMI5UtxPVK5ioB7e94
a/83BzxqYfRwY3EmUrXZhel+m0sivf9DVtq8tB+GH/e/d2jGLTSLrFAyWlVkjPs/wEhfpstCxVql
9pU2trsvpBHfwjosVipqDoFGNHjoD3FjV9p4HPc4nRXb7n7/B4KFVZhujWVf1BTqlAj8CEaqXU/p
0edEOAkW/dJxQ4pfOWlW5uDvziN85mFJ5+KqyGwWZcnLdJFNpxfvzl/cvHzz4+3lf1y+ubm9Or/4
x+XN1IE1qtQLUbFocrlJYUBnZ2eCtS+yQnzjN7U5T/S96oJNJ65JqPmApEmj1E/OIET3G22MstU9
G53G2eZlGquHD7XI/GL8sbkgVGtFRaUCUKvS+MIJ1zjM3hwmhyFcfufN6cIpTBUXSWbUFV/brUCO
2iAVOTomFe6S6GEmj8mLpZUeM7BUyI+/IKiTRlBu4Vm9ULkQbve68SENZnhRyIVFFHktU0SCgowR
q7tOomNc/+n/s8X/+WzR6ywVrFomFKXBiNEZondnNDiCLOalTuLOdIiw7mNDZ3p03OvIXOPMeDAc
DHFqqS2ehk/8BwCFvEv0nGAGzxhDmUqqrzrv2UWMeHMjrl6dX78+FyNcIZgM/Jw8Oxbd6sxouC80
VgBORdC0cwJyJnj6FZ6Nx0NPHTZvM0PIX755c4MFfoAzdupsZYj3q7JQl6nVVit+9iS1lnstCRF2
mPwqKwx5yFond8hJJyRTFtCHWkKjwegIP7ChUglLAH0wFKTHWOWglsCxZ7KFfR4urCVlUkYMpYEQ
5QmBJ7XJIq/Dyeub83c3P11hYaPmRltiYGVtbqYHB9DSqpwPomx9UFF60MICcVwizuIRwfvqMpBB
a7ktg9HgsC2FV/BHMPB28fri6lLcKLkO5OHl0POC+YPyCMmZzZxDNTK4ent98/7tu1fPvyYFR6kj
9KDFIkmCpLL1MTIURWs9lMV4cPI/ag9sC9u1o2Q22yXsD1pEGw0E8Rrl0A0sL/SJZm3HIfrnSb6S
bTGsdgxgXEng8M9bQk0IomZA0+9ZQoouC2z9TaXR6rUs7gK2mrW/mC29sPCb2awmKPj5NPaQdGAZ
8XO1APKWAe/uPIFVR85/P7s7pD1aeCLrvr65IUJe6IeQ992ttv8+Sc//BH53yQCjjwl7AqfPJbK6
QiGMzG6zUMm7OztK3s1cr7S1ifqbXr6+aDH7J3gMUM5mO+S4EudpPL6QxToMPe65zc+4L/86o2WC
/H+extKPiNyJgmEHbDVrIWvDwelfFXpqgoKfT2OvKjWfq/sbVNWh8h5ttfV4NBi1GW3qbi4kBGKB
QPG/XWi0mfOteI54+F7etxLsKJDBn020u/Q2dXTAwZcTrRfIOVLqxUpJG0iiWWuHoPGuCDyLoks/
yv2vs+oNYfxHefYXzmYhiV/hkQppWYAzq4oKPXdFA7QNuSpcSd3Zu6qfqJ1e6KWg0dKsmKV7Lwot
zvNCjMdiNJ5OTqeTQ/G36xsxHo6O6cA6s/EZ/fCdbJ4V9mx0Ojoc0+JmBWL6iTb2LFssaEWmaVam
kern3HL2ZbTS6l6tqd0/y1LGRPOKPjU26LGggDN3U6FiY7NU9aHmqEwkbzmItXzw+MzZZMjXJEm2
6S8SvVzVVzu8MtVrVJOtu9bZvFpY+j72jNEssgKk1mse0UoWcYSypnrO73MPHevFQoM4uz0bMTZu
4RBa+0ZZSiSGZZWA46RPJne2yYokbtaMUnFwhMaEZ88vX5z/9OqGVp3h9H8pVbH1V/qlIiJpOHro
9yBHTwvk8dm/8D8QSWmzvpH3qqbVMGSSLUnbtZScHnUOLcKUj5+R7Y9PaIuatrotHmzXCc2u9gQl
DRGx3ZQFq4XNR0B4otXfkj2Jm5UySlTiELJQwq6UgGINfkgrIjIRK+Y0aIySMkZIAf5HduuwXWdr
wC4IxS5WIxeqJzLsFIaQCp7RiG1WFh6b0AsKW5rDFi7LigIWl2wd6jdqUyM8iNVCQq1GbLL0Oytk
nitZCBLpGhzTWGULFgQNdRzzm5VKRZkvCxkDwYBQOuk6hFN6EHs3K1TG/QSLoCaR6bJEPhY0m2Xp
eV0Yjeckwy36V5avA0YQiDw/bVAQUrUSKh1s9J3OVazlICuWB/R0QLPS22xx+/L67e3x4Wl/fEtw
LNIa1VTMEKeWs4677P1KkSSFzQRN6AQ49nMMqK2QqYFDQoq8zbJlennUCPZYxbG615ESK2SLhJW+
ZtTOx5preUTJO2ZV2jgj/3TTcSLJTXVERMO+eABrkumdYWFRAKCxCriHskPD8yR9U/FyTsFBUFTi
OZgbNYh7LcW/k2PxIXaxvt+bCgrUDvh6BVhJ9m4ysOFJc/qWHpkoDawZYR32xGI5v3qJk0gesRNy
s9UHYXPwEl5xyS5d4aLkStFGwPZhWkQyUqw3SAbwIaDeD2W4915DU1kK+5RxLAplnBkTuTDcO5Al
TVlwABYw3rki2UCc6pdSJqTPpb7H2XuZlEp0/bUI//uM3t2J8KMo8PdhEDQfm2Lf3f6mXM9pXrYQ
52abRjfS3MGFijv45MCd+Al69Ppz7NK5VZEhTcCycN70BAdJ4YMp7L8HgawhQUP5mQWEvEdr6zKl
UharHvs12x74gscW2QNCv1UQBdhiv0lr8kjCFUkvF+T4dIgcvCe0/Q4ytAXDxYrSEhv0DrToggto
XoydbJiTvud2yriqMED5pNj6IPBjks0hakr8wm3ANtfaUthbq6Wcby1IE9eOpCET4WJ3FUTA30Yz
iSx+QbnPYao0YlhKCw0zgnMomrYTngXCT3WnMwmwVbJBLzNwlJGvkfz4piUT2mfipmJYMSP2OANY
xDIZ/y9ggwqqrzBBGf5PMoFaJWc6fDys6fL4jIDbUZJWcUMV3VuRNhqPhgF5V6rQGadCcltDN0ec
ADyZtWuOcCOiU+yMkM/04TaIMKMGG7010Sk8GrKkiPIlUTsRo4xLOK1QbHDHHHKHBZ7aeH4detxF
bynyUJ5lqMFjCJKEr4ch11xFlI4NS4qodoJ3sDUrEK7KTcPy4dDzbPa/QJeXwGEj0KUs5jCQfpQl
iasznTt+VtJscUSShxIeCg6P/qvk9B9SgwKphKHs96pA8shSvKm4wLxYVCFl3RjhQLx1GZefYC6r
rEzimhSNwLNJRUO+M26RM/Vg9XgYmI/Ye8FO8yi4sh05HDVziyJbV1HaQfsT/TCkNRmrYsgr9LGd
fMa8dg2FSvhoVSKZV2p4xX5CwZWXiVBqd4hB4Yr9Hjt2gerIuEN9Kk2o3GqwOWSVFXjXmrQk8zxz
0LvKpdxCNZ2DbSNy1/mDf1YSLWjOdehxYO2VKKpK3V9KW0G58FWU9DdVlrQWlJ0wp8Ql3rm0aMKo
EuJ3jMi3sEEf6Nh9XXHtd110m6s6Bfv4tRfGxGqP4kextYS9J/qjwAlcquWr+7YiZ4ozVXxq8ju3
QpRYYxdEvZIdMBY9YQPxd3R7kPoZinrY+sXVTz1B3xngYBpvdGxXLif4EFFf0OcLpuKkLkiaYsWV
lsHhgTiP4YwrmSwO0LO4GipWsEd/Ga51dpqloTcHFUGArVWpXT6Q71IhJpOeiwx0uX+vhlq34MCY
cY3x01V6VVUoTQtCRRgBbZBHGGmZp3nfL7QrQ24B1bxcVjaR+TAsKCcVbP3qQUWlK7gojtELvEG9
a8hMuIrKV/lAp5rIGdUV1A9iRJWTT4ZUNPNtVcHM0BTxfCEdwI134GR8T5+bxE9A4DU5DOtoIw6M
lbaEXR8so0r5NL82O+KoWvCdFk1VxTZJFrJ2bSof9t5ACmHTjKBq6x3CA/Ud0FSssbmsmzdwysMf
Ih8+Ar/iqCtbdyBBUCtsAxIgY/uYIg403sj23ry9uZwKTi/4NyrR1aboahmVXucJ1/qeSH97TWRg
jucty4rQaCE0eq7Z6jkTgx6ycvoEQxwNfcakEO0SsjN7mjzQjs/Cdehqb1TR+WhYBxRXB8zpI5jm
yu4ILj5+fFdP0CdGo89tKBsN9n3EMSqkxRvsDWGnntaPkQR9auTupBLIaZdnCc2QgSIZd5JUWbp4
JpON3BqH32PasbENDGSlikdWli2X3NqZjbZ0c+2NiAA+ZAoP23Qp8D4YoFk5LaTch7ozZBHhpIMi
Yo9bmH+DTqOCQmbxnambLis+9/KxPnnw3qH17x/DrtNfGPavf6ecJ9NtVQY5OmXqrZpUWpEZl1R+
/qu4Ki1sv2qoCjT6BRw0W886LgCjR0WL5PG5POkF6demwgN4ObfqAS/k83VWpmFJYXz/UCmdTIZ0
51pbIKcH2Mjw9+BlgdXYGYxDtFvQVPXGZzCwQFLlJidz5TDOFX3rJng2STZBAgswu5llkDS9DV/L
ewRv0rimSZGisUG+9dMxX+LU1TSLdSGNZYtmKdXpb1EmfDAzCBt9Cp46cnUJDw4KGkbBNYG4EtzP
mTMi7nfkmrx17fMsVSu1IFqu4FREIm5U9Fo+CLkrJHTuERcajVfuaOiZl+87GevSBKBeOdJTyuGz
AvdRgCBqHfPAuF/msWSbasJhlCjpbuNxdrvCcpw084mGmcFjbnza2kjN46dfSlUqr32Pwcdm3ukb
aJIs6A+izLO8TGqU/omKnsfY6S+Hzj4E61hww/I+W5yhyOzIWNMHVRTE/PqojuY0X56KqvWotE+f
cJX5VJw2dbczYo74VZnrsQLf2LPr72f1+JWNpIvr9fHEH1zP6SNQFHGT6gZOLm4uNa0SCo3SComA
6db94NCZV+UBvhkNAhr5R58mpLtrdRDfWUdBpOlbzcB+VhkZDV8+CIboqMtretMs3a6pZ2WPM1CF
CQinftwfEM0BZoA+TxRyuUR94cdj9RiSUgJ9Knj3iLtd0gin+RJpiUbarKi5fJBURVSPVKPB+vzb
sqnwP/wm7IEmIVPxgX72kTB7PBr5WBddWeX7IpwxUyyrJ8lLQeKkCoWqUtdE3ImufyeA/f1BwNxO
mIGLLCt73hNPSrQOpI0z9PeqIZsnEFcdwcSHCUrek9OP/qoL/0qEakONq/h03cdzYQdIn82Fj7vg
z1BN4XhzQ5imaxI0QF+rxHJDxaOAeVlwkqBBueBOy3C5UxccHLebYjZ8TcLFa9VDu/lG9cKKC/7P
vXdhirjuMVxz0t1rlKIaJuHLw5aZTJuu1vs5veOiWHLkHusrp8K/6ZqOvz/pTU4fRr3Dh8Pe+PvR
9zHqOBdau7ZQeED8O3s2FEv4k3FPRxNX4KVsQ1+96o079ugmV7prhNg0fiKq5+7072H0b8+0fynR
vD/zX+OrB6tS8hp+K3+B7B98NzmPYPirYIFerKSxLMIl/z8UVM+Uv4LHhU6sCs+vEIfqbyU1dQHB
5s+mfvFP22hctrkN9q+vXgVPedSi9p1a+OFJsGhcuxuuWEksxMHSemt+SfgTUf9LTLAzGvdjdS/6
9MZ5MjwanuDnty8pgMWH80Us58dHR8g30enxfDyZK7k4Po2H49HR0cn8ZH6koon4FrhtdqdS5LpQ
Br/q3H0qSW/l8eg+fa128fTAbzhrkWZr+hRgODwcjcanWLh6/jbYvlqxQuitP2G75k7rP1+Hkmrj
28TxQ3uT5gQtCrG2KXRbc+jnkl2h6VCweLTqkL9SOSHR0RpHdROCzd3Lu2BpK5k8/mzh3QV9M5n7
0SN/tDsa0Be9aAtu48zCMwLIZahFdAp3hVrw/STYT5/+C/rjWpY=
===END CRASH DUMP===

**Comment by dterweij** [comment]
Show your console errors too (or show that part from your logfile if turned on).
Also describe when it happend.

**Comment by DarkWav** [comment]
problem already sloved.
//closed
