### ISSUE TITLE
error while loading shared libraries: libltdl.so.7

### ISSUE THREAD

**Issue by alicheek** [ImagicalMine/ImagicalMine#231406]
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

Get this after using your : curl -sL http://get.imagicalmine.net | bash

was working fine before but seems a recent change has messed something up 

Thanks in advance

**Comment by SkygridRex** [comment]
I using ubuntu same problem

**Comment by alicheek** [comment]
my issue was solved i had to install a build of php7 on my centos 7 server fixed the issue
