### ISSUE TITLE
0.14.2

### ISSUE THREAD

**Issue by Muqsit** [ImagicalMine/ImagicalMine#231445]
- [] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
Players cannot interact or break/place blocks. There are some new protocol changes to 0.14.2
Maybe revert the protocol 60 commit?

## Reproducing the issue
Use protocol 60

## Client information
PHP 7.0.4
Ubuntu 14.04 64-bit

**Comment by remotevase** [comment]
You title it 0.15, You talk about 0.14, and then you switch back to 0.15...
Please reword this, and recheck the 

>  This issue is understandable - feel free to use your native language to write issues if you are not 
> comfortable with English.

box please

**Comment by Muqsit** [comment]
Apologies, *Title must be 0.14.2*

**Comment by Muqsit** [comment]
0.14.2 uses protocol 60, where's the third switch, there was only one switch?

**Comment by remotevase** [comment]
Thank you. What do you mean, "where's the third switch"? Are you talking about the jump from 46 to 60?
