### ISSUE TITLE
API is missing a lot, 

### ISSUE THREAD

**Issue by BenasPaulikas** [ImagicalMine/ImagicalMine#231426]
$this->api->addHandler("player.block.action", array($this, "handle"), 15); //Priority higher that API
        $this->api->addHandler("player.equipment.change", array($this, "handle"), 15);

This was in pocketmine, how do I make it in imagicalMine ?

**Comment by AndreTheGamer** [comment]
Hmmn, that's outdated @BenasPaulikas

**Comment by iPocket** [comment]
This is old API.

**Comment by BenasPaulikas** [comment]
Yes, code I showed with *$this->api->addHandler* is old. But I didn't found any reference to new API
