### ISSUE TITLE
Issue downloading updated imagicalmine phar.

### ISSUE THREAD

**Issue by Pandaken** [ImagicalMine/ImagicalMine#231457]
## Issue description

Everytime I download the latest release it gives me the same release I had before? After i upload it into my server it says:
"This server is running ImagicalMine 1.4 [ELITE] implementing API version 2.0.0 for Minecraft: PE v0.14.x alpha (protocol version 45)"

Everytime i try to join my server it says that its outdated even though the new imagicalmine phar is uploaded. If possible, can someone resolve this for me or give me a direct latest imagicalmine phar. download just in case I'm downloading the wrong item? Thanks.

**Comment by remotevase** [comment]
We fixed this in yesterday's phar builds. Are you using 0.15?

**Comment by Pandaken** [comment]
Should I download the phar from the releases here in github or from imagicalmine.net?

**Comment by keithkfng** [comment]
This depends on what OS you installed IM on. If you installed it on Linux or Mac(I think, not sure about Mac), all you need to do is run update.sh, specify which PHP binary you installed when you installed IM and then start it again. If you installed it on Windows, you'll have to download it from the releases, yes.
