### ISSUE TITLE
/banclient playername not work... clientid missing banned-client.txt

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231419]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Reproducing the issue
/banclient playername
`|2016-04-15 21:49:24 +0000|Yasacu|Forever|Banned by an operator.`
(clientid missing)

## Client information
latest dev. im., php 7.0.3, multicraft 2.0.1

**Comment by deotern** [comment]
d0dc5c38b27be6a4217ebc27ce51ee13143306de
