### ISSUE TITLE
Not work crafting survival inventory

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231408]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Reproducing the issue
1. break log blocks
2. open inventory craft menu.
3. Not show wood crafting.

## Client information
latest dev version.

## Optional information
![screenshot_20160408-134638](https://cloud.githubusercontent.com/assets/8324198/14382843/207f2d94-fd91-11e5-9263-a07dc78305e0.png)

**Comment by Craicerjack** [comment]
Having the same issue. Fresh install on raspberry pi just in the last hour.

**Comment by alicheek** [comment]
i can confirm this issue

**Comment by Ad5001** [comment]
Just use the Crafting And Benchemark plugins that are on the IM source and installer ;)

**Comment by remotevase** [comment]
The IM installer contains CraftingTableFix. Although, that is old version. Google it for the newer version of the plugin.

**Comment by alicheek** [comment]
@remotevase what do you mean exactly? im running on linux centos 7 the only thing i saw of a crafting table fix was this : https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/blob/master/README.md

**Comment by remotevase** [comment]
Never mind what I said. The IM installer contains the latest (and apparently the only) version

**Comment by andris155** [comment]
CraftingTableFix - fixed this bug
Thanks!

**Comment by alicheek** [comment]
Where is this fix exactly i cant find it?

**Comment by alicheek** [comment]
@andris155  can u send me the link?

**Comment by andris155** [comment]
https://github.com/ImagicalMine/ImagicalMine-Windows/tree/master/plugins
