### ISSUE TITLE
new bug?

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#231463]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Client information
WINDOWS 10
PHP 7
LAST BUILD OF IMAGICALMINE

## Optional information

Warning: yaml_parse(): end of stream reached without finding document 0 in phar://D:/MINECRAFT/ImagicalMine/ImagicalMine-Windows-master/ImagicalMine.phar/src/pocketmine/utils/Config.php on line 158

Warning: yaml_parse(): end of stream reached without finding document 0 in phar://D:/MINECRAFT/ImagicalMine/ImagicalMine-Windows-master/ImagicalMine.phar/src/pocketmine/utils/Config.php on line 158

Warning: yaml_parse(): end of stream reached without finding document 0 in phar://D:/MINECRAFT/ImagicalMine/ImagicalMine-Windows-master/ImagicalMine.phar/src/pocketmine/utils/Config.php on line 158

**Comment by BlackShadow1** [comment]
Plugin issue.

**Comment by keithkfng** [comment]
@BlackShadow1 you're back :D

**Comment by BlackShadow1** [comment]
@keithkfng Yes, but I don't have much time

**Comment by keithkfng** [comment]
@BlackShadow1 while you're here, do you care to look through and try to fix some bugs? Thanks!

**Comment by BlackShadow1** [comment]
@keithkfng of course.
