### ISSUE TITLE
CraftingTableFix v2.0-Alpha - slow onPlayerJoin event

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231434]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14761269/7fd2c320-095b-11e6-9398-88c9f754c18d.PNG)

**Comment by dterweij** [comment]
maybe the plugin sucks :P

**Comment by remotevase** [comment]
lol @dterweij
