### ISSUE TITLE
Chat Not Working [0.14.0] build #25

### ISSUE THREAD

**Issue by blui22** [ImagicalMine/ImagicalMine#23852]
The chat does not work and when you try it shows this : 
 <%s> %s

**Comment by DavidJBrockway** [comment]
i dont have this bug are you using the stable build

**Comment by blui22** [comment]
No I am using the 0.14.0 latest build. I will try the stable build.

**Comment by blui22** [comment]
The latest build is #25 and the stable build is #25.

**Comment by PocketKiller** [comment]
list plugins.

**Comment by remotevase** [comment]
yes, this is most probably a plugin issue, as many other people do not have this issue.

**Comment by blui22** [comment]
Here are my plugins: 
ImagicalMine 1.0dev: AdvancedMOTD 1.0.1; Afk 0.3; AlwaysSpawn 2.2.2; BanItem 2.1; BenchMark 1.0-Alpha; Broadcaster 1.16; ChatCensor 1.4; ClearLagg 1.1.0; CommandSigns 2; CraftingTableFix 2.0-Alpha; CustomAlerts 1.6; CustomRanks 1.0.0; EconomyAPI 2.0.9; EconomyAuction 2.0.2; EconomyCasino 2.0.2; EconomyJob 2.0.4; EconomyLand 2.0.9; EconomyPShop 2.0.2; EconomySell 2.0.7; EconomyShop 2.0.7; EconomyTax 2.0.3; EconomyUsury 1.0.1; Farms 1.2-alpha; JoinCommands 1.4.1; MoreTrees 1.0-Alpha; MyDearest 1.1-alpha; PlayHarder 1.0-TEST; ImportMap 2.2-1.5upd2; PocketDockConsole 0.0.14; ServerMail 0.0.2; SignPortal 1.1.2; SimpleAuth 1.7.1; TimeCapsule 1.1.1; TimerBan 2.1; WorldProtect 2.2.0; EconomyAirport 2.0.4; SimpleAuthHelper 2.0.4; SimpleWarp 2.1.0

**Comment by PocketKiller** [comment]
remove all plugins and text/

**Comment by ecoron** [comment]
Try this build http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/lastSuccessfulBuild/artifact/releases/ImagicalMine.phar
