### ISSUE TITLE
Chunk Bug 0.14.0

### ISSUE THREAD

**Issue by DavidJBrockway** [ImagicalMine/ImagicalMine#23961]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

Hi i am aka Zena my server chuncks wont load but the old version of imagicalmine worked but it is a carazy bug and it carshed my server players cant move as well.

**Comment by blui22** [comment]
Yah  i have noticed this in my server too. Just restart the server and it will be fixed and wait intl a new build comes out.

**Comment by darkspive** [comment]
Yay!!! You are cool!!!

**Comment by DavidJBrockway** [comment]
i hope it fixed

**Comment by DavidJBrockway** [comment]
This bug could be the world bug geneartor or something in the src file i can code but i dont nkow that mutch still learing at https://www.codecademy.com/learn/php done %50 of the coruse

**Comment by PocketKiller** [comment]
are you @ZenaGamingsky ?

**Comment by remotevase** [comment]
I also have this same bug, and I think it can be fixed in pocketmine.yml by changing the chunk/world settings.

**Comment by PocketKiller** [comment]
@remotevase no, it's a problem of sending packets to client...

**Comment by DavidJBrockway** [comment]
yes

**Comment by DavidJBrockway** [comment]
can you help me on fixing mcg76 skywars

**Comment by DavidJBrockway** [comment]
https://github.com/DavidJBrockway/SkyWars-old-mg76- the carsh dump cant fix i have fixed his spleef

**Comment by DavidJBrockway** [comment]
plz dont ban me agin i stoped makeing pull request

**Comment by PocketKiller** [comment]
@DavidJBrockway I'll unblock your old account if you stop making invalid pull requests. Ok?

**Comment by DavidJBrockway** [comment]
can you help fix skywars

**Comment by DavidJBrockway** [comment]
my old acount got hacked

**Comment by DavidJBrockway** [comment]
and cant use it

**Comment by DavidJBrockway** [comment]
PocketKiller i have been learing php now %50 but i can code a plugin but cant fix crash dumps yet

**Comment by DavidJBrockway** [comment]
sorry going of topic i cant fix it i loocked at the packets to client it needs a update

**Comment by DavidJBrockway** [comment]
i been hacked so i dont use that any more

**Comment by PocketKiller** [comment]
@DavidJBrockway seriously learned %50 PHP? nah you PM pulls are still invalid and yeah STOP_GOING_OFFTOPIC

**Comment by keithkfng** [comment]
If you keep making bad pull requests and keep bypassing bans, I'll ban every account you have that I can find with GitHub Support.

**Comment by legoboy0215** [comment]
> I been hacked so I don't use that anymore

BS...

**Comment by DavidJonathanBrockway** [comment]
Hi i am back agin befor you blcoked me plz read this

Sorry for all the pull request i was just trying to help i have re learnt php and codeing plugin but i have a sc / asd it is Autism i am verry sorry for what happend block me if you want all i did was report a bug i have cahned and my old acount is hacked i cant get control over it ban me if you wnat i dont care wont make any more acount

**Comment by DavidJonathanBrockway** [comment]
I get it am am usless and cant code some stuff and stoped helping but i was just trying to help add more stuff i am so sorry for what i ahve done i would like to donate $15 for the trouble i have caused you

**Comment by DavidJonathanBrockway** [comment]
or $20 plz send paypale and i payyou verry sorry bye

**Comment by DavidJonathanBrockway** [comment]
sorry

**Comment by DavidJonathanBrockway** [comment]
Keithfng plz dont ban me i am sorry and wongt make any pull request

**Comment by DavidJonathanBrockway** [comment]
fix this bug

**Comment by dterweij** [comment]
Someone working at it to fix this? Put label in progress to it :) I think this is a prio bug to be fixed above all others.

**Comment by keithkfng** [comment]
Of course nobody here's gonna fix this bug. It's an MCPE bug - and we can't fix that LOL

**Comment by dterweij** [comment]
ah okay. But why it is only in for example Imagical mine as server and not when in local worlds and connected clients? or do i think wrong :)

**Comment by keithkfng** [comment]
It happens on local worlds for me sometimes - I get stuck into an invisible wall when I'm flying and chunks load as slow as a tortoise limping LOL

**Comment by dterweij** [comment]
Is it this? https://bugs.mojang.com/browse/MCPE-8159 Not reported for 0.14.0 yet.

**Comment by dterweij** [comment]
Tho I never had this for IM 0.12.x / 0.13.x. Chunks always loaded fine, flying or walking. Now it is annoying, walk/fly a few chunks and then the "wall". TP to another coordination and no Chunk loading at all. I never had this problem before with IM and never seen it with client<>client worlds.  I have to relogin a lot to play. Like relogin 25 times in just 5 minutes playtime. Before 0.14.0 I was even connected for days without chunk problems. I realy think something wrong also with IM.

**Comment by keithkfng** [comment]
@dterweij feel like looking at this - https://bugs.mojang.com/browse/MCPE-13577
So maybe it actually is an MCPE bug. I mean, Lifeboat, they don't use IM do they? I wish they were :P

**Comment by DavidJonathanBrockway** [comment]
Ok

**Comment by dterweij** [comment]
Everyone should report there, then it will be fixed faster :) I did also.

**Comment by ecoron** [comment]
Now i get it too, and players report it also. Occurs sometimes local and mostly in external Servers. Hopefully mojang will fix it fast, but we should also take a look in IM maybe there is also something to optimize.

**Comment by xxFlare** [comment]
@keithkfng Did you log network packets to come to that conclusion?

It's not an MCPE bug. Just fix it with packet: 0xc9

**Comment by keithkfng** [comment]
@PocketKiller it's an MCPE bug -_-

**Comment by xxFlare** [comment]
@keithkfng It's a server bug. PM dose not handle the correct packet.

**Comment by keithkfng** [comment]
Really? It happens in local worlds as well...

**Comment by xxFlare** [comment]
@keithkfng That's strange, but a new packet (Chunk Radius) was added and it seems to be the problem. MiNET and another fork of PM have it fixed.

**Comment by ecoron** [comment]
OK, so we should fix it too :)

**Comment by legoboy0215** [comment]
Which fork?

**Comment by keithkfng** [comment]
Duh, it's ClearSky. https://github.com/ClearSkyTeam/ClearSky/commit/df6227a6f11fdf237cdab202bc7713e82f21ddae

**Comment by ecoron** [comment]
Nice looks cool

**Comment by keithkfng** [comment]
Applied the fix here, try it out and if it doesn't work, reopen it.
