### ISSUE TITLE
Chat messages appear in console instead of chat page

### ISSUE THREAD

**Issue by ABAxStorm-zz** [ImagicalMine/ImagicalMine#24]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

I use a NetherBox server, and when players chat, it shows up in the console instead of the actual chat page. When running PocketMine, it doesn't do this. On ImagicalMine, it does. (**By the way, I cannot currently post screenshots for some reason, so at the moment no pictures are present.

## Reproducing the issue

Chat/have players chat in your server, and then check the console, and look in the chat page.

## Client information

ImagicalMine 1.4 [ELITE] implementing API version 2.0.0 for Minecraft: PE v0.14.x alpha (protocol version 70)

## Optional information

There are no crash dumps/files to post, but a downside of having chat messages in console is that the console constantly gets spammed.

**Comment by ABAxStorm-zz** [comment]
When I say the console gets spammed, I mean spammed with stuff like directory errors and blah blah blah on line 256 so it's really hard to see user's messages on there.

**Comment by remotevase** [comment]
Plugin list please?

**Comment by ABAxStorm-zz** [comment]
@remotevase ImagicalMine 1.4: RealVanish 1; ReportRTS 1.1.3; SwaggyHUD 0.4.1; NoOpCMD_Prank 1.0.0; iProtector 3.1b; MSpawns 1.5; CapsLimit 1.0.0; MagicTelePortal 1.3.2; SetLobby 1.0.0; ServerHub 0.1_BETA; LightningStick 1; Oplist 1.0.2; SimpleKits 0.5; CustomChat 5.0.0; Whois_player 2.0.0; SteakIt 3.0.0; AdminFun 1.0.0; WorldGM 1.1.0; ManyWorlds 2.1.0; SwaggyMOTD 1.0.0; BlockCmdPE 1.0.0; EAC 1.3.1; Critical 1; ImagicalAuth 1.1.3; NoAdvertisingPE 1.0.1; VPNGuard 1.0.5; Op-Manager 4.3.0; Dimensions 1; BanItem 2.2; AlwaysSpawn 2.2.2; BlockSniffer 1.0.0; Lightning_Strike 2; CustomJoin 1.0.0; WarnPlayer 1.0.0; essentialsTP 1.1.0; AntiSpam 1.3; InstaPerms 1.0.0; SignTP 1; PlayerStats 0.1.0; pHomes 0.8.0; SimpleRanks 1.0.0; PurePerms 1.3.7; VIPcmds 1.0.0; Mentions 1; SimpleWarp 2.1.0

**Comment by remotevase** [comment]
May be a problem with CapsLimit
Gonna investigate more and more soon

**Comment by MKBandzz** [comment]
I can probaby help out... but you need to copy/paste some of the errors from console that is getting spammed.

**Comment by ABAxStorm** [comment]
@MhikeiMPC
24.05 18:03:44 [Server] INFO Warning: file_put_contents(/plugins/PlayerStats//breaks.yml): failed to open stream: No such file or directory in phar:///jar/imagicalmine.phar.conf/src/pocketmine/utils/Config.php on line 226
24.05 18:03:44 [Server] INFO Notice: Undefined variable: kills in phar:///plugins/PlayerStats_v0.1.0.phar/src/ImagicalGamer/Stats/Main.php on line 63
24.05 18:03:44 [Server] INFO Warning: file_put_contents(/plugins/PlayerStats//breaks.yml): failed to open stream: No such file or directory in phar:///jar/imagicalmine.phar.conf/src/pocketmine/utils/Config.php on line 226

**Comment by ABAxStorm** [comment]
Oops, that's plugin related. Disregard that.

**Comment by ABAxStorm-zz** [comment]
@MhikeiMPC 
24.05 18:09:38 [Server] INFO Warning: yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1) in phar:///jar/imagicalmine.phar.conf/src/pocketmine/utils/Config.php on line 158

24.05 18:09:38 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///jar/imagicalmine.phar.conf/src/pocketmine/plugin/PluginDescription.php on line 125

**Comment by ABAxStorm** [comment]
Did I really

**Comment by ABAxStorm-zz** [comment]
Lol accidentally closed this

**Comment by remotevase** [comment]
@ABAxStorm this is caused by a plugin that has
1. an empty config
2. Has an invalid plugin description in plugin.yml. 
Gonna close this, but leave it as a chat between us, k?

**Comment by remotevase** [comment]
Try removing all plugins and then tell us. Then, re add all of the plugins one by one and test them each, one by one to see which one is the problem
