### ISSUE TITLE
[QUESTIONS] How does this work?

### ISSUE THREAD

**Issue by remotevase** [ImagicalMine/ImagicalMine#25]
I am working on implementing the BigBrother plugin, and I have a few questions about how IM Works.
How does ImagicalMine retrieve data from pocketmine.yml?
What code do I need in order to retrieve the data from pocketmine.yml?
More questions will follow.

**Comment by Ad5001** [comment]
$pmyml = new Config(Server::getFilePath() . "pocketmine.yml", Config::YAML);

**Comment by k3ithos** [comment]
Do code cleanup and performance optimisation first.

**Comment by remotevase** [comment]
@keithkfng this is something that I have been told to work on by You for the past month, and I will not stop

**Comment by k3ithos** [comment]
@remotevase -_-
