### ISSUE TITLE
Imagicalmine bugs. I changed other pe szoftver my server.

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#26]
- Cheat protection: Randomly kick players fly hack if players not use fly hack, and players randomly moved wrongly...
- Protocols: ImagicalMine not support 0.14.0, 0.14.1, 0.14.2
- Kicked players randomly timeout error.
- Type: N flood console. (new)
- My server randomly crash if not used Alwaysspawn. (crash report sents: 3) This error: ImagicalMine says: "world error" other server szoftver: works perfectly and not world error...
- Crafting not work
- jenkins page not work
- linux installer page not work
- Enchants not work.
- Console style not support multicraft (Mainlogger.php)

**Comment by Michael-Tanjuakio** [comment]
Crafting does work, "Moved wrongly / flying" means that there lagging on the server.

**Comment by ABAxStorm-zz** [comment]
@Mike4l6 Crafting does not work.

**Comment by Ad5001** [comment]
IM support lastest versions.
Didn't you know that you can download the lastest phar from the website?
Enable the allow flight and download an Anti cheat
Please update the phar to correct some of the bugs -_-

**Comment by alicheek** [comment]
You can actually use the raw files to run the server instead of downloading the packaged phar. It has the latest updates and for the crafting issue there is a plugin to fix that

**Comment by remotevase** [comment]
> Cheat protection: Randomly kick players fly hack if players not use fly hack, and players randomly moved wrongly...

Fixed.

> Protocols: ImagicalMine not support 0.14.0, 0.14.1, 0.14.2

Yes, we only support the latest version

> My server randomly crash if not used Alwaysspawn. (crash report sents: 3) This error: ImagicalMine says: "world error" other server szoftver: works perfectly and not world error...

That plugin works fine on dozens of other ImagicalMine servers, plus, ImagicalMine already has the feature built in so you don't even need the plugin

> Kicked players randomly timeout error.

Caused due to a login plugin

> Crafting not work

AND

> linux installer page not work

WE are working on fixes for those

> jenkins page not work

We have not used Jenkins for a long time. Follow up on forums for more info

> Console style not support multicraft (Mainlogger.php)

Why should it?

**Comment by HimbeersaftLP** [comment]
> Console style not support multicraft (Mainlogger.php)

It does!

**Comment by remotevase** [comment]
> Enchants not work.

Working on a fix at the moment

> Type: N flood console. (new)

Create New issue for this. My points have proven everything in this issue invalid except for this

**Comment by remotevase** [comment]
@HimbeersaftLP it doesn't crash on startup but many feature make it crash

**Comment by HimbeersaftLP** [comment]
> @HimbeersaftLP it doesn't crash on startup but many feature make it crash

Multicraft works fine for me with IM...

**Comment by andris155** [comment]
> Multicraft works fine for me with IM...

Confirm. Modify Mainlogger.php, and works perfectly Multicraft + ImagicalMine.

**Comment by andris155** [comment]
Type: n flood issue:
https://github.com/ImagicalCorp/ImagicalMine/issues/21
