### ISSUE TITLE
Bug in a CMD prompt

### ISSUE THREAD

**Issue by laurobeleche** [ImagicalMine/ImagicalMine#26235]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
----------------------------

after a while the console to recognize the commands .

**Comment by DavidJBrockway** [comment]
what i have this bug the concell wont take commands i think it php or windows erro i fuixed it by updating php

**Comment by blui22** [comment]
I have the same problem.

**Comment by keithkfng** [comment]
Does it come up with a RakLib Interface problem?

**Comment by da123rrell** [comment]
no its just when we type it sometimes it doesnt respond anything

**Comment by laurobeleche** [comment]
I do not understand much of ranklib but I think not , not yet found the solution, I will do a new clean install and test without any plugin, leave running to see.

**Comment by keithkfng** [comment]
Issue closed for now, reopen if needed.
