### ISSUE TITLE
Hello, ImagicalMine.

### ISSUE THREAD

**Issue by inxomnyaa** [ImagicalMine/ImagicalMine#27]
Hello. As you may have heard, we started to upgrade ClearSkyand need a bit help.

Current problems:
Server starts and crashes when loading chunks or world.

I know you already fixed this, but i'd like to know if you still remember how, because i can't check commits anymore due to the deletion of ImagicalMine/ImagicalMine

All help appreciated.

**Comment by k3ithos** [comment]
Lol, ask @HmHmmHm
