### ISSUE TITLE
Attributes reset when joining

### ISSUE THREAD

**Issue by MCPEPIG** [ImagicalMine/ImagicalMine#272]
Health, Hunger, XP don't save when leaving

**Comment by robske110** [comment]
That's am well known bug.
They are not saved to player.dat and are just saved in the memory, wich is really bad, but no one including me knows how to save anything to a player.dat! Health should work though.

**Comment by deotern** [comment]
Health is working... :) Idk if its work on ImagicalMine... But since Minedox LITE Build is a fork from ImagicalMine, i think health should be worked

**Comment by aodzip** [comment]
Yes , I need add RedstoneSource and DirectRedstoneSource two array to Redstone Thins , They just store in RAM not to the file.
We need a deep mod in core code.

**Comment by aodzip** [comment]
Some plugins give Command Block(Need store command in Block data) use a external file to store them 
That is what a plugins do , also can use this method for a temp fix
But we are the dev of server core , we should save data in these .dat

**Comment by thebigsmileXD** [comment]
no. NO. Do not implement such "temp fix yml"-s! They just mess up everything!

**Comment by robske110** [comment]
So we should try to save this in the player.dat?

**Comment by thebigsmileXD** [comment]
Not should. We must.
And the redstone stuff: command blocks are a different thing and currently have nothing to do with pocketmine. Therefore are tiles. They are saved in a seperate file, the level file i think, not the region file.
So command blocks are tiles.
For things like comparators, repeaters.. The redstone stuff:
Everything is made with meta. No need for extra saving!

**Comment by aodzip** [comment]
I need two Array
At least one Array
For a high-performance Redstone calculation

These can reduce lag and avoid death loop

**Comment by robske110** [comment]
DeathLoops... In all my programms every Loop has an counter and if this counter goes over 1000 it exites the loop... But that has nothing to do with this, and you should never use loops...

**Comment by thebigsmileXD** [comment]
In PM/IM death loops are limited to 100.

**Comment by aodzip** [comment]
The Redstone Calculation we have is check every near  8 blocks and send onRedstoneUpdate to them  , and will receive onRedstoneUpdate , this loop will stop at the power won't change . If there is many redstone wire , this is more than 100 and make the server crash

**Comment by robske110** [comment]
Redstone signals do only transfer 8Blocks (Then you would need an repeater)
Idea:
Make one loop for south one for north one for east...

**Comment by thebigsmileXD** [comment]
Incorrect.. 15 blocks. A line of redstone wire can be powered for 15 blocks

**Comment by aodzip** [comment]
15*8 maybe if there is call back is 15*8^n
enough to crash server

**Comment by thebigsmileXD** [comment]
That nesting prevention seems to be against Redstone :p

**Comment by aodzip** [comment]
If I can save some data in block class I can make a high performance way .

**Comment by smyb** [comment]
#355 Player food is saved in Player.dat :smile:

**Comment by thebigsmileXD** [comment]
Is XP already saved?

**Comment by MCPEPIG** [comment]
No.

**Comment by smyb** [comment]
should i make a pull reuest to save XP in player.dat ?

**Comment by thebigsmileXD** [comment]
If you would be so kind to do so, of cause!

**Comment by keithkfng** [comment]
@thebigsmileXD of course, not of cause...
cause means the outcome of something...

**Comment by robske110** [comment]
I think he knows that he just made a typo

**Comment by thebigsmileXD** [comment]
Didn't knew that. Of cause is wrong? I learnt it so

**Comment by robske110** [comment]
Realy? Ok sorry...

**Comment by keithkfng** [comment]
@thebigsmileXD should I start giving you English lessons? It'll be helpful XD
"I didn't know that." Knew means you have already known that beforehand.

**Comment by thebigsmileXD** [comment]
But i didn't

**Comment by BlackShadow1** [comment]
The food isn't save in the player.dat, it reset on rejoin..

**Comment by smyb** [comment]
it's saved :confused:

**Comment by BlackShadow1** [comment]
Doesn't work for me. Is saved at regular interval?

**Comment by thebigsmileXD** [comment]
It is saved everytime you save the server

But the overflow saturation maybe isn't saved

**Comment by ZombiePower** [comment]
fixed?

**Comment by robske110** [comment]
Not realy

**Comment by thebigsmileXD** [comment]
Xp saving is missing and hunger saturation will not be saved

**Comment by robske110** [comment]
But hunger should be saved (not saturation)

**Comment by thebigsmileXD** [comment]
Hunger is, saturation not. When you eat a yummy steak and your food is full and you leave/rejoin, you don't have the saturation and have to eat again after some seconds.

**Comment by PocketKiller** [comment]
health and XP

**Comment by keithkfng** [comment]
Fixed as well - see PR -_-
