### ISSUE TITLE
Crafting table fix plugin?

### ISSUE THREAD

**Issue by ABAxStorm-zz** [ImagicalMine/ImagicalMine#28]
Isn't much of an issue, but I need this. Does anyone have the CraftingTableFix plugin? I need it.

**Comment by Ad5001** [comment]
I dunno

**Comment by remotevase** [comment]
Should be in the ImagicalMine-windows repo under "plugins"

**Comment by remotevase** [comment]
https://github.com/ImagicalCorp/ImagicalMine-Windows/blob/master/plugins/CraftingTableFix_v2.0-Alpha.phar
