### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by TonyWAV** [ImagicalMine/ImagicalMine#30]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

ImagicalMine Crash Dump Sun May 29 10:41:37 AWST 2016

Error: Call to a member function setTime() on null
File: /src/pocketmine/level/Level
Line: 1309
Type: notice

Code:
[1300]   _/
[1301]  public function save(bool $force = false) {
[1302] 
[1303]      if (!$this->getAutoSave() and !$force) {
[1304]          return false;
[1305]      }
[1306] 
[1307]      $this->server->getPluginManager()->callEvent(new LevelSaveEvent($this));
[1308] 
[1309]      $this->provider->setTime((int) $this->time);
[1310]      $this->saveChunks();
[1311]      if ($this->provider instanceof BaseLevelProvider) {
[1312]          $this->provider->saveLevelData();
[1313]      }
[1314] 
[1315]      return true;
[1316]  }
[1317] 
[1318] 
[1319]  /_*

Backtrace:
#0 /src/pocketmine/Server(2873): pocketmine\Server->doAutoSave(boolean)
#1 /src/pocketmine/Server(2514): pocketmine\Server->tick(boolean)
#2 /src/pocketmine/Server(2370): pocketmine\Server->tickProcessor(boolean)
#3 /src/pocketmine/Server(1949): pocketmine\Server->start(boolean)
#4 /src/pocketmine/PocketMine(519): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\TONY\Desktop\Imagical Corporation\ImagicalMine\ImagicalMine.phar/, string C:\Users\TONY\Desktop\Imagical Corporation\ImagicalMine\, string C:\Users\TONY\Desktop\Imagical Corporation\ImagicalMine\plugins)
#5 (1): require_once(string phar://C:/Users/TONY/Desktop/Imagical Corporation/ImagicalMine/ImagicalMine.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.4 #0 [Protocol 70; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT TONZ 6.3 build 9600 (Windows 8.1 Home Premium Edition) i586
PHP Version: 7.0.1
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
BenchMark 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 2.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
CommandDefender 1.0-Alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
CraftingTableFix 2.0-Alpha by hm for API(s) 1.13.0, 2.0.0
DevTools bleeding-x by PocketMine Team, shoghicp for API(s) 2.0.0
EasyMOTD 1.0a by LDX for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
ExternalIPChecker 1.0-Alpha by hm for API(s) 2.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
Farms 1.2-alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
HealthStats 1.1.1 by Striker209_MPE for API(s) 1.3.1
ImagicalDevTools 1.4.1 by PocketMine Team and modyfied by DarkWav for API(s) 2.1.0, 2.0.0, 1.14.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
MoreTrees 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
MyDearest 1.1-alpha by ifteam for API(s) 1.4.1, 1.12.0, 2.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
NoOpCMD_Prank 1.0.0 by  for API(s) 2.0.0
NoVoid 0.2 by rirititi for API(s) 1.0.0
AdvancedKits 5.0b1 by luca28pet for API(s) 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 2.0.0
Elytra 1 by BoxOfDevs Team for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 2.0.0
Whois_player 1.0.0 by TonyGonnt for API(s) 1.14.0,2.0.0
PlayHarder 1.0-TEST by hm for API(s) 1.13.0, 2.0.0
PurePerms 1.1.5 by 64FF00 for API(s) 1.12.0
ScoreBoardStats 1 by TutoGamerWalid for API(s) 1.13.0
ServerHub 0.1 BETA by ImagicalGamer for API(s) 1.0.0, 2.0.0
ShootingRod 1.0.0 by PocketKiller for API(s) 1.0.0
Slapper 1.2.9.4_PHP7 by jojoe77777 for API(s) 2.0.0
Texter 1.0.0 by ImagicalGamer for API(s) 1.0.0, 2.0.0
VersionModifier 1.0.0 by applqpak, keithkfng for API(s) 1.0.0, 2.0.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
VPNGuard 1.0.4 by basprohop for API(s) 1.10.0
PureChat 1.2.8 by 64FF00 for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPGtz27aWfwWVO3vtjl6U5Jc67q5jO02mdqyNlaa7ZccDkZDEmiQYgrSsdvrf95wDkARpO5YT
d+5+aO7D4gFwcN4PENKfrSyIRGvsjPZGo4PDvcP9divkKjtLU5m2xn+2snUCw61YZoEnWu1WJJTi
CwSd8DBkmWScRSKaiZTN89jLAhkzJbIpYN3eYfAQ52EI6+bw53UQ4sJkydNxr3cy7n1QIlW96eW7
/+mdCnWTyaT3NuKLwOMhO5FpIlOOCEvgRRCL2kMXcfVU6vUS6d2ILMIJobgVYe8c/x/GE9xcb/yZ
iTApBBAIYtg/bLeylAO3419bW33WXHUl0luRbg8O9oc7Y1YNuK4e6fzgy+M8k1f8VmzPpAwFj3cA
/5bzKKpdZ/QIKpD6TQ3J4FEkw/3+Z5BMUumB6mRawzZ8DJtzODp8BJvKeJrVsIzuYZnQR9TQ9q7z
GKLra0/GKktzL9u2x09klIDeZ6E4AVNU55L7YF1y9rvwsnYNU54FoXLdCx7E53KxsGYB2iBesNLU
XJdszXXR2FzXWJvrPmRuFfSCdrlvcCX+r0P8QmiSMF8EMawlZeyybQcEnopPeZCKaxl7Yrspjb/J
8Sqto9/ttH77q90SLx5InufLQIKWT2s856ES7ZYnfYEEwWgfELkZ+64HS+DRocckn4WBZxFR+DH7
di5TT7AjRph22J962QCW6U9DQuBmwZxtf/NttgxU54eFyMposMN47LNvNJ5y/ciscrNUZHkaa/Tf
68FdM/iXftwr99o3A2YbZZwKtpsQvxc8BvGm2zudH0Bn4dmtiLPtWKwYyQjJ0SBav7Njtjso8R/W
8SepvA188n+jlO0gznaYGcYsYnA4/QZlsNXJMo9v1HYxw7Hk1MDPwJIzDkYr5+wVV4KonZjBQmTO
oBTZffJgO1p0yjNe7jisidEZFWw6hXyN6CEaGck7ezRiFuyXC0oJOVpCve++a/31T8b4J2P8kzFe
IGO0WwsRi5SHGKFB5wpwgps53RFQOsuD0G+N+xDSU5lJT8KsfXjiSQBzBt1+tw+zFkEGT/0N/8GC
lN+EwQzXdA8IQx5zrIlbH4PYlyvF3k0ZMP6/bK87ZEQDO9zr99l2MX7QddgbGQk2SUUU5BE78wMU
xg4Ldg/2ACFWoePWPhDowNMfIgYuWkNDLwxeS4XbvX33bgoAelhBxipzl0JpvBKxt7zg6Q0+GAor
WLsmrX7nOAR5A5Tn2VKmCiPTMkL5krB+hTnOgLaHD0P6oOUHM0TMwZOARAyG7ZYvEiAYMcCYkvPs
1AZEHFNrK5hngkeuWxJkfcR8DB4JsyaXV9OPl+/PTwG0EjMVZMAE5nXg9FUopf/6F5s5A6mz5hCx
NltyHcSRM4o89h/sZA0FxEk+E503P7EpkHSf5S/ksNrGdWdI2fwOeCxJ3ITDFOZ40FyJ1ObSgjY4
3aszenYrwyugzmLpq3Rm7awjYsXG1fT4/fTDxGaitcyyBGLBarXqCqAEsXazGzTSV/n6JOVAmMVV
AaqzNOgO6jy95uFNkN6ompq+gqdZvvZwX1BNRcEGuoEMEkFtdirmgLKmn+bIBo6mneHvd7YGafcA
G7KOUoJgP0VCXgd3Nu/NIZv5wWZR5gX4bZIBjN4nbANOT8XtFIoQZXFYgmzOAKfwAXvnrs5ala10
aAGKl3KxDLzkpVyyIAfzeUnYEz6pwCkh5y3zWdeTkZVSeyUO4P2Mq/XF5fTU4r0ENUy6odDz019e
LIgCLtct9m0GnQdV9xCLgKVzcTI565UcIINQGspofTx5a7NYARum2z2scyljMYP/3YtD7TLlYPQq
/jr0d2ieh+Z5ZJ5H8PyFAjJkuK7QlAMtIDCbiw3s3My/WsrkviwI2hTG/tPCeFLttrCfwSG4UFKy
aIjbhMc7SFsxD99OTpYCLN4O2ffHnlsdfZUT39se2HuAog2YfM3pCEJBK2axZ0PrjA2b6XUqsqVI
hX/9Yh5sbe665mEDNy4ZSiNVYwWfGzVCh//7UioRZP5sxtIbwcNseZXxzGbMhjbrV6fO2hW0WmAR
g/7h9cXkrMbi8MsDiUWA69ap2YCponF7IGPeG6qzN2qy10iadAIWSX89D4TPZmt2Ch3CR35bcz7H
UihpePTlmm3SW/XCG6VYI5DzYLHMYqgJrrW6LIHcG7IEMqiJ4iLwllyEF/3RS5W75d56a9dtADbT
9gWP1x9lGvq2ni1gM1sM6xrmYZCH65eKnhqb60Ihu17R/hvVCQUrMhXTVIgaJyXs39wkl4QARxZN
m7C1PhU8FcpusSpYI8BsGD9HpmoxLL5I+Cxpsj5uxuE7eewDF1mgwHghDFZ8NkcaSmzGm595cCv+
2Nt7sYxXIHTdBiUNwKZ8XiYnF6fXk5THNzUubXiTx/qRxwt5mtnyOe71Tv4sA79GNgEsevvdetBL
gzTI4D8vFfIKfCh93Ps55IO28NWC/1NQS9Y1sC363W5/1jCvMPf44CARL3YKY2/+xR1RSVWvxgt2
9yF44TlfLOy2voQ9cbR2LhZA7+Ucm62X4rfcHJIVndN/SQNo0dWruMG2IFxnKbd7AQ2wGHVqLL6S
d5dzqARU87Tw647WCqxQ+hMBz7HSM6VEnAU8VLU4WAM3U/KDilNaQi/KmU3FS2mwxhkIQL/uOQZ2
LPYtYJ15Z/j3HpNWGxcvogwRX3RW+nEpA3WdhHxda1lr4M9H/9ZUxusfZRxn9RQHNXL7qxglGlyX
/myiUsPgit/mMR26dmMIi8DjBNh4w9P6OaoFbJZh07Or6ZcdIppX+huxVxHgujViNnDJSZ6Kiaj3
rhWsGUV368zsjV6/7vdfrB651viAiYIA6+PzjwtxpX7J1KuwoBN6UKK+kiCkZm/bHHk0tk7zTP4I
a9KPUNT79zX6pQ6J+8/K/Z8TWrX/vsln9wILwmw9Ql3JXp1Nj+uqLFpH4uqBs8IXCDRACDY/G3O0
lBJPwt9LuyyzoU9EE92f/xSE4QMcfSEnNk4ImhUxz9JVyJOkFkIKSPOd0mF3dD15M2kcYv4uf5di
H/+9VCZQev/nqGcq7uqv+wzgCaX8rXamSXiOKn7WtF5IP5gHNXaaI0/wBfILPyUcG5wbAUHoZg59
0wuz1yDpWXzKTLwXK4gsNosV0D7Z6TqffUvy2LuD4Ve+PKmoeRZjk3c/5g22ClBTZaO6ymZcJanE
c/la/P6ad7QFRuCmIuLJIzjMTidLnjVSMIGaEeHg6QzsPPU6o8qG93ipHcE/kpmRrurTV+dlQoJR
MYiSUHzkqf1qxwI2auOmAz74vv351QjgUdk05bGak9NfhXJlPdYK+ko+c7O56yoiGKwYbKBG/CZ5
geZPZJrx2sF0HV7P5ffOLB+Ww1NGbQv6Mwbe5DPRNBWsViQ+yS3eAOIp8AcBu1AEVQld8KAET57w
pLO1NSmf2ImM58GC4TVZN3Xjras8Zhd8zQaHzOmP+854OGTHH6+mbNB39nCGuTmKUjzCY3oq5ccM
+kZdkFhzkJEj59AZDhDoBwrl1AnlAnc76iMw4ncd3caoI6dPIJXwVdzBK1uCvOZI77taAp+dMFDZ
kZzPEaLl3vmUi3R9JGMLlHqwzMyKZOY/SiiPYwndiDA0dLi3DMStiMAclUGZCl9lMhYdyK9eHtK1
NTPEQ7DjzjzEQ/RiO009j4MIdGbmaVgkZwVgAcKLpC+OSDB0vbdTwgyiJcQ5rFyL5+Q2MashUc0D
ICVbHzmEja7AZTLtKJFh5aSOEExXnLWe6GC8gikhfGsKXrU+Oj17ffzhfEocg/S6CVcKlvlH39E/
YBaq8w7eljVU4FW08mZedx2FaFgMcwzzyKZyfcWPTIsBj6x2qTDeYtOlUIIVNDOeCpYtBQNZK/jA
M+ahejI2EyyIvTD3hQ8f2D2LRlxXeJ9OzhFBE6fic9FmEt9sKkTJZqngN2wt89TgYsEc3zEF9I4J
tpJpCqYXrhHxO7Eq0fV8Mecgd8VWMv5XxrC84ylDyUTAK96bXuPVc7xjrNleLUXM8mSRcrwg0nVj
9A2NbOzGbGu6TAUYNYCAipDHi5wvBMMr5yQx40cqgOdQAv7gD31BE5bSm2HNRX0hEFAkCBF3V8FN
kAg/4F2ZLnr41DsHH7qW8+u3V5fXe8PDzuAa14EYS0Rj5kJUW7gt3Ojjkt4K45V7CNM+w+v3+r4n
qAmDOPgEyI2GSZpEKdABn0RGKvXFbeAJtuSxH5KSI0Cszb7akppzgKtlnvkSHUZf+UditMcyL5RK
+F2wHB7fKBIROi5ePQWuQbW2iRlyvtFcHKOvMgwfdFFVp0p2G3D23xg/YArFkY4ZGdPVblwI7ciK
cbRpJYF4Q5TWLDeIWK7AZiHwg92QMI4nb2EmpA8fxVoNdICgGfBQoT+jiFXgWUFGJwssLigTJphn
w+7TWEeCr0wxcjBwEbBC5He2ZsZ2YboJkuVoJfqtj9CDgSjBjLnvs1Qobe3IK97xBp64guoC4yMD
G58JFCpoQXzKOX0pYxHcwtxbHuaCbZstIXXsAHK9HwRnSnAdsCC8UD2GUdz5XU7f5QAXPlbr2Jty
dQNelt6A03Zx/AMo3ihcM4mzlqmE+A1mCLNVm1GYYyYcgpu0GQoNuMDETmKBdImwKI/BSnAK4b4i
MwV+wKFTeQehOxMgAmCH3CsuSUOpanLezjEq0NdQwPvbLMj+hd9KSWmVLzB1keU31rJt4ACMhQ1Q
IsRDx3A5JkwYITAPpGuKDz+GcgaCxcqBaTCYcBRkGAcjseCzdQYEsStNSp8212lWRxfgaRUQYSRs
hvlK4ynkr0gu8wDMBfxH4Hc8EMsc4lKxo1Y/MJOT5S8k8CHRHVFmsM+CiOwQYWPWdyk8USLIILxx
//85+ViFfYZ4zMNfRTxUDwntb8JjSY/Bphi4FKZb4RfU4J4FSXv9vqEKuotAUgpEX1S4oUdJwFBX
+psDW0G88tHGaEYH/EFoT6PUIaHajsFDQW4YHR4TqxYnFF4hZRX0dT3NpRyPOMD7Kk/W4Qh3uMQQ
glmVpnfvT0a2Td0MIkyEh8lXkViQVi1jvbZkACQpElWxOewbPtXOgwQZroea6wVPZ6D/jifDUBeW
6GEPSpXMCUkxa5hZA74b8TinNG9TARVQDraw0y5iQsMYjDXouDqfF7Ehqqysyy51jqUnsIilzEO/
JCSACLKKWUU62i1LiHJgsDQRtvWaPOFebCRb0atLpuapjIoQi2vNeMeOSpZOgQmjuqYpPGA/1jqs
8D36PpeW9zlZPQZEAiJl2NcgN0xX4W1yzxSKHqUndbDuwPqpwoWoCjUbRzncM3SeSr2sqT5MAlid
6WU2Br2LmfYCPFMigoYBbFdzXfQ+ZiMcKLP3Z1G5cSwy1EVZLoJphDoTzngG7QpWMxzrcEiAYE8m
KpED6mLYjOpgNBNlTqRws2WHr2IEHT9dZ4i7zTqOZcyY+2jbTlaQAmFld09HlSrXUmOBic7X4c4o
UK8FoKGpy95A7wTiPYL6Gwz3ZPKhDWuBghnEn1XgQzVEUZv8u0TfIfRjtm8Kg6pk0DWhNbXLjn3w
pyUP5z1oLHQV4wuwM7MRbKntT8a2Q5bZ2cJl1Ulnd+h8WAbxsK0dGzc23/CBAjWlaCYp13+YxJOi
Uqj6BCyCcBGdzWGTECcd82jXZNDuiVm+0OqXJmYyzBYpGbS4E16uix0MPvhloW45qtAiqIZJlkk3
iAMkwzH1yw/MwbrFJCmscmmnosKltRimTOXrGq2ONQJdcirWUxnPcrC93sLTWsKvFCiL/qLnrLU9
oqhHUQQgFN3w0VRjqSg5sh0P9JGRsZolHb1kzCIYWph2CBii4xckF+/YKB3feA0/BGFsKDNrexBI
dp8acneygq13l9OzMaMADv/1cugNY+gNCRGdz6AVEHlm55K80lqOa4r3oHmBoGR4JYOk7AaUoAFm
aISDvslGGBV1kkOLxBYc4SazmQBSBxfhUJfVV+j5yOCMK2Fttu2Azz2wS5sNYMB5aEBkXneH/F8J
mwoyhylixs7QHOYwATFO74dVhNYk9eBVc44xhboyLMQwsvBwxddK4zZ4LClipNJxHbvpvGr/YFq7
VCBXbJfKHgy0euIYIW68AjNairRhiXKxoA5JQeuFFJcuBshN0GNmZVH4g0OBiaql1lhM3aCegXZj
nytgUGtTV/BfoH8vxaiX/kuVPUzGHjjKrWb2Pmq05rvZVetmtrOE8waTE4/XRS2iieSxMXy0gIJG
P8ei7z/ZJAdplQ1KCl02NPO+jNyWDqLQ6UHrYfBhUjPyM5AxM9NBtLUsTXI9jmQe22lemcq8sA+0
LFQ0NoaAFD+Snh5bylOA+tqsNI56bcGcw8GDq4n/WOgTipnQ2GZijvmGDuZQ+yifEqs+rrMSnM5v
+HVrEBioNsCDGIFNdrI2h07GMsuylUQ4py/LFcnPJKt5HtI0qSCKdDB6Bp4uGKjRTvGkB3wW0Bai
+l1qW6EegkfoxhFlRCwjSv7LeKuVgQItlHHB7xhvyiXR39cWfuWqNV2MKH68165WLTN64IY6ip96
qQkJ2uOGmC7wXLSTJz4ncyls1cMLWNrJ8TimqnU04VX7XtDevU+8SU0rHtBxzqdc5MLo16yniEzw
jgJljdnBF2FLZJKHBpv5jAVIA7EbU7jsgPSQaH362yE7UihJFGWEX0XH8GOgjonceKRadHmFSvGL
73kCJa2u67VBUlzX5aTBBVj2cZXZEJGiBwEjuFEJJBiPZgFYvp5iTnP1ScxYB1c8NEo5RDUNNeFV
G4m2XtOvlXkH7bqDR4d1SBlfa1AoQIJ4LiszWErUPW3ZtQ6Sodwl+mIZryNs5shDFMhXlYRid2qG
WTVMBIOtccYXCygMzBFQeUKHcRp/duHmYW40PYhOPURPGEDa0ySc3XHM+/oBCycwHvP2aMzMBxoC
zWLzP2a/4scOJLs2nQb8RmWR1M7J7PNVDDHlKeqCocSwlsBCTxfhN2zb1GNdmLDTLRmp3AhseqHt
cIttlN70AhtVVXuavmUWgkTKmMJ+3YXScf/wN9rjxJz2Y7kWwB40t2xhqd6CdZQ8mYl/+DMpmPg1
q/qwoWoyGJ4VRyLMqP+gHniWpxSn8VyYUWOiqB4BpG68AGlEmt/LpJDVfTbJi9Drr2LY+kdcRBu/
hUZZP6KtwliHEHZKAyksNoCJj4xBdUERvKhu7XcQVM0WHa0+Vihe2FDJ/tArDSKMiiNFhSjyHkF5
E4DdmcrRskTalQjQUsD3Oxh2RvRU7jZmr8+Pp+PB9/vt3cM7pz28G7YH3zvf+1Dg6Yi7naUCHiA6
Hh302QJ8U+mn0e4OvfEJzPl69c7HXKnDOyIxGj69Yj2B5Gr9gsHMAxteWgB8PxD7PLVB5gd/imdM
GtbjPAjpYkwJWELc0DcQkCwsva3B31X59SIchj5hnWTW+NXk3HpKvBq178XcnBZYQKVbQBuScWTB
t0DRWn0K6ccazCe2iyODji9uWQffoO72R/19+PjtW1DQvtgfzA/3DvszZ3R4wJ0Z9J37fG+47w2H
/GDoeH1/MN/b3WXfAu5M3ogY8o0tgz+CRF8h1Pcd/9A/S1GMwtMdvZUrRSojfMvf7w8dZ4DfZ52c
XlrDkyUpBC/T4NcC9cvnXy5sSdXxrXz/rj6InXONQoCt0qCuOWihwqbQAluw8JiJIb2I30fRIYwC
srKXzfQ7KAu05kQe3QZ6f0I/pGHO0+jnM/RFS6iwr32Z4dXTauXC1iIU3TepmNP++A3Jv/76P1BK
iBk=
===END CRASH DUMP===

## Client information

critical> Error: "Call to a member function isChunkLoaded() on null" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2764
[10:41:27] critical> Could not tick level "": Call to a member function isChunkLoaded() on null

**Comment by k3ithos** [comment]
Try resubmitting your issue, I can't believe how people don't follow instructions.
