### ISSUE TITLE
Thank you for the time

### ISSUE THREAD

**Issue by dterweij** [ImagicalMine/ImagicalMine#31]
Thank you for the time with ImagicalMine.

I still using it, but downgraded to 0.14.2 as 0.14.3 contains bugs that are not being solved now.

i still dont know what other i am going to use. ClearSky or Genisys. ImagicalMine was way ahead of features that are not yet implemented with ClearSky/Genisys yet. And about PocketMine-MP the original, that one sucks, seems that that project is dead as there are almost no commits there.

I realy hope IM code survives and will be picked up somewhere else. 

Again, thank you for the time and codings.

I am stick to ImagicalMine version i use now, my kids are happy for now, but when 0.15.0 comes out they want to play with the horses :) So then i move away from ImagicalMine server software when Horses are implemented in one of the other projects. Also i hope AI will be implemented soon in some other project. Our World is very big, we (my kids and I) builded a lot. 

Regards,
Danny.

Greetings from Holland

**Comment by k3ithos** [comment]
@dterweij I see you read the forums post - come over to the forums and socialise with the rest of the community if you need to! There are also lots of plugins there for you to download so you and your kids can have a fun time :)

**Comment by remotevase** [comment]
@dterweij if you use many plugins, don't switch to Genysis as many will stop working

**Comment by Taki21** [comment]
Tested out Genisys they actually work and now ill test SGV3 4 myself @remotevase

**Comment by lolcraftboy14** [comment]
@youare1ame  you litle ......

**Comment by Ad5001** [comment]
He did same on the new repo.

**Comment by remotevase** [comment]
Ikr

**Comment by ZeroDevOfficial** [comment]
I really love ImagicalMine and sad to see it die

**Comment by Ad5001** [comment]
You can still see on the new *unoficial* repo: http://github.com/Inactive-to-reactive/ImagicalMine ;)
