### ISSUE TITLE
Join and Raklib troubles

### ISSUE THREAD

**Issue by FaanMaario** [ImagicalMine/ImagicalMine#32146]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

When my server is running, nobody can join it. It stays on "locating server" and when I restart it, Raklib crashed.
My server have 0 plugins.

**Comment by ecoron** [comment]
Which build is it?

**Comment by FaanMaario** [comment]
This is the last i guess

**Comment by ecoron** [comment]
on which php version it runs? is this caused by 0.13 clients? maybe you try this, to be shure to have the latest: http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/lastSuccessfulBuild/artifact/releases/ImagicalMine.phar

**Comment by FaanMaario** [comment]
with php7, and thanks I'll try it

**Comment by PocketKiller** [comment]
its a problem, you shutdown your server incorrectly, so RakLib could not stop binding port 19132, you should wait for a long time for it.
