### ISSUE TITLE
Gliching through blocks

### ISSUE THREAD

**Issue by Tolo0** [ImagicalMine/ImagicalMine#365]
When at 2 - 3 blocks abuve bedrock lvl. You glitch through the ground and die in void.

**Comment by thebigsmileXD** [comment]
That glich also happens on teleporting on a 3 high layer of blocks..
You glich through

**Comment by robske110** [comment]
You basically glich thorugh blocks, espacially on join
On my server ther is a 50% chance that you glitch through the spawn and fall in the void again

**Comment by thebigsmileXD** [comment]
And then respawn, then glich, respawn and so on, until you get "kicked for flying"
This bug is so critical

**Comment by robske110** [comment]
Yes, exactly that my users complain every day about that
I fixed it with building multiple layers:
X=Block
0=Air

Here is the spawn
XXXXXXXXXX
00000000000
XXXXXXXXXX
00000000000
XXXXXXXXX

Does reduce the chance to bug slighly, but not efficiently, so i removed that again

**Comment by thebigsmileXD** [comment]
Didnt work on my server

**Comment by Tolo0** [comment]
My spawn starting point is glass blocks with fire underneath. I dont think iv ever had a problem.

**Comment by keithkfng** [comment]
Moving to #483.
