### ISSUE TITLE
Time isn't synchronized

### ISSUE THREAD

**Issue by matcracker** [ImagicalMine/ImagicalMine#383]
The time isn't synchronized with the tick's, anyone know how to resolve?

**Comment by SavionLegendZzz** [comment]
wait please explain in more detail

**Comment by matcracker** [comment]
/time set night don't go at night...

**Comment by SavionLegendZzz** [comment]
ok i will check this out

**Comment by HimbeersaftLP** [comment]
Also the RealTime PlugIn doesn't work anymore. If it's 09:00 AM the server time will be night. If it's night in Real Life the server time will be day.....

**Comment by thebigsmileXD** [comment]
I cant even change time with realtime.

**Comment by HimbeersaftLP** [comment]
You have to set the time with standart /time Command, and then /rt lock, that's annoying...

**Comment by ZombiePower** [comment]
wt... that would mess up everything... i think it works now?

**Comment by BlackShadow1** [comment]
Yes, @matcracker fixed this.

**Comment by thebigsmileXD** [comment]
Wellllll.. But still, i get raklib errors, sometimes when a player joins the time resets to day

**Comment by matcracker** [comment]
I don't fix anything o.O

**Comment by BlackShadow1** [comment]
I remember you had write in a commit in the weather branche "time no longer delay after 24000", so i thinked this was fixed..

**Comment by matcracker** [comment]
This only prevent that go over 24000 ticks but if you set in game 23500 ticks you can see night (moon in middle) but immedialty return day without sunrise..

**Comment by BlackShadow1** [comment]
Oh..

**Comment by remotevase** [comment]
Yeah...

**Comment by Pub4Game** [comment]
https://github.com/ImagicalMine/ImagicalMine/commit/620d7fe955ccb08fe49d57fc5b066af60eab8d2e

fixed
