### ISSUE TITLE
Rail Cannot Make Turns

### ISSUE THREAD

**Issue by KyleBernhardt** [ImagicalMine/ImagicalMine#396]
Rail cannot make turns. Only straight rail segments can be placed.  Build ImagicalMine-IC_1.0dev#185.phar

**Comment by thebigsmileXD** [comment]
Work in progress.

**Comment by KyleBernhardt** [comment]
Good to know.  Let me know if there's any testing I can do when it's close to ready.

**Comment by thebigsmileXD** [comment]
Its far away, i won't work on it for now

**Comment by thebigsmileXD** [comment]
Now active

**Comment by KyleBernhardt** [comment]
Awesome!  Is there something I can watch that indicates that the work has been submitted?  I'm glad to do a QA pass on the build.

**Comment by CraftingMania** [comment]
rails now turn around on place but not making turns lol

**Comment by thebigsmileXD** [comment]
I wrote on the "revert rail" commit

**Comment by remotevase** [comment]
Good to know that this is actually getting worked on

**Comment by thebigsmileXD** [comment]
That was a debug by me.

**Comment by rWardy** [comment]
Rails seem to work and turn OK for me at the moment.  Is this still and issue?

**Comment by thebigsmileXD** [comment]
Don't connect properly with non-normal rails, but no, fixed
