### ISSUE TITLE
Please support of API VERSION 2.0.0

### ISSUE THREAD

**Issue by jhelom** [ImagicalMine/ImagicalMine#39650]
Hi

API VERSION 2.0.0, Official PocketMine and Genisys supported. 
ImagicalMine does not support..

Best regards

**Comment by jazzwhistle** [comment]
I think Genisys's approach of supporting both the new and old API's is good for a short transition period... but if everyone doesn't force API 2.0.0 pretty soon it will get messy.

**Comment by InfornoFire** [comment]
Did you delete your opening statement that says not to delete
