### ISSUE TITLE
Crafting does not work

### ISSUE THREAD

**Issue by jarne** [ImagicalMine/ImagicalMine#4]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description

Crafting does not work with Minecraft PE 0.14.2, it doesn't shows anything you can craft like you would have no blocks.

![img_0341](https://cloud.githubusercontent.com/assets/15860314/15098668/a844638e-1542-11e6-8f8a-5dd9f1f73d5e.jpg)

## Reproducing the issue

Try crafting in gamemode 0 with a stack wood or stone.

## Client information

Latest ImagicalMine source with PHP 7 on Mac OS X 10.11.4
iPad Mini & iPhone 6 with iOS 9 and Minecraft PE 0.14.2

**Comment by Ad5001** [comment]
Issue already known and no one found a way to resolve it. @ImagicalCorp/imteam ?

**Comment by MarcoDiGio** [comment]
Mhh..

**Comment by remotevase** [comment]
@Ad5001 @Taki21 fixed it, I believe in his commits

**Comment by tnpxxsheepdog** [comment]
Won't fix?? @Ad5001 Soooooo no more crafting in MineCRAFT?

**Comment by Ad5001** [comment]
@tnpxxsheepdog as @remotevase said, he think it's fix but yeah minecraft without crafting is not minecraft anymore xD

**Comment by HimbeersaftLP** [comment]
@Ad5001 Then we have to call it MineCreative or MineBreakEverthingWithYourHands

**Comment by remotevase** [comment]
@Taki21 did you remake the commits that fixed this?

**Comment by 0x15f** [comment]
@remotevase did we restore ALL commits when Dalton deleted the organization?

**Comment by remotevase** [comment]
No, almost all, but not the ones that taki latest did

**Comment by Taki21** [comment]
oops i just noticed i will fix soon xD

**Comment by remotevase** [comment]
Lol

**Comment by ABAxStorm-zz** [comment]
Not fixed to those who are saying it is, by the way. I had to disable survival on my server because of the bug.

**Comment by ABAxStorm-zz** [comment]
It WAS fixed before but I guess it just decided to stop working. That was a week or two ago.

**Comment by Ad5001** [comment]
So as @ABAxStorm said, it's in he loose comits of @Taki21 !

**Comment by remotevase** [comment]
@Taki21 @Taki21 I won't stop mentioning you until you redo those commits. @Taki21 @Taki21 @Taki21 @Taki21 @Taki21

**Comment by Taki21** [comment]
Sorry i was on vacation so im back.

**Comment by remotevase** [comment]
Lol k... Idk why you would go on vacation in the middle of the school year... But, not my life, it's yours. :hand: Bye :hand: bye

**Comment by k3ithos** [comment]
@remotevase @Taki21 is back from holiday, not going to holiday -_-

**Comment by remotevase** [comment]
@keithkfng I know, but still... In NY, most schools didn't get any break recently, thats why I was saying that

**Comment by Taki21** [comment]
i skipped 3 days of school because of "vacation"

**Comment by remotevase** [comment]
oh

**Comment by Michael-Tanjuakio** [comment]
when is it gonna be fixed?

**Comment by Taki21** [comment]
tomorrow maybe

**Comment by remotevase** [comment]
It's yesterday's tomorrow!

**Comment by Taki21** [comment]
ok ok

**Comment by Taki21** [comment]
gimme a few min and let u know if i can do it now

**Comment by remotevase** [comment]
Great, should work now

**Comment by ABAxStorm-zz** [comment]
@remotevase @Taki21 Nope, doesn't work yet.

**Comment by 0x15f** [comment]
@ABAxStorm @remotevase @Taki21 possible protocol changes that affected this? Or packet changes?

**Comment by 0x15f** [comment]
0.15 is on the way prepare for a lot of updates we will need to do, I will start on the new spawn eggs (maybe).

**Comment by ABAxStorm-zz** [comment]
@ImagicalGamer Spawn eggs are evil on servers lol

**Comment by k3ithos** [comment]
@ImagicalGamer off-topic, but if you have a GitHub upgraded account, post your proxy on GitHub on a private repo and let meh see XD

**Comment by jarne** [comment]
@ImagicalGamer Wow, you developed a proxy? Are you going to publish it some time? That would great for every bigger server.

**Comment by remotevase** [comment]
@Taki21 you disappeared from this issue! Come back!!!

**Comment by MarcoDiGio** [comment]
Revert Win10 fix, maybe is it

**Comment by Taki21** [comment]
ok
