### ISSUE TITLE
[To-Do] server.log disabled

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#422]
I was scrolling through Katana's warnings in the README the other day, and found something that could be pretty good for reducing lag. Disabling the log file for the console stuff, where it logs the chat, join and quit messages, etc. It takes a lot of time to write to disk, and if it was disabled, it would reduce lag by A LOT. I'll add this to @matcracker's to-do list if you guys like the idea.

EDIT: what about also disabling auto-updater completely as well?

**Comment by smyb** [comment]
:+1:

**Comment by MCPEPIG** [comment]
Disabling redstone-calculations by default would reduce even more lag.

**Comment by aodzip** [comment]
shutdown server will reduce all lag
lol
2015年12月27日 下午3:45，"Mr. Piggy" <notifications@github.com>写道：

**Comment by keithkfng** [comment]
You guys are just being sarcastic. I'm asking for your comments on this.

**Comment by thebigsmileXD** [comment]
:+1: haha

**Comment by MCPEPIG** [comment]
Just remove all the code except the joining parts and the servers won't lag at all, same with the clients :stuck_out_tongue_winking_eye:

**Comment by aodzip** [comment]
Make a switch like redstone-cal.

**Comment by MCPEPIG** [comment]
Make a switch for everything, then turn everything off

**Comment by aodzip** [comment]
Great idea , just do it

**Comment by thebigsmileXD** [comment]
Genisys has switches for brewing stands, redstone, anvils etc

**Comment by PeratX** [comment]
@thebigsmileXD Yes.Actually at first,Genisys is designed for poor computers.

**Comment by aodzip** [comment]
@PeratX 
Seems you have a good time in ImagicalCorp?

PS:我正在试图读懂iTX的编写风格以后就可以投入实际维护了

**Comment by PeratX** [comment]
@aodzip It seems it is.

**Comment by matcracker** [comment]
I'm working on weather and some blocks at the moment D:

**Comment by PeratX** [comment]
@matcracker You can see mipy weather system at https://github.com/iTXTech/Genisys/tree/master/src/pocketmine/level/weather

**Comment by matcracker** [comment]
Yes and some one merge it in ImagicalMine but I don't like it, I'm
rewriting the code look at the weather branch is better (with events and
weather in level file).

**Comment by PeratX** [comment]
:P

**Comment by aodzip** [comment]
Hey guys How about add more switch

But turn off features isn't a good idea improve performance is the basic thing

**Comment by thebigsmileXD** [comment]
@PeratX toggeling the wether did nothing, just saying

**Comment by thebigsmileXD** [comment]
By the way, i really try to improve the performance using bitwise operators.. But most can' read them and change them to something different.. -.- which is pretty annoying. Stop doing that!
