### ISSUE TITLE
Critical Inventory Bug!

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#44231]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

Windows 10, not sure if MCPE has this, but still critical.
Hold the item in hand, press E (Show Inventory), then ESC (Close Inventory), and the item automatically be dropped.
You guys know how annoying this bug gives !

**Comment by dterweij** [comment]
Also with chest. Items I put in chest I get back in in the Inventory, or the chest wont open at all after such actions (a relogin and chest can be opened again)

**Comment by Saburo40** [comment]
![0_35](https://cloud.githubusercontent.com/assets/17522680/13407841/42901926-df09-11e5-90a9-d9f764eafd69.jpg)

**Comment by c-hri-s** [comment]
See here for an example: http://webmshare.com/0EZq1

W10 w/latest build of IM: If you select an item to replace one already in your tray, you start throwing items on the floor. Sometimes one, sometimes loads.

If I run a local W10 server this doesn't occur.

**Comment by leonardosnt** [comment]
Same here!

**Comment by keithkfng** [comment]
If this isn't fixed, can @Pub4Game commit this into IM? Thanks. https://github.com/Nukkit/Nukkit/commit/03d0e15d1567e8fbf5127a3ddb1d6504daa1ffd7

**Comment by Pub4Game** [comment]
Well, tonight

**Comment by keithkfng** [comment]
@Pub4Game try your best, people are busy like you :)
