### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by carstenberger** [ImagicalMine/ImagicalMine#448]
My daughter is complaining that boats are not working and it is always raining

**Comment by thebigsmileXD** [comment]
Read other issues and before that the contribution file.
This is 1. a duplicate and 2nd we are working on that

**Comment by thebigsmileXD** [comment]
Actually they are something totally new in PocketMine/ImagicalMine.

**Comment by Tee7even** [comment]
Is there any plans for boats in 1.0?

**Comment by keithkfng** [comment]
Well, not for now they're currently driving @thebigsmileXD insane LOL

**Comment by thebigsmileXD** [comment]
If you could read that would make it so much easier

**Comment by Tee7even** [comment]
@keithkfng I see.

**Comment by thebigsmileXD** [comment]
Not actually.. @Perax had them fixed now

**Comment by keithkfng** [comment]
Wow, I must be watching the news on the wrong day. Maybe 1986 LOL

**Comment by thebigsmileXD** [comment]
@PeratX How do they work now? Are they real entities? As long as i know, the linking is already in Player.php, so may you teach me how they are coded and how i could implement them to IM?

**Comment by PeratX** [comment]
@thebigsmileXD Boats work properly now :) $entity->setLinked

**Comment by thebigsmileXD** [comment]
@PeratX ah, i see.. would you be so kind to implement them to IM? IDK what files you need

**Comment by ZombiePower** [comment]
does anyone else want to work on this?

**Comment by NML32** [comment]
I thought I saw that boats can be placed if so it's not working for me.

**Comment by thebigsmileXD** [comment]
They were placed as blocks. It was.. Naah. Didn't work

**Comment by PeratX** [comment]
@thebigsmileXD I will try to implement it next weak.

**Comment by thebigsmileXD** [comment]
@PeratX thanks

**Comment by keithkfng** [comment]
@PeratX English correction: *week*

**Comment by PeratX** [comment]
@keithkfng :)
