### ISSUE TITLE
Doensn't Auto-Save

### ISSUE THREAD

**Issue by XFuryMCPE** [ImagicalMine/ImagicalMine#452]
Server restarts, everything I build before the restart is gone. Make this configurable maybe?

**Comment by XFuryMCPE** [comment]
or is it already ._. probably should've checked

**Comment by keithkfng** [comment]
/save-all
You can use this with TimeCommander if you like. I think this is a bug though if it doesn't save itself when the server is shutting down. Or did you force shut it?

**Comment by XFuryMCPE** [comment]
it shuts down with ASR, wont save when it does that nor when it crashes

**Comment by matcracker** [comment]
You should do /save-all first of restart the server

**Comment by thebigsmileXD** [comment]
Actually.. i never have any problems with saving. Wen the server crashes, it saves. When you close the executeable, it won't save.

**Comment by matcracker** [comment]
Me too

**Comment by thebigsmileXD** [comment]
I have a vanilla server and one with 64 plugins. Just works fine

**Comment by remotevase** [comment]
I also have this problem, but just as @keithkfng suggested, I use TimeCommander and have it issue the command "/save-all" every 10 minutes

**Comment by remotevase** [comment]
The "auto save" does not ALWAYS work when stopping the server, only SONETIMES

**Comment by thebigsmileXD** [comment]
It works for me. And also when it stops/crashes

**Comment by robske110** [comment]
I NEVER had autosave problems!
Do you know that that was one of the best programmed features?

**Comment by thebigsmileXD** [comment]
Okay. Maybe your pocketmine.yml is messed up? 3 people confirm there are no saving issues..
