### ISSUE TITLE
Survival: When removed fire block you still get on fire.

### ISSUE THREAD

**Issue by dterweij** [ImagicalMine/ImagicalMine#456]
Example: Grassblock. Put fire on it with Flint & Steel.
I used a Diamond PixAxe to kill the fire. Now the fire is gone.
If I walk over the Grassblock I still get on fire and my healt is going down.
Every time I walk over a Grassblock where ever was a fire and removed, I still get on fire.

**Comment by thebigsmileXD** [comment]
I had this when WorldProtect was on my server. Place the fire there again and remove it

**Comment by InfornoFire** [comment]
Haha, i remember this glitch, it used to happen with local multiplayer where the client would have the same thing happening, way to fix it is to put a block on top or have the owner (not for imagicalmine) remove it

**Comment by HimbeersaftLP** [comment]
I have also the same problem, with and without WorldProtect. P.S.: If you put water on it, it will stop to burn. 🚒

**Comment by ZombiePower** [comment]
fixed?

**Comment by BlackShadow1** [comment]
Yes, it is
