### ISSUE TITLE
Glitch Through Protected Blocks

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalMine/ImagicalMine#483]
When blocks are protected, even if they cannot be broken, you can try and glitch right through them. It does not happen on bukkit pc, and it shouldn't happen on MCPE.

**Comment by InfornoFire** [comment]
To reproduce, go on a 1 block ceiling, dig straight down (mine the block under you) and you will pass through it.

**Comment by PocketKiller** [comment]
wait.. i did test this with the official PocketMine.. it doesn't happen.
but are you sure..

**Comment by thebigsmileXD** [comment]
It does happen with PocketMine also.

**Comment by MCPEPIG** [comment]
On my server, it's fixed (I used genisys, but before, when I was using ImagicalMine, it wasn't happening either) BTW, can you remove my server from the list. I use genisys now.

**Comment by InfornoFire** [comment]
Welp, it used to be fixed, something happen that messed with pocketmine codes. What files did you based ImagicalMine on, the 1.5 dev or 1.6 bleeding builds and stuff.

**Comment by ZombiePower** [comment]
not possible... it will only happen to blocks extending transparent (slabs etc...)

**Comment by robske110** [comment]
Why closed?
Issue is still there and that are not only transperent blocks!

**Comment by thebigsmileXD** [comment]
I can confirm

**Comment by InfornoFire** [comment]
...

**Comment by ZombiePower** [comment]
well... you will need to make a seperate plugin for that (like on BC Realms), however, i am sure that you cant actually break* the protected block

**Comment by thebigsmileXD** [comment]
You can. Tested on a vanilla server. A bit lag and you glich through

**Comment by robske110** [comment]
How about cancelling playerMovement if BlockBreakEvent is being cancelled by a plugin?

**Comment by thebigsmileXD** [comment]
Yea.. maybe

**Comment by PocketKiller** [comment]
How do you wanting us to fix this? just Adventure mode so client won't be able to break blocks and it's client fault.
