### ISSUE TITLE
MCPE Randomly crashing (Not server)

### ISSUE THREAD

**Issue by NML32** [ImagicalMine/ImagicalMine#487]
I'm hearing from my players that their MCPE is randomly crashing. Is this happening to anyone else?
Sorry, I don't have any details since it's random.

**Comment by BlackShadow1** [comment]
This happens because their RAM is very small and go to the 80% consume and crash MCPE, sorry for my english.

**Comment by NML32** [comment]
I don't think that is what's happening it only started a few builds ago. It even happens on my Win10 MCPE.

**Comment by BlackShadow1** [comment]
Maybe MCPE crash?

**Comment by thebigsmileXD** [comment]
Sometimes my MCPE on iOS also crashes. Any snowfall on the server? Might be because of the leaf coloring

**Comment by InfornoFire** [comment]
Happens when i exit a chest sometimes

**Comment by NML32** [comment]
I've had it happen to me while just standing in spawn not doing anything.

**Comment by CLiu13** [comment]
This happens to me whenever I step on a leaf, snowy or un-snowy.

**Comment by keithkfng** [comment]
Personally I think it's a MCPE bug, cos when you go on Lifeboat that happens too.

**Comment by EpicSteve33** [comment]
I've had this problem on linux sometimes the server just closes without a crash dump

**Comment by robske110** [comment]
With segmentation fault?

**Comment by EpicSteve33** [comment]
Idk sometimes my server just stop and nobody was on there

**Comment by HimbeersaftLP** [comment]
My Windows Phone has never crashed, but on IOS it crashes sometimes without reason.

**Comment by thebigsmileXD** [comment]
iOS version also lags like shit in the menu

**Comment by robske110** [comment]
Wich device?
I have ... iP6SP...

**Comment by thebigsmileXD** [comment]
iPhone 5, iOS 8.1. but Jailbreak, Minecraft thinks i have an 6+ because i've increased the resolution.

**Comment by EpicSteve33** [comment]
I have a iPad, HTC one m7, Samsung s3, LG lucid

**Comment by EpicSteve33** [comment]
Idk maybe that will help

**Comment by TBNRFrags2468** [comment]
same with me i am crashing when i join and it loads and i have the last build of imagicalcorp

**Comment by TBNRFrags2468** [comment]
aka imagicalmine

**Comment by dterweij** [comment]
Got a Windows 10 crash a few times just by placing and deleting blocks. But the Androids also sometimes crashes.  When crashed, sometimes the player is not logged out of the game. Takes a long long time before Imagicalmine detects that the player is gone. I have to /kill player from console else the player wont get in.
Tho it is not annoying, most of the times the players (read: my kids haha) can be in for hours and breaking/placing blocks a lot :)

**Comment by robske110** [comment]
You mean /kick

**Comment by dterweij** [comment]
I use /kill. For this it does not matter what to use, Just the player needs to be logged out by force :(

**Comment by thebigsmileXD** [comment]
Kill doesn't log out.

**Comment by NML32** [comment]
MCPE crashes even while standing still and crashes every time if you run on leaves.

**Comment by robske110** [comment]
What? I'm happy to use old builds.

**Comment by thebigsmileXD** [comment]
@NML32 I confirm the thing with leaves.. happened 5 times to me when i jumped to my house over the hedge.

**Comment by PocketKiller** [comment]
No more crashes
