### ISSUE TITLE
Player.php line 2827-2828 , switch syntax

### ISSUE THREAD

**Issue by smyb** [ImagicalMine/ImagicalMine#496]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/Player.php#L2828
there is a **break** before the **case** and brackets are wrong

**Comment by matcracker** [comment]
On which case there as are *break*

**Comment by BlackShadow1** [comment]
switch($recipe->getResult()->getId()){
					case Item::WORKBENCH:
						$this->awardAchievement("buildWorkBench");
						break;
					case Item::WOODEN_PICKAXE:
						$this->awardAchievement("buildPickaxe");
						break;
					case Item::FURNACE:
						$this->awardAchievement("buildFurnace");
						break;
					case Item::WOODEN_HOE:
						$this->awardAchievement("buildHoe");
						break;
					case Item::BREAD:
						$this->awardAchievement("makeBread");
						break;
					case Item::CAKE:
						//TODO: detect complex recipes like cake that leave remains
						$this->awardAchievement("bakeCake");
						$this->inventory->addItem(Item::get(Item::BUCKET, 0, 3));
						break;
					case Item::STONE_PICKAXE:
					case Item::GOLD_PICKAXE:
					case Item::IRON_PICKAXE:
					case Item::DIAMOND_PICKAXE:
						$this->awardAchievement("buildBetterPickaxe");
						break;
					case Item::WOODEN_SWORD:
						$this->awardAchievement("buildSword");
						break;
					case Item::DIAMOND:
						$this->awardAchievement("diamond");
						break;
				}
				break;
			case ProtocolInfo::CONTAINER_SET_SLOT_PACKET:
				if($this->spawned === false or $this->blocked === true or !$this->isAlive()){
					break;
				}

**Comment by smyb** [comment]
so, is also not possible start the server

**Comment by smyb** [comment]
just move the break; and the bracket

**Comment by BlackShadow1** [comment]
I think isn't a syntax error, look, the case are in the switch, so the break is for the switch..

**Comment by TBNRFrags2468** [comment]
do you guys still have to copy the latstbuild of imagicalmine because i just save the file it works perfectly

**Comment by ZombiePower** [comment]
@TBNRFrags2468 random commits messed up the whole thing...

**Comment by ecoron** [comment]
looks fine for me, the break is from the case ProtocolInfo::CRAFTING_EVENT_PACKET: (line 2669)
and the bracket is from the switch statement (line 2793) which is inside  the case starting line 2669
it isn't an issue

**Comment by smyb** [comment]
the break on line 2814 should be removed

**Comment by ecoron** [comment]
as i explained, there is no need to remove this.
btw Player.php is realy messed up, shoud be rewritten or better structured.

**Comment by thebigsmileXD** [comment]
Which we are slowly doing.
