### ISSUE TITLE
More players than configured slots can join

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalMine/ImagicalMine#535]
I have set that i have 5 slots. 6 Players are online, i don't have VIPSlots or other Slot modifying plugins..

**Comment by mwvent** [comment]
CustomAlerts plugin does this to me do you have that?

**Comment by thebigsmileXD** [comment]
Nope.

**Comment by thebigsmileXD** [comment]
10:11:31] [INFO]: Plugins (64): Alias v1.2.0, AlwaysSpawn v2.2.2, BetterGenerators v0.8.1, BloodFX v1.1.0, BulkCommands v1.0-build#007, ChairStairsPE v0.1.0, ChestLocker v1.2, CommandRepeater v1.0.1, CommandSigns v2, DevTools v1.10.0, EmptyWorld v1.0.0, EnderPearl v1.2.3, EssentialsPE v1.1.3, essentialsTP v1.1.0, Firecracker v0.1.1, GrabBag v2.2.7, iControlU v1.3, InstantBreak v2.1.0, iProtector v3.1a, ItemCasePE v1.0.8, JoinCommands v1.4.1, LiveSigns v1.2.1, ManyWorlds v2.0.3, MCG76_WorldEdit v0.5.2, OneHitKill v1.0.1, PlanB v1.2.0, PocketGuard v2.1.1, PocketMoney v4.0.1, Popper v1.0.0, PurePerms v1.2.2, RealTime v2.1.1, ReasonWL v1.1, ReportRTS v1.1.3, RocketPads v1.0.0, ServerAuth v2.11, SignModifier v1.0.0, SignShop v1.1.3, SkinTools v1, SnowHalation v1.8-alpha, TimeCommander v2, VoteReward v3.0τ, WorldProtect v2.2.0, PureChat v1.3.3, SignWarp v1.5.1, SimpleWarp v2.1.0, DynMapPE v0.0.3, HotPotatoPE v0.0.1, InstantRespawn v0.3.1, LIAB v1.0.0, HelpModifer v1.4 Beta, Minecart v0.0.1, MinigameBase v0.0.1, OITCPE v1.0.0, ParcourPos v0.0.1, PlayerStats v2.1, PocketJobs v2, PocketPets v0.1.0, SlapperWatch v0.1.0, Specter v0.4, SpleefPE v1.0.0, WolvesFortress v0.0.1, feed v1.0.0, MyPlot v1, SkyBlock v1.0.2

**Comment by keithkfng** [comment]
... @mwvent is back LOL

**Comment by robske110** [comment]
Is this happening to an ^vanila^ server too?
I can't realy test it because I have 50 slots, but only 25 online (average)

**Comment by thebigsmileXD** [comment]
We could try on 5.175.226.133:19133

**Comment by keithkfng** [comment]
Define what "vanilla" means...

**Comment by robske110** [comment]
Without plugins

**Comment by keithkfng** [comment]
Ah

**Comment by thebigsmileXD** [comment]
Only devtools. Do you have time to join?

**Comment by robske110** [comment]
Joining now

**Comment by robske110** [comment]
Hello?

**Comment by thebigsmileXD** [comment]
Okay

**Comment by thebigsmileXD** [comment]
Sorry, i am at work.

**Comment by lolcraftboy14** [comment]
How can y get dowload link );

**Comment by lolcraftboy14** [comment]
Of EntityManager

**Comment by thebigsmileXD** [comment]
Y link? Sorry, what? And use google. http://gidf.com?q=Entity+Manager

**Comment by TBNRFrags2468** [comment]
Vanilla means normal game no modpacks no spechial addons just minecraft no cheats

**Comment by TBNRFrags2468** [comment]
and same with me i think its a bug so i just set it to 0 players

**Comment by thebigsmileXD** [comment]
Set to 0. still atleast 2 players can join..

**Comment by InfornoFire** [comment]
Here is from google "having no special or extra features; ordinary or standard"

**Comment by thebigsmileXD** [comment]
Tested, still exists in the latest build. Always atleast 1 player too much can get on, i am not sure if more players can join

**Comment by rWardy** [comment]
This this is caused by line 1926 in Players.php:

```PHP
if(count($this->server->getOnlinePlayers()) > $this->server->getMaxPlayers() and $this->kick("disconnectionScreen.serverFull", false)){
```

Should be
```PHP
if(count($this->server->getOnlinePlayers()) >= $this->server->getMaxPlayers() and $this->kick("disconnectionScreen.serverFull", false)){
```

Note that > changes to >= (i.e. kick player if number players online greater than or equal to MaxPlayers in config)

Will stick a Pull Request in once my Hunger, Health and XP fix has gone through.

**Comment by rWardy** [comment]
LOL, was just working out how to close issue :)
