### ISSUE TITLE
Please revert MainLogger

### ISSUE THREAD

**Issue by jazzwhistle** [ImagicalMine/ImagicalMine#54224]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

Since /server was added to the start of all $messages I have to compile each update from source, edit the $message format, makeserver etc for Multicraft to display things correctly; is there any chance of either removing that (imho unnecessary) addition to the already overlong console output, or at least have it toggled by a config switch for us multicraft users? Thanks

**Comment by keithkfng** [comment]
You mean the "system>" back to that stupid "[INFO]" output? No way, sorry. But - @HmHmmHm was planning to make Utils:CustomLogger so that you could customise the message. Except for the fact he hasn't been active on GitHub for a couple of weeks(he probably joined the army :D). @ecoron would this be possible?

**Comment by dterweij** [comment]
Then close this :) And do not change something for just one user whereby all other users has to follow that only one user whishes. I think he just doing fine to checkout the source. If he uses a diff to patch it back just before the phar make then he does not even look at it.
Like:
build.sh
- patch -p jazzwhistle-logger-multicraft.patch
- build.php

So easy :)

**Comment by keithkfng** [comment]
@dtjerweij yes, but it's not just him. It's all Multicraft users - especially ones that host their servers with a server hosting provider. So we have to do something about it anyway XD

**Comment by dterweij** [comment]
ok :) then indeed a full revert and then start to develop a CustomLogger.

**Comment by ecoron** [comment]
There is no need for revert. It's the prefix of logger->info() This can easily removed, or maybe changed to info. I think logging has only configured via a loglevel setting or, a bit more advanced, a configured log format.
