### ISSUE TITLE
Fallable sometimes fall + stand still

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalMine/ImagicalMine#554]
When you place fallable blocks (anvil, sand etc), they sometimes stay, but also create an falling entity.
Tested with @matcracker

**Comment by dterweij** [comment]
Correct. It is there for ages,  I have a small building in the air that have sandblocks in it. Everytime I walk or fly in the neighbourhood i see a Zombie falling out of the building and drops far below on the grass.  I have to say this exists for about 7 weeks orso. Its fun to see some action in a world where every entity stands still :)

**Comment by thebigsmileXD** [comment]
It was fixed in PM in 0.11, but somehow is back.

**Comment by keithkfng** [comment]
Make it the falling zombie game XD

**Comment by dterweij** [comment]
hehe :) i go right away make more sand castles in the air :)

**Comment by ZombiePower** [comment]
any test servers?

**Comment by thebigsmileXD** [comment]
5.175.226.133:19133

**Comment by keithkfng** [comment]
@thebigsmileXD how about play.imagicalmine.me or play.imagicalmine.net(when @aodzip and I get the domain setup)?

**Comment by thebigsmileXD** [comment]
It will change to WolvesFortress.de today

**Comment by InfornoFire** [comment]
Love the thing, dupe items XD

**Comment by keithkfng** [comment]
Bug fixed.
