### ISSUE TITLE
Crash on stop

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalMine/ImagicalMine#565]
```
Fatal error: Call to undefined method pocketmine\nbt\tag\Enum::quit() in C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\src\pocketmine\PocketMine.php on line 475

Call Stack:
    0.0034     127064   1. {main}() C:\Users\Administrator\Desktop\Server\MinecraftPE\ImagicalMineTestServer\src\pocketmine\PocketMine.php:0
```
No arguments cause crash.

**Comment by robske110** [comment]
So if a plugin calls stop() the server will crash?

**Comment by ZombiePower** [comment]
well... maybe reasoning the stop might be causing it? @thebigsmileXD try using it without the reasoning part

**Comment by thebigsmileXD** [comment]
plugin? vanilla /stop

**Comment by robske110** [comment]
Oh CRITICAL
man i planned to upgrade to a newer build today but thats too critical!
Is it crashing before, while or after the world saves?

**Comment by thebigsmileXD** [comment]
I don't really know what caused the crash. the crash dumb was too small. "crashed while crashing"

**Comment by HimbeersaftLP** [comment]
It crashes after the world saves *huch*. Happens for me to.

**Comment by remotevase** [comment]
@thebigsmileXD ur latest post "crashed while crashing" HUGE SMILE ON MY FACE also upset about this bug

**Comment by robske110** [comment]
This bug seems fixed!
