### ISSUE TITLE
Cocoa pods?

### ISSUE THREAD

**Issue by ZombiePower** [ImagicalMine/ImagicalMine#586]
i just noticed, that there is no cocoa block, and wanted to confirm, that if we should add it?

**Comment by thebigsmileXD** [comment]
There are no cocoa plants yet.

**Comment by ZombiePower** [comment]
http://minecraftpocketedition.wikia.com/wiki/Cocoa_Beans

**Comment by thebigsmileXD** [comment]
Don't you understand? They aren't in PE for now

**Comment by ZombiePower** [comment]
i saw them in single player..... forest biome.. but if you believe so...

**Comment by HimbeersaftLP** [comment]
They are in PE, you need them to make Cookies

**Comment by thebigsmileXD** [comment]
Wohoo, cookies. Okay i was wrong them. Wasn't sure because PM removed them again. Want me to add them? With all 3 stages?

**Comment by ZombiePower** [comment]
yes sure :D

**Comment by kiyoshi-kurosaki** [comment]
Added cocoa beans -> 2f94c727de2d577dcf50d0adf14fbd10a7fa211b

**Comment by thebigsmileXD** [comment]
Added the blocks.
https://github.com/ImagicalMine/ImagicalMine/commit/34fcf579c605e6a71d75db2330221aa1b8269fb4
