### ISSUE TITLE
Ban these idiots!!!

### ISSUE THREAD

**Issue by MCPEPIG** [ImagicalMine/ImagicalMine#5976]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------
Ban these spammers, @keithkfng

**Comment by keithkfng** [comment]
Contacted GitHub Support.

**Comment by PocketKiller** [comment]
@keithkfng I contacted them many times, then what they did is disabled the issue feature...
@MCPEPIG I tried closing his issues to fast then blocked him, then he created those spam accounts...

**Comment by keithkfng** [comment]
@PocketKiller blocking him makes no difference. It only bans him from YOUR repository and profile.

**Comment by zzm317** [comment]
@keithkfng @PocketKiller i know who did this
the reason i guess is ibookcc said something rude
and than for some reason he made zhymc angry
so he wrote a machine to open issues
=-=sorry that i didn't close the issue feature at once=-=

**Comment by PocketKiller** [comment]
@keithkfng *Blocked them from ImagicalMine org.
