### ISSUE TITLE
Any way to disable Golems?

### ISSUE THREAD

**Issue by NML32** [ImagicalMine/ImagicalMine#599]
I'm worried that snow golems drag snow everywhere and they could be used to grief in protected areas if somebody just pushes along a snow golem.
Not to mention over population of Golems on the server. lol

**Comment by matcracker** [comment]
I'll do that :+1:

**Comment by thebigsmileXD** [comment]
Genisys has settings for that, they are already copied. You just have to update the yml and so on

**Comment by MCPEPIG** [comment]
The snow won't do anything, when you tap it or relog, it disappears

**Comment by rWardy** [comment]
Is this something that should be going into IM, or is a more of a mod thing?

**Comment by keithkfng** [comment]
Should be implemented.

**Comment by BlackShadow1** [comment]
I think @matcracker is off, so I assigned me.
