### ISSUE TITLE
MSG

### ISSUE THREAD

**Issue by Martin77Epic** [ImagicalMine/ImagicalMine#6]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## /msg bug

When i do /msg fywgjfjg vjhwyjfwfjg it white and not red like anthoner ....

**Comment by Martin77Epic** [comment]
Because..

**Comment by Ad5001** [comment]
Just use a §4 at any space
