### ISSUE TITLE
2 Issues, Main: Gamemode Error

### ISSUE THREAD

**Issue by remotevase** [ImagicalMine/ImagicalMine#6228]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

**Main Issue: **

This happened when someone joined: (Did Not Crash The Server)

`TypeError: "Return value of pocketmine\Player::getGamemode() must be of the type boolean, null returned" (EXCEPTION) in "/src/pocketmine/Player" at line 1070`

**Other Issue: **

Over 20 pages of the issues are spammed with innappropriate issues. They are from multiple accounts. This is not related to ImagicalMine code, but the ImagicalMine Github Issue Tracker.

**Comment by InfornoFire** [comment]
Ok, I emailed them, but to fix this is a bit easy, Delete every file in the Player folder I think should help

**Comment by InfornoFire** [comment]
Or you can give us the log

**Comment by ecoron** [comment]
Hmm, didn't saw this issue in the latest builds, so on which build you noticed it. Seems the default gamemode isn't set proper for any reason.

**Comment by remotevase** [comment]
@InfornoFire thanks, that fixed the problem
@ecoron I am using the latest build, but @InfornoFire helped me fix the problem (Player files were still from 0.13)

**Comment by remotevase** [comment]
Also, thank you for deleting the other spam issues
