### ISSUE TITLE
(Enchantment) Need help whether if this is a bug or my mistake

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#627]
About Enchantment problem.
If i do :

$enchantment = Enchantment::getEnchantment(9);
$enchantment->setLevel(2);
$item->addEnchantment($enchantment);
$player->getInventory()->setItemInHand($item);

for my item for the first time, no problem, not big deal. The "Sharpness II" has been added to my item.
Then, i do it again, same slot, same item, with the setLevel(3) and Enchantment::getEnchantment(10) , then my Sharpness II was GONE, and it has been replaced by Smite III.

No, thats not my mean. If i do the above code, add my Sharpness II to my item, then i CHANGE THE SLOT OF THE ITEM, then do it again with level 3 Smite, i will get TWO ENCHANTMENT, and its Sharpness II and Smite III.
Is this a bug ?

**Comment by robske110** [comment]
It looks like a bug...
Wich build are you on?

**Comment by intagaming** [comment]
457 maybe ? I dont know exactly but 45x

**Comment by thebigsmileXD** [comment]
I don't get it.

**Comment by KillerXtream** [comment]
Hey. Its a new bug.

I´ll ask the team for a fix.

Thanks!

**Comment by intagaming** [comment]
@thebigsmileXD I mean i cant have 2 enchantment on my sword if i dont change the slot of the sword in my Inventory .......

**Comment by thebigsmileXD** [comment]
Aahh i see. I'll check

**Comment by Creeperface01** [comment]
it seems to be fixed
