### ISSUE TITLE
Problem with Chest.

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalMine/ImagicalMine#643]
Os: Windows 10
Hardware: Intel i5 4460, 16GB Ram, 2TB SSHD, only local network ( high bandwith use is not a problem)
Wifi Router from Lancom: LANCOM L-451agn Wireless
my smartphone is a Galaxy s6 Edge with newest update ( 5.1.1)
Build: Jenkins1.0Dev #487
 

So if i take some items from my chests they go instantly back.
I see in this time my pc and smartphone use 0kb/s of internet and I think this is the reason, why this ot work correctly.

**Comment by dterweij** [comment]
Correct. Noted here also.

**Comment by keithkfng** [comment]
Maybe we should get the original PocketMine repo files - all the files seem to have errors in them -_-

**Comment by ZenaGamingsky** [comment]
yes

**Comment by keithkfng** [comment]
I believe this is not a bug anymore, reopen if needed however.

**Comment by remotevase** [comment]
nope, we fixed it
