### ISSUE TITLE
Can I start PHP7 compatible write of using another branch?

### ISSUE THREAD

**Issue by HmHmmHm** [ImagicalMine/ImagicalMine#645]
Hello @keithkfng and first time!
I think many times ImagicalMine must be support PHP7
can I commit some part to the another branches?

there are must be can support windows and linux etc...
I already can support windows x86 and x64 both,
https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher

and linux php7 compile scripts also same can start
(i already checked php7 is can be done of the universial support)

**Comment by keithkfng** [comment]
Yup, sure! @mixailenko5 can also help you I think.

**Comment by dterweij** [comment]
Everyone can make a own fork. Then make a branch like IM-PHP7 and go coding. Then testers can use your fork->branch to test if it works with PHP7 and its stability on different systems (Win/Lin/Mac).
I dont think this has to be asked anyway, everyone can do this if they can code :)
btw always keep track of the upstream/master so a final PR or merge can be done without (some) conflicts.

**Comment by dterweij** [comment]
Great : http://pecl.php.net/package/Weakref
Finaly fixed for PHP 7

**Comment by dterweij** [comment]
To help you a bit:

---

Installing:
 php-pecl-weakref                 x86_64                 0.3.1-1.el6.remi.7.0                   remi-php70 

---

[danny@server03 minecraft-pe]$ zts-php -v
PHP 7.0.2 (cli) (built: Jan  6 2016 15:34:53) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

---

[danny@server03 minecraft-pe]$ zts-php PocketMine-MP.phar
PHP Fatal error:  Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/danny/minecraft-pe/PocketMine-MP.phar/src/pocketmine/Server.php on line 117

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/danny/minecraft-pe/PocketMine-MP.phar/src/pocketmine/Server.php on line 117

**Comment by HmHmmHm** [comment]
I already knew that problem ( • ̀ω•́ )✧ thanks for report @dterweij

**Comment by keithkfng** [comment]
@HmHmmHm you'd better start if you want to finish before you go and join the conflicts in the world :)

**Comment by keithkfng** [comment]
Anybody else know PHP 7 and the PocketMine API here? XD

**Comment by PocketKiller** [comment]
Yes, me.
example : 
```php
function test($msg){
echo $msg;//string
}

//on PHP 7 it can check if it is a string

function test(string $msg){
echo $msg;//string
}

**Comment by jojoe77777** [comment]
> To help you a bit:
> 
> Installing:
> php-pecl-weakref x86_64 0.3.1-1.el6.remi.7.0 remi-php70
> 
> [danny@server03 minecraft-pe]$ zts-php -v
> PHP 7.0.2 (cli) (built: Jan 6 2016 15:34:53) ( ZTS )
> Copyright (c) 1997-2015 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
> with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
> 
> [danny@server03 minecraft-pe]$ zts-php PocketMine-MP.phar
> PHP Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/danny/minecraft-pe/PocketMine-MP.phar/src/pocketmine/Server.php on line 117
> 
> Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/danny/minecraft-pe/PocketMine-MP.phar/src/pocketmine/Server.php on line 117



> I already knew that problem ( • ̀ω•́ )✧ thanks for report @dterweij

(I'm guessing the reason for that crash is that PHP7 adds a class called Float, so you need to change ImagicalMine/PocketMine's Float class name to something else, like FloatTag. (Done in the php7 branch of PM https://github.com/PocketMine/PocketMine-MP/commit/7f8b39a63c7d3d0849b722412f2cdaf362d80349))

**Comment by keithkfng** [comment]
@PocketKiller could you start with the upgrade? Thanks...

**Comment by dterweij** [comment]
I think its is a bad design by start. I did looked at it for 15 minutes and cant believe what is done. But making it ready for PHP7 is big task. Good luck, i hope you guys will make this happen :) As PHP7 is way more faster, PM will be way more faster as well :)

**Comment by keithkfng** [comment]
@dterweij yes, and we need more active devs to make it happen :)

**Comment by HmHmmHm** [comment]
oh good news now i have many time!.. i'll do my work

**Comment by keithkfng** [comment]
Awesome! Take your time :)

**Comment by PocketKiller** [comment]
@keithkfng i've got 15 free days time, but i need help replacing all class renaming on the IM ;-;

**Comment by keithkfng** [comment]
Anybody helping? XD how about I invite @applqak

**Comment by PocketKiller** [comment]
@keithkfng im not sure ;)

**Comment by keithkfng** [comment]
He has wanted to work on IM :)

**Comment by PocketKiller** [comment]
Ok could everyone also commit their commits on php7 branch with php5 then i'll update it to php7 so the php7 branch won't get outdated.

**Comment by thebigsmileXD** [comment]
Or you use update from master?

**Comment by PocketKiller** [comment]
php7 branch.

**Comment by lolcraftboy14** [comment]
Can y use php7 on android armv7 from pocketmine ore use php7.0.2 wand its sepport
Not android

**Comment by DRedDogPE** [comment]
Should we do this or would it just be too long.


```php

<?php
// Pre PHP 7 code
use some\namespace\ClassA;
use some\namespace\ClassB;
use some\namespace\ClassC as C;

use function some\namespace\fn_a;
use function some\namespace\fn_b;
use function some\namespace\fn_c;

use const some\namespace\ConstA;
use const some\namespace\ConstB;
use const some\namespace\ConstC;

// PHP 7+ code
use some\namespace\{ClassA, ClassB, ClassC as C};
use function some\namespace\{fn_a, fn_b, fn_c};
use const some\namespace\{ConstA, ConstB, ConstC};
?>
```

**Comment by PocketKiller** [comment]
it'll be too long :/

**Comment by DRedDogPE** [comment]
Thought so.

**Comment by lolcraftboy14** [comment]
I PHP 7 android ARMv7 use pocket or mine should I use php7.0.2 fore android I think it does not exist fore android

**Comment by lolcraftboy14** [comment]
I sorry bad translat

**Comment by PocketKiller** [comment]
@DRedDogPE would you like to help me on PHP7 branch?

**Comment by DRedDogPE** [comment]
@PocketKiller sure

**Comment by PocketKiller** [comment]
@DRedDogPE Yes ;)

**Comment by DRedDogPE** [comment]
@PocketKiller What are the main things we need to do?

**Comment by PocketKiller** [comment]
@DRedDogPE to make PHP7 work with IM, like making that define of the return of functions ;)

**Comment by DRedDogPE** [comment]
```php
(is_integer($key) ? $key : '"' . $key . '"')
```
to
```php
(is_integer($key) ?? '"' . $key . '"')
```
correct?

**Comment by DRedDogPE** [comment]
```php
	if(version_compare("5.6.0", PHP_VERSION) > 0){
		$logger->critical("You must use PHP >= 5.6");
		++$errors;
	}
```
to
```php
	if(version_compare("7", PHP_VERSION) > 0){
		$logger->critical("You must use PHP >= 7");
		++$errors;
	}
```
??

**Comment by PocketKiller** [comment]
7.{what} i dunno..

**Comment by PocketKiller** [comment]
will make a test and a plugin to show PHP Version.. 0_0

**Comment by DRedDogPE** [comment]
ok

**Comment by PocketKiller** [comment]
no luck..
@HmHmmHm look at this
![screenshot 51](https://cloud.githubusercontent.com/assets/13422058/12491244/1dc3d44e-c08b-11e5-9dad-d406df69b380.png)

**Comment by DRedDogPE** [comment]
ok ill look into it too

**Comment by DRedDogPE** [comment]
![DERP](http://i.imgur.com/keXRQLr.png)

**Comment by PocketKiller** [comment]
@DRedDogPE :+1: i should learn how to use the internet..

**Comment by keithkfng** [comment]
Anybody know where the pthreads extension for php7 is? Travis and Jenkins are driving me insane...

**Comment by dterweij** [comment]
extenstions are at pecl.php.net  do a search term in the bar and you get the page link to it.

**Comment by dterweij** [comment]
For the people running on CentOS, Use the REMI repository and enable php7

Current info:
php-pecl-pthreads-3.1.5-1.el6.remi.7.0.x86_64
php-pecl-weakref-0.3.1-1.el6.remi.7.0.x86_64

[root@server03 ~]# zts-php -v
PHP 7.0.3RC1 (cli) (built: Jan 20 2016 12:04:38) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

[root@server03 ~]# cat /etc/centos-release
CentOS release 6.7 (Final)

[root@server03 ~]# arch
x86_64

You need to use the zts-php binary as that one is used with pthreads. The normal php binary is a non-zts build.
That means, the start scripts should check OS versions and use the proper PHP binary. But thats for later guys, no hurry :) In short, no extra PHP package needed anymore, we can use the systems PHP when IM is PHP7 ready.
