### ISSUE TITLE
Forum CPU Exceeded

### ISSUE THREAD

**Issue by remotevase** [ImagicalMine/ImagicalMine#6503]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------
Very often, I go to forums.imagicalmine.me and it redirects me to this website: http://www.hostinger.com.hk/cpu_exceeded?forums.imagicalmine.me

Is this an issue only for the U.S? Or for everyone?

**Comment by remotevase** [comment]
I still have this issue, so @keithkfng why did u close it

**Comment by keithkfng** [comment]
Not an issue with ImagicalMine really.

**Comment by remotevase** [comment]
Ok, but can you fix this ASAP plz, that would be nice, as I love forums...

**Comment by applqpak** [comment]
Yeah.

**Comment by remotevase** [comment]
Thanks for fixing!

**Comment by keithkfng** [comment]
I don't fix the servers - it automatically comes up when it recovers from the error LOL

**Comment by remotevase** [comment]
The error again... Here it is...

**Comment by flaxues** [comment]
It's no error :P You just reached you monthly usage you better some other 'free' webhost because hostinger sucks!
