### ISSUE TITLE
Armor dont break

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalMine/ImagicalMine#654]
Os: Windows 10
Hardware: Intel i5 4460, 16GB Ram, 2TB SSHD, only local network ( high bandwith use is not a problem)
Wifi Router from Lancom: LANCOM L-451agn Wireless
my smartphone is a Galaxy s6 Edge with newest update ( 5.1.1)
Build: Jenkins1.0Dev #.500

Error:

The Armor dont loose HP so the armor is unlimited. Thanks for help. 

Sorry for my bad english I am german.

**Comment by keithkfng** [comment]
@kiyoshi-kurosaki same here? Could you try fixing this... This is probably not a crafting issue, sorry XD

**Comment by ZombiePower** [comment]
?

**Comment by PocketKiller** [comment]
@ZombiePower you know what armor does right? but not workin' anymore

**Comment by ZombiePower** [comment]
@PocketKiller again..how do you understand these sort of english?

**Comment by PocketKiller** [comment]
> @PocketKiller again..how do you understand these sort of english?

use your mind.
and uhh this isn't a chat room LOL

**Comment by ZombiePower** [comment]
@PocketKiller I knew what the problem was... -_- I was talking to Keith. (I talked to him on Twitter, so it doesn't matter anymore)

**Comment by keithkfng** [comment]
I never receive any messages from you... Maybe it's my blindness XD

**Comment by ZombiePower** [comment]
Yep ;p

**Comment by UltimateMcraft** [comment]
(On-Topic)
I kind of think I have the issue, I'll check
(off-Topic)

@keithkfng  I just read this issue, from what I can see, it means the armour won't break, my issue says It has no effect

**Comment by keithkfng** [comment]
The armour doesn't lose HP basically means it has no effect... Unless I don't understand it correctly?

**Comment by UltimateMcraft** [comment]
I think it means it doesn't do this:
![image](https://cloud.githubusercontent.com/assets/6726237/12482062/883064d2-c05e-11e5-8d88-9358738aeee7.jpg)
See those green bars? that's the armours health

**Comment by PocketKiller** [comment]
@UltimateMcraft oh maybe yes.. he edited his main post
