### ISSUE TITLE
Iron Pickaxe durability bug

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalMine/ImagicalMine#655]
Os: Windows 10
Hardware: Intel i5 4460, 16GB Ram, 2TB SSHD, only local network ( high bandwith use is not a problem)
Wifi Router from Lancom: LANCOM L-451agn Wireless
my smartphone is a Galaxy s6 Edge with newest update ( 5.1.1)
Build: Jenkins1.0Dev #.500

Error:

The Iron Pickaxe dont work correctly. The durability is like from the stonke pickaxe i can only brake ~128 Blocks.Thanks for help. 

Sorry for my bad english I am german. :)

**Comment by keithkfng** [comment]
Since @kiyoshi-kurosaki is so good at fixing crafting and item issues, I'll assign you to this...

**Comment by kiyoshi-kurosaki** [comment]
Tested, but item has durabillity?!

**Comment by MyHwu9508** [comment]
I mean the iron pickaxe has the durability of a stone pickaxe. So I can not brake more Blocks.

**Comment by ZombiePower** [comment]
they seem fine to me

**Comment by ZombiePower** [comment]
seems fine to me...

**Comment by dterweij** [comment]
I do break a lot blocks, and no problem with the axes.

**Comment by rWardy** [comment]
Been testing this and need a little advice. Tested with an iron pickaxe and dirt blocks.
Durability is correctly set at 251 when the item is created.
Breaking a dirt block with a pickaxe should remove 2 points of durability (as the correct tool for dirt is a shovel). I can see this happening in Item\Tool.php useOn function, and the numbers look right when it drops in there and leaves.

However when I break the next block the durability has changed by a further point.  This is happening by a call to setDamage in Level.php on line 1697.

My thoughts are that the call in Level.php is not needed as the durability is handled in Tool.php

Anybody got any thoughts?

**Comment by ecoron** [comment]
The  call in Level.php looks ok for me. In Tools.php is the value of meta is incremented but i don't see where this value is used. Maybe getDamageCount() should return variable values depending on what's the Tool is used.

**Comment by rWardy** [comment]
setDamage and getDamage change/return the meta value.When meta/getDamage() = getMaxDurability() then the tool is destroyed.  This is checked in Level.php line 1835, and Player.php line 2659.

I'm thinking only one of the two calls should take place either the useOn or the setDamage call. Not fully followed all the logic to check if they will always happen together, or once may get called without the other,

**Comment by ecoron** [comment]
Seems you are right. I can check it tomorrow, now it's time for me to get some sleep.
