### ISSUE TITLE
Can't Craft Wood Planks

### ISSUE THREAD

**Issue by BobbyTowers** [ImagicalMine/ImagicalMine#673]
I can't craft wood planks in the crafting table. It only's shows wood pressure plates are craftable. I'm using version #521

**Comment by kiyoshi-kurosaki** [comment]
Works for me....

**Comment by rWardy** [comment]
Not working for me.  I'm not sure where to look in the code to see the issue,  Can see the recipe is registered in CraftingManager, but not sure where it works out what you can craft.

**Comment by dterweij** [comment]
Report your OS client. Android or Windows 10 beta. Can be significant I think.

**Comment by rWardy** [comment]
Client would have been android.  Server running on Ubuntu.

**Comment by kiyoshi-kurosaki** [comment]
I hope commit d0f75ca4885d58de0c762aee9a5c35ea5e488157 will fix that :)

**Comment by rWardy** [comment]
I'll get it applied now and tested tonight

**Comment by rWardy** [comment]
Still not working.  I think there is a problem with ShaplessRecipes in general.  Have added the following code to make a Wooden Button:
$this->registerRecipe((new ShapelessRecipe(Item::get(Item::WOODEN_BUTTON, 0, 1)))->addIngredient(Item::get(Item::WOODEN_PLANK, Planks::BIRCH, 1)));

And this isn't working either.  Still investigating.

**Comment by kiyoshi-kurosaki** [comment]
@rWardy You just write, you cannot craft wooden planks, but not wooden button....

**Comment by kiyoshi-kurosaki** [comment]
So just fixed :) 9ea17d2f1a17fef54e1f1517b23028f4c592c551

**Comment by rWardy** [comment]
I can't craft anything that is a shapeless recipe from what I can tell.

**Comment by kiyoshi-kurosaki** [comment]
For me it works :D

**Comment by rWardy** [comment]
Any pointers in where I can look to debug?

**Comment by PocketKiller** [comment]
@rWardy after you craft, open the inventory and look, you'll find it ;)/

**Comment by rWardy** [comment]
Is there a chat room we have somewhere to discuss rather than on here :)

**Comment by PocketKiller** [comment]
@rWardy http://forums.imagicalmine.me/

**Comment by kiyoshi-kurosaki** [comment]
![button xd](https://cloud.githubusercontent.com/assets/10975001/12497480/4d5ec946-c09c-11e5-91cb-c1b118260085.png)

**Comment by rWardy** [comment]
That's a forum, not a chat room. Do we not have IRC or something?

**Comment by PocketKiller** [comment]
@rWardy yes we did on gitter, but it is removed.

**Comment by kiyoshi-kurosaki** [comment]
@keithkfng can it be closed? but for me it's fixed

**Comment by rWardy** [comment]
How does that work? I have an issue, but because it works for you it can be closed?

**Comment by rWardy** [comment]
@PocketKiller would an IRC channel not encourage collaboration?

**Comment by rWardy** [comment]
OK, does this help. Did the following to my code:
REMOVED (line 68):
```PHP
$this->registerRecipe((new ShapelessRecipe(Item::get(Item::WOODEN_PLANK, Planks::SPRUCE, 4)))->addIngredient(Item::get(Item::WOOD, Wood::SPRUCE, 1)));
```

Then ADDED:
```PHP
$this->registerRecipe((new ShapedRecipe(Item::get(Item::WOODEN_PLANK, Planks::SPRUCE, 4),
    "X"
))->setIngredient("X", Item::get(Item::WOOD, Wood::SPRUCE, 1)));
```

And the planks now show in the crafting table.

**Comment by kiyoshi-kurosaki** [comment]
I don't know if i need to change ShapelessRecipes to ShapedRecipes...i don't know

**Comment by rWardy** [comment]
Only thing I can think is the format of the DataPacket for a ShapelessRecipe is not being understood by my client (Android). Are you using iOS?

**Comment by kiyoshi-kurosaki** [comment]
No just using Windows 10 Edition.

**Comment by rWardy** [comment]
Hmmm. Could edit the registerShapelessRecipe function (line 1407) to call registerShapedRecipe instead if only a single ingredient?

**Comment by kiyoshi-kurosaki** [comment]
Isn't it correct?

**Comment by rWardy** [comment]
It must be correct up to a point because it is working for you, but I can't see why it not working for me.  Just thought that if no issue with using a ShapedRecipe instead, it would be easier to change registerShapelessRecipe to call registerShapedRecipe rather than update all Shapeless Recipes in the file.

**Comment by BobbyTowers** [comment]
I'm on android by the way.

**Comment by kiyoshi-kurosaki** [comment]
But for me it works on Android :D i testet it 10 min ago

**Comment by kiyoshi-kurosaki** [comment]
Line 1385 -> public function registerShapedRecipe(ShapedRecipe $recipe) that?

**Comment by rWardy** [comment]
Hmmm, interesting. Let me get latest blank code into new folder and see what I get.

**Comment by rWardy** [comment]
Completely blank folder, installed using:
```
wget -q -O - http://get.imagicalcorp.ml/Linux64 | bash
```

And it doesn't work. I tried giving me oak wood form command line and also wood that I have collected, and when I go into Inventory and crafting tab it doesn't list anything I can make.

**Comment by kiyoshi-kurosaki** [comment]
[CraftingManager.txt](https://github.com/ImagicalMine/ImagicalMine/files/100125/CraftingManager.txt)

**Comment by rWardy** [comment]
That file is identical to the file on my server (compared in Nodepad++)

**Comment by BobbyTowers** [comment]
![screenshot_2016-01-21-19-33-04](https://cloud.githubusercontent.com/assets/12857229/12499168/28469574-c076-11e5-9d4f-1e7b67702f02.png)

**Comment by 0Hughman0** [comment]
I'm also having this issue. I'm currently running dev#538. I can craft planks on the Win10 version, but not on android. I feel like it may have temporarily fixed it, and for some reason the issue has re-appeared. I appreciate your work trying to get this fixed.

**Comment by rWardy** [comment]
Still looking @0Hughman0

**Comment by rWardy** [comment]
Any objections if I change any Shapeless Recipes to Shaped Recipes similar to those I posted above. Not got access to iOS or Windows version of Pocket Mine so can't check if this causes any issues.

The change would be from this:
```PHP
$this->registerRecipe((new ShapelessRecipe(Item::get(Item::WOODEN_PLANK, Planks::SPRUCE, 4)))->addIngredient(Item::get(Item::WOOD, Wood::SPRUCE, 1)));
```

to this:
```PHP
$this->registerRecipe((new ShapedRecipe(Item::get(Item::WOODEN_PLANK, Planks::SPRUCE, 4),
    "X"
))->setIngredient("X", Item::get(Item::WOOD, Wood::SPRUCE, 1)));
```

**Comment by GreenNature-MC-Server** [comment]
Hi!
I have the same issue where players can't craft wooden planks!
I'm using an older version but i tried it with the newest version 543 since some minutes but i'm downdatet again...
Why? Since i had updated i had nothing crafting recipes.
Is it normal and if crafting recipes work in one version... Which version i must donwload?

**Comment by kiyoshi-kurosaki** [comment]
Normaly fix the bug -> 788186eb0e9e6dbf08dc386492527f2f368d0eb7

**Comment by NML32** [comment]
I have the same issue on both of my Survival server.
Can't craft wood planks.

**Comment by rWardy** [comment]
I'll test tonight.  I think there may be a few more, but i'll have a look later.

**Comment by rWardy** [comment]
This is now fixed
