### ISSUE TITLE
Wrong check of log.enable in Server.php, logging disabled

### ISSUE THREAD

**Issue by ecoron** [ImagicalMine/ImagicalMine#678]
setting log.enable to false enables logging - should be otherwise...
if log.enable isn't set or isset true then logging is disabled noticed in build 527

Line 1617
```
		if(!$this->getProperty("log.enable", true)){
 			$this->logger->info("Enabled log writing to server.log");
 			$this->logger->Enable();
 		}else{
 			$this->logger->info("Disabled log writing to server.log");
 			$this->logger->Disable();
 		}
```
btw. is there somewhere an updated doc of possible server config settings?

**Comment by ecoron** [comment]
i like the project, realy but i'm confused about the closed pr.
from my point of view it makes no sense to set log.enable: false in the config to get the log.
and it makes no sense to fix a mistake with another one.
translation of line 1617: if log.enable is not true or not set then enable logging (the ! is the negiation)
thats what i changed, maybe not everyone should accept or decline pr's

**Comment by keithkfng** [comment]
It's been changed to enable log writing by default now.
