### ISSUE TITLE
build527 instable, server crashes by running out of memory

### ISSUE THREAD

**Issue by ecoron** [ImagicalMine/ImagicalMine#679]
After upgrading from 494 to 527 the server is running instable. Fast increasing memory usage until limit is reached. The server crashes without writting a Crashdump. No time to track it down, but maybe other seen the same issue. so i switched back to 494 for now.

**Comment by FienixEC** [comment]
i have the same issue with anything after 5xx phars... no crash dump
generated.

**Comment by keithkfng** [comment]
Nobody has reported this issue after the RakLib fix, and their servers seem to be working fine...

**Comment by FienixEC** [comment]
hmm...im actually using a 2xx build due to the random crashing on the
latest..last one i used was 524 and the crashes were non stop. ill try 527
and let you know :D

**Comment by ecoron** [comment]
that's what i see on 527, crashing after some minutes, again and again.

**Comment by keithkfng** [comment]
It should be a problem with your configuration? Many features were added in pocketmine.yml, so you may wish to delete it and make it regenerate automatically, then try running again. Apparent @dterweij could run it for 11 hours and still no crash(I think it's STILL ONLINE LOL)

**Comment by FienixEC** [comment]
im going to try that, 2:55pm my time, just loaded build 527, deleted
existing pocketmine.yml, keep you guys posted! also...my console is now
empty...any idea? or has this been common with latest builds? Thanks for
the help, never the less, im proud to be using imagicalmine, and all of you
are doing an amazing job!! xD

**Comment by keithkfng** [comment]
Console empty? Do you have a screenshot you can provide?

**Comment by FienixEC** [comment]
nevermind on the console thing. apparently deleting old pocketmine.yml
fixed that...so maybe we are on to something!!! (:

**Comment by keithkfng** [comment]
Nice! BTW - server.log writing should be disabled by default... Would you mind deleting server.log and running it again? Take a look at the file after running it - it should be empty... Thanks XD

**Comment by ecoron** [comment]
yes console empty is the previous issue (#678) wrong check in Server.php - set in pocketmine.yml
```
log:
 enable: false 
````
and you get the log

**Comment by FienixEC** [comment]
yea it was just a black screen, both online and through my cpanel app...but
its fixed for some reason after deleting and generating a new yml.

**Comment by keithkfng** [comment]
That shouldn't be the case - I've tested it myself and it works fine... The server.log file is empty. I deleted it before running the latest build if you wanted to know.

**Comment by FienixEC** [comment]
so i deleted the server log, restarted and this is in it...its displaying
the activity shortly after the restart...

**Comment by FienixEC** [comment]
okay, so i loaded build 527, generated a new pocketmine.yml and log file at
2:55pm my time, and the server crashed at 3:09pm and just now again at
3:52pm, no crash report. and all i get is a "Disconnected From Server"
message.

no means of tracking the cause :/

**Comment by keithkfng** [comment]
Console messages?

**Comment by FienixEC** [comment]
nothing. just disconnects everyone and reloads imagicalmine.

**Comment by FienixEC** [comment]
the only other thing i my players and i notice is that any in game builds
about 15 minutes before the crash get deleted, so i do assume it has to be
a memory exhausted thing..

**Comment by isoz** [comment]
Hey I'm sorry for commenting this on here but I didn't know any other place.
I just switched to IM thinking it would give me better performance over PM, but its quite the contrary, I'm feeling at least 30% less performance on latest build, server with 35 people on gets laggy, I have 30 plugins, 32GB ram, Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz @ 8 threads, TPS constantly going down.. I used to be able to keep 20 TPS on PM, with minor spikes here and there.

**Comment by keithkfng** [comment]
Obviously IM isn't made for performance, it's more for an MCPE feel trying to keep up with singleplayer features...

**Comment by SoyPro** [comment]
the same happen in my server,it crash and throw me a message "Disconnected from server"

**Comment by ecoron** [comment]
now i checked it on a dev server in debugmode with exactly the same config and build, without players, and with one player the server runs without crashing. i see some high load peaks. so i will try it tomorrow on my prod server maybe i can catch it there...

**Comment by dterweij** [comment]
Weird. Its running smootly here now. 24+ hours. I just did a git pull and made a new phar a minute ago. So I just started it again. Will report back here only if there is a problem again. So no message from me here means it runs fine. 

" Apparently @dterweij could run it for 11 hours and still no crash(I think it's STILL ONLINE LOL) "

Can the wolf fortress test server be online with latest build? Then let it run for at least a week on that build.Sometimes I join that server :)

**Comment by keithkfng** [comment]
@thebigsmileXD hear that?

**Comment by FienixEC** [comment]
Keith.. im using latest 535 and finally got a crash i can track with a
crash log. seems to be the only crash, after about an hr of running....any
idea of the cause? see attached screenshot.

**Comment by keithkfng** [comment]
Try using the web, not email -_-

**Comment by SoyPro** [comment]
Please put me the lasted version of imagical mine here because i cant download from jenkins,when i try to download from jenkins it throw me DownloadIncorrect,pls put me the lasted version in mediafire or in dropbox or mega

**Comment by DRedDogPE** [comment]
@HostingItAll needs to be updated i think cause its not reading the server.log ![img](http://i.imgur.com/Sd0x6aA.png)

**Comment by keithkfng** [comment]
Yes, @HostingItAll - I merged your PR for your convenience

**Comment by ecoron** [comment]
i think the issue is gone.
i'm now on build 535 and i changed step by step the config to the default one.
i didn't see the crashes anymore.
as conclusion for other people, rename your pocketmine.yml to something as backup and start the server again it creates the default one.
if it's running stable update the config with the changes you need.

**Comment by robske110** [comment]
This is fixed i will close #529 soon, if there won't be further reports! (It was RakLib)
