### ISSUE TITLE
Armour has no effect 

### ISSUE THREAD

**Issue by UltimateMcraft** [ImagicalMine/ImagicalMine#682]
Diamond armour?
It's the same as wearing NO armour

Any armour at all?
No Effect

This kind of ruins PVP, and if you want to reproduce it...

1. Someone else kills you without armour
2. Put armour on
3. Someone kills you with armour

**Comment by robske110** [comment]
Lol, thats why my players are complaining the kits are useless
Confirmed

**Comment by keithkfng** [comment]
See #654.
