### ISSUE TITLE
Slots

### ISSUE THREAD

**Issue by FutureTeam7** [ImagicalMine/ImagicalMine#684]
More slots!

**Comment by kiyoshi-kurosaki** [comment]
How more slots?

**Comment by PocketKiller** [comment]
asking how?

**Comment by kiyoshi-kurosaki** [comment]
I don't understand what he wants to say with "more slots" xD

**Comment by PocketKiller** [comment]
open your inventory on minecraft, isn't it having little bars? on SinglePlayer there are many.

**Comment by thebigsmileXD** [comment]
What is this issue for? USELESS
