### ISSUE TITLE
Not compatible Multicraft.

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#686]
Added cool design + Colored ASCII update not compatible Multicraft. Multicraft not detect server runing.

**Comment by PocketKiller** [comment]
multicraft fault.

**Comment by HimbeersaftLP** [comment]
No, it's because the 'system >' before each console message. Please remove it.

**Comment by HmHmmHm** [comment]
it is not problem, and you can change in your local file.

https://github.com/ImagicalMine/ImagicalMine/blob/dd676c1a34ce43a2d6044b7e3b8df22d511136a2/src/pocketmine/utils/MainLogger.php#L209

$message = TextFormat::toANSI(TextFormat::AQUA . "[" . date("H:i:s", $now) . "] ". TextFormat::RESET . $color . $prefix . "> " . TextFormat::WHITE . $message . TextFormat::RESET);

=>
$message = TextFormat::toANSI(TextFormat::AQUA . "[" . date("H:i:s", $now) . "] ". TextFormat::RESET . $color . TextFormat::WHITE . $message . TextFormat::RESET);

**Comment by thebigsmileXD** [comment]
Of cause, change it after every release ;)

**Comment by HimbeersaftLP** [comment]
That would be exhausting, why don't simply remove it, to keep it compatible with Multicraft = compatible for people using ImagicalMine on a hosted server.

**Comment by HmHmmHm** [comment]
hmm.. may be we can consider about add like a 'ConsolePrintEvent'

**Comment by HimbeersaftLP** [comment]
Or make a switch in the pocketmine.yml ?

**Comment by HmHmmHm** [comment]
it is inefficient. hmm try the development about console output related to plug-in....?

**Comment by HimbeersaftLP** [comment]
I don't understand, what you are meaning... (I'm not so good at English)

**Comment by keithkfng** [comment]
@thebigsmileXD I thought I taught you "of course", not "of cause"... XD
Blame @KillerXtream - he did that LOL

**Comment by thebigsmileXD** [comment]
@keithkfng make the sentence more complicated and you need a network of pc's to understand this.

And i know. This comment is old, and my autocorrect still doesn't get it. I searched it up some hours ago also.

**Comment by robske110** [comment]
Yey English mayhem
