### ISSUE TITLE
Core problem and question on php7

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [ImagicalMine/ImagicalMine#688]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\pocketmine\Server.php on line 117

so i hope to edit from

use pocketmine\nbt\tag\Byte;
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\tag\Double;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\Float;
use pocketmine\nbt\tag\Int;
use pocketmine\nbt\tag\Long;
use pocketmine\nbt\tag\Short;
use pocketmine\nbt\tag\String;

to

use pocketmine\nbt\tag\ByteTag;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\DoubleTag;
use pocketmine\nbt\tag\EnumTag;
use pocketmine\nbt\tag\FloatTag;
use pocketmine\nbt\tag\IntTag;
use pocketmine\nbt\tag\LongTag;
use pocketmine\nbt\tag\ShortTag;
use pocketmine\nbt\tag\StringTag;

and then this error xD

Fatal error: Uncaught RuntimeException: Declaration of pocketmine\Thread::start($options = pocketmine\PTHREADS_INHERIT_ALL) should be compatible with Thread::start(int $options = NULL) in D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\pocketmine\Thread.php:0
Stack trace:
#0 D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\spl\BaseClassLoader.php(128): ExceptionHandler::handler(2, 'Declaration of ...', 'D:\\SERVER\\GAME ...', 0, Array)
#1 D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\spl\BaseClassLoader.php(128): include()
#2 [internal function]: BaseClassLoader->loadClass('pocketmine\\Thre...')
#3 D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\pocketmine\command\CommandReader.php(31): spl_autoload_call('pocketmine\\Thre...')
#4 D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\spl\BaseClassLoader.php(128): include('D:\\SERVER\\GAME ...')
#5 [internal function]: BaseClassLoader-> in D:\SERVER\GAME SERVERS\Minecraft Windows 10 Edition\PocketMine-MP-master\src\pocketmine\Thread.php on line 0

I don't trust myself to edit it, but you can check this :D 

Regards

Kiyo

**Comment by keithkfng** [comment]
Try the pho7 branch - but it's still a work in progress..

**Comment by kiyoshi-kurosaki** [comment]
Have i the permission to commit it on php7? if not, ist's okay

:=)

**Comment by keithkfng** [comment]
You can if you know how to do it and you know what you're doing or changing.

**Comment by kiyoshi-kurosaki** [comment]
But i try to test it localy before commit it ;)

**Comment by applqpak** [comment]
Hi xP

**Comment by applqpak** [comment]
You guys are spamming my notifications D :

**Comment by PocketKiller** [comment]
I fixed that on PHP7 branch, try it out
