### ISSUE TITLE
No hunger tick?

### ISSUE THREAD

**Issue by SavionLegendZzz** [ImagicalMine/ImagicalMine#689]

**Comment by SavionLegendZzz** [comment]
title explains all i thought of this since i have a minigames server but i use Spartan but i want to use IM for potions but its hard to implement it in Spartan

**Comment by keithkfng** [comment]
Hunger base is from Katana... But most of it changed by @thebigsmileXD

**Comment by SavionLegendZzz** [comment]
hmmmm is this i good idea? because i will try to implement it

**Comment by keithkfng** [comment]
Yes, very good idea... We should have it indeed.

**Comment by dterweij** [comment]
I get hungry when i don't eat. I tested for some time now just survival mode, Planting seeds and make bread etc. I have to eat because hunger is working fine else I am dead :) Also run/walk speed decreases when hunger is about 60% orso.

**Comment by SavionLegendZzz** [comment]
Ok new branch?

**Comment by thebigsmileXD** [comment]
Its 100% changed.

**Comment by rWardy** [comment]
Is this still an issue. Hunger seems to work OK, as long as it is enabled in the yml file
