### ISSUE TITLE
MultiCraft join, and leave support

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#690]
MultiCraft players list
![c87cbee6-96dd-11e5-94cf-4fe33a2dafea](https://cloud.githubusercontent.com/assets/8324198/12495562/adfdb2f0-c090-11e5-9d1e-571514113a2d.PNG)
Connected players list
![06ab7f0a-96dd-11e5-8142-ab65fe760bae](https://cloud.githubusercontent.com/assets/8324198/12495561/adfcd4ac-c090-11e5-8208-ae75c126138f.PNG)
[Connect] User Replay85[/XX.XXX.XXX.XXX:19132], IP 
[Server] INFO Replay85 joined the game

**Comment by SavionLegendZzz** [comment]
we dont control/own MultiCraft

**Comment by keithkfng** [comment]
Multicraft problem.

**Comment by andris155** [comment]
Multicraft easy install pc, and free.

**Comment by andris155** [comment]
http://www.multicraft.org/site/page?view=download
