### ISSUE TITLE
need php7 : type definer remove

### ISSUE THREAD

**Issue by HmHmmHm** [ImagicalMine/ImagicalMine#696]
@DRedDogPE has so many part writed php7 type definer

e.g.:
coreside:
public function FF() : array{
}

pluginside:
public function FF(){
}
=Fatal Error Occur!

if all function makes that
imagicalmine is can not compatible pocketmine...

I already had jobs, but DRedDogPE commit has
makes occurs many wide conflict problem with my coding version

![0505](https://cloud.githubusercontent.com/assets/8337568/12521405/d75dc740-c18d-11e5-867b-6f19f6156658.png)

so i write everything again...... (∩´﹏`∩);
if you think imagicalmine need to compatible with pocketmine
do not add more type definer (only follow pocketmine code)

**Comment by DRedDogPE** [comment]
I can remove it if needed. But are we keeping the array, bool, int and stuff
```php
public function Example() : array{
}
```

**Comment by HmHmmHm** [comment]
@DRedDogPE no that's not need
just follow the pocketmine work way

**Comment by DRedDogPE** [comment]
what about https://github.com/ImagicalMine/ImagicalMine/commit/c83ce5fb08470c67cd02d8eec1d20bd78492ecdd then?

**Comment by HmHmmHm** [comment]
that also need remove again (っ;▽;)っ

**Comment by legoboy0215** [comment]
Make 2 branches, PHP 5 and PHP 7.

**Comment by thebigsmileXD** [comment]
There are.

**Comment by HmHmmHm** [comment]
Fixed 1343609670c7db368f694052b169437cd0a485e6
