### ISSUE TITLE
Banned Player Disconnect Reason

### ISSUE THREAD

**Issue by DRedDogPE** [ImagicalMine/ImagicalMine#699]
I think that when a player who is banned gets kicked when they try to join the message in the banned-players.txt should be used (like with Bukkit) otherwise what point is there for this?

**Comment by thebigsmileXD** [comment]
I'll have a look.. Because i am courious why this happens

**Comment by rWardy** [comment]
This can work for name bans, but not IP bans.  IP bans are done at the network level (using blockAddress), so the Player.php code does not execute.

I've put the code in required to output the reason for both name and IP bans in case the blockAddress code is changed.
