### ISSUE TITLE
Please cancel the player action detection! 

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#700]
Please cancel the player action detection! 
This feature seriously affects the normal game player! 
A large number of false positives, 
players even jumping up the mountain will be pulled back to where!
 If, cannot be done to cancel, then please add a switch in the configuration file! Optimization algorithm!

**Comment by ibookcc** [comment]
In earlier versions, there was a switchLet you decide whether to open the player action detectionPlayer action detection: 1

**Comment by ibookcc** [comment]
But now it has gone!

**Comment by zzm317** [comment]
if you can not speak english well
please use other languages

**Comment by HmHmmHm** [comment]
ummm.... so you mean about
like a fly mode detect?
or invalid move detect?

**Comment by keithkfng** [comment]
I think he means the "<player> moved wrongly!" in the console + the option that holds you back while you're sprinting or flying sometimes...

**Comment by thebigsmileXD** [comment]
Thats when the server has a hickup. caused by raklib. Thats also the reason snow balls don't move smoothly.

**Comment by robske110** [comment]
Just an question: MultiThreading? Does anyone know how to do MultiThreading in php?

**Comment by robske110** [comment]
I know RakLib uses it

**Comment by ibookcc** [comment]
"(player) moved wrongly!" in the console + the option that holds you back while you're sprinting or flying sometimes...

**Comment by ibookcc** [comment]
yes often "(player) moved wrongly!"

**Comment by ibookcc** [comment]
When they walk

**Comment by thebigsmileXD** [comment]
You can't cancel that except when you enable flying on your server

**Comment by robske110** [comment]
He means to disable that "flying" protection by default

**Comment by keithkfng** [comment]
No way...

**Comment by robske110** [comment]
The flying protection is BROKEN

**Comment by thebigsmileXD** [comment]
Oh yea, thats right. Yesterday someone with Ghost hack was online and was flying around.
