### ISSUE TITLE
Jenkins Link

### ISSUE THREAD

**Issue by HimbeersaftLP** [ImagicalMine/ImagicalMine#701]
Jeninks link in the readme doesn't work...

**Comment by Thorodonson** [comment]
link is jenkins.imagicalcorp.ml:8080/job/imagicalmine/lastbuild

**Comment by Thorodonson** [comment]
Close this. this is not an issue anyways so dont post stuff like this on the issues page

**Comment by HimbeersaftLP** [comment]
Somebody should change the link in readme...

**Comment by thebigsmileXD** [comment]
I will.

**Comment by keithkfng** [comment]
@HimbeersaftLP can't you see "DO NOT POST ISSUES ABOUT JENKINS" in the README? Geez, some people really need to read - I'm getting really annoyed now.

**Comment by robske110** [comment]
@keithkfng Some people don't have time to read the mistructured readme! It should be in contributing! And there is so many text to read Try to cool down a little bit and don't get to annoyed by us. If this post annoyed you, i'm sorry
German lol
