### ISSUE TITLE
fishing rod / bobber doesn't retract

### ISSUE THREAD

**Issue by unerds** [ImagicalMine/ImagicalMine#705]
the game just sends out another bobber, and the old one doesn't go away.

**Comment by thebigsmileXD** [comment]
😂 soz

**Comment by HimbeersaftLP** [comment]
Help! How can I remove the bobber?

**Comment by thebigsmileXD** [comment]
I use grabag. /et nuke others
(but ClearSky fixed it)

**Comment by HimbeersaftLP** [comment]
thx

**Comment by robske110** [comment]
@thebigsmileXD could you prot the bobber fix over?

**Comment by thebigsmileXD** [comment]
Currently not. Player.php is rewritten also

**Comment by PocketKiller** [comment]
why didn't my commit close this issue?
