### ISSUE TITLE
Why？

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#709]
Create the item bar with four identical fish

**Comment by keithkfng** [comment]
Do read the contributing guidelines, else you'll be banned.

**Comment by thebigsmileXD** [comment]
Fixed in clearsky by @MCPEPIG

**Comment by keithkfng** [comment]
Possible to port it over?

**Comment by thebigsmileXD** [comment]
@MCPEPIG can you do this? (or is he banned)

**Comment by keithkfng** [comment]
No, he was never banned...
