### ISSUE TITLE
Painting can't be placed

### ISSUE THREAD

**Issue by SuperAdam47** [ImagicalMine/ImagicalMine#711]
Painting item is not working

**Comment by keithkfng** [comment]
There is no need to put a label like that in the title.

**Comment by SuperAdam47** [comment]
fix try?

**Comment by NML32** [comment]
It would be nice to have paintings working. Big thanks to who ever gets them working.

**Comment by thebigsmileXD** [comment]
They are placeable in clearsky but have nice bugs.
They drop 2 paintings, can't be instantly killed and they are on the wrong position.

**Comment by thebigsmileXD** [comment]
But atleast they rotate correct

**Comment by BlackShadow1** [comment]
https://github.com/ImagicalMine/ImagicalMine/commit/a0a77efef164acb251ff40b07efb9e99569a70ce

**Comment by SuperAdam47** [comment]
clos?
