### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalMine/ImagicalMine#712]
When player enter into the server.... And this problem not only with PurePerm...also with SimleAuth.
![screenshot_2016-01-24-14-33-00 01](https://cloud.githubusercontent.com/assets/15706847/12536316/47bffea0-c2aa-11e5-88ed-c295df3a801a.png)

**Comment by thebigsmileXD** [comment]
Are you sure you use the latest plugin version? i think not.
