### ISSUE TITLE
MultiCraft srever has started but say it ofline

### ISSUE THREAD

**Issue by ZenaGamingsky** [ImagicalMine/ImagicalMine#713]
Hey your have some probelms with multicarft srever started but it offline fix it
![untitled](https://cloud.githubusercontent.com/assets/11705460/12537314/cef2761a-c2b3-11e5-924e-89cc2cfdef98.png)

**Comment by robske110** [comment]
Again, It's because of the system>

**Comment by thebigsmileXD** [comment]
Nonono.. You tried to set localhost as ip, right? you need the real ip

**Comment by HostingItAll** [comment]
This looks like a server configuration issue and not an issue of this repo.

**Comment by HmHmmHm** [comment]
duplicate issue #686

**Comment by ZenaGamingsky** [comment]
it not i ghave tried it what i o

**Comment by ZenaGamingsky** [comment]
no ip is 192.168.0.28
