### ISSUE TITLE
Hunger not saved on player disconnect

### ISSUE THREAD

**Issue by HostingItAll** [ImagicalMine/ImagicalMine#716]
Please add saving of hunger amount when player disconnects, players currently disconnect and reconnect to reset hunger.

**Comment by robske110** [comment]
Is XP working now?
And I know that it was on ToDo-Lists but it never got implemented!

**Comment by rWardy** [comment]
Am looking at Hunger at moment.  Think Health is persisted, although takes a couple of ticks to show on client side.

**Comment by thebigsmileXD** [comment]
Uhm.. Hunger is saved since a couple of builds

**Comment by InfornoFire** [comment]
Uhh, are you using latest build, and robske110, xp has /xp and stuff, but the things that need xp is still on ToDo

**Comment by rWardy** [comment]
@thebigsmileXD doesn't seem to be working on mine, but I am using a bit of a hybrid build.  Any idea which build added it?  I've added a couple of lines on mine in Player to Save() and ProcessLogin() to store and load the food variable.

**Comment by keithkfng** [comment]
@rWardy you may choose to make a PR if it isn't working...

**Comment by rWardy** [comment]
@keithkfng I might do. Just trying to work out an issue. Looking at Health and Hunger, they both seem to start full on initial login, but then change to display the correct value when they are updated (e.g. Hunger reduces food by 1, or i am attacked or eat food).
Not sure what I need to do to fix this.  I might add the PR for the hunger saving, and look at the other issue separately.

**Comment by rWardy** [comment]
@thebigsmileXD I've had a look back and there was a Pull Request that doesn't look like it made it into the master branch #355 
My Pull request  #731 is very similar.
