### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalMine/ImagicalMine#718]
Issue #712 . @thebigsmileXD , I'm sure I use the latest 540 build -_-

**Comment by alex2534alex** [comment]
It is PHP error maybe. Just I install kernel on my Android via PocketMine-MP, and all is OK. But on my PC it isn't be all OK.

Sorry by my English if I somesing tell wrong.

**Comment by alex2534alex** [comment]
If I install PocketMine (http://www.pocketmine.net) (NOT ImagicalMine), and just replace kernel to ImagicalMine, all be OK. BUT, if I follow this instruction (http://imagicalmine.readthedocs.org/en/latest/installation.html), it isn't be OK (I mean #712)

**Comment by alex2534alex** [comment]
I used this link on by x64-bit PC : http://get.imagicalcorp.ml/Linux32

**Comment by dterweij** [comment]
PlayerStats plugin same error. Did not happen before. But everything seems works fine, I dont complain :)

**Comment by alex2534alex** [comment]
It's plugin issue
