### ISSUE TITLE
Jenkins appears to be stuck

### ISSUE THREAD

**Issue by NML32** [ImagicalMine/ImagicalMine#722]
Could someone take a look and see why Jenkins has stopped. Looks like there are two builds that have stopped compiling.

**Comment by BlackShadow1** [comment]
if(!Terminal::hasFormattingCodes()){
			echo $cleanMessage . PHP_EOL;
		}else{
			echo $message . PHP_EOL;
		}
Undefined variabile $cleanMessage on linea 213.

**Comment by keithkfng** [comment]
Fixed. Do read the README as well please.
