### ISSUE TITLE
Planks from logs

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#723]
Planks still can't be made from logs. This was fixed in the latest build of ImagicalCORE.

**Comment by keithkfng** [comment]
ImagicalCore shouldn't be used for production or use.

**Comment by Skyladd** [comment]
ImagicalCore is the only version that allows players to craft planks on my server though. No one can craft wood to planks it only crafts into pressure plates.

**Comment by rWardy** [comment]
I think this is same as #673 It only affects Android from what we can tell, but struggling to find correct fix.  Still being investigated.

**Comment by PocketKiller** [comment]
oops, i thought ImagicalCorp

**Comment by kiyoshi-kurosaki** [comment]
Fix 5a83a5d94b3a933f03ef36c6fbc4ca97c3a732ff

**Comment by rWardy** [comment]
This is duplicate of #673 Above referenced fix will not correct this issue.

**Comment by kiyoshi-kurosaki** [comment]
Aaahh i'm overheating xD

**Comment by rWardy** [comment]
:)
