### ISSUE TITLE
Eat food can not get of hunger.

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#725]
Eat food can not get of hunger.

**Comment by ibookcc** [comment]
on #540

**Comment by kiyoshi-kurosaki** [comment]
Don't have any problem :/

**Comment by robske110** [comment]
There is still the giveItem bug

**Comment by thebigsmileXD** [comment]
Only on signs

**Comment by ibookcc** [comment]
Some food like Carrot and Raw potato still can't get of hunger.

**Comment by ibookcc** [comment]
on #570

**Comment by ibookcc** [comment]
@thebigsmileXD

**Comment by rWardy** [comment]
I might be mis-understanding, but what is the actual problem? When you eat Carrot it is not filling your food bar up?

**Comment by PocketKiller** [comment]
@rWardy yes.

**Comment by rWardy** [comment]
OK, i'll take a look later if nobody beats me to it :)

**Comment by thebigsmileXD** [comment]
Search in player.php for milk, then you'll be at the food lines @rWardy

**Comment by rWardy** [comment]
Carrot and Potato are working OK for me. Any more detail you can add?
