### ISSUE TITLE
Nether Quartz Ore should drop 1 Nether Quartz instead of mt_rand(4,8) Nether Quartz

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#726]
I found this:

public function getDrops(Item $item){
		if($item->isPickaxe() >= Tool::TIER_STONE){
			return [
				[Item::QUARTZ, 0, mt_rand(4, 8)],
			];
		}else{
			return [];
		}
	}

In Minecraft Wiki: "Nether quartz ore mined using a pickaxe will drop one unit of nether quartz"
Hnmm please fix this (I don't know how to use Git so ...)
Oh, here is the link: http://minecraft.gamepedia.com/Nether_quartz

**Comment by PocketKiller** [comment]
as I see and tested on Minecraft PE, it drops 3 or 4 units, hmm.. this is the first time i see gamepedia doing something wrong.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/12546815/b59b64da-c34c-11e5-82ab-29f0a8a8024a.jpg)
It just drops 1 unit. With enchantment you could get up to 4.

**Comment by thebigsmileXD** [comment]
fixed via https://github.com/ImagicalMine/ImagicalMine/commit/5ad63e8c1727adb67ca042d59059ba77999b868f

**Comment by PocketKiller** [comment]
i was using an enchanted pickaxe LOL
