### ISSUE TITLE
Still can't Synthesis board.

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#727]
Still can't Synthesis board.
In the latest version.
I'm version is #543.
Please fix it.´<_´
This is my third time to report a similar problem

**Comment by PocketKiller** [comment]
can't get paintings..

**Comment by PocketKiller** [comment]
Stop duplicating

**Comment by ibookcc** [comment]
@PocketKiller Can you give me a reply?

**Comment by ibookcc** [comment]
What's copy？？

**Comment by ibookcc** [comment]
copying

**Comment by ibookcc** [comment]
I can't know You's some word.

**Comment by ibookcc** [comment]
Ver #400 maybe can do.
I try it

**Comment by thebigsmileXD** [comment]
@ibookcc We'll ban you if you continue

**Comment by ibookcc** [comment]
What's continue china mean?

**Comment by ibookcc** [comment]
@thebigsmileXD IF I CAN UP PIC,I CAN SHOW YOU !!

**Comment by ibookcc** [comment]
WHY CAN'T BELIVE ME!!

**Comment by zzm317** [comment]
just ban him

**Comment by PocketKiller** [comment]
actually i don't believe anything he says
