### ISSUE TITLE
When update?

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalMine/ImagicalMine#729]
MCPE 0.14.0 build 1 will be released after 2 hours! When ImagicalMine will be updated to 0.14.0?

**Comment by robske110** [comment]
We're still working on the 0.13.x Bugs, so we will only start 1 month before the OFFICAL Release!

**Comment by PocketKiller** [comment]
when you find the link give me it please i was searching it now ;)

**Comment by robske110** [comment]
Good idea, but should be fed with the fixed from master too (But we don't know enough whats changed right now...)

**Comment by PocketKiller** [comment]
it'll be merged when a **Release** (not beta or dev) on the google play and app store comes out.

**Comment by matcracker** [comment]
Keep calm and play 0.13 xD

**Comment by keithkfng** [comment]
Geez... Just play 0.13 :P

**Comment by keithkfng** [comment]
But having said that, I think we should also make a mcpe-0.14 branch and start working on it for preparation.

**Comment by SalmonGER** [comment]
http://pocketbeta.minecraft.net/2016/01/changelog-whats-new-in-0140.html?m=1

I don't know if it's different but thats the official changelog.

**Comment by SalmonGER** [comment]
Its again time to let the iOS users cry and update all the servers to the beta build. I like that.

**Comment by KillerXtream** [comment]
SHUTUP

**Comment by MasterWolf** [comment]
0.14 released! So lets make branch?

**Comment by keithkfng** [comment]
So let's actually start to look...

**Comment by robske110** [comment]
0.14 hasn't been released yet!! (Still beta)

**Comment by MasterWolf** [comment]
Oh yes! I See it...
