### ISSUE TITLE
Has the Console output changed?

### ISSUE THREAD

**Issue by NML32** [ImagicalMine/ImagicalMine#733]
Something must have changed recently with the ImagicalMine console output that has affected the way my chat and console windows look on both of my Virtual Gladiator  servers.

**Comment by keithkfng** [comment]
It's only the prefixes like "system> blahblahblah" instead of "[INFO] blahblahblah"

**Comment by Thorodonson** [comment]
Once again now an issue.

I know how u fell keith. PEOPLE WONT READ

**Comment by kiyoshi-kurosaki** [comment]
Not realy a problem? xD

**Comment by NML32** [comment]
It's a big problem for anyone using Virtual Gladiators to run their PM server.

**Comment by keithkfng** [comment]
I'll contact Multicraft to get something done.  I like the current text output format :)
