### ISSUE TITLE
Options to turn off server broadcasts

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#736]
On/off give, effect broadcast, it's spammy

**Comment by kiyoshi-kurosaki** [comment]
Which broadcast?

**Comment by XiangZhao969** [comment]
Give and effect, it's spammy

**Comment by ecoron** [comment]
I can take look on it, maybe could be done by a config or permission flag.

**Comment by matcracker** [comment]
Do a plugin

**Comment by PocketKiller** [comment]
@matcracker I can make one exactly like the latest version of MHelpMoifer :smile:

**Comment by matcracker** [comment]
@PocketKiller, we must follow the way to create a vanilla server without more other "inutil" features. This feature can be done with a plugin, if you do a config for each request of people we always change config...

**Comment by XiangZhao969** [comment]
how it's going :v
