### ISSUE TITLE
Specter and Slappers support?

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#737]

**Comment by keithkfng** [comment]
Slapper was fixed. You may want to try Specter as well.

**Comment by XiangZhao969** [comment]
[Server] Fatal error: Call to undefined method pocketmine\Server::getUpdater() in phar:///storage/emulated/0/PocketMine/plugins/Specter_v0.4.phar/src/specter/network/SpecterPlayer.php on line 59
[Server] [04:14:55] emergency> An unrecoverable error has occurred and the server has crashed. Creating a crash dump

Specter crash, please fix

**Comment by keithkfng** [comment]
That'll be because of the auto-updated being removed. Nothing can be done about that.

**Comment by thebigsmileXD** [comment]
Add it back ;)

**Comment by keithkfng** [comment]
There's no way I'm adding the stupid auto-updated back...

**Comment by thebigsmileXD** [comment]
*updater

Why not? You have a jenkins. Just let a website check if the current build is older than the jenkins one.
(Btw i started to do it)

**Comment by keithkfng** [comment]
Why don't you do it LOL

**Comment by thebigsmileXD** [comment]
As i said i started

**Comment by keithkfng** [comment]
But gave up or haven't finished?

**Comment by thebigsmileXD** [comment]
Not finished.

**Comment by XiangZhao969** [comment]
Tks @thebigsmilexd

**Comment by XiangZhao969** [comment]
Could you tag me when it's done @thebigsmileXD ? #bigthanks

**Comment by thebigsmileXD** [comment]
@XiangZhao969 of course #bigsmilethanks
