### ISSUE TITLE
players cannot join 0.14

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalMine/ImagicalMine#738]
[20:07:32] system> [/0.0.0.0:19132] logged out due to Login timeout
[20:07:46] system> [/0.0.0.0:19132] logged out due to Login timeout
[20:09:10] system> [/0.0.0.0:19132] logged out due to Login timeout

**Comment by keithkfng** [comment]
What happens on your client? Are you sure you're using a compatible build?

**Comment by EpicSteve33** [comment]
im using build 1 of 0.14.0 and it says locating server

**Comment by keithkfng** [comment]
Are you using a compatible build of IM, not your client -_-

**Comment by EpicSteve33** [comment]
im using the 0.14 build sorry

**Comment by EpicSteve33** [comment]
https://github.com/ImagicalMine/ImagicalMine/tree/mcpe-0.14 

this one

**Comment by keithkfng** [comment]
Try this phar - http://jenkins.imagicalmine.net:8080/job/ImagicalMine-0.14/lastSuccessfulBuild/artifact/releases/ImagicalMine-IC_1.0dev%232.phar

**Comment by EpicSteve33** [comment]
ok

**Comment by EpicSteve33** [comment]
same issue

**Comment by EpicSteve33** [comment]
when I try to join it says locating server and then disconnected from server

**Comment by PocketKiller** [comment]
@EpicSteve33 can I have the APK Please?
@keithkfng maybe some packets are changed.

**Comment by keithkfng** [comment]
@PocketKiller push commits to the mcpe-0.14 branch if you have any changes...
And BTW, the APK is available if you have bought MCPE from Google Play.

**Comment by PocketKiller** [comment]
i haven't bought it, got something from Genisys.

**Comment by EpicSteve33** [comment]
https://www.dropbox.com/s/35jgxfx9eeq404f/Minecraft%20-%20Pocket%20Edition-com.epicsteve.minecraftpe-760140001-v0.14.0.b1.apk?dl=0

This is my version of 0.14 the only thing I changed was the package name

**Comment by PocketKiller** [comment]
try it now, i changed login packet.

**Comment by EpicSteve33** [comment]
do i use the master or 0.14 branch?

**Comment by keithkfng** [comment]
mcpe-0.14 obviously.

**Comment by EpicSteve33** [comment]
ok ill try it

**Comment by EpicSteve33** [comment]
[01:55:28] system> Starting GS4 status listener
[01:55:29] system> Setting query port to 19132
[01:55:29] system> Query running on 0.0.0.0:19132
[01:55:29] system> Default game type: Survival Mode
[01:55:29] system> Done (12.5s)! For help, type "help" or "?"
[09:55:35] notice> [RakLib Thread #-1281111232] Blocked 10.0.0.26 for 5 seconds
[01:55:45] system> [/10.0.0.26:19132] logged out due to Login timeout

**Comment by EpicSteve33** [comment]
still now working and now theres a new message

**Comment by keithkfng** [comment]
Does it connect? Is there a message on your client?

**Comment by EpicSteve33** [comment]
locating server then disconnected from server

**Comment by EpicSteve33** [comment]
![screenshot_2016-01-26-01-59-02](https://cloud.githubusercontent.com/assets/12077835/12577649/893fd86a-c3d0-11e5-8f6a-0b33fbd31472.png)
![screenshot_2016-01-26-01-59-10](https://cloud.githubusercontent.com/assets/12077835/12577652/8fddc196-c3d0-11e5-96ae-6271f3b64116.png)
![screenshot_2016-01-26-01-59-17](https://cloud.githubusercontent.com/assets/12077835/12577659/9859252c-c3d0-11e5-9ba5-1825080380c6.png)

**Comment by lolcraftboy14** [comment]
is tish fixst

**Comment by lolcraftboy14** [comment]
?????

**Comment by PocketKiller** [comment]
no.

**Comment by EpicSteve33** [comment]
Is it?

**Comment by robske110** [comment]
Wait does anything come up on the console?

**Comment by MasterWolf** [comment]
Same problem... Me and my friends can't join! :(

**Comment by PocketKiller** [comment]
with debug now.. CRAZY!
![screenshot 54](https://cloud.githubusercontent.com/assets/13422058/12585870/f5bf7296-c45e-11e5-9b24-358aae8dc68c.png)
![screenshot 55](https://cloud.githubusercontent.com/assets/13422058/12585874/f6515724-c45e-11e5-9376-7eeabb98af67.png)
![screenshot 56](https://cloud.githubusercontent.com/assets/13422058/12585872/f5e7a798-c45e-11e5-9eba-80fd55aa3197.png)
![screenshot 53](https://cloud.githubusercontent.com/assets/13422058/12585873/f5fecffe-c45e-11e5-8695-766ce7f86bbc.png)

**Comment by thebigsmileXD** [comment]
Thats the skin. Lol.

**Comment by PocketKiller** [comment]
Fixed
