### ISSUE TITLE
Can someone explain for me this "multiple attacks" ?

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#739]
http://s15.postimg.org/9h558qvjf/Untitled.png
After my chat is my Problem! It loops 4 times!

This is my problem. I was hit another player 1 time with hand, and my debug shows multiple time.
Ahmm its hard to say, but i used "EntityDamageEvent" to print out it. 
My build is IM dev 540. 
If i havent gave u guys enough infomation, please ask me!

**Comment by kiyoshi-kurosaki** [comment]
Normaly it just hits 1 time....

**Comment by intagaming** [comment]
I hit 1 time but it send 4 messages . . .
Any mistake of "Hit" event ?

**Comment by ecoron** [comment]
DamageEvents are executed several times, maybe you can track down on which entities the DamageEvemts occur

**Comment by intagaming** [comment]
@ecoron Ermmmmm... Minecraft: Windows 10 Edition players as Damager will send the DamageEvents as long as they hold down the left click key, and MCPE players as Damager doesnt.
I tried to debug that, and if i touch very fast my left click, it send 3 and can be 1 sometime . . . then i hold down my left click, it spam my console, 2 seconds and the console in window mode is full of Windows 10 Edition player name which means all of the Damager is the same player.
