### ISSUE TITLE
Incorrect the order of Enchantments

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#742]
I don't know if its called "order" because im bad at english ...
Anyway: 
const TYPE_ARMOR_THORNS = 5;
	const TYPE_WATER_BREATHING = 6;
	const TYPE_WATER_SPEED = 7;
	const TYPE_WATER_AFFINITY = 8;
This should be below code as at the Wiki:
http://minecraft.gamepedia.com/Enchanting

const TYPE_ARMOR_THORNS = 7;
	const TYPE_WATER_BREATHING = 5;
	const TYPE_WATER_SPEED = 8;
	const TYPE_WATER_AFFINITY = 6;

**Comment by BlackShadow1** [comment]
@kiyoshi-kurosaki you forgot to close
