### ISSUE TITLE
About Bow: Are these Critical Bugs ?

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#743]
I have a bow and arrows.
If i trying to throw Arrows on the ground (throw out of Inventory), then the Bow will be throw WITH Arrows too. Both DISAPPEAR.
If i trying to throw Bow that in my Inventory, NOT HOT BAR, then the Bow in Hot Bar will be throw.
And MUCH MORE. Arrrrr so much Bugs. Its better try yourself. If you can't see the bug, ask me to make the video about it. (only if you guys can't see the bug, because im very busy now so sorry . . .)

**Comment by kiyoshi-kurosaki** [comment]
If you hit "Q", it drops the istem :D

**Comment by keithkfng** [comment]
@kiyoshi-kurosaki you can be in charge of item bugs :P

**Comment by intagaming** [comment]
@kiyoshi-kurosaki  it should drop only the Arrows, but both Bow and Arrows were threw :(

**Comment by intagaming** [comment]
And press Q on windows 10 will throw all of Arrows instead of 1...

**Comment by thebigsmileXD** [comment]
@intagaming Thats something because IM/PM can't know if you use win10 edition or pocket edition.
in PE you can only throw full stacks.

I din't understand the initial issue..

**Comment by intagaming** [comment]
@thebigsmileXD But i can actually throw 1 stack of item on Steak, or Wool, or some things other except Arrow ...

**Comment by thebigsmileXD** [comment]
Oooooh i see.. You mean they don't stack up in the inventory?

**Comment by intagaming** [comment]
@thebigsmileXD No. For example im having 63 stacks of Arrow now, so if i press Q, it should be 62 left in my Inv. But its 0, and all the arrows on the ground. 63 stacks of Wool worked fine, and only 1 stack of Wool was on the ground ...

**Comment by thebigsmileXD** [comment]
Lol? Wtf. For me i ever drop all

**Comment by intagaming** [comment]
Agrrrr Minecraft Windows 10 Edition can't connect to localhost anymore, dont know why ...
I think i should work with PE now ...
Okay this problem will be for later, close it ...

**Comment by thebigsmileXD** [comment]
localhost is bugged since 0.11

**Comment by intagaming** [comment]
@thebigsmileXD Windows 10 Edition doesnt have 0.10 ...
I was able to connect to localhost on 0.13.1    a week ago, but now it doesnt .......
I don't know the reason too ...
