### ISSUE TITLE
WOW I HAVE MY NEW ERROR (0.14.0)

### ISSUE THREAD

**Issue by SuperAdam47** [ImagicalMine/ImagicalMine#744]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/aronf/Desktop/Programlar/Pocketmine/ClearSky Minigames - yeni hub/PocketMine-MP.phar/src/pocketmine/Server.php on line 117

**Comment by keithkfng** [comment]
WOW LOOKS LIKE YOU'RE USING CLEARSKY

**Comment by SuperAdam47** [comment]
NO FİLE NAME CLEARSKY

**Comment by keithkfng** [comment]
What's this? "phar://C:/Users/aronf/Desktop/Programlar/Pocketmine/ClearSky"

**Comment by SuperAdam47** [comment]
FİLE NAME CLEARSKY BUT imagicalmine.phar using

**Comment by keithkfng** [comment]
You're using either a PHP7 build or a PHP7 binary anyway
