### ISSUE TITLE
Can't craft carpet

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#749]

**Comment by kiyoshi-kurosaki** [comment]
So fixed -> 95cc6ba86cd27e393583f40aa796cd11462a9c68

**Comment by XiangZhao969** [comment]
Wow thanks, so fast lol

**Comment by kiyoshi-kurosaki** [comment]
I hope it works now :D yeah i do my best for the core ;))

Regards

**Comment by XiangZhao969** [comment]
Carpets can be craft now, but i can't craft wood planks anymore

**Comment by kiyoshi-kurosaki** [comment]
Just rewrote some recipes..please try it again

**Comment by XiangZhao969** [comment]
Just installed #562, the bug is still there...

**Comment by kiyoshi-kurosaki** [comment]
Fix -> c004e18bfab2a85926f59d17b22f66157c1ae772
