### ISSUE TITLE
Recipes show multiple times in crafting interface

### ISSUE THREAD

**Issue by rWardy** [ImagicalMine/ImagicalMine#750]
Think this may be Android related (possibly not Windows 10 due to different crafting interface).

Example recipe is Paper. it shows 3 times in workbench. 1st version shows sugarcane in top row, 2nd version shows sugarcane in middle row, 3rd version shows sugarcane at the bottom.

I can see the code that is doing this (CraftingManager.php line 925 - 943):

```PHP
$this->registerRecipe((new BigShapedRecipe(Item::get(Item::PAPER, 0, 3),
	"SSS",
	"   ",
	"   "
))->setIngredient("S", Item::get(Item::SUGARCANE, 0, 3)));
		
$this->registerRecipe((new BigShapedRecipe(Item::get(Item::PAPER, 0, 3),
	"   ",
	"SSS",
	"   "
))->setIngredient("S", Item::get(Item::SUGARCANE, 0, 3)));
		
$this->registerRecipe((new BigShapedRecipe(Item::get(Item::PAPER, 0, 3),
	"   ",
	"   ",
	"SSS"
))->setIngredient("S", Item::get(Item::SUGARCANE, 0, 3)));
```

ClearSky has this just listed as:
```PHP
$this->registerRecipe((new BigShapedRecipe(Item::get(Item::PAPER, 0, 3),
	"SSS"
))->setIngredient("S", Item::get(Item::SUGARCANE, 0, 3)));
```

This works on my Android (shows sugarcane across middle row), but not sure of iOS or Windows 10.  If somebody could test these changes on iOS and Win 10, I'm happy to make changes.  Key test is that you should be able to place sugarcane on top, middle or bottom row if you have to drag ingredients to the table (Android just shows a list of available recipes).

Thanks,

**Comment by kiyoshi-kurosaki** [comment]
The 1st. works for Windows 10 Edition but on Android it is 3 times in the table, but crafting works.

**Comment by rWardy** [comment]
Does the suggested change not work on Win 10?

**Comment by kiyoshi-kurosaki** [comment]
I can retry it, just wait a few minutes

**Comment by rWardy** [comment]
Thanks!

**Comment by kiyoshi-kurosaki** [comment]
So here's the fix -> 5a83a5d94b3a933f03ef36c6fbc4ca97c3a732ff

**Comment by rWardy** [comment]
Looks good on Android here. If OK on Win10 and iOS can close :)  Now just need to pin down #673 Can you check my proposed fix on Win10?

**Comment by kiyoshi-kurosaki** [comment]
I'm looking right now

**Comment by keithkfng** [comment]
Thanks for working on it! :)
