### ISSUE TITLE
Spam in server console when i put the rails

### ISSUE THREAD

**Issue by Creepername** [ImagicalMine/ImagicalMine#752]
![image](https://cloud.githubusercontent.com/assets/16905629/12607412/04950e68-c4ee-11e5-98eb-5b2b908b8a6b.png)

**Comment by kiyoshi-kurosaki** [comment]
So i temporary disabled the debug, now it doesn't spam the console

-> 3d90bb57f45645af7dc25cf893b66f7ba94f3f3b

**Comment by thebigsmileXD** [comment]
@kiyoshi-kurosaki You don't even know why this happens. It was my fault.

**Comment by kiyoshi-kurosaki** [comment]
Yes i know....wtf

**Comment by thebigsmileXD** [comment]
Fixed via https://github.com/ImagicalMine/ImagicalMine/commit/1bb375c4335dac7c88ac2994433795489be60e09
