### ISSUE TITLE
0.14 items & stuff

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalMine/ImagicalMine#756]
can you guys add "dispensers, droppers, repeaters, **comparators**, slime blocks, **cauldrons**, dyeable armor"

oh and able to open chest and other stuff in c mode

**Comment by matcracker** [comment]
SlimeBlocks added, I'm implementing other :)

**Comment by EpicSteve33** [comment]
R they place able and able to be obtained in c mode

**Comment by matcracker** [comment]
I close this, the same content is in #767

**Comment by EpicSteve33** [comment]
I made mine first but whatever

**Comment by matcracker** [comment]
Yes, don't worry, the 767 has got more things (included this)

**Comment by EpicSteve33** [comment]
Lol
