### ISSUE TITLE
Timezone is not right

### ISSUE THREAD

**Issue by robske110** [ImagicalMine/ImagicalMine#757]
The Timezone is not right here in Germany (-1hour) and there is no place to configure this!

**Comment by keithkfng** [comment]
In your php.ini.

**Comment by MasterWolf** [comment]
But wait. Where to find php.ini file?

**Comment by PocketKiller** [comment]
@MasterWolf /bin/php.ini

**Comment by thebigsmileXD** [comment]
the one in php.ini doesn't work either

**Comment by robske110** [comment]
Mind reopening?

**Comment by robske110** [comment]
I think this has sonething to do with the startup code. I saw a few months ago an statement wich messed around with the timezone. Will try to find it :)

**Comment by robske110** [comment]
And why is this closed now?

**Comment by HmHmmHm** [comment]
@robske110 here using this plug-in
it will be automatically fix your timezone

https://github.com/organization/TimezoneFix
