### ISSUE TITLE
Inventory items disappearing  

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#759]
Players have been reporting that their items in their inventory sometimes randomly disappear. We can't seem to find a trend that may causing it but sometimes it's a single item such as a pickaxe while other times entire inventories disappear. Some players report that their hotbar spazzed out just before losing items too.

**Comment by Driesboy** [comment]
0.14.0 or 0.13.0

**Comment by JasonLamey** [comment]
I have been having this issue in 0.13.0 too.
