### ISSUE TITLE
More inventory bug(s)

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#760]
Sometimes a player will be holding, say a dirt block, when they place it another block in their inventory gets placed as if the picture of the item in the hotbar was wrong. My buddy was tryng to place dirt and on his screen he was holding dirt but on mine he was holding a hoe and the hoe was actually tilling the dirt.

**Comment by PocketKiller** [comment]
i was going to report this, yes it happens on 14.0 version, i get 99+ Fake mashroom blocks, and can't see the real items im having, some are invisible.

**Comment by dterweij** [comment]
Can everyone that reports an issue say if its a 0.13 or 0.14 thing? Makes it now kind of a issue mess :)
Like: [version] Problem with .... or something like that.

**Comment by thebigsmileXD** [comment]
That are the real items. Just the one client side in the hotbar isn't updated. When you choose a new block in c-inventory, it will be changed.

**Comment by robske110** [comment]
This issue is for 0.13 and 0.14
And: I think you can fix it by sending the inventory more often!

**Comment by kakichi** [comment]
On 0.14 when you set the custom nbt tag to a item, (eg. $item->setCustomName("test"); or set enchant tags)
It then gets messed up like showing 99+ mushroom blocks, and the real item disappears.
No above issue in 0.13 though, so maybe something is wrong with nbt structure in 0.14?
