### ISSUE TITLE
UUID ban

### ISSUE THREAD

**Issue by Ragnok123** [ImagicalMine/ImagicalMine#761]
Hello guys, how do you think, is better add to imagicalmine uuid ban, or it will be only plugin? For info: plugin on imagicalmine is DeviceBan.

**Comment by PocketKiller** [comment]
only plugin, why do we need to copy from Genisys?

**Comment by Ragnok123** [comment]
Link please?

**Comment by dterweij** [comment]
Not realy a issue tho .. close or del :P
