### ISSUE TITLE
Error - Server stop

### ISSUE THREAD

**Issue by voviks21** [ImagicalMine/ImagicalMine#766]
ImagicalMine Crash Dump Thu Jan 28 23:38:56 AMT 2016

Error: Maximum function nesting level of '100' reached, aborting!
File: /src/pocketmine/level/Position
Line: 71
Type: E_ERROR

Code:
[62] 		$this->level = $level;
[63] 		return $this;
[64] 	}
[65] 
[66] 	/**
[67] 	 * Checks if this object has a valid reference to a Level
[68] 	 *
[69] 	 * @return bool
[70] 	 */
[71] 	public function isValid(){
[72] 		return $this->level !== null;
[73] 	}
[74] 
[75] 	/**
[76] 	 * Marks the level reference as strong so it won't be collected
[77] 	 * by the garbage collector.
[78] 	 *
[79] 	 * @deprecated
[80] 	 *
[81] 	 * @return bool

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/block/Block(1008): pocketmine\block\Block->getSide(boolean)
#2 /src/pocketmine/block/RedstoneLamp(52): pocketmine\block\Block->isCharged(boolean)
#3 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#4 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#5 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#6 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#7 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#8 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#9 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#10 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#11 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#12 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#13 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#14 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#15 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#16 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#17 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#18 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#19 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#20 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#21 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#22 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#23 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#24 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#25 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#26 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#27 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#28 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#29 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#30 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#31 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#32 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#33 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#34 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#35 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#36 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#37 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#38 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#39 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#40 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#41 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#42 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#43 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#44 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#45 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#46 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#47 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#48 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#49 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#50 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#51 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#52 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#53 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#54 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#55 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#56 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#57 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#58 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#59 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#60 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#61 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#62 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#63 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#64 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#65 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#66 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#67 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#68 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#69 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#70 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#71 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#72 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#73 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#74 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#75 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#76 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#77 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#78 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#79 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#80 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#81 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#82 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#83 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#84 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#85 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#86 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#87 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#88 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#89 /src/pocketmine/block/Block(1074): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#90 /src/pocketmine/block/RedstoneLamp(54): pocketmine\block\Block->BroadcastRedstoneUpdate(boolean)
#91 /src/pocketmine/level/Level(842): pocketmine\block\RedstoneLamp->onRedstoneUpdate(boolean)
#92 /src/pocketmine/Server(2433): pocketmine\level\Level->doTick(boolean)
#93 /src/pocketmine/Server(2591): pocketmine\Server->checkTickUpdates(boolean)
#94 /src/pocketmine/Server(2332): pocketmine\Server->tick(boolean)
#95 /src/pocketmine/Server(2210): pocketmine\Server->tickProcessor(boolean)
#96 /src/pocketmine/Server(1811): pocketmine\Server->start(boolean)
#97 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(boolean)
#98 (1): (boolean)
#99 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT PC 6.1 build 7601 (Windows 7 Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

**Comment by kiyoshi-kurosaki** [comment]
Console output?

**Comment by voviks21** [comment]
This is crash dump

**Comment by kiyoshi-kurosaki** [comment]
Android
iOS
or Windows 10 Edition?

**Comment by ecoron** [comment]
on which build?

**Comment by keithkfng** [comment]
Review contributing guidelines.
