### ISSUE TITLE
Large list of bugs for [0.14.0] version

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#767]
[Actual Bugs]
- [x] Duplicated recipes for oak planks, spruce planks and birch planks (but at least they are now all craftable! xD)
- [x] Hopper has the wrong icon in the inventory as well as cauldrons
- [ ] Items placed in chests in creative vanish
- [ ] Custom inventory in creative doesn't save after exit, so you'll lose any named items
- [ ] Pressure plates and buttons make the wrong sound when triggered
- [ ] Lever makes no sound at all
- [ ] Some non-solid blocks float unsuspended when the supporting block is broken (like torches)
- [ ] Sending a redstone signal to a note block doesn't make the note block emit a sound. The block can be tuned, but can't be triggered by redstone.
- [x] Breaking sounds of blocks are not played
- [x] No particles when a block is broken
- [ ] Boats follow you when you leave them
- [ ] Sudden transition between night and day
- [x] Nether reactors can still be crafted

[Not Yet Implemented Bugs]
- [ ] Hoppers don't work
- [x] Dispenser GUI can't be accessed
- [x] Droppers are not currently present
- [ ] Item frames, repeaters and comparators vanish when placed.
- [ ] Daylight sensors, tripwires and minecarts don't work
- [ ] Maps don't work

**Comment by kiyoshi-kurosaki** [comment]
Duplicated recipes? Ehm normaly its fixed.....

**Comment by Skyladd** [comment]
Could be OS specific, no clue. I have a bug reporter that helps make this list for you guys

**Comment by kiyoshi-kurosaki** [comment]
Also on Android and Windows 10 edition, works

**Comment by BlackShadow1** [comment]
I'll add Dispenser GUI, if anyone isn't working on that.

**Comment by matcracker** [comment]
Nice list! 
I'm working on all 0.14 blocks. Please be patient :)

**Comment by BlackShadow1** [comment]
@matcracker Dispenser GUI is mine. Remember :P

**Comment by Pub4Game** [comment]
` Breaking sounds of blocks are not played`
` No particles when a block is broken`

fixed https://github.com/ImagicalMine/ImagicalMine/commit/6d2896d693309fdbca101b2c11bc288fe54aca6e

**Comment by BlackShadow1** [comment]
` Droppers are not currently  present
https://github.com/ImagicalMine/ImagicalMine/commit/48c1ba6cd83999bb536a813afd742fb8ff9bafc8
Done. Probably it GUI cant be accessed, like Dispenser.

**Comment by simontay78** [comment]
in 0.14.0 MCPE on iPad Air 2 I find the following items cannot be used

Redstone Repeater
Redstone Comparator

Will report more when I find them

**Comment by simontay78** [comment]
I tried to feed Ocelot raw fish to turn them into cats but they remain Ocelot and no feed button appears and the Ocelot still follows me like a cat

**Comment by simontay78** [comment]
Nether Portal don't seems to work

**Comment by simontay78** [comment]
in 0.14.0 MCPE ImagineMine on mac with PureEntities plugin, I find the following items cannot be used
- [ ] Redstone Repeater cannot be placed
- [ ] Redstone Comparator cannot be placed
- [ ] Ocelot feeding fail to turn into cats but beaten with raw fish will still follow you (PureEntities)
- [ ] Nether Portal not working
