### ISSUE TITLE
Console spamming...

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalMine/ImagicalMine#768]
When installed plugin SimpleAuth, Warning/Critical messages are filling up the console (When player joined and left the server).
![screenshot_2016-01-28-21-28-03](https://cloud.githubusercontent.com/assets/15979343/12658888/6435671a-c614-11e5-87f9-c6e80825e556.png)

**Comment by Skyladd** [comment]
If I'm not mistaken, simple auth doesn't do too well, it has many errors. I'd recommend this auth plugin https://github.com/EvolSoft/ServerAuth

**Comment by MasterWolf** [comment]
@Skyladd Emm... Wait! In my server is registered 4K players. So will their passwords saved after installinng ServerAuth?
