### ISSUE TITLE
Missing item EnchantedBook

### ISSUE THREAD

**Issue by GODLIKE5** [ImagicalMine/ImagicalMine#771]
Well it crashes and says missing Enchanting table on src/pocketmine/btn/bin something like that

**Comment by thebigsmileXD** [comment]
Please provide the full crash

**Comment by GODLIKE5** [comment]
Sorry I delete them :/ but it's like Base/item/Enchanting Table

**Comment by GODLIKE5** [comment]
I'll try to get a new one today

**Comment by GODLIKE5** [comment]
ImagicalMine Crash Dump Sun Jan 31 03:45:03 UTC 2016

Error: Class pocketmine\item\EnchantedBook not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 	        if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 		        $name::onClassLoaded();
[138] 	        }
[139] 	        
[140] 	        $this->classes[] = $name;
[141] 
[142]             return true;
[143]         }elseif($this->getParent() === null){
[144] 	        throw new ClassNotFoundException("Class $name not found");
[145]         }
[146] 
[147]         return false;
[148]     }
[149] 
[150]     /**
[151]      * Returns the path for the class, if any
[152]      *
[153]      * @param string $name
[154]      *

Backtrace:
#0 /src/pocketmine/item/Item(1397): spl_autoload_call(string pocketmine\item\EnchantedBook)
#1 /src/pocketmine/nbt/NBT(116): pocketmine\item\Item::get(integer 403, integer 0, integer 1)
#2 /src/pocketmine/tile/Chest(119): pocketmine\nbt\NBT::getItemHelper(pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:403.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:20.pocketmine\nbt\tag\Short:2.}.}.}.pocketmine\nbt\tag\Byte:3.})
#3 /src/pocketmine/tile/Chest(60): pocketmine\tile\Chest->getItem(integer 3)
#4 /src/pocketmine/tile/Tile(88): pocketmine\tile\Chest->__construct(pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:266.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Byte:1.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:403.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:20.pocketmine\nbt\tag\Short:2.}.}.}.pocketmine\nbt\tag\Byte:3.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:361.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:3.pocketmine\nbt\tag\Byte:5.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:263.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:8.pocketmine\nbt\tag\Byte:7.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:263.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:5.pocketmine\nbt\tag\Byte:22.}.}.pocketmine\nbt\tag\String:Chest.pocketmine\nbt\tag\Int:218.pocketmine\nbt\tag\Int:27.pocketmine\nbt\tag\Int:-1100.})
#5 /src/pocketmine/level/format/generic/BaseFullChunk(176): pocketmine\tile\Tile::createTile(string Chest, pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:266.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Byte:1.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:403.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:20.pocketmine\nbt\tag\Short:2.}.}.}.pocketmine\nbt\tag\Byte:3.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:361.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:3.pocketmine\nbt\tag\Byte:5.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:263.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:8.pocketmine\nbt\tag\Byte:7.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:263.pocketmine\nbt\tag\Short:0.pocketmine\nbt\tag\Byte:5.pocketmine\nbt\tag\Byte:22.}.}.pocketmine\nbt\tag\String:Chest.pocketmine\nbt\tag\Int:218.pocketmine\nbt\tag\Int:27.pocketmine\nbt\tag\Int:-1100.})
#6 /src/pocketmine/level/Level(2732): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#7 /src/pocketmine/level/Level(2393): pocketmine\level\Level->loadChunk(integer -69, integer 13, boolean 1)
#8 /src/pocketmine/level/Level(3009): pocketmine\level\Level->getChunk(integer -69, integer 13, boolean 1)
#9 /src/pocketmine/Player(735): pocketmine\level\Level->populateChunk(integer -69, integer 13)
#10 /src/pocketmine/Player(1678): pocketmine\Player->sendNextChunk(boolean)
#11 /src/pocketmine/Server(2598): pocketmine\Player->checkNetwork(boolean)
#12 /src/pocketmine/Server(2336): pocketmine\Server->tick(boolean)
#13 /src/pocketmine/Server(2214): pocketmine\Server->tickProcessor(boolean)
#14 /src/pocketmine/Server(1815): pocketmine\Server->start(boolean)
#15 /src/pocketmine/PocketMine(472): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#16 (1): require_once(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.0dev #0 [Protocol 42; API 1.14.0]

**Comment by GODLIKE5** [comment]
Maybe it's world edit?

**Comment by rWardy** [comment]
Looks like Enchanted Book, not table causing the problem.  Doesn't look like they are implemented in IM yet.

**Comment by GODLIKE5** [comment]
Lol woops sorry 🙏

**Comment by PocketKiller** [comment]
no more crashes.

**Comment by thebigsmileXD** [comment]
You open issues when they are already done since an hour or more
