### ISSUE TITLE
PHP 7 compliant work completed

### ISSUE THREAD

**Issue by HmHmmHm** [ImagicalMine/ImagicalMine#776]
now I report the completion of a work of php7 brunch.
It should consider merging to master brunch.

You can check windows x86 PHP7-launcher
https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher

**Comment by HmHmmHm** [comment]
![23512](https://cloud.githubusercontent.com/assets/8337568/12669865/2db6904a-c6a7-11e5-80aa-9a7926e2d7ca.png)

**Comment by keithkfng** [comment]
Hey - what about the mcpe-0.14 branch? Perhaps you can also start on that as well? Thank you @HmHmmHm for all the work you are doing!

**Comment by HmHmmHm** [comment]
hmm.. of course i can start manage that part

but first of all i think we need to work about
repair imagicalmine <-> pocketmine compatible

and apparently imagicalmine is having entity&tile spawn-move problem.
Is the plan to merge the master brunch and php 7?

**Comment by ChalkPE** [comment]
:+1

**Comment by keithkfng** [comment]
I thought IM & PM were always compatible...

**Comment by HmHmmHm** [comment]
@keithkfng some plug-in developer say to me,
IM doesn't exist e.g. Attribute static instance, TextFormat::ESCAPE

**Comment by HmHmmHm** [comment]
anyway can i start 'IM php7 launcher' repo in ImagicalMine group?

**Comment by keithkfng** [comment]
Sure! Do whatever you need to do.

**Comment by kiyoshi-kurosaki** [comment]
Just started ImagicalMine php7 but i have this error

> Error: Class pocketmine\scheduler\AsyncTask cannot extend from interface Collectable
> File: /src/pocketmine/scheduler/AsyncTask
> Line: 0
> Type: E_COMPILE_ERROR

Regards

**Comment by HmHmmHm** [comment]
@kiyoshi-kurosaki hmm
your pthreads is 3.0.7 and IM pthreads 3.0.0
i'll update pthreads to 3.0.7 IM repo

**Comment by HmHmmHm** [comment]
@kiyoshi-kurosaki patched 9f2cba642e0942e7f1d5799f8bfdb131fd2939d5

**Comment by keithkfng** [comment]
@HmHmmHm don't work on mcpe-0.14 branch yet - wait until it is stable or merged jnto the master branch...

**Comment by kiyoshi-kurosaki** [comment]
For me works :D cannot connect, but i don't have 0.14 xD

**Comment by HmHmmHm** [comment]
@keithkfng so 0.14 branch should be the priority?
php7 merge is 0.14 later?

**Comment by PocketKiller** [comment]
don't merge directly, make a PHP5 branch or i die ;-;

**Comment by HOSTMARCEL** [comment]
is there php 7  for windows pocketmine already? just asking im worried ...

**Comment by HmHmmHm** [comment]
@HOSTMARCEL 
You can check windows x86 PHP7-launcher
https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher

**Comment by HmHmmHm** [comment]
@keithkfng Please tell me whether to allow the merge
i can start merge php7 - master branch

and waht exactly 'main' branch is the purpose?
Is that different master branch and main branch?

**Comment by keithkfng** [comment]
@HmHmmHm the main branch was used to make a backup, but it's not needed now. And yes, make a backup of the current master branch and start the merge please. Thanks!

**Comment by HmHmmHm** [comment]
ok but there will be so many conflicts exist
so first of all i'll sleep and proceed after seven hours
(here is AM:06:08)

**Comment by robske110** [comment]
I would like to have two branches (after 0.14 work completed) PHP7 and master. Please don't simply override the master, just keep two branches and then people can decide wich php version they will use!

**Comment by keithkfng** [comment]
The php7 branch will be merged into master, and a new php5 branch will be kept as well. I don't think it's worth continuing on php5 anyway, because it's a bit outdated... You can use it it you wish, but MCPE 0.14.0 is the last version that php5 will support.

**Comment by robske110** [comment]
@HmHmmHm Do I have to do something with my plugins or are they fully compatible?

**Comment by HmHmmHm** [comment]
@robske110 you just change or add api 1.14.0 -> 2.0.0
e.g.
api:
- 1.13.0
- 1.14.0
- 2.0.0

**Comment by robske110** [comment]
But an API Bump is useless when nothing has changed...

**Comment by keithkfng** [comment]
@HmHmmHm is it possible to implement something such as an automatic plugin updater? I’ve got many people asking me about the changes and what they need to change...

**Comment by robske110** [comment]
If @HmHmmHm would not bump the API we would have nothing to change, because nothing changed!
So please do not bump the API, DevTools won't like that either! Without bumping all plugins would not have to DO ANYTHING!

**Comment by robske110** [comment]
No response?

**Comment by keithkfng** [comment]
Wait... So you're saying we only dusted everything in your bedroom? We upgraded to a new version of the language... What has this got to do with API problems if we have to upgrade plugins anyway....

**Comment by robske110** [comment]
We DO NOT have to upgrade plugins.
(PHP5+7 are compatible, unless you added type identifeier to functions, wich was reverted!)

**Comment by keithkfng** [comment]
@HmHmmHm clarification?

**Comment by HmHmmHm** [comment]
Certainly it should be considered compatible with the older version
So I will be also enabled the old API... which mean,
ImagicalMine is can support 'API 1.X.X' and 'API 2.X.X'

**Comment by robske110** [comment]
How about JUST 1.15 ? (1.14 is current, one bump should be enough!)

**Comment by HmHmmHm** [comment]
nope, we need to compatible with pocketmine.

**Comment by robske110** [comment]
Err then it's compatible

**Comment by robske110** [comment]
What I am trying to point out:
DevTools won't accept 2.0.0 just leave it on 1.14, as every plugin will still WORK!

**Comment by HmHmmHm** [comment]
@robske110 because their 1.1.4 API plugin has still using deprecated function and their really having some other nbt call problem. the ifteam devtool is support api 2.0.0, and i'll add devtool 2.0.0 in imagicalmine repo, so you don't need to worry about it.

**Comment by robske110** [comment]
I don't want an mess like the 1.0.0 update :(
Please add an tutorial/change-instructions what we have to do!

**Comment by lolcraftboy14** [comment]
Wat are you doe with 14.0 branche is gonING to php7

**Comment by MichaelM04** [comment]
@robske110 I do see what you mean about updating api to 2.0.0 but it doesn't seem like that much of a big deal though sertain devs may be inactive and don't want to switch and regular PM hasn't done a "full" php7 conversion yet but it shouldnt be too hard to convert certain old plugins :P

**Comment by robske110** [comment]
Ok, let point me re-explain my Ansicht <-DAFAQ, English:
-I LIKE the php7 upgrade.
-I LIKE API Updates (If well documented)
-I Don't like massive changes to the API  N U M B E R, because almost nothing changed.
