### ISSUE TITLE
What is the reason for the presence of the Katana?

### ISSUE THREAD

**Issue by HmHmmHm** [ImagicalMine/ImagicalMine#781]
I don't understand why Katana source is still remain ImagicalMine project,
and it should be removed..... seriously! (っ;▽;)っ

it even having some syntax problem!
https://github.com/ImagicalMine/ImagicalMine/blob/master/src/pocketmine/katana/KatanaModule.php#L32

if you need just print some imagicalmine logo,
rather, how about we create a Utils::CustomLogger? (･ω･)??

**Comment by matcracker** [comment]
Yeah, I'm agree

**Comment by thebigsmileXD** [comment]
It was added some weeks ago

**Comment by HmHmmHm** [comment]
so i'll remove katana, and there will be exist CustomLogger

**Comment by keithkfng** [comment]
It was actually taken from Katana to make the system> prefixes and the nice messages on startup LOL

**Comment by HmHmmHm** [comment]
If we should do anyway (like a system>?)
I'll make that people can customize using plug-in

**Comment by keithkfng** [comment]
I'd love to keep the existing prefixes - but yes, you may want to make an API for plugins to customize them as well.

**Comment by KillerXtream** [comment]
I will assign myself because i put Katana there.

I will use easily Utils:Terminal and fix it on a future build.

**Comment by keithkfng** [comment]
Okay - I contacted Multicraft support and they fixed up the errors so it works perfectly now. Get rid of Katana later XD
