### ISSUE TITLE
Join creative

### ISSUE THREAD

**Issue by darkspive** [ImagicalMine/ImagicalMine#782]
I cant join 2 times with creative.

**Comment by darkspive** [comment]
It is 0.13 php7

**Comment by PocketKiller** [comment]
we need more info.

**Comment by darkspive** [comment]
Freeze joining
![screenshot_2016-01-29-22-22-54](https://cloud.githubusercontent.com/assets/14966273/12682750/fa4b5a6c-c6d6-11e5-97eb-7562be09e2d2.png)

**Comment by darkspive** [comment]
When i try join by creative twice.
Sry for my english

**Comment by HmHmmHm** [comment]
you need to send console print or crashdump

**Comment by darkspive** [comment]
Join please... Two times.
Server with creative.
IT IS NOT ADVERT!
I will disable this server in 2 day
Ip: 185.46.9.225
port: 19132

**Comment by darkspive** [comment]
U cant join twice

**Comment by darkspive** [comment]
Even u cant join once.
Because server with defaultgamemode creative
