### ISSUE TITLE
cant craft any things

### ISSUE THREAD

**Issue by darkspive** [ImagicalMine/ImagicalMine#786]
cant craft any things.
php7 0.13 and 0.14

**Comment by PocketKiller** [comment]
you can, craft the thing then check your inventory.

**Comment by darkspive** [comment]
![screenshot_2016-01-30-00-42-53](https://cloud.githubusercontent.com/assets/14966273/12686252/741c5c20-c6ea-11e5-816b-b0ad88aeb8a5.png)
Sorry for dark screen

**Comment by HmHmmHm** [comment]
it will be patched

**Comment by HmHmmHm** [comment]
Fixed 50ccc441c8217b954d855a54d4a57aaf3791e2e5
