### ISSUE TITLE
Please add commits to 0.14

### ISSUE THREAD

**Issue by darkspive** [ImagicalMine/ImagicalMine#794]
Add it to 0.14
![screenshot_2016-01-30-09-10-11](https://cloud.githubusercontent.com/assets/14966273/12693637/6748d554-c731-11e5-882d-cc52e2d33420.png)

**Comment by darkspive** [comment]
It is not fixed for 0.14

**Comment by keithkfng** [comment]
You'll be banned if you create "issues" that are not even issues.

**Comment by darkspive** [comment]
You are cool :)
I will donate to when i open my large server.
With bind roundrobin balance.

/*By the way... Lets create udp load balancer base on java?
Bind has too many bugs in my load balancing...
McpeTransfer is not completed*/

**Comment by darkspive** [comment]
:+1:

**Comment by darkspive** [comment]
:(

**Comment by keithkfng** [comment]
In other words, please read the contributing guidelines before creating a new issue.
