### ISSUE TITLE
SimpleAuth 1.7.1 - spam in console when IM server is full 

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#795]
critical> "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': spl_object_hash() expects parameter 1 to be object, null given on SimpleAuth\EventListener                                                             [15:05:42] warning> InvalidArgumentException: "spl_object_hash() expects parameter 1 to be object, null given" (E_WARNING) in "/SimpleAuth.phar/src/SimpleAuth/task/ShowMessageTask" at line 46

**Comment by robske110** [comment]
YOU SHOULD INSTALL SimpleAuth 1.8!!!!
And this has nothing to do with Im

**Comment by XiangZhao969** [comment]
o.O 1.8.0 is out? Can i have link?
