### ISSUE TITLE
Chunk not loaded

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/ImagicalMine#796]
Chunks not loading is a big bug

**Comment by Creepername** [comment]
I have the same bug

**Comment by keithkfng** [comment]
Check your version.

**Comment by HmHmmHm** [comment]
that is mcpe bugs, and it is a fixed 0.14

**Comment by erkam2002** [comment]
I have 0.14.0 alpha build 3 chunks loaded but only low

**Comment by HmHmmHm** [comment]
you need to report more detail
os, build version, branch

**Comment by erkam2002** [comment]
Chunk is is from the beginning of 0.14 branch and we have 2GB ram in 0.13.1 havent chunk bugs but in 0.14

**Comment by HmHmmHm** [comment]
ok i'll check that problem
