### ISSUE TITLE
I can´t find link to php7 imagicalmine-master

### ISSUE THREAD

**Issue by DarkWav** [ImagicalMine/ImagicalMine#799]
Can please anyone send me a link to the imagicalmine-php7-master?
(normal master doesn´t work for me)

**Comment by PocketKiller** [comment]
https://github.com/ImagicalMine/ImagicalMine/blob/php7

**Comment by DarkWav** [comment]
THANKS!

**Comment by DarkWav** [comment]
Page not fuond?

**Comment by DarkWav** [comment]
That one doen´t work

**Comment by HmHmmHm** [comment]
https://github.com/ImagicalMine/ImagicalMine/tree/php7
