### ISSUE TITLE
Request to join back Imagicalmine

### ISSUE THREAD

**Issue by NIIP99** [ImagicalMine/ImagicalMine#8]
Hi, Keith :)
I left the community for a while... And just found out that ImagicalMine repo got deleted by a person...
Anyway, im requesting to join back Imagicalmine, hope u can accept it :)

Thank you, my old friend, keith :D

**Comment by k3ithos** [comment]
@deotern you keep leaving the community and rejoining, don't you? XD
Invited you again :)

**Comment by NIIP99** [comment]
LOL :P I think yeah! xD Because sometimes I felt tried.. xD
Anyway, Im planning to make something big for PocketMine community, mainly for ImagicalMine and PocketMine-MP, the unified PocketMine-MP plugin with graphical user interface, https://plugswork.com/panel :)

Thank you for inviting me :) But I dont see notifications... Neither at email or Github...

**Comment by k3ithos** [comment]
@deotern https://github.com/ImagicalCorp

**Comment by NIIP99** [comment]
Thank you :) Joined

**Comment by k3ithos** [comment]
:)
