### ISSUE TITLE
MultiCraft srever has started but say it ofline bug agin

### ISSUE THREAD

**Issue by ZenaGamingsky** [ImagicalMine/ImagicalMine#803]
i put my ip to 192.158.0.28 and still wont work
![ssssssssss](https://cloud.githubusercontent.com/assets/11705460/12698271/78f81a1c-c790-11e5-92d8-f57fe60056ac.png)

**Comment by kiyoshi-kurosaki** [comment]
Which interface is that? looka nice xD

**Comment by Skyladd** [comment]
Does imagicalmine have a gui? If so how do i access it on linux ubuntu? I currently run it from terminal

**Comment by InfornoFire** [comment]
Did you portfoward and use the ip from http://www.whatsmyip.org/

**Comment by InfornoFire** [comment]
Oh yea, i forgot to mention, if you use verision port forward wont work correctly

**Comment by InfornoFire** [comment]
Btw, thats from a website, he is hosting it from there.

**Comment by ecoron** [comment]
Maybe it's just a typo, console says query is running on 192.168.0.28 not 192.158.0.28

**Comment by InfornoFire** [comment]
Quick question, is localhost thing a built in terminal or a online server hoster. If its built in, then to join use your private ip but for friends its public.

**Comment by SalmonGER** [comment]
Are you using the IP 192.168.0.28 with Port 25565 to join?

**Comment by robske110** [comment]
@Skyladd No this has no guy

**Comment by ZenaGamingsky** [comment]
yes all the old pocketmine works with multicrfat

**Comment by ZenaGamingsky** [comment]
my public ip is 87.81.153.106

**Comment by ZenaGamingsky** [comment]
MultiCraft say this server has started but i has a problme in phar so muticrat can reqisione it as the srever has started

**Comment by SalmonGER** [comment]
@ZenaGamingsky So you use Port 25565 to connect?

**Comment by ZenaGamingsky** [comment]
i used any port the server have started but it says it offline it your phar erro pocketmine works

**Comment by ZenaGamingsky** [comment]
it is not problem, and you can change in your local file.

https://github.com/ImagicalMine/ImagicalMine/blob/dd676c1a34ce43a2d6044b7e3b8df22d511136a2/src/pocketmine/utils/MainLogger.php#L209

$message = TextFormat::toANSI(TextFormat::AQUA . "[" . date("H:i:s", $now) . "] ". TextFormat::RESET . $color . $prefix . "> " . TextFormat::WHITE . $message . TextFormat::RESET);

=>
$message = TextFormat::toANSI(TextFormat::AQUA . "[" . date("H:i:s", $now) . "] ". TextFormat::RESET . $color . TextFormat::WHITE . $message . TextFormat::RESET);

**Comment by ZenaGamingsky** [comment]
the old bug

**Comment by ZenaGamingsky** [comment]
it does

**Comment by ZenaGamingsky** [comment]
i am the ceo of PocketServer.co.uk
