### ISSUE TITLE
Oak trees grow from acacia and dark oak saplings

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#805]
An oak tree grows from acacia saplings and dark oak saplings and when you use bonemeal on a sapling it grows extremely small like a bush

**Comment by dterweij** [comment]
Yes, the trees are low indeed. I always place a few grassblocks on top and then I let grew a tree. Then I replace the grassblocks with the wood.

**Comment by thebigsmileXD** [comment]
I am about to create generators for big trees and other structures (simple village houses, temples etc)

**Comment by rWardy** [comment]
@Skyladd not sure about the bonemeal.  I've used it on a sapling and got a tree of similar size to the ones that normally generate.  The Big trees are not implemented yet as @thebigsmileXD details above.
