### ISSUE TITLE
Compass acts as an Ender Pearl 0.14

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#806]
When holding a compass you can use it as an ender pearl, you teleport!

**Comment by Thorodonson** [comment]
i dont

**Comment by InfornoFire** [comment]
Lol, this was so old, I wonder why they kept it for so many years

**Comment by DesPlaysMC** [comment]
do yu have toybox or compasstp? they do have this function

**Comment by DesPlaysMC** [comment]
toybox has compasstp function hidden in it

**Comment by SalmonGER** [comment]
@DesPlaysMC I have this issue, too. Even on a Server without any plugins.

**Comment by PocketKiller** [comment]
this issue is true, just hold a compass and touch the screen you get TELEPORTED.

**Comment by XxDXM-hippiexX** [comment]
#WorldEditArt

**Comment by Creeperface01** [comment]
i think it is fixed
