### ISSUE TITLE
Development stopping at 0.14 upgrade(temporarily of course!)

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#807]
@ImagicalMine/developers - I'd like to stop IM development after 0.14 is released - because IM is upgrading to PHP7. @HmHmmHm is leading the upgrade - @HmHmmHm has done most of the work already really. It's only temporarily - and it'll only take a few days... What are your thoughts on this?

**Comment by matcracker** [comment]
Yes, a very very good work @HmHmmHm! We can start a 0.14-php7 branch? What do you think about?

**Comment by keithkfng** [comment]
@matcracker I think we need to do more performance improvement like faster loading and less lag... What ideas do you have to make this achievable?

**Comment by thebigsmileXD** [comment]
.. is it unconfirmed or invalid. Both is impossible

**Comment by keithkfng** [comment]
@ImagicalMine/developers gotta clean up some code. Can somebody remove all the ASCII? Too annoying LOL

**Comment by PocketKiller** [comment]
@keithkfng I'll try to remove (Files ASCII)

**Comment by keithkfng** [comment]
@PocketKiller thanks for that!

**Comment by PocketKiller** [comment]
I failed. I Dunno why are you trolling me Notepad++

**Comment by applqpak** [comment]
Lmao
