### ISSUE TITLE
Pocketmine 1.8 running PHP7?

### ISSUE THREAD

**Issue by GODLIKE5** [ImagicalMine/ImagicalMine#808]
No Please don't. We have many android users who use ImagicalMine like me and if PHP 7 comes none of androids will be able to run it because android runs PHP 5.6 I think but please no

**Comment by lolcraftboy14** [comment]
A run it on android

**Comment by keithkfng** [comment]
ImagicalMine doesn't provide mainstream support for Android. Android was never meant to run servers anyway.

**Comment by robske110** [comment]
@keithkfng Yes, i agree. Buy a small rasperyPI or something like that mess around with linux and finished

**Comment by keithkfng** [comment]
I'll tell you what though. Why don't you have a little scroll here and see what you can dig out of it - https://bintray.com/package/files/pocketmine/PocketMine/Unix-PHP-Binaries

**Comment by GODLIKE5** [comment]
No.... Try out the new ImagicalMine Android app... lets you run PHP 7 on an android
Sources: ImagicalMine

**Comment by YoutubeESG12** [comment]
@GODLIKE5 what is it called? And send me link?

**Comment by MasterWolf** [comment]
@GODLIKE5 wait i will give u link.

**Comment by MasterWolf** [comment]
@GODLIKE5 https://github.com/ImagicalMine/IM-Android
