### ISSUE TITLE
PHP7 upgrade information

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/ImagicalMine#811]
Hi all,
As you know, ImagicalMine is upgrading to PHP7, which means you'll have to upgrade your PHP binaries and builds. This post will mainly talk about upgrading your binaries.

Windows:
Select the ZIP PACKAGE from the link below - make sure it's PHP 7.0.2. Maybe thread safe would be the safer option. Then extract the files into the folder where you installed ImagicalMine. (http://windows.php.net/download)

Linux & Android:
Select your package from the link below - it'll be at the bottom. Then extract the files into the folder where you installed ImagicalMine. (https://bintray.com/package/files/pocketmine/PocketMine/Unix-PHP-Binaries)

Mac OS X:
This is a third party download system - you may want to compile binaries yourself if you feel uncomfortable and insecure with this method.
Open the terminal use "cd <directory>" to go to the folder where you installed ImagicalMine and type this in:
curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0
It'll install the binary - you may need to follow instructions.

We'll be releasing a script that automatically compiles binaries and downloads IM without you doing it soon. Look out!

**Comment by PocketKiller** [comment]
@keithkfng duh, maybe I'll just replace the /bin/php with the PHP7 one, because you can't do that without extensions ;)

**Comment by erkam2002** [comment]
not work : /usr/bin/php/php.exe: error while loading shared libraries: VCRUNTIME140.dll: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127

pls help me

**Comment by rWardy** [comment]
@keithkfng the PHP binaries for Linux don't have the correct version of pthreads? Get this when loading:
```
Failed loading /var/lib/jenkins/jobs/PHP-PocketMine-Linux/workspace/compile/linux/64bit/bin/php7/lib/php/extensions/no-debug-zts-20141001/opcache.so:  /var/lib/jenkins/jobs/PHP-PocketMine-Linux/workspace/compile/linux/64bit/bin/php7/lib/php/extensions/no-debug-zts-20141001/opcache.so: cannot open shared object file: No such file or directory
[17:37:03] critical> pthreads >= 3.1.5 is required, while you have 3.0.7.
[17:37:03] critical> Please use the installer provided on the homepage, or recompile PHP again.
```

**Comment by MasterWolf** [comment]
Plz help i don't know where to put this files... Where is ImagicalMine instalation folder?? Help... :(

**Comment by MasterWolf** [comment]
Im using android

**Comment by MasterWolf** [comment]
And i don't know where is folder /bin/php
Can you plz help me how to find it?

**Comment by HmHmmHm** [comment]
android(specially droid pocketmine) can't use php7,
because droid pocketmine core file has still using php5.
mobile support is need more work about arm compile & repacking

**Comment by MasterWolf** [comment]
No i dont use droid pocket mine. Im  using PocketMine-MP for android.

**Comment by HmHmmHm** [comment]
both same bro..

**Comment by dterweij** [comment]
Is updating of DevTools in progress? 

[00:08:45] system> This server is running ImagicalMine version 1.0dev "ImagicalMine" (API 2.0.0)
[00:08:45] system> ImagicalMine is distributed under the LGPL License
[00:08:46] error> Could not load plugin 'DevTools': Incompatible API version
[00:08:46] system> Preparing level "world"
[00:08:46] system> Starting GS4 status listener
[00:08:46] system> Setting query port to 19133
[00:08:46] system> Query running on 0.0.0.0:19133
[00:08:46] system> Default game type: Survival Mode
[00:08:46] system> Done (1.221s)! For help, type "help" or "?"
[00:08:50] system> This server is running ImagicalMine 1.0dev [ImagicalMine] implementing API version 2.0.0 for Minecraft: PE v0.13.1 alpha (protocol version 38)
[00:08:55] system> Unknown command. Try /help for a list of commands
[00:09:00] system> [CONSOLE: Stopping the server]
[00:09:00] system> Unloading level "world"
[00:09:00] emergency> RakLib crashed!
[00:09:00] system> Stopping other threads

**Comment by kiyoshi-kurosaki** [comment]
You can do it yourself :D

**Comment by kiyoshi-kurosaki** [comment]
But i can you give it :D here is it but just rename from zip to phar :D 
[DevTools_v1.10.0.zip](https://github.com/ImagicalMine/ImagicalMine/files/111570/DevTools_v1.10.0.zip)

**Comment by dterweij** [comment]
Thanks. I have to say, php7 works fine. Seems a lot faster indeed. (I started it directly from src to test).

To stay ontopic, CentOS 6/7  Use PHP7 from REMI repository (also the devel package) , install weakref and pthreads extentions (php-pecl-xxxx packages). Start Imagicalmine with zts-php. I created a start7.sh with php path changes (/usr/bin/zts-php)

No more the need of a seperate PHP installation for IM/PM if people dont want to have that. Tho use the pre-compiled packages from ImagicalMine when your hoster/server does not have php7  installed or having missing extentions.

I am happy when IM is fully merged (master) or have a PHP5 and PHP7 branch. Tho i think its best to merge/push the master changes to PHP7 for some time to test if this is realy stable to use.

One bug found: When in console doing stop to exit the server:
[00:23:02] system> xxxx joined the game
op xxxx
> [00:23:42] system> [CONSOLE: Opped xxxx]
[00:23:55] system> [xxxx: Set own game mode to Creative Mode]
_stop_
> [00:40:10] system> [CONSOLE: Stopping the server]
[00:40:10] system> xxxx left the game
[00:40:10] system> xxxx [/192.168.0.204:**19132**] logged out due to Server Closed
[00:40:10] system> Unloading level "world"
[00:40:11] **emergency> RakLib crashed!**
[00:40:11] system> Stopping other threads

I am running the server on:
[00:40:41] system> Setting query port to **19133**
[00:40:41] system> Query running on 0.0.0.0:**19133**

Some PORT problem so indeed RakLin is crashing on that.

**Comment by dterweij** [comment]
@kiyoshi-kurosaki That DevTools has the same API error. Tho i dont mind it yet, i start it from source until a DevTools for API 2.0.0 is made.

**Comment by kiyoshi-kurosaki** [comment]
Just edit DevTools :) in plugin.yml API to 1.14.1 xD for me it works

**Comment by dterweij** [comment]
Okay. I give it a shot again. Dont understand yet how to unpack and use a unpacked phar plugin yet. I tried once for a few days but gave up :)

**Comment by kiyoshi-kurosaki** [comment]
-> here you can convert it to zip and back http://pmt.mcpe.me/

**Comment by MasterWolf** [comment]
So i cant use ImagicalMine on android anymore?

**Comment by lolcraftboy14** [comment]
Fuck ImagicalMine

**Comment by lolcraftboy14** [comment]
Booooooo

**Comment by lolcraftboy14** [comment]
Fuck it y go to clearsky

**Comment by robske110** [comment]
Hey

**Comment by lolcraftboy14** [comment]
What hay

**Comment by lolcraftboy14** [comment]
Noting php7

**Comment by robske110** [comment]
Could anyone delete those messages? @ImagicalCorporation

**Comment by lolcraftboy14** [comment]
Ban me  than

**Comment by lolcraftboy14** [comment]
Noting fore android  this is a bad  day

**Comment by lolcraftboy14** [comment]
👏👏👏😠😠😠 Just do it

**Comment by lolcraftboy14** [comment]
👏👏👏😠😠😠 Just do it

**Comment by robske110** [comment]
Hey, Android isn't meant to be a server hotter!

**Comment by rWardy** [comment]
@keithkfng Did you see my note above about PHP distro for Linux not including the correct version of pthreads,  Any idea on where I can get one, or how I put one together?

**Comment by keithkfng** [comment]
@rWardy pecl install channel://pecl.php.net/pthreads-3.1.5

**Comment by Driesboy** [comment]
make a new repository for php scripts php7

**Comment by rWardy** [comment]
@keithkfng think i've finally got somewhere.  Have built a version of php7 using the following configure line:

```
./configure --prefix=/home/Richard/php7 --with-config-file-path=/home/Richard/php7 --enable-maintainer-zts --with-zlib --enable-sockets --with-curl --with-openssl --enable-bcmath --enable-pthreads --with-yaml
```

There's probably more to it, so need to get all the steps, but it seems to launch IM and login if I point the PHP 7 version at the php bin file that has been built!

**Comment by mwvent** [comment]
Got PHP7 working on linux too, with these steps https://gist.github.com/mwvent/92fcf4a48cd34809c461

Starts up IM PHP7 build fine (OK until it stops with a Tile.php error but its a dev branch after all!), hopefully Ill actually have some time to contribute over the weekend - very exited for PHP7 compatibility :-)

**Comment by keithkfng** [comment]
I have been waiting for 2 months for you @mwvent LOL

**Comment by mwvent** [comment]
Yeah busy few months lol sorry guys - scratch that gist I just posted. I have bumped a few API versions on my plugins and mysqli support has not been compiled in

**Comment by keithkfng** [comment]
@mwvent add --with-mysql and --with-mysqli

**Comment by mwvent** [comment]
Got here eventually - Turns out extension=mysqlnd.so and extension=mysqli.so had to be explicitly added to the php.ini, maybe because I am trying to make a static build that I can push to other machines. Everything seems to work fine now & I have updated the gist with the procedure I used

**Comment by rWardy** [comment]
Are we not trying to get it so we don't need the extension= lines in PHP.ini?  The build I have done doesn't currently use a PHP.ini (need to get the php5 one and use), and it still loads.

This is the configure line I have currently used
```
./configure --prefix=/home/Richard/php7 --with-config-file-path=/home/Richard/php7 --enable-maintainer-zts --with-zlib --enable-sockets --with-curl --with-openssl --enable-bcmath --enable-pthreads --with-yaml --with-mysqli
```

I needed to statically include the yaml-beta and pthreads pecl extensions as per http://php.net/manual/en/install.pecl.static.php 

The only problem is my environment is a bit all over the place at the moment so not sure what pre-installed stuff is affecting things. I going to try a blank system with and write some steps to see if I can get a TAR file to use similar to existing PHP 5 version.

**Comment by Delimer** [comment]
./bin/php7/bin/php: error while loading shared libraries:  .../lib/libz.so.1: file too short
