### ISSUE TITLE
Does not works anvil pc maps. 

### ISSUE THREAD

**Issue by darkspive** [ImagicalMine/ImagicalMine#814]
I tried to install anvil maps.Does not works.  Idk.... I cant install. How to install it?

**Comment by intagaming** [comment]
It should be Region folder with *.mca or *.mcr files in it.
You can use some converter like:
https://github.com/ljyloo/LevelDb2Avnil

**Comment by darkspive** [comment]
It worked in 0.13 php5 pocketmine... It is unusual

**Comment by darkspive** [comment]
But if my map is mcregion?
Can i covert?

**Comment by Skyladd** [comment]
I load pc 1.9 maps all the time..you simply just drag and drop the pc world into the worlds folder in imagicalmine

**Comment by darkspive** [comment]
:(
Doesnt works.
I tried it

**Comment by PocketKiller** [comment]
https://github.com/ImagicalCorp/MConverterUltimate
