### ISSUE TITLE
Weird random errors 0.14 Linux

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#815]
Warning: file_put_contents(/home/Desktop/ImagicalMine/server.log): failed to open stream: Too many open files in system in phar:///home/Desktop/ImagicalMine/ImagicalMine.phar/src/pocketmine/utils/MainLogger.php on line 274

**Comment by dterweij** [comment]
Could be your system itself. Too low hard/soft limits. I always increase them right after installation of Linux OS or when using a VM.

See ulimit command or make them system wide with sysctl.

**Comment by PocketKiller** [comment]
Your fault, I also got this, I closed unused apps running :P
