### ISSUE TITLE
New Server start text.

### ISSUE THREAD

**Issue by thedeibo** [ImagicalMine/ImagicalMine#817]
![image](https://cloud.githubusercontent.com/assets/10010369/12721538/480ee890-c8f8-11e5-97a4-030e8e019561.png)

SUre, the ideas is good, but it isnt good for every person's needs. 4 years ago, i increased the font of the start.cmd.... ( so I could actually see the server ) Since then, when ImagicalMine came along, i could still see the ASCII art text. But Now... It looks seperated and weird ( as picture above proves.

Just pointing out that even people with poor eyesight may want to use ImagicalMine too :p 
Many Thanks,
TheDeibo

**Comment by PocketKiller** [comment]
so that's your fault, try to reset the start.cmd properties (settings)

**Comment by thedeibo** [comment]
I dont think you are getting the situation. 

> but it isnt good for every person's needs.


Basically, if i revert it back... I will not be able to see the font at all... and will wither go back t earlier versions, or use PM. (Its nice to always think about accessibility when making websites / software / applications, 
:3 
Just put yourself in the shoes of a visually impaired person, then you'll realise. :) 
(Not meaning any offence at all )

**Comment by InfornoFire** [comment]
Sounds like a good idea to increase font as an option.

**Comment by dterweij** [comment]
Lines should not exceed 39 chars. I think the IM logo lines are longer.

**Comment by thedeibo** [comment]
yes. i agree, because i just changed the size down (temporary) and it still is broken

**Comment by KillerXtream** [comment]
I will fix all design bugs. Please, give me a few days and it will be fixed aroundly 2 days.

University is hard...

**Comment by applqpak** [comment]
@KillerXTream lol

**Comment by thedeibo** [comment]
(aimed for when your free) could you try decreace the ammount of characters?
or
a more better ascii art (more unuique art, that is hard to copy)

**Comment by PocketKiller** [comment]
@removevase this is not a thread and you can bump anywhere.
