### ISSUE TITLE
Server erros server have started but multicarft syas offline

### ISSUE THREAD

**Issue by ZenaGamingsky** [ImagicalMine/ImagicalMine#818]
Look at this agin VG said it your phar fault so fix this
![djdmd](https://cloud.githubusercontent.com/assets/11705460/12727359/a81b5054-c914-11e5-9b09-6aa9bbf8218f.png)

**Comment by InfornoFire** [comment]
It is against rules to KEEP ON REPOSTING.

**Comment by InfornoFire** [comment]
Plus, you grammar for the title is very professional and understandable. (not)
