### ISSUE TITLE
strange startup message and serv wont start

### ISSUE THREAD

**Issue by sscoolqaz** [ImagicalMine/ImagicalMine#820]
hmm after redownloading imagicalmine + pocketmine  to my new computer i get this strange message:

Failed to fork child process: Resource temporarily unavailable.
DLL rebasing may be required. See 'rebaseall --help'.

**Comment by robske110** [comment]
Oh, I know that error. But I don't know how to fix it...

**Comment by robske110** [comment]
Oh, but are you using this file: https://github.com/PocketMine/PocketMine-MP/blob/master/start.cmd ?

**Comment by PocketKiller** [comment]
@PeratX Said :  
Simple to solve.Just follow my steps. This is a bug of PHP :
- stop ALL PHP process in your computer.
- Delete temp file generated by PHP. Usually in C:/Users/Username/AppData/Local/Temp
- Restart your program
