### ISSUE TITLE
About harvester Importance it can be  destroy the server

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#824]
Harvesters can be in any place, 
and once placed will not be able to destroy, 
 if you click falls out of the harvesters have been placed a harvesters ite
ms.
(Chinese mean: 
矿车可以放置在任何地方，
而且一旦放置就无法破坏，
如果你点击矿车，矿车就会掉出一个矿车物品)

**Comment by ibookcc** [comment]
on #582

**Comment by PocketKiller** [comment]
what do you mean

**Comment by PocketKiller** [comment]
do you mean TNT?

**Comment by PocketKiller** [comment]
he means when you place the Tub (the thing where you dye your armor) you cannot break it
and If you click on the tub, the tub will fall out of a tub article)

**Comment by ibookcc** [comment]
tub = harvester is it？

**Comment by ibookcc** [comment]
sorry, my teacher have not teach m
e 'word'.

**Comment by zzm317** [comment]
@pocketkiller
he means
the minecart can't remove after you place it
i have already founded this bug but forget to report it LOL

**Comment by PocketKiller** [comment]
@zzm317 :0 XD

**Comment by zzm317** [comment]
@pocketkiller 
i don't where changed after i update the minecraft file
so i can't deal with this bug..

**Comment by zzm317** [comment]
@pocketkiller
i don't know (i forget 'know'..and lazy to change into desktop version to edit my comment LOL

**Comment by thebigsmileXD** [comment]
Harvester.. Hoppers they are called, for future requests/edits

**Comment by HimbeersaftLP** [comment]
@thebigsmileXD I just wondered about... xD

**Comment by rWardy** [comment]
I think hopper places and breaks now.  Doesn't work yet

**Comment by keithkfng** [comment]
@ImagicalMine/developers somebody wanna work on this? Issue closed for now, reopen if needed.
