### ISSUE TITLE
You can use Fly hacks because of boats.

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#825]
Sometime if player get in boot,
the player will be fly with boot.
My server's a player tell me. 
(Chinese mean: 
在某些时候玩家坐在船上
船会带着玩家飞起来
这是一个玩家告诉我的)

**Comment by ibookcc** [comment]
on #582

**Comment by ibookcc** [comment]
I am testing When will result in such cases.
(Chinese mean: 
我正在测试在什么特定情况下导致的船那样)

**Comment by PocketKiller** [comment]
When you get on a boat you get kicked with flying not enabled on this server message.

**Comment by zzm317** [comment]
@pocketkiller 
this bug is because that server just set the position of the boot report from the client and didn't calc other things...

**Comment by PocketKiller** [comment]
@zzm317 I know.. and that's what I am wondering about.

**Comment by zzm317** [comment]
@pocketkiller
...that needs a excellent system to calc gravity

**Comment by thebigsmileXD** [comment]
Actually, boats are linked to players so they should move EXACTLY like the player and raklib should handle them the same. But it doesn't

**Comment by thebigsmileXD** [comment]
And i already said that in my commit where i edited boats. "Players will be able to cheat movement via Boats"

**Comment by ibookcc** [comment]
@zzm317 @MagicDroidX @PeratX
我来这里是因为这里的人都很公平。
这是真正的交流，
从凤鸟的那封邮件，
第二天大家开始漫骂我，
你也许不知道那天我生日
我看着消息，我哭了
你不知道这对一个14岁的孩子意味着什么
我于是远离ZXDA来到了LTSP
我渴望公平，那儿的时光很太平
直到，
你来的IC，开始骂我"英语说的那么垃圾就不要来装逼"并且带上截图和其他人议论我！于是我开始于你争论
结果你不论是非把我从群里踢出。
我在后来的自我检讨里
一直以为那是我的错，
所以后来我的提出问题都是很谨慎
用两种语言翻译，
热心的PocketmineKiller总会帮我
解释含义
你也许不会懂得在大家都那样对你的时候
有人帮助你，那你会如何感受，
所以，我很感谢所有帮助我的人
是他们使我不变得像你一样铁石心肠。
有一句话我一直想对你说
[我不是玻璃心，我只是还没有遗忘]我来这里是因为这里的人都很公平？
这是真正的交流，
从凤鸟的那封邮件，
第二天大家开始漫骂我，
你也许不知道那天我生日
我看着消息，我哭了
你不知道这对一个14岁的孩子意味着什么
我于是远离ZXDA来到了LTSP
我渴望公平，那儿的时光很太平
直到，
你来的IC，开始骂我"英语说的那么垃圾就不要来装逼"并且带上截图和其他人议论我！于是我开始于你争论
结果你不论是非把我从群里踢出。
我在后来的自我检讨里
一直以为那是我的错，
所以后来我的提出问题都是很谨慎
用两种语言翻译，
热心的PocketmineKiller总会帮我
解释含义
你也许不会懂得在大家都那样对你的时候
有人帮助你，那你会如何感受，
所以，我很感谢所有帮助我的人
是他们使我不变得像你一样铁石心肠。
有一句话我一直想对你说
[我不是玻璃心，我只是还没有遗忘]

**Comment by ibookcc** [comment]
@ zzm317 @ MagicDroidX @ PeratX
I'm here because the people here are very fair.
This is the real communication,
The email from phoenix bird,
The next day everyone began to invective me,
You may not know my birthday that day
I look at news, I cried
You don't know what this means to a 14 years old children
I so far away from ZXDA came to the LTSP
I desire for fair and it is very peaceful time
Until,
IC, you start to scold me "speak English so rubbish, don't pack to force" and take a screenshot and others talk about me!!!!!!! So I started to your argument
Results no matter is you take me out from the group.
I in later review
Always thought it was my fault.
So then I ask questions are very cautious
With two kinds of language translation,
Enthusiastic PocketmineKiller always help me
Explain the meaning of
You may not know when to you all
Someone to help you, then how would you feel,
So, I am very grateful to all the people who helped me
Are they make me to like you a heart of stone.
There's a phrase I've always wanted to say to you
[I'm not glass heart, I just haven't forgotten] I came here because the people here are very fair?
This is the real communication,
The email from phoenix bird,
The next day everyone began to invective me,
You may not know my birthday that day
I look at news, I cried
You don't know what this means to a 14 years old children
I so far away from ZXDA came to the LTSP
I desire for fair and it is very peaceful time
Until,
IC, you start to scold me "speak English so rubbish, don't pack to force" and take a screenshot and others talk about me!!!!!!! So I started to your argument
Results no matter is you take me out from the group.
I in later review
Always thought it was my fault.
So then I ask questions are very cautious
With two kinds of language translation,
Enthusiastic PocketmineKiller always help me
Explain the meaning of
You may not know when to you all
Someone to help you, then how would you feel,
So, I am very grateful to all the people who helped me
Are they make me to like you a heart of stone.
There's a phrase I've always wanted to say to you
[I'm not glass heart, I just haven't forgotten]

**Comment by thebigsmileXD** [comment]
Finally start to write in english. Thats one reason i left IM. You talk EVERY language and never translate

**Comment by Skull3x** [comment]
I left a boat in c-mode and flew away and it hovered after me for some
reason

**Comment by Skull3x** [comment]
In the build 3 version

**Comment by PocketKiller** [comment]
what do you mean by "hovered"?

**Comment by thebigsmileXD** [comment]
It follows him.

**Comment by Skull3x** [comment]
Yap
