### ISSUE TITLE
Some small bug

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#826]
1. Empty water bottles can't hold water.
2. When you tp someone potion effect still display,but it didn't work.
(Chinese mean: 
1. 空瓶子不能装水。
3. 使用喷溅药水时没有瓶子摔破的声音。
4. 在你传送某人之后，药水效果依然会显示，但是药水效果功能就没有了，比如隐身，虽然显示隐身图标，但是传送之后你其实没有隐身，也是某个玩家告诉我的(๑¯ω¯๑))

**Comment by ibookcc** [comment]
on #582

**Comment by ibookcc** [comment]
卧槽 数字标错了

**Comment by PocketKiller** [comment]
yes of course water can be placed on Nether.

**Comment by ibookcc** [comment]
饿，怎么用英语说

**Comment by ibookcc** [comment]
I want to accumulate some problems besides

**Comment by ibookcc** [comment]
if i find other i will report(๑¯ω¯๑)
Thanks for you reading

**Comment by MagicDroidX** [comment]
用英文说大概就是曾生强你的长辈体积迅速膨胀超过爆炸极限成为小分子的物理反应过程？

**Comment by robske110** [comment]
Too much chinese here

**Comment by MagicDroidX** [comment]
Do you have a prejudice against Chinese? @robske110

**Comment by ibookcc** [comment]
Can you is under the respect of others, don't so foul-mouthed,@MagicDroid 不要玷污你的祖国,在国内你可以乱骂人我不管，麻烦你在国外不要丢我们国家的脸

**Comment by ibookcc** [comment]
@MagicDroid 我只是做我该做的事情，请你尊重一下我

**Comment by ibookcc** [comment]
@robske Don't worry he didn't mean that he is not have a good mood today.●ｖ●

**Comment by MagicDroidX** [comment]
自嘲完美。真知道你自己丢脸呢，HAHA。为什么我要尊重一个不尊重他人的人。还有我好心教你说英语你这样对我真的好吗？

**Comment by ibookcc** [comment]
Please speak English @MagicDroidX I don't want to fight with you (it's too stupid)

**Comment by ibookcc** [comment]
i have a question------ Now is 1am.why you don't feel sleepy?눈_눈@MagicDroidX

**Comment by robske110** [comment]
@MagicDroidX No, I don't hate it. I just can't understand it.

**Comment by ibookcc** [comment]
Understand what？@robske110 May Magic take a photos to show other........they happy to do it.
in China.

**Comment by MagicDroidX** [comment]
@ibookcc Of course I can, but it is you who cannot read and write English without a translator. It is you who want a fight when I am trying to teach you English using Chinese.

**Comment by robske110** [comment]
By "understand" i didn't try to say i don't like it. I did try to say I can't speak it (And as an result of that I don't know what 

> 自嘲完美。真知道你自己丢脸呢，HAHA。为什么我要尊重一个不尊重他人的人。还有我好心教你说英语你这样对我真的好吗？

 means!

**Comment by keithkfng** [comment]
@robske100 Well guess what? I don't have a problem against you speaking German here, so you won't have a problem with @MagicDroidX and @ibookcc speaking Chinese -_-

**Comment by robske110** [comment]
I don't have an problem with that!
And I don't speak german here.

**Comment by ibookcc** [comment]
@MagicDroidX i can understand chinese texts,ok?What are you saying, we all know.

**Comment by zzm317** [comment]
@ibookcc
your fuc*ing idolt
if you continue doing this i will let other people ban you

**Comment by ibookcc** [comment]
@zzm317 If I do something wrong, you can blame me, or even ban me, but now I just do what I should do,

**Comment by PeratX** [comment]
@Zzm317 idiot, not idolt (MDX)
And please remain clam : )

**Comment by zzm317** [comment]
@ibookcc
we are not your mother
we don't have any reason to blame you every time
and open fuc*ing issues which can't even be understanded is not what you should do

**Comment by PeratX** [comment]
@zzm317 just clam down

**Comment by zzm317** [comment]
@peratx
只是为了避开脏话
这智障小学生已经不是第一次开这种脑残issue了

**Comment by zzm317** [comment]
@peratx
看见每次github发来的邮件
这脑残小学生的issue总是让我火大
根本就看不懂他想表达什么

**Comment by zzm317** [comment]
@peratx
都特么刷邮件了

**Comment by ibookcc** [comment]
Why no matter where you have to do this to me
 Is I was a child, or are you?

**Comment by PeratX** [comment]
@zzm317
同感+1
虽然我也看不懂。
最好还是不要骂他。

**Comment by keithkfng** [comment]
I don't understand Chinse, but I understand that this is an argument -_-

**Comment by zzm317** [comment]
@ibookcc
here is not in china
no one will blame you because you are a child
你个傻逼小学生要卖小给我滚回中国去别在外面丢脸
你特么以为你小你就是天了？
你以为网络上还有未成年人保护法这种没卵用的东西？

**Comment by zzm317** [comment]
@peratx
这小学生找骂
在LTSP就在装逼已经被我t了
还跑到这里来瞎搞

**Comment by zzm317** [comment]
@keithkfng
...not argument
that's education

**Comment by PeratX** [comment]
@zzm317 好了好了，骂也骂完了 息怒息怒-_-别和他一般见识就行了。

**Comment by zzm317** [comment]
@peratx
主要是我ban不了人
不过ban了估计他也会开小号
