### ISSUE TITLE
When Noteblock is on a glowstone and you touch the Noteblock,the server load will go to 100%

### ISSUE THREAD

**Issue by zzm317** [ImagicalMine/ImagicalMine#829]
When Noteblock is on a glowstone and you touch the Noteblock,the server load will go to 100%
i don't know why=-=

**Comment by robske110** [comment]
For me the server load is always on 100% because we don't have two threads...

**Comment by zzm317** [comment]
@robske110 so sad

**Comment by thebigsmileXD** [comment]
I know why. I won't fix it. Because your redstone is not fully done.

**Comment by Driesboy** [comment]
glowstone is not redstone

**Comment by robske110** [comment]
@thebigsmileXD Is the redstone in ClearSky better?

**Comment by Driesboy** [comment]
yes

**Comment by thebigsmileXD** [comment]
its improved.

**Comment by ecoron** [comment]
I take a look in it

**Comment by ecoron** [comment]
seems also it crashes by outofmemory without crashdump. saw this after activating Noteblocks.

**Comment by robske110** [comment]
Just confirmed it

**Comment by ecoron** [comment]
i think i'm close on it, just testing some fixes, if this works i will push...
