### ISSUE TITLE
add PluginAPI::Experience (setExperience)

### ISSUE THREAD

**Issue by robske110** [ImagicalMine/ImagicalMine#830]
Let's begin with code

```php
$player->setExpLevel(1);
```
Will result into an full level bar, but no ^level^ 1 (ISSUE)

```php
$player->setExperience(0);
$player->setExpLevel(1);
```
Will result in an empty level bar, and an displayed 1 (WORKS)

```php
$player->setExpLevel(0); //NotNeeded
$player->setExperience(2);
```
Will result into NOTHING (ISSUE)

```php
$player->setExpLevel(0); //NotNeeded
$player->setExperience(100);
```
Will result into an 3/4 filled bar and level 28 (WORKS)

**Comment by thebigsmileXD** [comment]
_The rename set to Add.

**Comment by robske110** [comment]
What? Then rename set to add ???

**Comment by thebigsmileXD** [comment]
> then rename set to Add.
> then

but nvm

**Comment by ecoron** [comment]
`$player->addExperience($exp);` should do the trick to add Experience,
setExperience set's a new experience value. so i think it isn't an issue

**Comment by robske110** [comment]
I however won't be updating this anymore, moved to CS and it works there!
[This issue persists test it yourself]
[setExpLevel(); does not work]
