### ISSUE TITLE
Support MCPE v0.13.2

### ISSUE THREAD

**Issue by AdversariusPE** [ImagicalMine/ImagicalMine#831]
We Need a Version of Imagical Mine that supports The v0.13.2 of MCPE. :)

**Comment by robske110** [comment]
![image](https://cloud.githubusercontent.com/assets/16020100/12817287/9bc8d580-cb51-11e5-8598-2a20e598aeff.png)
@ImagicalCorp Confirmed+as this update does not do much we just need to update the protocol and the version!

**Comment by robske110** [comment]
https://github.com/PocketMine/PocketMine-MP/pull/3924

**Comment by kiyoshi-kurosaki** [comment]
Just updated it :D 825d17f24454b9cf213ae643e82633886d7f1a9d and 037f25e90ab626e4ea30bac68981b8802ae11882

**Comment by thebigsmileXD** [comment]
@robske110 Jailbreak, right?

**Comment by robske110** [comment]
Why do you think i have jailbreak? (The screenshot was not from an jailbroken iPhone at the moment there are no good jailbreaks for ios9.2 (There are some,but i had some bad experience with jailbreaking, it failed me 5times)

**Comment by thebigsmileXD** [comment]
@robske110 Oh, is the yellow battery bar normal in ios9? i am still on 8 xD and i like it.

**Comment by robske110** [comment]
It is when you're in power-saving-mode (automatically kicks in at 20%) and i have it enabled always, because yknow the battery strenthg of iPhones...
Why are you still on 8? What holds you from upgrading to 9.2.1?

**Comment by thebigsmileXD** [comment]
The missing call list in the app switcher and the app swicher at all. I hate that the apps overlap. There are no tweaks to change this back to the iOS 8 style. and 15 or more threads havent updated yet..

**Comment by HimbeersaftLP** [comment]
That's why I have WP.... xD

**Comment by thebigsmileXD** [comment]
WP, the new Blackberry

**Comment by HimbeersaftLP** [comment]
WP = Windows Phone

**Comment by robske110** [comment]
Windows phone has almost no apps though

**Comment by HimbeersaftLP** [comment]
That's the disadvantage

**Comment by thebigsmileXD** [comment]
> WP, the new Blackberry
> WP = Windows Phone

-.-" i mean its the same kind of *

**Comment by HimbeersaftLP** [comment]
:O P.S.: Contiributing Guidelines: Issue tracker is not a chatroom
