### ISSUE TITLE
Armor does not reduce damage

### ISSUE THREAD

**Issue by UltimateMcraft** [ImagicalMine/ImagicalMine#832]
This is issue #682 **again** yes, this may be a duplicated **but** _read the issue_, #682 was closed because it wasn't read **properly**, I bring you the issue again, please read it _**carefully**_

1.  Armour has no effect, which means **it is pointless**
2.  This has nothing in common with #654 which says **Armor dont break** mine says _it has no effect_
3. If you insist on locking this, let's have a conversation first about this.

On to the issue now:

Steps to reproduce:

- Get someone to kill you
- Put armour on
- Get killed again

Any difference? _**No**_ so the armour **doesn't work**

> Conclusion: Armour is pointless due to this.

**Comment by UltimateMcraft** [comment]
I put armo**u**r because I am from England :P

**Comment by thebigsmileXD** [comment]
But you didn't in your text

**Comment by UltimateMcraft** [comment]
with --  which says Armor -- I did that because that's what the title of that issue said

**Comment by ecoron** [comment]
seems the order of executed DamageEvents needs to be changed. Looks like related to #739

**Comment by Creeperface01** [comment]
structure of calculating damage with armor must be changed

**Comment by Creeperface01** [comment]
is it fixed now?

**Comment by keithkfng** [comment]
@dterweij said there was an error...

**Comment by Creeperface01** [comment]
i think, it's fixed

**Comment by UltimateMcraft** [comment]
It might not be fixed...

**Comment by Creeperface01** [comment]
I tested it and it worked
