### ISSUE TITLE
MCPE release 0.13.2 is withdrawn.

### ISSUE THREAD

**Issue by dterweij** [ImagicalMine/ImagicalMine#835]
Majong removed 0.13.2 release for android (big bug). Tho windows 10 beta is at 0.13.2.
IM is now at 0.13.2 , makes it impossible to play for android clients at 0.13.1

I suggest to revert the 0.13.2 for IM back to 0.13.1 until majong does have a 0.13.2 release for android.

How to downgrade the windows version back to 0.13.1 ?

**Comment by Driesboy** [comment]
idk

**Comment by Driesboy** [comment]
do you have a backup

**Comment by Driesboy** [comment]
i have 0.13.2 for android and it work for me

**Comment by robske110** [comment]
MCPE 0.13.2 was ~1day released in januaray, then fast-removed and now (today) it came back! Have android users who play on 0.13.2! I have ~100different IPs per day and now the OUTDATED Client messages are almost gone

**Comment by robske110** [comment]
AppStore and WindowsStore have the update! (Came out today)
//EDIT Just got an reply from my friend today 0.13.2 got released on android again!

**Comment by astersx** [comment]
Yep :),  and im back to imagicalmine :)!!!!

**Comment by rWardy** [comment]
13.2 is released for android and windows 10 can confirm. Not got an iOS to check against, but by the sounds of it can close this?

**Comment by robske110** [comment]
iOS is out too!

**Comment by Driesboy** [comment]
this update is released for apple,android and windows
