### ISSUE TITLE
Really? :( crash

### ISSUE THREAD

**Issue by astersx** [ImagicalMine/ImagicalMine#836]
ImagicalMine Crash Dump Thu Feb 4 22:57:50 UTC 2016

Error: Call to a member function onPlayerAction() on null
File: /src/pocketmine/Player
Line: 2559
Type: E_ERROR

Code:
[2550] 					break;
[2551] 				}
[2552] 				$this->craftingType = 0;
[2553] 				$target = $this->level->getEntity($packet->target);
[2554] 				$cancelled = false;
[2555] 				if($target instanceof Player and $this->server->getConfigBoolean("pvp", true) === false
[2556] 				){
[2557] 					$cancelled = true;
[2558] 				}
[2559] 				$target->onPlayerAction($this, $packet->action);
[2560] 				// @todo move this to the entity
[2561] 				//if($target instanceof Boat or $target instanceof Minecart){
[2562] 				if($target instanceof Boat) {
[2563] 					if($packet->action === 1){
[2564] 						$this->linkEntity($target);
[2565] 					}elseif($packet->action === 2){
[2566] 						if($this->linkedEntity == $target){
[2567] 							$target->setLinked(0, $this);
[2568] 						}
[2569] 						$target->close();

**Comment by astersx** [comment]
If i kill a mob it crash :(

**Comment by astersx** [comment]
is xp function,  i killed blaze and didnt give xp = server no crash!!!

**Comment by astersx** [comment]
Really -.-' , nobody noticed this huge bug?

**Comment by astersx** [comment]
ImagicalMine still unstable -.-' dam,  were i can get a decent Pocketmine ? :0

**Comment by kiyoshi-kurosaki** [comment]
Why you have problems? Can anyone confirm this problem?

**Comment by astersx** [comment]
Really -.-,  go and kill a mob and see wtf.....  just do it

**Comment by kiyoshi-kurosaki** [comment]
Ehm yeah, is the mobspawn implemented?

**Comment by kiyoshi-kurosaki** [comment]
And is the MobAI implemented?

**Comment by astersx** [comment]
It spam crashed my server,  now i whitelist it.....  i had a mob plugin -.-,  removed,  but mobs was still spawned.
Is not plugin fault so dont try to use this reason "Plugin Fault"

**Comment by astersx** [comment]
If a mob give xp,  it crash

**Comment by astersx** [comment]
I see u contributed on clearsky,  i will try tomorow,  until now i used genisys

**Comment by kiyoshi-kurosaki** [comment]
The AI isn't implemented yet, so don't care about the crash

**Comment by astersx** [comment]
? I had Al plugin!!!!  You dont understand at all!!!!

**Comment by astersx** [comment]
If a player spawn Villager,  then kill it,  server crash -.-'

**Comment by kiyoshi-kurosaki** [comment]
......

**Comment by astersx** [comment]
Nvm,  i will go back to genisys, ....  ,

**Comment by kiyoshi-kurosaki** [comment]
Ok do it but for me no problems ...... no crash

**Comment by MasterWolf** [comment]
I havent got any problems too...

**Comment by rWardy** [comment]
Same here, spawned a Skeleton, killed it.  Gave me XP, but no server crash

**Comment by FienixEC** [comment]
currently experiencing same issue. exact crash report. server crashes every
5 mins.

**Comment by robske110** [comment]
This is an BIG Problem it occurs with boats and mincarts too!!!

**Comment by thebigsmileXD** [comment]
..he is on a historic build. @astersx 1st you are very spammy. 2nd yes, its a bug when spawning in EXPorbs, but i thought thats already have been fixed for ages..

**Comment by astersx** [comment]
wtf....  i just downloaded master and run it from source!!  Im not noob enough to report bugs from old version!!!! And yep im spammy 😝

**Comment by thebigsmileXD** [comment]
But that was fixed once..

**Comment by astersx** [comment]
I use 0.13.2,  how the **** i use old version!!!!
![screenshot_2016-02-05-15-30-19](https://cloud.githubusercontent.com/assets/13157548/12847552/c678f5f0-cc1c-11e5-97da-a1a475d42b89.png)

**Comment by robske110** [comment]
Temp switched almost all my servers to clear sky because of this bug (But sadly on clear sky some of my plugins don't work!)

**Comment by robske110** [comment]
And this issue is due to the minecart implemenatation

**Comment by astersx** [comment]
I use genisys php7,  but.....  noooo....  my mobs plugin (not mine) dont work and many worlds too 😭

**Comment by thebigsmileXD** [comment]
@robske110 can you please create an issue in CS what plugins don't function?

I told @keithkfng that i won't work on IM anymore, so i will not fix this.

**Comment by astersx** [comment]
aaaa...  u no more on im?

**Comment by robske110** [comment]
@thebigsmileXD My own plugin setExpLevel does not exist...

**Comment by rWardy** [comment]
@thebigsmileXD you mention it being to do with EXP orbs, but when I mine and get XP orbs it works, so is it a combination of things?

**Comment by robske110** [comment]
No its caused by minecarts and boats

**Comment by rWardy** [comment]
doing what with Minecarts and Boats

**Comment by ItzQuiet** [comment]
@thebigsmileXD Hab von Salmon herausgefunden das du Deutscher bist und hätte da eine Frage.
Immer wenn ich sterbe dann spawne ich im Hub des Servers kann man das ändern?

**Comment by thebigsmileXD** [comment]
Has that something to do with IM?

**Comment by ItzQuiet** [comment]
@thebigsmileXD  Ich ich dir leider nicht sagen ich benutze nur IM

**Comment by ItzQuiet** [comment]
@thebigsmileXD Kann ich leider nicht beantworten benutze nur IM
