### ISSUE TITLE
Level generates without flowers

### ISSUE THREAD

**Issue by rWardy** [ImagicalMine/ImagicalMine#837]
I'm having a look at the generator and have tried to put in flowers (as a starting point).  Can you have a look at my initial commit to see if I am going down the correct road. It seems to work for the biomes I have added, but want to know if there is a better/correct way of doing it:  I've tried to work with TallGrass as an example, but also needed a way of always having a Flowers populator (as there are defaults when none are specified in the specific Biome)

https://github.com/rWardy/ImagicalMine/commit/8448b9d4c3b31597444b8c5904f1a40c6f6d93a5

Once I've got this right I'll start adding other ground based stuff such as bushes, cacti, sugarcane etc.

Thanks

**Comment by kiyoshi-kurosaki** [comment]
Also another thing, is the trees just generate a radius of ~50 blocks, and the rest of the world no trees :/

**Comment by rWardy** [comment]
@kiyoshi-kurosaki I've not seen that. I have walked for long time in single direction and there are still trees being generated.

**Comment by InfornoFire** [comment]
There was a plugin to fix that, meh only a plugin.

**Comment by InfornoFire** [comment]
MoreTrees, included in the Php7 branch

**Comment by Skyladd** [comment]
Will this generator perform like the PC version? It would be amazing to not have to pre generate a pc world and load it xD
