### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by SavionLegendZzz** [ImagicalMine/ImagicalMine#842]
ok so i am running my server that uses multicraft how do i get it to use "/bin/php7/bin/php" ? or do i ask multicraft?

**Comment by PocketKiller** [comment]
just delete the bin and put the PHP7 files then rename it to bin.

**Comment by SavionLegendZzz** [comment]
but it says it needs php5 stuff then and crashes

**Comment by keithkfng** [comment]
Consider editing your start script to make the PHP binary path to /bin/php7 rather than php5.

**Comment by PocketKiller** [comment]
use the PHP7 Branch
