### ISSUE TITLE
Question- Not an issue

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#847]
Just to confirm, will 0.14 IM stop receiving updates until official release? Or is it being upgraded to PHP 7? I see all these epic bug fixes for 0.13 IM but not for 0.14 xD

**Comment by keithkfng** [comment]
If someone can be bothered to solve the conflicts then they will be merged :P

**Comment by ecoron** [comment]
Didn't checked the conflicts yet, but I can try it

**Comment by keithkfng** [comment]
Thanks @ecoron :)
Can you merge mcpe-0.14 into php7, then master into php7? Thanks.
