### ISSUE TITLE
[ synthesis methods of fluorite ] have a bug

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#849]
Destruction will drop two fluorite fluorite powder, and the synthesis methods of fluorite is a synthesis a fluorite fluorite powder, this led to some players brush fluorite.
{Chinese mean: 破坏萤石会掉落两个萤石粉，而合成萤石的方法是一个萤石粉合成一个萤石，这导致了一些玩家刷萤石}

**Comment by ibookcc** [comment]
on #813 FOR MC 0.13.2

**Comment by thebigsmileXD** [comment]
What the hell is fluorid?

**Comment by ibookcc** [comment]
Yellow.Will be light.In hell. @thebigsmileXD

**Comment by ibookcc** [comment]
I don't know how to speak it

**Comment by keithkfng** [comment]
Don't worry, @PocketKiller is the expert translator around here :)

**Comment by thebigsmileXD** [comment]
Its easy. Glowstone

**Comment by InfornoFire** [comment]
XD

**Comment by ecoron** [comment]
Didn't understand this issue.
Does it mean if a player breaks Glowstone then it drops 2-4 GlowstoneDust? And from the GlowstoneDust the player can craft new Glowstone, which seems to be OK for me?
