### ISSUE TITLE
hunger value fell

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#850]
hunger value fell to a semilattice began to not drop, so the player even if hungry a day without eating won't buckle blood.
{Chinese mean: 饥饿值下降到半格时就开始不下降，所以玩家即使饿着一天不吃东西也不会扣血}

**Comment by ibookcc** [comment]
on #813 FOR MC 0.13.2

**Comment by ibookcc** [comment]
@Pocketkiller OK?

**Comment by PocketKiller** [comment]
hunger stucks at 1 (half hunger)...
