### ISSUE TITLE
Just some off title question . . .

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#851]
I don't know where to ask this ...
You guys using PHPStorm to make the codes right ?
What is the Standard configure for PHPStorm to Developing Pocketmine PHP Code ?
I was imported ImagicalMine into my External Libraries, but the getPluginManager() still shows yellow ?
It said "not found in class" and no class name has been provided.
I think there is something wrong with my Libraries Importing Method ?

http://postimg.org/image/3t7ugwv9t/

**Comment by keithkfng** [comment]
There is no coding style in ImagicalMine :P

**Comment by thebigsmileXD** [comment]
Which is a big problem

**Comment by PocketKiller** [comment]
+ I don't use PHPStorm I use a text editor
