### ISSUE TITLE
[ Golden apple ]bug and help

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#852]
Two golden apples look the same, and ate two apples for the effect is not the same with the original.
The golden apples wiki:http://minecraft.gamepedia.com/Golden_Apple effect
{Chinese mean: 两种金苹果的样子相同，而且吃两种苹果获得的效果与原版不相同。
金苹果效果wiki：http://minecraft.gamepedia.com/Golden_Apple}

**Comment by thebigsmileXD** [comment]
@MCPEPIG May you fix that? You already did in ClearSky

**Comment by PocketKiller** [comment]
yes.
