### ISSUE TITLE
PHP 7 and 0.14 build

### ISSUE THREAD

**Issue by FunnyCrafteur** [ImagicalMine/ImagicalMine#860]
Hi ! I have an error with PHP 7 and 0.14 build 

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/gsp_6/srv5.hmserv.eu-19132/ImagicalMine.phar/src/pocketmine/Server.php on line 117

thanks

**Comment by keithkfng** [comment]
@ImagicalMine/developers someone mind fixing it up? :)

**Comment by PocketKiller** [comment]
0.14.0 branch is not for PHP7...

**Comment by ecoron** [comment]
looks more like a build from master, which has this line 117, and this i still 0.13.2 on php5. @FunnyCrafteur can you specify which build you use?

**Comment by FunnyCrafteur** [comment]
I have try with the last build of 0.13.2 and 0.14 same error

**Comment by dterweij** [comment]
You are starting the 0.13.2/0.14.0 which is for PHP5 with PHP7, so yes that gives a error.
Use the 0.14.0 PHP7 branch or the PHP7 branch for 0.13.2.
Works fine here.

**Comment by FunnyCrafteur** [comment]
This http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine-PHP7-0.14/lastSuccessfulBuild/ ?

**Comment by ecoron** [comment]
ok thx, i'm just starting to merge latest changes into it... this can took hours since there are so many conflicts. therefore i take a look on the existing version

**Comment by ecoron** [comment]
not complete finished yet, but most changes should now in php7-0.14 branch, build was successfull, maybe someone can test it too.

**Comment by FunnyCrafteur** [comment]
Works : srv5.hmserv.eu:19132 ! :)

**Comment by FunnyCrafteur** [comment]
But crash when a player join 

Load 1.12%]0;ImagicalMine 1.0dev | Online 1/10 | Memory 26.56/1.95/123.47/948.09 MB @ 10 threads | U 0 D 0 kB/s | TPS 20 | Load 2.25%]0;ImagicalMine 1.0dev | Online 1/10 | Memory 26.56/1.95/123.47/948.09 MB @ 10 threads | U 0 D 0 kB/s | TPS 20 | Load 1.23%]0;ImagicalMine 1.0dev | Online 1/10 | Memory 26.56/1.95/123.47/948.09 MB @ 10 threads | U 0 D 0 kB/s | TPS 20 | Load 1.08%[36m[21:01:51] [m[31mcritical> [37mTypeError: "Return value of pocketmine\Player::getName() must be of the type string, null returned" (EXCEPTION) in "/src/pocketmine/Player" at line 3250[m
[36m[21:01:51] [m[31memergency> [37mAn unrecoverable error has occurred and the server has crashed. Creating a crash dump[m
[36m[21:01:51] [m[31memergency> [37mPlease upload the "/home/gsp_6/srv5.hmserv.eu-19132/CrashDump_Mon_Feb_8-21.01.51-CET_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.[m
[36m[21:01:52] [m[31memergency> [37mCrashed while crashing, killing process[m
[36m[21:01:52] [m[31memergency> [37mError: Call to undefined method pocketmine\network\rcon\RCONInstance::kill()[m

**Comment by ecoron** [comment]
ok will fix it. for more, please create an issue. it's easier to follow.
