### ISSUE TITLE
0.14.0 PHP7 Wont Start

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#864]
When i try to start the newest build from the 0.14 branch i get    Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
I was getting other errors until i changed the permissions of a file in the bin php 7 folder as well

**Comment by Skyladd** [comment]
Just checked and i actually do have the file it is asking for in that directory..i dont get why it doesnt see it..

**Comment by ecoron** [comment]
is the same on jenkins and also on my dev env, but the server should start. it's something related to the php bin dependencies. i will investigate

**Comment by ecoron** [comment]
i added https://github.com/ImagicalMine/ImagicalMine/blob/php7-0.14/compile-php7.sh
so try to build your php7 with this one. tested on linux ...

**Comment by ecoron** [comment]
trying a new packed php7 , but download on jenkins quite slow.
@keithkfng maybe you can add it manualy faster https://github.com/ecoron/ImagicalMine-php7-linux/releases/download/0.1/ImagicalMine-php7-linux.tar.gz
i tested it on my dev linux, seems to be working

**Comment by Skyladd** [comment]
The compile says i have to install bison. Can someone just send me an easy tut to install IM PHP7 lol...apparently replacing the bin folder and the compile dont work

**Comment by mwvent** [comment]
Bison should be available from the package manager of most distros -  apt-get install bison works for Ubuntu and probably anything debian related

**Comment by Skyladd** [comment]
@mwvent Understandable, i just didnt want to install anything extra considering with the php 5 i just dragged the bin folder, phar and start into a folder and ran it lol
