### ISSUE TITLE
Slab still incorrect meta ...

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#865]
I just pull requests from 
const NETHER_BRICK = 7;
to
const NETHER_BRICK = 6;

And i still get Nether Brick if i set the slab's meta to 7.
What happen ? Seriously ...

**Comment by thebigsmileXD** [comment]
Because of the function. Bitwise calculation. &0x07

**Comment by intagaming** [comment]
@thebigsmileXD oh i don't know how to fix it ... can u fix it for me ?
