### ISSUE TITLE
Server Crash on disconnect 0.14.0 php7

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/ImagicalMine#868]
09.02 15:38:17 [Server] INFO [14:38:17] critical> [Network] Stopped interface pocketmine\network\RakLibInterface due to Class pocketmine\Long not found

**Comment by ecoron** [comment]
Should be fixed now

**Comment by eddir** [comment]
Error in pocketmine\Player in lines 3208, 3211, 3212, 3213 undefined class Long and Short (LongTag and ShortTag). Please fix :)

**Comment by ecoron** [comment]
Ok will check it

**Comment by ecoron** [comment]
try the latest one 291 of php7-mcpe0.14 - there it should be fixed
