### ISSUE TITLE
I cant login with the new update

### ISSUE THREAD

**Issue by AmiroEmad** [ImagicalMine/ImagicalMine#870]
when you made it make all mcpe version able to login i cant login tested it with mcpe 0.13.0 and 0.13.1 and 0.13.2

but when i downgraded to old imagial mine i am able to join

**Comment by ecoron** [comment]
which IM build?

**Comment by dterweij** [comment]
Works fine here. MCPE 0.13.1  / Windows 10 minecraft 0.13.2 and latest IM. Tho it says 0.13.0 and is RED in serverlist, I can connect fine.

**Comment by PocketKiller** [comment]
@dterweij sorry I did that because what version with only numbers should I choose?

**Comment by AmiroEmad** [comment]
0.13.2

**Comment by AmiroEmad** [comment]
ok then custom alerts kick me out
