### ISSUE TITLE
Nametag bugs

### ISSUE THREAD

**Issue by Naniiii** [ImagicalMine/ImagicalMine#872]
Hello. This is Nani. There are nametag bugs. The nametag of some players suddenly disappears and never appears again. Fix it.

**Comment by ecoron** [comment]
please provide more infos. which version / build are you using.

**Comment by Naniiii** [comment]
Latest build. It is not a plugin bug. It is ImagicalMine's fault

**Comment by ecoron** [comment]
latest build for 0.13.x or 0.14.x?

**Comment by applqpak** [comment]
Yeah, as @ecoron said, what version?

**Comment by keithkfng** [comment]
@applqpak see the other issue - i think this one is a duplicate and the same.

**Comment by applqpak** [comment]
Ok.
