### ISSUE TITLE
Change gamemode give an error message

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/ImagicalMine#874]
It changes the gamemode but give an error message.

**Comment by ecoron** [comment]
didn't get it, for what should it be

**Comment by erkam2002** [comment]
A bug i can change my gamemode but in display write failed

**Comment by ecoron** [comment]
confirmed, GM is changed but the message is wrong.

**Comment by erkam2002** [comment]
The bug is not fixed

**Comment by ecoron** [comment]
i see build 306, where the fix should be is corrupted, so i trigger a new one

**Comment by erkam2002** [comment]
Can you german?

**Comment by ecoron** [comment]
ja kann ich, ist meine default Sprache. yes i can it's my default language :)

btw. fix should now available on build 310

**Comment by erkam2002** [comment]
Ok ich kann auch deutsch mein english ist schlecht
