### ISSUE TITLE
Lag when moving on stairs

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#877]

**Comment by intagaming** [comment]
Picture please? Move on stairs still very smoothly for me ...

**Comment by XiangZhao969** [comment]
I got stuck while walking on it.

**Comment by XiangZhao969** [comment]
Sometimes it lag going backward

**Comment by intagaming** [comment]
Ermmm... I don't have that problem ... Whats your build ?

**Comment by XiangZhao969** [comment]
649

**Comment by PocketKiller** [comment]
server lagg.

**Comment by thebigsmileXD** [comment]
Server lag and missing bounding box calculation in Stairs.php (its commented out because it caused even more problems.)

**Comment by zzm317** [comment]
so what does he mean.....

**Comment by intagaming** [comment]
When you step up the stairs, you lag. That's it, and nobody know how it looks like.
