### ISSUE TITLE
Enchantment Table Block setblock error (?)

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#878]
$this->getServer()->getLevelByName($this->worldname)->setBlock(new Vector3($x+8, 64, $z+2),Block::get(Block::ENCHANT_TABLE),true);

Result with no book on the table:

http://s12.postimg.org/zepllfonh/Untitled.png

My fool ? Or something with Enchantment Table ?
And i can set the block 116 (Enchantment Table) with /we (WorldEditArt) with the book above.

**Comment by thebigsmileXD** [comment]
You spawn the block without the tile. Your fault

**Comment by intagaming** [comment]
Okay thank you i'll do it right now

**Comment by intagaming** [comment]
@thebigsmileXD  hey can i ask you the same problem too ? (oh my english ...)

`$signpos = new Vector3($x+5, 66, $z-1);
        $this->getServer()->getLevelByName($this->worldname)->setBlock($signpos,Block::get(Block::SIGN_POST, 2),true);
        $tile = $this->getServer()->getLevelByName($this->worldname)->getTile($signpos);
        if($tile instanceof Sign) {
            $tile->setText($this->restaurant[(($x-12) >> 4) .":". (($z-12) >> 4)]["owner"]."'s'","Restaurant");
        }`

Why Wall Sign doesn't appear ?

**Comment by thebigsmileXD** [comment]
1st you set sign post.. Also it has meta
2nd do an output if you really have a tile.. I guess instanceof Tile doesnt return true

**Comment by intagaming** [comment]
@thebigsmileXD Yea the Tile really doesnt exist.
I was went to the source code of the Enchantment Table and it have the line Tile::createTile which Sign Post doesnt
Trying some way to create one ...

**Comment by intagaming** [comment]
@thebigsmileXD Done! Thank you a lot, i learned very helpful things of Tile :D (RIP English)
And maybe the code for another too ?

$signpos = new Vector3($x+5, 66, $z-1);
        $owner = $this->restaurant[(($x-12) >> 4) .":". (($z-12) >> 4)]["owner"];
        $this->getServer()->getLevelByName($this->worldname)->setBlock($signpos,Block::get(Block::WALL_SIGN, 2),true);
        $nbt = new Compound("", [
            new String("id", Tile::SIGN),
            new String("Text1", $owner."'s"),
            new String("Text2", "Restaurant"),
            new String("Text3", ""),
            new String("Text4", ""),
            new Int("x", $x+5),
            new Int("y", 66),
            new Int("z", $z-1)
        ]);
        Tile::createTile(Tile::SIGN, $this->getServer()->getLevelByName($this->worldname)->getChunk($x+5 >> 4, $z-1 >> 4), $nbt);
