### ISSUE TITLE
Error create config.yml php7 0.14.0

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/ImagicalMine#881]
10.02 18:13:27 [Server] INFO Warning: file_put_contents(/plugins/EntityManager/config.yml): failed to open stream: No such file or directory in phar:///imagicalmine_php7.phar/src/pocketmine/utils/Config.php on line 213

**Comment by DarkWav** [comment]
I answerd to your issiue here: [EntityManager/Issiues/22](https://github.com/milk0417/EntityManager/issues/22)

**Comment by DarkWav** [comment]
please close this issiue, if you have more questions you can ask at [ImagicalMine-Forums-Support](http://forums.imagicalmine.me/forums/support.14/).

**Comment by erkam2002** [comment]
Thx ok
