### ISSUE TITLE
Crazy Minecart

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#883]
Place a straight line of rails (normal rails) then place the minecart on it, then ride it. First of all, it will drop 1 minecraft where you was placed minecart. Secondly the minecart will not stop, it will go back. And if you hit Jump, it will drop another minecart too. Then you have 2 minecarts.
And another types of rails except normal rails are not working now ...

UPDATE: Oh dear, you can place Minecart on the block. And if you destroy it, it will drop 2 minecarts. Oh dear ...

**Comment by ecoron** [comment]
Yes Minecart needs more improvements. Will check it.

**Comment by ecoron** [comment]
drops should be fixed, rails working also fine for me. yes at the moment it will go back if reaching the end of the rails...

**Comment by dterweij** [comment]
Yeah the cart is not working well but thats because it is not 100% fixed yet so i dont complain :) I just wait. Give the developers time to fix things and this issue was already reported some time ago.
