### ISSUE TITLE
Little Problem

### ISSUE THREAD

**Issue by Christian665** [ImagicalMine/ImagicalMine#885]
I have install on my  Linux system PHP7
Php -v = 7.0.3-3dev .....

I copy the PHP7 binary in Imagicalmine order with the PHP7 Phar file.
Who can I find the start.sh for PHP7 ?

PHP7 compatible with the version of Imagicalmine php5 ?or can i start no more php5 server

**Comment by intagaming** [comment]
Maybe Genisys have that start.sh (?)

**Comment by MichaelM04** [comment]
Looking for ./start.Sh php 7 myself haven't found anything yet

**Comment by MichaelM04** [comment]
https://github.com/iTXTech/Genisys/blob/master/start.sh you'll just have to edit a lot of the read directory's

**Comment by intagaming** [comment]
What about this?
https://github.com/iTXTech/Genisys/blob/master/start.sh

**Comment by Christian665** [comment]
[URL=http://www.bilder-upload.eu/show.php?file=e40239-1455203348.jpg][IMG]http://www.bilder-upload.eu/thumb/e40239-1455203348.jpg[/IMG][/URL]

When I start the server my world in Minecraft  not load and in my console looks like MATRIX :-)
On

**Comment by Christian665** [comment]
[URL=http://www.bilder-upload.eu/show.php?file=e40239-1455203348.jpg][IMG]http://www.bilder-upload.eu/thumb/e40239-1455203348.jpg[/IMG][/URL]

**Comment by Christian665** [comment]
I have download php7 build scripts.zip
I start install.sh     -> ok
I start compile.sh   -> ok
Start.sh    -> error could not found correct BIN php ...
I copy the BIN folder from Imagicalmine PHP7-Linux.tar.gz    
In the folder and start.sh
Error Line54 can't binary file execute ....


What's wrong ???

**Comment by MichaelM04** [comment]
Imagicalmine says php7 but doesn't even know how to do ./start.sh script for it typical.....

**Comment by PocketKiller** [comment]
you've missing binray (/bin) PHP files...
