### ISSUE TITLE
Sign text disapears

### ISSUE THREAD

**Issue by MichaelM04** [ImagicalMine/ImagicalMine#886]
I've had this problem for a week now various updates later still not fixed the signs you have to type with 2 seconds or the text disapears

**Comment by thebigsmileXD** [comment]
Then get better internet. Its a connection issue

**Comment by MichaelM04** [comment]
I have 10 gig a second wifi its not the connection there is another bug where its the connection but thats not the issue this time 
Forget it I'll just use a sign editor
