### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by eddir** [ImagicalMine/ImagicalMine#898]
12:24:43] critical> TypeError: "Return value of pocketmine\Server::getTick() must be of the type integer, null returned" (EXCEPTION) in "/src/pocketmine/Server" at line 708

**Comment by ecoron** [comment]
yes this are the previous php7 changes for strict usage, will fix later ore maybe someone else can do that
line 217 should also changed to private $tickCounter = 0;

**Comment by mwvent** [comment]
Works on my test machine I will close the issue based on that
