### ISSUE TITLE
CommandReader hangs shutdown

### ISSUE THREAD

**Issue by mwvent** [ImagicalMine/ImagicalMine#903]
Not sure this will affect everyone I think PHP7 needs to be compiled with --with-readline ?

CommandReader is awesome - will be great to enter commands without them being scrolled away as you are trying to type! But when the server shuts down it will wait forever on [23:56:05] debug> Stopping CommandReader thread - until enter is pressed. 
 
I am calling it a night and I will look into this tomorrow but I am going to pop the issue in here in case anybody knows of a quick fix.

**Comment by ecoron** [comment]
I have also noticed this on shutdown. Maybe it's related with the RakLib issue.

**Comment by ecoron** [comment]
seems CommandReader isn't hanging anymore, but maybe you can test it too.

**Comment by mwvent** [comment]
Glad RakLib crash is sorted :-) CommandReader was still stalling on the php7 build with Readline enabled though.

I have disabled using readline in https://github.com/ImagicalMine/ImagicalMine/commit/c7b0b3b21e92de23bc5c1b52932044847194be81 - there was no way it would ever work, the readline function will not return until the user input has finished and there is no way of force-killing the thread in the latest pthreads.

The official IM PHP7 build script has readline disabled anyway
