### ISSUE TITLE
Client Crashing

### ISSUE THREAD

**Issue by RustyWar** [ImagicalMine/ImagicalMine#907]
The client which is version 14.0 on all beta version is crashing when trying to join an IM 14.0 server.I found a solution (wait 10sec before joining) for it but it kinda gets anoyying.Please fix this..

**Comment by PocketKiller** [comment]
its also for MCPE 0.13.0+.

**Comment by mwvent** [comment]
I'm sorry I cant reproduce this :-(

I have tried (with 14.0B6) 
 - loading the client and attempting to join immediately after it started
 - starting the server and joining immediately while its starting up

Are there and server plugins / client mods in effect ? I am going to remove myself as an assignee in case somebody else who can reproduce it can gather more info

**Comment by mwvent** [comment]
I am going to close this issue, as far as I know its not happening anymore. If am wrong I do apologise
