### ISSUE TITLE
Fix code style

### ISSUE THREAD

**Issue by ZINGDING** [ImagicalMine/ImagicalMine#911]
Please fix code style......
There are each code styles....
# Combine code style!

**Comment by PocketKiller** [comment]
@keithkfng we messed up coding style, we couldn't undo..

**Comment by ZINGDING** [comment]
@PocketKiller  Eh... I fix code and I do Pull request!

**Comment by PocketKiller** [comment]
@ZINGDING That would be awesome, Thanks!
