### ISSUE TITLE
Enchantment Bug - Critical, Destroy entire Inventory!

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#91183]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

Add an Enchantment to ANY item. Inventory crash.
I mean, hold your sword is the hotbar, /enchant name 9 1, and BOOM.
http://s21.postimg.org/4mz5hhg7r/Untitled.png

Your Inventory is completely as much like a trash as possible. Your item display in the hotbar while turn on the Inventory Dialog, but when it close, nothing in your hand, and hotbar. Swap the slot of items is impossible, and specially have the Iron Bar 99+ in the hotbar.
Ermm, im seriously.
Latest Build, Windows 10 Beta 0.14.0.

**Comment by PocketKiller** [comment]
it's back...

**Comment by Creeperface01** [comment]
i know how to fix this

**Comment by Creeperface01** [comment]
enchantments, names, armor color works for me

**Comment by PocketKiller** [comment]
You found the NBT?!

**Comment by Creeperface01** [comment]
NBT is same but @kvetinac97 changed addEnchantment() method and it works!

/**
     * @param int $id
     * @param int $lvl
     * @return Item
     */
    public function addEnchantment($id, $lvl){
        if(!$this->hasCompoundTag()){
            $tag = new CompoundTag("", []);
        }else{
            $tag = $this->getNamedTag();
        }
        if(!isset($tag->ench)){
            $tag->ench = new ListTag("ench", []);
            $tag->ench->setTagType(NBT::TAG_Compound);
        }
        $found = false;
        foreach($tag->ench as $k => $entry){
            if($entry["id"] === $id){
                $tag->ench->{$k} = new CompoundTag("", [
                        "id" => new ShortTag("id", $id),
                        "lvl" => new ShortTag("lvl", $lvl)
                        ]);
                $found = true;
                break;
            }
        }
        if(!$found){
            $tag->ench->{count($tag->ench) + 1} = new CompoundTag("", [
                    "id" => new ShortTag("id", $id),
                    "lvl" => new ShortTag("lvl", $lvl)
                    ]);
        }
        $this->setNamedTag($tag);
    }
