### ISSUE TITLE
0.14 Crash with PHP7

### ISSUE THREAD

**Issue by sixteeN11** [ImagicalMine/ImagicalMine#914]
Hi,

INFO Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///jar/ImagicalMine-IC_1.0dev_014.phar/src/pocketmine/Server.php on line 121

what can i do?

**Comment by PocketKiller** [comment]
you did not use PHP7... did you?

**Comment by sixteeN11** [comment]
yes i get php7

jar/imagicalmine/bin# ls
php5  php7

**Comment by PocketKiller** [comment]
did you get the PHP7 ImagicalMine? nah, I've seen the branches.

**Comment by sixteeN11** [comment]
thank you

**Comment by sixteeN11** [comment]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///jar/ImagicalMine-IC_1.0dev_014.phar/src/pocketmine/Server.php on line 121
14.02 20:48:27 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory


with a the new 0.14 php7 imagicalmine branch

**Comment by ecoron** [comment]
it must be FloatTag instead Float. it's changed in php7-0.14
