### ISSUE TITLE
logged out due to Oops! Server veraltet!

### ISSUE THREAD

**Issue by sixteeN11** [ImagicalMine/ImagicalMine#915]
with the newest 0.13.x build 656

**Comment by PocketKiller** [comment]
outdated* set custom alerts server-outdated-message and client-outdated-message to off.

**Comment by sixteeN11** [comment]
ok, but where? in pocketmine.yml?

**Comment by PocketKiller** [comment]
don't you know how to read?

**Comment by sixteeN11** [comment]
Where are these Settings?

**Comment by thebigsmileXD** [comment]
under /plugins/CustomAlerts/config.yml

**Comment by sixteeN11** [comment]
thanks, solved.
