### ISSUE TITLE
Cannot use pocketmine\nbt\tag\Float

### ISSUE THREAD

**Issue by sixteeN11** [ImagicalMine/ImagicalMine#916]
Hi,

on all of my Server the same Issue:

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///jar/ImagicalMine-IC_1.0dev_014.phar/src/pocketmine/Server.php on line 121
14.02 19:05:35 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

ive downloaded the php7 0.14 zip and extracted them into imagicalmine,
php7 is on imagicalmine/bin/

**Comment by ecoron** [comment]
like in #914 said, it must be FloatTag try the latest phar from jenkins http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine-PHP7-0.14/lastSuccessfulBuild/artifact/releases/ImagicalMine.phar

**Comment by sixteeN11** [comment]
great! thanks!
