### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/ImagicalMine#920]
Senden
15.02 22:42:45 [Multicraft] Server stopped
15.02 22:42:45 [Multicraft] Looks like a crash, check the server console. Return value: 255
15.02 22:42:45 [Multicraft] Received stop command
15.02 22:42:43 [Multicraft] Stopping server!
15.02 22:42:43 [Multicraft] Restarting crashed server in 5 seconds
15.02 22:42:43 [Multicraft] Server shut down (starting)
15.02 22:42:43 [Server] INFO Parse error: syntax error, unexpected '<', expecting end of file in /imagicalmine_php7.phar on line 1588
15.02 22:42:43 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by ecoron** [comment]
looks like a corrupted phar try the latest php7-0.14 from jenkins
