### ISSUE TITLE
0.14 PHP7 wont run!!

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#927]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
--START ISSUE DETAILS BELOW--
I can't seem for the love of me find out how to get 0.14 PHP 7 running. Please someone post a tutorial I've followed all of the links and extracted bin files etc. The terminal in linux just instantly closes out. It says it cant a working php binary but i have PHP 7 installed and the bin folder with the php7 libraries...someone please clarify this!

**Comment by keithkfng** [comment]
Do try the instructions for reinstalling IM @ imagicalmine.net

**Comment by Skyladd** [comment]
I did either im not finding it or idk..curl doesnt work on my computer and i cant find anything else man

**Comment by keithkfng** [comment]
Try wget -q -O - get.imagicalmine.net | bash

**Comment by Skyladd** [comment]
bash: line 16: _: command not found
bash: command substitution: line 16: syntax error near unexpected token `|'
bash: command substitution: line 16: ` | |/ __/ _'
 | | '_  |/ _ | | |\/| | | '_ \ / _ \ 
 | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/ 
 |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___| 
                     __/ |                                   
                    |___/                                    
system> Choose which PHP binary you want to install
system>	1) Linux x86(32-bit system)
system>	2) Linux x64(64-bit system)
system>   3) Mac x86(32-bit system)
system>   4) Mac x64(64-bit system)
system> Number (e.g. 1): error> Unknown selection. Restart the script, and then choose again.

**Comment by Skyladd** [comment]
I'm running 32 bit if that helps any lol..

**Comment by keithkfng** [comment]
Do it again and type 1

**Comment by Skyladd** [comment]
command not found. it returns me to the basic input, nothing special

**Comment by keithkfng** [comment]
Updated - try again

**Comment by EpicSteve33** [comment]
can u guys make a php7 for Linux 32bit cuz I really need it

**Comment by Skyladd** [comment]
bash: line 16: _: command not found
bash: command substitution: line 16: syntax error near unexpected token `|'
bash: command substitution: line 16: ` | |/ __/ _'
 | | '_  |/ _ | | |\/| | | '_ \ / _ \ 
 | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/ 
 |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___| 
                     __/ |                                   
                    |___/                                    
system> Choose which PHP binary you want to install
system>	1) Linux x86(32-bit system)
system>	2) Linux x64(64-bit system)
system>   3) Mac x86(32-bit system)
system>   4) Mac x64(64-bit system)
system> Number (e.g. 1): 1
this is as far as it got. it allowed input but is now sitting there xD

**Comment by Skyladd** [comment]
oop update it returned command not found again

**Comment by EpicSteve33** [comment]
Can I have a link the the ImagicalMine php7 for 32bit

**Comment by EpicSteve33** [comment]
![image](https://cloud.githubusercontent.com/assets/12077835/13132813/13de1efa-d5ab-11e5-9bf7-2a4301947b5f.png)


Why no 32bit?

**Comment by keithkfng** [comment]
@Skyladd try installing unzip
@EpicSteve33 READ.

**Comment by Skyladd** [comment]
I have unzip applications installed. I can tar and unzip. Is it possible to send the files? Or compile them for me? I just dont want to have to install stuff and etc..php5 seems much easier lol

**Comment by EpicSteve33** [comment]
What there is only php7 for 32bit linux

**Comment by EpicSteve33** [comment]
I have a 32bit Linux operating system and there is only php7 for 64bit for Linux

**Comment by keithkfng** [comment]
@Skyladd then there is a problem with your computer.
@EpicSteve33 you aren't reading are you? Read my responses to @Skyladd.
