### ISSUE TITLE
help me php 7 whont work

### ISSUE THREAD

**Issue by GrimDevs** [ImagicalMine/ImagicalMine#934]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###--START ISSUE DETAILS BELOW
-----------------------------------

-----------------------------------

help me i dont how to ise php 7 to malke it work i might haft go back to pocketmine :( wichh i dont wont

**Comment by PocketKiller** [comment]
...
use the forums : http://forums.imagicalmine.me
