### ISSUE TITLE
i dont usersad it i tink how to upadte it or what erver i haft to do

### ISSUE THREAD

**Issue by GrimDevs** [ImagicalMine/ImagicalMine#935]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###--START ISSUE DETAILS BELOW
-----------------------------------

-----------------------------------
idk unsdetand pocketkilller what do  have to do it hard i dont get it say i cant be run becouse of stuff i tied both 36 86 and not work shoud i try 32 or use pocketmine i dnt know how to plz help me or give the files path in here for were to get the php for it so i can get me server back plz

**Comment by PocketKiller** [comment]
USE THE IMAGICALMINE FORUMS AND STOP DUPLICATING LMAO
