### ISSUE TITLE
not loding plz help ke

### ISSUE THREAD

**Issue by GrimDevs** [ImagicalMine/ImagicalMine#936]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###--START ISSUE DETAILS BELOW
-----------------------------------

-----------------------------------

i do it  it keeps saying /usr/bin/php/php.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127

**Comment by GrimDevs** [comment]
i keep on try it and it not working it keeps say this or crash the server befor it evens runs

**Comment by GrimDevs** [comment]
need help

**Comment by PocketKiller** [comment]
what platform?

**Comment by GrimDevs** [comment]
windowns 7

**Comment by PocketKiller** [comment]
make sure you have Visual C++ 2015 Redistributable Package.
and make sure that your download it success.

**Comment by GrimDevs** [comment]
ok what the link for it

**Comment by PocketKiller** [comment]
\#UseGoogle

**Comment by GrimDevs** [comment]
i mean what onw 86 or 64

**Comment by PocketKiller** [comment]
is your windows x64 or x86? lmao

**Comment by GrimDevs** [comment]
how do i check

**Comment by PocketKiller** [comment]
Windows Info

**Comment by GrimDevs** [comment]
help i keep get a erro say it cant be intileed
