### ISSUE TITLE
EntityDamageEvent call not cancelled  [PHP7-0.14]

### ISSUE THREAD

**Issue by Guillaume351** [ImagicalMine/ImagicalMine#937]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###--START ISSUE DETAILS BELOW
-----------------------------------
It happens with the php7 0.14 branch.

Hello,
I use a plugin to cancel EntityDamageEvent, like this : 

` 
public function onPlayerDamage(EntityDamageEvent $event){

        $this->getServer()->broadcastMessage("CALLED");
        $event->setCancelled();
}
`

Each time the EntityDamageEvent is called, it broadcast the message. I added 2 lines in Player.php for debug : 

`
public function attack($damage, EntityDamageEvent $source){
        if(!$this->isAlive()){
            return;
        }

        if($this->isCreative() and $source->getCause() !== EntityDamageEvent::CAUSE_SUICIDE and $source->getCause() !== EntityDamageEvent::CAUSE_VOID){
            $source->setCancelled();
        }elseif($this->allowFlight and $source->getCause() === EntityDamageEvent::CAUSE_FALL){
            $source->setCancelled();
        }

        parent::attack($damage, $source);
        $this->server->getPluginManager()->callEvent($source);

        if($source->isCancelled()){
            $this->getServer()->broadcastMessage("CANCELLED");
            return;
        }elseif($this->getLastDamageCause() === $source and $this->spawned){

            $this->getServer()->broadcastMessage("--------------NOT CANCELLED---------------");
            $pk = new EntityEventPacket();
            $pk->eid = 0;
            $pk->event = EntityEventPacket::HURT_ANIMATION;
            $this->dataPacket($pk);
            if($this->getHealth() < 0 or $this->getHealth() == 0){
                $pk = new RespawnPacket();
                $pos = $this->getSpawn();
                $pk->x = $pos->x;
                $pk->y = $pos->y;
                $pk->z = $pos->z;
                $this->dataPacket($pk);
            }
        }
    }
`

Now, if I try to jump in lava, the console will display this : 

`
[18:59:18] system> --------------NOT CANCELLED---------------
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
[18:59:18] system> CANCELLED
[18:59:18] system> CALLED
[18:59:18] system> CALLED
[18:59:18] system> CANCELLED
`

As you can see, I take damages from the lava the first time, then it's called twice, cancelled twice ....

-----------------------------------

**Comment by keithkfng** [comment]
WTF?! LOL
This issue hasn't been submitted before...

**Comment by Guillaume351** [comment]
I saw someone else reported EntityDamageEvent duplication (one hit => 4 event calls) maybe it has a link... I tried to delete my src folder and download again ImagicalMine bug same problem... I don't have the problem with an older version

**Comment by jazzwhistle** [comment]
Not sure if this is related, but neither worldprotect or peacefulspawn plugins can cancel pvp events on latest builds

**Comment by Guillaume351** [comment]
I just checked : If I fall one time, EntityDamageEvent is called 2 times. So there is an event call duplication too.

**Comment by mwvent** [comment]
I put some echo statements in my plugins that can cancel EntityDamageEvent - the function never gets called so the plugin doesnt have a chance to cancel it

**Comment by intagaming** [comment]
@Guillaume351 Yea, its my issue #739 . But its on the Windows 10. Hold down the left click, and it spam your console like damn. That doesn't work on the MCPE, but win 10.

**Comment by mwvent** [comment]
I added to pluginmanager.php callevent

 public function callEvent(Event $event){
                $isDebug = ($event instanceof \pocketmine\event\entity\EntityDamageByEntityEvent);
                if($isDebug) {
                        print_r($event->getHandlers()->getRegisteredListeners());
                }
                foreach($event->getHandlers()->getRegisteredListeners() as $registration){
                        if(!$registration->getPlugin()->isEnabled()){
                                continue;
                        }

                        try{
                                if($isDebug) {
                                        echo "Calling an event handler for EntityDamageByEntityEvent\n";
                                }

When a player hits another I see
Array
(
)

So far I have got to a point where it seems that the plugins have been unable to register themselves to handle the event (I should see two plugins registered here)

**Comment by jazzwhistle** [comment]
That is what I suspected... The same problem exists in the official
pocketmine too

**Comment by mwvent** [comment]
Still tracing this - I found that the plugin event does get registered and can get called but the plugins event handler must specify the exact class, not a parent class

So this used to work to cancel all PvP

    public function onPvP(EntityDamageEvent $ev) {
        if(!($ev instanceof EntityDamageByEntityEvent)) return;
        echo "ONPVP Called!!\n";
        $ev->setCancelled();
        return;
    }


Now you need to do this - this works

    public function onPvP(EntityDamageByEntityEvent $ev) {
        echo "ONPVP Called!!\n";
        $ev->setCancelled();
        return;
    }

**Comment by Guillaume351** [comment]
I have the problem with lava :/ No solution ?

**Comment by mwvent** [comment]
Looks like this affects EntityDamageByBlockEvent EntityDamageByEntityEvent and /EntityDamageByChildEntityEvent then. getRegisteredListeners() for these events does not return functions registered that used the parent EntityDamageEvent 

I am sure there is a solution

**Comment by mwvent** [comment]
Well changing the PluginManager.php registerEvents function can kind of make things work...

change

    $this->registerEvent($class, $listener, $priority, new MethodEventExecutor($method->getName()), $plugin, $ignoreCancelled);

to

    if($class == 'pocketmine\event\entity\EntityDamageEvent') {
        $class = 'pocketmine\event\entity\EntityDamageByBlockEvent';
        $this->registerEvent($class, $listener, $priority, new MethodEventExecutor($method->getName()), $plugin, $ignoreCancelled);
        $class = 'pocketmine\event\entity\EntityDamageByEntityEvent';
        $this->registerEvent($class, $listener, $priority, new MethodEventExecutor($method->getName()), $plugin, $ignoreCancelled);
        $class = 'pocketmine\event\entity\EntityDamageByChildEntityEvent';
        $this->registerEvent($class, $listener, $priority, new MethodEventExecutor($method->getName()), $plugin, $ignoreCancelled);
    } else {
        $this->registerEvent($class, $listener, $priority, new MethodEventExecutor($method->getName()), $plugin, $ignoreCancelled);
    }

This is hax though, not a solution - just pointing in the direction of the issue perhaps

**Comment by Guillaume351** [comment]
Flame still does damage (not lava, only the flame that comes with it)  :| But thanks for the temporary solution :)

**Comment by ecoron** [comment]
DamageEvents needs improvements, thats true

**Comment by mwvent** [comment]
It was such a simple fix but it took ages for me to understand the event listener registration code enough to work out what was happening :-)
