### ISSUE TITLE
[Attention] branch has changed, take care

### ISSUE THREAD

**Issue by ecoron** [ImagicalMine/ImagicalMine#939]
Just to notice. We have changed the master to the base of the php7-0.14 branch. 

Take care and don't push anything from your local master branch to this until you havn't pulled the latest version of the master. Don't try to merge your old local master with the new one... would be painfull :)

master is now for support of 0.14.x running on PHP7.

the legacy branch for supporting 0.13.x can be found on the branch 0.13.2

**Comment by AbelGamerC** [comment]
PHP7 NO plis

**Comment by AndreyNazarchuk** [comment]
where can I get a phar?
seems that jenkins is offline.

**Comment by InfornoFire** [comment]
Andrey, you download the zip, and then you get the scr, The scr folder is = to the phar file

**Comment by AndreyNazarchuk** [comment]
...I know, but how do I compile it?

**Comment by AndreyNazarchuk** [comment]
ok so I compiled it usiving devtools and downloaded the php7.0.3x86_64 and extracted it then put them together and it says it cant find php

**Comment by AndreyNazarchuk** [comment]
Can someone just send me a zip with the bin folder and far?

**Comment by keithkfng** [comment]
Why don't you just follow the installation instructions on imagicalmine.net?

**Comment by AndreyNazarchuk** [comment]
Wow you're genius!

**Comment by AndreyNazarchuk** [comment]
@keithkfng jenkins isnt working

**Comment by keithkfng** [comment]
You don't need Jenkins -_-

**Comment by AndreyNazarchuk** [comment]
The link to the phar on ImagicalMine.net is Jenkins.

**Comment by keithkfng** [comment]
You do the installation not the phar -.-"

**Comment by AndreyNazarchuk** [comment]
I know, but the instructions for Windows have a link to Jenkins, which
doesn't work.

**Comment by keithkfng** [comment]
It does work - I can access from here perfectly fine.

**Comment by AndreyNazarchuk** [comment]
Well it does now, thanks!

**Comment by keithkfng** [comment]
LOL magic XD

**Comment by AbelGamerC** [comment]
But I have android: /

**Comment by remotevase** [comment]
@AbelGamerC use this for Android: https://github.com/ImagicalMine/IM-Android
that will work fine with Android... don't worry

**Comment by AbelGamerC** [comment]
Look here APK PocketMine with PHP7 
https://github.com/AbelGamerC/PM-Android-PHP7

**Comment by keithkfng** [comment]
This isn't an advertising thread.
