### ISSUE TITLE
Well, pocketkiller, THE TEMPLATE DOES NOT APPEAR

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalMine/ImagicalMine#941]
Anywho what you mean ImagicalMine org

**Comment by PocketKiller** [comment]
lmao I will unlock conversation

**Comment by InfornoFire** [comment]
You havent answer the 2 questions

**Comment by InfornoFire** [comment]
Where is the template, and what is ImagicalMine org, the website you guys made.

**Comment by PocketKiller** [comment]
Imagical Mine org : https://github.com/ImagicalMine -_-
The Issue template is the thing you found it written on the start of issue

**Comment by InfornoFire** [comment]
It was not there

**Comment by InfornoFire** [comment]
It was blank like last 3 months

**Comment by PocketKiller** [comment]
LMAO @keithkfng Template files are removed on merging...

**Comment by InfornoFire** [comment]
Did i say 3 months i meant 1

**Comment by InfornoFire** [comment]
Well ok

**Comment by InfornoFire** [comment]
Thank you, you can limit and stuff now

**Comment by PocketKiller** [comment]
I don't need lmao

**Comment by InfornoFire** [comment]
Uhh, so, Where is mac :P
