### ISSUE TITLE
"logged out due to Server Problem: Resolving..."

### ISSUE THREAD

**Issue by peepzandmeepz** [ImagicalMine/ImagicalMine#942]
I keep receiving this error from the latest build (#671). Unsure if it's something I might have done wrong or if other users are also experiencing this.

In MCPE, the version number off to the side "0.14.0" shows up red.

Sorry if this issue is invalid or duplicated ahead of time, thanks!

**Comment by PocketKiller** [comment]
it's about the protocol version... I'll fix it.
and all players get disconnected with that message?

**Comment by peepzandmeepz** [comment]
Correct.

**Comment by applqpak** [comment]
Yeah, I'm pretty sure someone posted an update changing the versions, but didn't change the protocols.

**Comment by keithkfng** [comment]
Sorry - someone updated the versions?
