### ISSUE TITLE
async-workers auto causes segfault core dump on servers with many cores. 0.14.x PHP 7 branch

### ISSUE THREAD

**Issue by ZizzyZizzy** [ImagicalMine/ImagicalMine#944]
PHP 7 (both 7.1.0-dev and 7.0.2)
[15:19:47] system> This server is running ImagicalMine 1.0dev [ImagicalMine] implementing API version 1.14.0 for Minecraft: PE v0.14.x alpha (protocol version 40)

The crash does not occur on my nearly identical dev server. After much head beating, comparing settings, packages, rebooting, etc. I've finally discovered the cause of this segfault. 

The only difference between my dev and production system is amount of memory and number of cores. (8GB/8 CPU vs 128GB/24 CPU) That eventually led me to async-workers in pocketmine.yml. 

The default for async-workers is "auto". Changing it to a reasonable number for a shared server (2 or 4) stops the segfault crashing..mostly. The higher the async-worker setting, the more likely it will crash when the server starts up. Sometimes it will start, then crash shortly after. It's MUCH more evident when you are trying to use plugins (that have been patched for PHP 7.)

A value of 2 on this huge server seems to be stable for the moment while using 3 plugins. A value of 4 causes crashing about 20-40% of the time. I cannot reproduce the crash on the dev 8 core server, even if I set async-workers to 8.

8 core server:
model name      : Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz

24 core server:
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

**Comment by ZizzyZizzy** [comment]
Something else interesting I just noticed is that changing "collect-async-worker to "false" returns stability to the server, regardless of the async-workers number...so far.

**Comment by mwvent** [comment]
These segfaults are a nuisance. I spent 2 days pulling my hair out until I analysed the core dump and found that it was crashing on mysqli fetch for one particular select query (that has 0 issues on PHP5!)

I would certainly try PHP 7.0.3 (the newer build script will most certainly bring newer versions of pthreads too ) - if that doesn't  change anything you can set things up to give you a core dump when it segfaults that can be analysed with gdb

**Comment by ZizzyZizzy** [comment]
I've since switched to ClearSky sunshine builds that run on PHP 5 very well. I noticed in their pocketmine.yml config, they've also changed the async-workers to 2 and disabled collect-async-worker as well. ClearSky is supposed to be an immense improvement over the ImagicalMine branch, but they have yet to release a 0.14.0 PHP 7 version.
