### ISSUE TITLE
Problem with PHP7. HELP!!

### ISSUE THREAD

**Issue by RarePika** [ImagicalMine/ImagicalMine#945]
I have Windows 10 and want to upgrade to the new PHP7-0.14 ImagicalMine. I needed to upgrade my PHP. I tried the method found here https://github.com/ImagicalMine/ImagicalMine/issues/811 . I still get an error for some reason.
![pocketmine-mp 2_18_2016 4_52_21 pm](https://cloud.githubusercontent.com/assets/17325905/13162210/7b519160-d660-11e5-8465-a5af7a8e7c03.png)

If you can't view the image, the error says "You must use PHP >= 7.0. Please use the installer provided on the homepage." Can someone tell me how to fix this error? Thanks!

**Comment by InfornoFire** [comment]
You need to install php7 here

**Comment by InfornoFire** [comment]
https://github.com/ImagicalMine/IM-PHP-Binaries

**Comment by InfornoFire** [comment]
Basically, delete the php folder in your bin folder, and replace it with your preferred windows file

**Comment by RarePika** [comment]
Thanks so much InfornoFire!
