### ISSUE TITLE
MCPE Map formats?

### ISSUE THREAD

**Issue by karlchan** [ImagicalMine/ImagicalMine#94667]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-----------------------------

I'm running the latest IM on a 64bit Linux Amazon Web services instance (Micro). Up until a week or so ago when IM moved to php7, I was able to download and add maps from sites like: http://mcpedl.com/ 

I had changed my pocketmine.yml file to use leveldb format maps (changed from mcregion). I would drop the downloaded map into the worlds folder and then change my server.properties to point to that folder.

After upgrading to the latest IM, when starting the server, it now reads says that it can't find the world and just generates a default mcregion world in that folder. A new directory is created named region.

Anyway to load leveldb worlds again?

thanks,

**Comment by XShockinFireX** [comment]
Right now you would need to convert your LevelDB world into an anvil world or mcregion. https://github.com/ImagicalCorp/MConverterUltimate

**Comment by keithkfng** [comment]
No you wouldn't. Linux servers have the ability to run LevelDB worlds directly. Is there any error when loading the worlds you can show us?

**Comment by karlchan** [comment]
Thanks for your replies!

Downloaded a map: http://www.9minecraftpe.net/tn-city-map-mcpe/

extracted and uploaded to /[imagicalminehome]/worlds/tn_city/

Changed my server.properties: `level-name=tn_city`
pocketmine.yml:
```
level-settings:
 #The default format that levels will use when created
 default-format: leveldb
 #If true, converts from a format that is not the default to the default format on load
 #NOTE: This is currently not implemented
 convert-format: false
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false

```

starting IM:
```
[21:14:35] system> ImagicalMine is a third-party build of PocketMine-MP, distributed under the LGPL licence
[21:14:35] system> Loading ImagicalMine system files....
[21:14:35] system> Loading server properties...
[21:14:35] system> Enabled log writing to server.log
[21:14:35] system> Selected English (eng) as the base language
[21:14:35] system> Starting Minecraft: PE server version v0.14.x alpha
[21:14:35] system> Opening server on 0.0.0.0:19132
[21:14:35] system> This server is running ImagicalMine version 1.0dev "ELITE" (API 1.14.0)
[21:14:35] system> ImagicalMine is distributed under the LGPL License
[21:14:36] notice> Level "tn_city" not found
[21:14:36] system> Preparing level "tn_city"
[21:14:36] notice> Spawn terrain for level "tn_city" is being generated in the background
[21:14:36] system> Default game type: Survival Mode
[21:14:36] system> Done (0.35s)! For help, type "help" or "?"
```

When I enter the world it is just a 'standard' build.

**Comment by XShockinFireX** [comment]
@keithkfng yeah i forgot about that... xD

**Comment by InfornoFire** [comment]
Did someone remove this feature, I wanted this for so long and no one told me...

**Comment by keithkfng** [comment]
Try using the worlds setting in pocketmine.yml?

**Comment by PocketKiller** [comment]
did you name the folder tn_city? and the name on level.dat is the same? if not, use ManyWorlds by @aliuly on the PocketMine forums and use /mw fix tn_city.

**Comment by karlchan** [comment]
tried looking up some examples of it but couldn't find exact syntax. can you help me out?

So if I uploaded the world into worlds/tn_city/  and in pocketmine.yml, I changed 'default-format: leveldb' and under the worlds: section I placed `tn_city:` but I don't know what else to put after that. I wouldn't need seed: or generator: right?

**Comment by PocketKiller** [comment]
try to do the step I gave you.

**Comment by karlchan** [comment]
I used the level.dat file that came with the download and the folder is named tn_city.

Tried ManyWorlds last night, but crashed when loading:
`
ImagicalMine Crash Dump Thu Feb 25 04:50:42 UTC 2016

Error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name
File: /ManyWorlds_v2.0.3.phar/src/aliuly/manyworlds/MwLvDat
Line: 36
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ManyWorlds v2.0.3

Code:
[27] use pocketmine\command\Command;
[28] 
[29] use pocketmine\utils\TextFormat;
[30] 
[31] use aliuly\manyworlds\common\mc;
[32] use aliuly\manyworlds\common\BasicCli;
[33] 
[34] use pocketmine\level\generator\Generator;
[35] use pocketmine\nbt\NBT;
[36] use pocketmine\nbt\tag\Int;
[37] use pocketmine\nbt\tag\String;
[38] use pocketmine\nbt\tag\Long;
[39] use pocketmine\nbt\tag\Compound;
[40] use pocketmine\math\Vector3;
[41] 
[42] class MwLvDat extends BasicCli {
[43] 	public function __construct($owner) {
[44] 		parent::__construct($owner);
[45] 		$this->enableSCmd("lvdat",["usage" => mc::_("<world> [attr=value]"),
[46] 										"help" => mc::_("Change level.dat values"),

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 45; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ip-172-31-48-252 4.1.13-19.30.amzn1.x86_64 #1 SMP Fri Dec 11 03:42:10 UTC 2015 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
`

**Comment by PocketKiller** [comment]
ManyWorlds is outdated, it is for PHP5...

**Comment by karlchan** [comment]
So... I guess instead of copying the levels directly, I need to make the extra step of conversion to Anvil format?

https://forums.pocketmine.net/threads/0-14-php7-cant-find-world.15498/

**Comment by karlchan** [comment]
Update:
Well this finally worked for me. Looks like I have to take the extra step to do the leveldb to Anvil conversion. Not as convenient as before, but at least my kids and I can play in a persistent server again.

So to recap:
* stopped IM server, 
* Download MCPE map from internet (comes over in leveldb format)
* I downloaded this converter: https://github.com/ljyloo/LevelDb2Avnil
* On my local machine, unzipped the leveldb map into the LevelDB2Anvil folder,
* renamed the folder to 'world'
* opened a command prompt and navigated to the LevelDB2Anvil directory and executed start.bat
* conversion completes and files are dumped to the worldanvil directory.
* I create a new folder on my IM server under worlds folder (in this case, tn_city)
* create a region folder
* upload all the local files from the worldanvil directory to the remote region folder (bunch of .mca files)
* I had to copy a level.dat and level.dat.old file from a working world to the tn_city directory.
* made sure my server.properties level-name was set to `tn_city`
* started IM and away we go! worked!
* I think your start position might be a little off depending on map, but after logging in I used /setworldspawn after I found a good spot.

Well, I hope this helps some others. Using/exploring the premade maps that others make is really fun for my kids. They love making their own worlds, but seeing something like TN-City made their jaws drop.

I hope that maybe IM can make leveldb worlds 'drag and drop' again without conversion someday. But I'm happy that I can load premade worlds again! (It's been a long week)

**Comment by keithkfng** [comment]
LOL - you ended up converting it...

**Comment by karlchan** [comment]
Well I spoke too soon. 

The world does not load completely, I'll navigate for a few seconds away from the spawn point and the 'rest of the world' never really loads or loads very slowly. It wasn't like it was before the switch to php7. In those builds after copying up the leveldb file to the server, it would load and display the world very quickly. 

@keithkfng, you mentioned using the world syntax in pocketmine.yml, do you have an example to load a leveldb world in the worlds folder?

thanks.

**Comment by keithkfng** [comment]
Now that isn't related to this - this is related to the chunk bug I think... @PocketKiller I thought it was fixed...

**Comment by PocketKiller** [comment]
@keithkfng not having it...
@karlchan on your MCPE settings on Render distance and pocketmine.yml render distance...

**Comment by InfornoFire** [comment]
Or you can preload the map and fly around to load chunks to see if that works
