### ISSUE TITLE
Hold on, what just happend. [Php7]

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalMine/ImagicalMine#948]
First, I would like to state I have no idea why the template is not loading. Now to get started, I was updating my server removing incompatible plugins that crash the server like anyone else. Now when I boot the server it crash. I then slowly put in plugins and it worked. So if it isn't one of the 48 plugins, what happen? As I was typing this long message that should've been cut in half, server crashed again. Im not expecting a glitch, but more of what you guys think happen. Is it just the unstable of the plugins, or the php7 itself. Lots of silly problems are happening and you guys don't seem to have enough time to solve all of these.

**Comment by keithkfng** [comment]
Well, first of all, you deleted the issue template. Second, there are no details about the crash. How do you expect us to solve it?

**Comment by PocketKiller** [comment]
@keithkfng he didn't, .github folder is removed while merging branches.

**Comment by keithkfng** [comment]
LOL

**Comment by ecoron** [comment]
Yes, was my fault. Didn't take care of it, as I shifted the branches :(
