### ISSUE TITLE
Litte problem with Level.php

### ISSUE THREAD

**Issue by intagaming** [ImagicalMine/ImagicalMine#949]
Straight into it.

> public static function blockHash(int $x, int $y, int $z){
> 		return PHP_INT_SIZE === 8 ? (($x & 0xFFFFFFF) << 35) | (($y & 0x7f) << 28) | ($z & 0xFFFFFFF) : $x . ":" . $y .":". $z;
> 	}

need to be change to 

> public static function blockHash($x, $y, $z){
> 		return PHP_INT_SIZE === 8 ? (($x & 0xFFFFFFF) << 35) | (($y & 0x7f) << 28) | ($z & 0xFFFFFFF) : $x . ":" . $y .":". $z;
> 	}

because the line 1552 in Level is allow the float to be in there.
And my plugin, if i try to get the block with a float, crash. Eventhough the coordinates should be in float.

**Comment by dterweij** [comment]
Is that the same or related to  #938 ?

**Comment by keithkfng** [comment]
Well, I think this is a fix for the issue XD

**Comment by intagaming** [comment]
Because i don't want to use Github Windows anymore..
It ruins my head :<
