### ISSUE TITLE
How to install the new phar and PHP7 on LINUX?

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalMine/ImagicalMine#951]

**Comment by XiangZhao969** [comment]
I switched to my user and typed this like on imagicalmine.net:
curl -sL http://get.imagicalmine.net | bash

but it doesn't work:
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

**Comment by 88keyz** [comment]
From your ImagicalMine base folder do the following..

`wget https://bintray.com/artifact/download/pocketmine/PocketMine/PHP_7.0.2_x86-64_Linux.tar.gz`

`tar -zxvf PHP_7.0.2_x86-64_Linux.tar.gz`

**Comment by XiangZhao969** [comment]
[root@static game]# tar -zxvf PHP_7.0.2_x86-64_Linux.tar.gz
tar (child): PHP_7.0.2_x86-64_Linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[root@static game]#

**Comment by XiangZhao969** [comment]
Ok, extracted the file! what should i do now

**Comment by XiangZhao969** [comment]
@88keyz

**Comment by 88keyz** [comment]
Since I'm not sure where you are in the process so here it is from the beginning for a clean install.  Assuming Ubuntu linux, adjust as necessary.

`cd ~`

`git clone https://github.com/ImagicalMine/ImagicalMine.git  $HOME/PocketMine`

`cd PocketMine`

`wget https://bintray.com/artifact/download/pocketmine/PocketMine/PHP_7.0.3_x86-64_Linux.tar.gz`

`tar -zxvf PHP_7.0.3_x86-64_Linux.tar.gz`

`sudo chmod -R 755 $HOME/PocketMine`

`./start.sh`

**Comment by XiangZhao969** [comment]
@88keyz this appeared after ./start.sh:

[root@static game]# ./start.sh
./bin/php7/bin/php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/game/bin/php7/bin/../lib/libz.so.1)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/game/bin/php7/bin/../lib/libyaml-0.so.2)
./bin/php7/bin/php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /root/game/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/game/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /root/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/game/bin/php7/bin/../lib/libcurl.so.4)
[root@static game]#

**Comment by 88keyz** [comment]
Sorry, you lost me there.  Looks like some dependency issues or missing libraries.

**Comment by ecoron** [comment]
Yes deps are missing, but take a look into the forum I think there is an answer.

**Comment by XiangZhao969** [comment]
can anybody help me pls? and the problem hasn't been solved yet so why did you close, keith? want to be the next Intyre?

**Comment by ecoron** [comment]
maybe take a look in our forum there you can find answers for different systems. 

```
sudo apt-get  install libc6

or
 
sudo apt-get  install libc6-dev
```
should help

**Comment by XiangZhao969** [comment]
[root@static ~]# sudo apt-get  install libc6
sudo: apt-get: command not found

i can't visit IM forum :(, could you give me a full guide to install please :(

**Comment by ecoron** [comment]
then is it sudo yum install instead. forum is here: http://forums.imagicalmine.me/forums/

**Comment by XiangZhao969** [comment]
how to install php7 on /home/game/bin (game is my server folder)
