### ISSUE TITLE
Client shows that it has 99+ of an item when adding NBT to item

### ISSUE THREAD

**Issue by PocketKiller** [ImagicalMine/ImagicalMine#952]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###START ISSUE DETAILS BELOW : 

------------------------------------------

When adding NBT to items, client shows that it has 99+ Grass Block and 99+ of a random block, and it hides some other items that does not contain NBT (or contains) I think this is a client bug (not sure) it's very annoying.

------------------------------------------

**Comment by CyberPowerCrazii** [comment]
Can you debug this issue? This happened to me in previous build

**Comment by PocketKiller** [comment]
I updated my MCPE to the official one, fixed. lmao it was a client bug

**Comment by kvetinac97** [comment]
#13ec6e1c3a79b999496ba2f9646f41e2b5c01718

**Comment by kvetinac97** [comment]
#119498
