### ISSUE TITLE
Server linux Centos 7.2 install - bash: 2: command not found

### ISSUE THREAD

**Issue by alicheek** [ImagicalMine/ImagicalMine#954]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###START ISSUE DETAILS BELOW : 

------------------------------------------

[screen is terminating]
[root@ns3015265 ~]# screen -S pocket
  _                       _           _ __  __ _
 (_)                     (_)         | |  \/  (_)
  _ _ __ ___   __ _  __ _ _  ___ __ _| | \  / |_ _ __   ___
 | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \
 | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/
 |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___|
                     __/ |
                    |___/
system> Choose which PHP binary you want to install
system>   1) Linux x86(32-bit system)
system>   2) Linux x64(64-bit system)
system>   3) Mac x86(32-bit system)
system>   4) Mac x64(64-bit system)
system> Number (e.g. 1): 2
error> An unexpected error occurred - either a 10 second timeout or an unknown selection. Restart the script, and then choose again.
[root@ns3015265 pocket]# 2
bash: 2: command not found
[root@ns3015265 pocket]#

------------------------------------------

Not really sure how to install since i need php7 and this would be the only way i know to install php7 to the server.

**Comment by rWardy** [comment]
I think there is a problem with the script. Have tired on Ubuntu and have a few issues.  Not got chance to recommend a change now, but there is an extra read line and the echo of the ImagicalMine logo causes issues.

**Comment by 88keyz** [comment]
Install from git and then run the following commands from your ImagicalMine base folder..

`wget https://bintray.com/artifact/download/pocketmine/PocketMine/PHP_7.0.3_x86-64_Linux.tar.gz`

`tar -zxvf PHP_7.0.3_x86-64_Linux.tar.gz`

**Comment by alicheek** [comment]
Thanks for that @88keyz got it working now :)
