### ISSUE TITLE
Hope can support mca format, or convert world format from mca to mcr

### ISSUE THREAD

**Issue by silence8620** [ImagicalMine/ImagicalMine#955]
My 0.13.2 map is .mca format , but in 0.14.x ,it can't load

**Comment by remotevase** [comment]
must be .mcr... use mconverter ultimate in ImagicalMine repo to convert

**Comment by silence8620** [comment]
@remotevase Can you give me link to download it? thank you !

**Comment by silence8620** [comment]
i can't find that software

**Comment by VonHirsch** [comment]
the converter doesn't work from region->anvil.  If you don't have an anvil version of your map you're hosed, however I believe Genisys still supports region...

**Comment by silence8620** [comment]
Thank you very much!

**Comment by silence8620** [comment]
I find that software!!

**Comment by silence8620** [comment]
That software cannot use :( because the server still cannot load that map!

**Comment by mwvent** [comment]
Tested anvil in 0.14 last week, is it not working now? What build are you using and what error do you get? You may need to change the setting in pocketmine.yml from McRegion to anvil too

**Comment by silence8620** [comment]
i set pocketmine.yml from Mcregion to Anvil but nothing change.
when i get in that map(Anvil Format) , it shows blank, no blocks can use,and cannot move.

**Comment by silence8620** [comment]
I use Mconverter Ultimate, to change Anvil to Mcrgion , but grass will black , no light.

**Comment by keithkfng** [comment]
We can't fix that - it's a bug with the map converting. There's no way you can fix it. Sorry.

**Comment by silence8620** [comment]
ImagicalMine forever cannot support Anvil?! :(

**Comment by keithkfng** [comment]
We can add support for it - but it'll take some time... @mwvent and @PocketKiller what do you think of this...

**Comment by Delimer** [comment]
I test anvil map on 0.14. It's work, but after some time chunks not draw and after reconnect map not load. Need support for anvil map, becouse soft for render map for web support only anvil.

**Comment by PocketKiller** [comment]
where are the templates?
