### ISSUE TITLE
urgent

### ISSUE THREAD

**Issue by GrimDevs** [ImagicalMine/ImagicalMine#956]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###START ISSUE DETAILS BELOW : 

------------------------------------------

//

------------------------------------------

i download all the thing but still me server for 0.13.2 shoud i try and code the phar to be php 5.x.x ok or tell me there othes ones likr builds so i can use it i tride a lot dspent all nihgt too i had no sleep at sall so this may sound odd if so sorry but help plz pl tell me what i need to do

**Comment by InfornoFire** [comment]
Well, php7 upgrade is one of the only ways. Coding to php5 is near impossible because you would have to restart the code. And why not use 0.14

**Comment by GrimDevs** [comment]
how to upadte then to php 7 idk how

**Comment by InfornoFire** [comment]
Ok, first tell me are you windows, mac, or whatever you use to host your server

**Comment by keithkfng** [comment]
Please review the contributing guidelines or you'll be banned.

**Comment by GrimDevs** [comment]
ok :( i have nw got pocket mine i miss inmgaiclemine it was better than pocket mine it had minecratsboats and stuff i will read it ok

**Comment by ecoron** [comment]
just go to the forum there are lot of answers how to update on different systems.
