### ISSUE TITLE
Getting this crash report after installing latest script(sorry if its a duplicate)

### ISSUE THREAD

**Issue by FienixEC** [ImagicalMine/ImagicalMine#957]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**
Welcome to the ImagicalMine issue tracker!
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!
###START ISSUE DETAILS BELOW : 
Getting this Crash Report with latest php7 script. can someone please give guidance? Thanks!

ImagicalMine Crash Dump Fri Feb 19 23:18:13 EST 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /EssentialsPE_v1.1.3.phar/src/EssentialsPE/Loader
Line: 106
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[97] use pocketmine\level\Level;
[98] use pocketmine\level\Location;
[99] use pocketmine\level\Position;
[100] use pocketmine\math\AxisAlignedBB;
[101] use pocketmine\math\Vector3;
[102] use pocketmine\nbt\tag\Byte;
[103] use pocketmine\nbt\tag\Compound;
[104] use pocketmine\nbt\tag\Double;
[105] use pocketmine\nbt\tag\Enum;
[106] use pocketmine\nbt\tag\Float;
[107] use pocketmine\network\protocol\MobEffectPacket;
[108] use pocketmine\network\protocol\SetTimePacket;
[109] use pocketmine\permission\Permission;
[110] use pocketmine\Player;
[111] use pocketmine\plugin\PluginBase;
[112] use pocketmine\Server;
[113] use pocketmine\utils\Config;
[114] use pocketmine\utils\Random;
[115] use pocketmine\utils\TextFormat;
[116] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 45; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Whiskey.HostingItAll.com 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevBAN 1 by Ragnok123 for API(s) 1.13.1
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
------------------------------------------

//

------------------------------------------

**Comment by HostingItAll** [comment]
Issue is within EssentialsPE and will need to have that plugin updated for full PHP7 support.

**Comment by FienixEC** [comment]
Any other known plugins causing this? If i remove essentials for now, will
i be okay with all others? Btw thanks for the response and help!

**Comment by HostingItAll** [comment]
This can be closed.

This is fixed by finding all cases of pocketmine\nbt\tag\Float and changing to pocketmine\nbt\tag\FloatTag

**Comment by ecoron** [comment]
It's an EssentialPE issue, but could be interesting if other plugins have also issues. Can be a topic in our forum.

**Comment by keithkfng** [comment]
I thought the issue template said don't submit plugin crashes - if you don't even read it what's the point -_-

**Comment by FienixEC** [comment]
oh I read it. but technically, my plugins didn't start to crash till I updated to PHP7 build. therefor, a direct association to my server crashes. Just wanted an update on a fix that's all, I said I apologize. I'm still learning. but thank you.

**Comment by keithkfng** [comment]
No problem, happy to help :)
