### ISSUE TITLE
block Fallable references to not existing block Compound

### ISSUE THREAD

**Issue by ecoron** [ImagicalMine/ImagicalMine#959]
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br)
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**
-----------------------------

```
[11:27:27] critical> Could not tick level "world": Class pocketmine\block\Compound not found
[11:27:27] critical> ClassNotFoundException: "Class pocketmine\block\Compound not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[11:27:27] debug> #0 /src/pocketmine/block/Fallable(52): spl_autoload_call(string pocketmine\block\Compound)
[11:27:27] debug> #1 /src/pocketmine/level/Explosion(230): pocketmine\block\Fallable->onUpdate(integer 1)
```
needs to be fixed, din't checked the code there yet, but maybe somehow can helpout with that.

**Comment by PocketKiller** [comment]
please tick...

**Comment by ecoron** [comment]
thx
